// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[proc_macro]
#[decl2(fn, name = "archive_event", vis = "pub", hash = "db2cb06b")]
pub fn archive_event(input: TokenStream) -> TokenStream {
    event_memory::archive_event_impl(input)
}
