// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[proc_macro]
#[decl2(fn, name = "mev_exclude", vis = "pub", hash = "7cb0b085")]
pub fn mev_exclude(input: TokenStream) -> TokenStream {
    mev_protection::mev_exclude_impl(input)
}
