// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[proc_macro]
#[decl2(fn, name = "dependency_graph", vis = "pub", hash = "55226dc5")]
pub fn dependency_graph(input: TokenStream) -> TokenStream {
    rustc_ring::dependency_graph_impl(input)
}
