// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[proc_macro]
#[decl2(fn, name = "emoji_to_math", vis = "pub", hash = "bdab912f")]
pub fn emoji_to_math(input: TokenStream) -> TokenStream {
    emoji_poetry::emoji_to_math_impl(input)
}
