// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[proc_macro]
#[decl2(fn, name = "decl", vis = "pub", hash = "9cec6423")]
pub fn extract_decl(input: TokenStream) -> TokenStream {
    rust_nix::extract_decl_impl(input)
}
