// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[proc_macro]
#[decl2(fn, name = "llm_redundancy", vis = "pub", hash = "f4c786ab")]
pub fn llm_redundancy(input: TokenStream) -> TokenStream {
    duplicate_analysis::llm_redundancy_impl(input)
}
