// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[proc_macro]
#[decl2(fn, name = "generate_common_macros", vis = "pub", hash = "7a7ed877")]
pub fn generate_common_macros(input: TokenStream) -> TokenStream {
    macro_generator::generate_common_macros_impl(input)
}
