// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
decl_module!(
    dao_governance,
    solana_lift,
    quant_trading,
    zk_proof,
    template_checker,
    sat_lfunction,
    rust_nix,
    rust_eigenmatrix,
    rustc_tracer,
    rustc_ring,
    repo_analysis,
    real_rustc_analysis,
    real_data_analysis,
    quine_relay,
    ollama_macros,
    mkbuildrs,
    mev_protection,
    macro_lattice,
    macro_generator
);
