// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[proc_macro]
#[decl2(fn, name = "lean4_theorem", vis = "pub", hash = "d26355c2")]
pub fn lean4_theorem(input: TokenStream) -> TokenStream {
    lean4_proof::lean4_theorem_impl(input)
}
