// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter.rs:211 from submodules/split-decls-rs/src/eager_splitter.rs
// Do not edit this file by hand. Your changes will be overwritten.

#[llm_error_message(message = "Module file not found for: dao_governance")]
#[llm_context(
    crate_name = "wrapped_patch_build_rs_macros",
    module_name = "dao_governance"
)]
pub struct wrapped_patch_build_rs_macros_decls_module_not_found_dao_governance;
