// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[proc_macro]
#[decl2(fn, name = "patch_rust", vis = "pub", hash = "d60f6cd9")]
pub fn patch_rust(input: TokenStream) -> TokenStream {
    rust_nix::patch_rust_impl(input)
}
