// Generated macro for fn_macro_declaration (function)
macro_rules! Depcrate_exprfn_macro_declaration {
() => {
// Module: crate::expr
// Provides: {"fn_macro_declaration"}
// Dependencies: {}
# [doc = " Parse a functional macro declaration from a list of tokens."] # [doc = ""] # [doc = " Returns the identifier for the macro and the argument list (in order). The"] # [doc = " input should not include `#define`. The actual definition is not parsed and"] # [doc = " may be obtained from the unparsed data returned."] # [doc = ""] # [doc = " Returns an error if the input is not a functional macro or if the token"] # [doc = " stream contains comments."] # [doc = ""] # [doc = " # Example"] # [doc = " ```"] # [doc = " use cexpr::expr::{IdentifierParser, EvalResult, fn_macro_declaration};"] # [doc = " use cexpr::assert_full_parse;"] # [doc = " use cexpr::token::Kind::*;"] # [doc = " use cexpr::token::Token;"] # [doc = ""] # [doc = " // #define SUFFIX(arg) arg \"suffix\""] # [doc = " let tokens = vec!["] # [doc = "     (Identifier,  &b\"SUFFIX\"[..]).into(),"] # [doc = "     (Punctuation, &b\"(\"[..]).into(),"] # [doc = "     (Identifier,  &b\"arg\"[..]).into(),"] # [doc = "     (Punctuation, &b\")\"[..]).into(),"] # [doc = "     (Identifier,  &b\"arg\"[..]).into(),"] # [doc = "     (Literal,     &br#\"\"suffix\"\"#[..]).into(),"] # [doc = " ];"] # [doc = ""] # [doc = " // Try to parse the functional part"] # [doc = " let (expr, (ident, args)) = fn_macro_declaration(&tokens).unwrap();"] # [doc = " assert_eq!(ident, b\"SUFFIX\");"] # [doc = ""] # [doc = " // Create dummy arguments"] # [doc = " let idents = args.into_iter().map(|arg|"] # [doc = "     (arg.to_owned(), EvalResult::Str(b\"test\".to_vec()))"] # [doc = " ).collect();"] # [doc = ""] # [doc = " // Evaluate the macro"] # [doc = " let (_, evaluated) = assert_full_parse(IdentifierParser::new(&idents).expr(expr)).unwrap();"] # [doc = " assert_eq!(evaluated, EvalResult::Str(b\"testsuffix\".to_vec()));"] # [doc = " ```"] pub fn fn_macro_declaration (input : & [Token]) -> CResult < '_ , (& [u8] , Vec < & [u8] >) > { pair (identifier_token , delimited (p ("(") , separated_list0 (p (",") , identifier_token) , p (")") ,) ,) (input) }
};
}
