// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_rustc_windows_rc_decls_RESOURCE_TEMPLATE,
    wrapped_rustc_windows_rc_decls_VersionInfoFileType,
    wrapped_rustc_windows_rc_decls_compile_windows_resource_file,
    wrapped_rustc_windows_rc_decls_write_resource_script_file,
    wrapped_rustc_windows_rc_decls_product_name,
    wrapped_rustc_windows_rc_decls_ResourceVersion,
    wrapped_rustc_windows_rc_decls_impl_for_ResourceVersion,
    wrapped_rustc_windows_rc_decls_parse_version
);
