// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Workaround because `?` is not (yet) available in const context."]
#[macro_export]
#[doc(hidden)]
macro_rules! try_opt {
    ($ e : expr) => {
        match $e {
            Some(v) => v,
            None => return None,
        }
    };
}
