// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Returns true if `stream` is a TTY or the current terminal"]
#[doc = " [supports_unicode]."]
pub fn on(stream: Stream) -> bool {
    if !is_a_tty(stream) {
        true
    } else {
        supports_unicode()
    }
}
