// Generated macro for impl_19 (impl)
macro_rules! Depcrate_attrimpl_19 {
() => {
// Module: crate::attr
// Provides: {"impl_19"}
// Dependencies: {}
impl AttrDef { # [doc = " Performs checks that can be performed without parsing other attributes,"] # [doc = " and returns `true` if at least one error occurs."] fn early_check (& self , cx : & Context , pos : Position , meta : & Meta) -> bool { let mut has_error = false ; if let Err (msg) = self . check_position (pos) { cx . error (format_err ! (meta , msg)) ; has_error = true ; } if let Err (msg) = self . check_style (meta) { cx . error (format_err ! (meta , msg)) ; has_error = true ; } has_error } fn check_position (& self , pos : Position) -> Result < () , String > { if self . position . contains (& pos) { return Ok (()) ; } let mut msg = format ! ("#[{}({})] may only be used on " , ATTR_NAME , self . name) ; let position = if self . position . contains (& Position :: NamedField) && self . position . contains (& Position :: UnnamedField) { let mut position : Vec < _ > = self . position . iter () . filter (| p | ! p . is_field ()) . map (Position :: as_str) . collect () ; position . push ("field") ; position } else { self . position . iter () . map (Position :: as_str) . collect () } ; let len = position . len () ; for (i , p) in position . iter () . enumerate () { if i != 0 { if len == 2 { msg . push_str (" and ") ; } else { msg . push_str (", ") ; if i == len - 1 { msg . push_str ("and ") ; } } } msg . push_str (p) ; msg . push ('s') ; } Err (msg) } fn check_style (& self , meta : & Meta) -> Result < () , String > { let meta = MetaStyle :: from (meta) ; if self . style . contains (& meta) { return Ok (()) ; } let mut msg = "expected " . to_owned () ; let mut first = true ; for style in self . style { if first { first = false ; } else { msg . push_str (" or ") ; } let _ = write ! (msg , "`#[{}({})]`" , ATTR_NAME , style . format (self . name)) ; } msg . push_str (", found ") ; let _ = write ! (msg , "`#[{}({})]`" , ATTR_NAME , meta . format (self . name)) ; Err (msg) } # [doc = " Performs checks that can be performed after parsing all attributes in"] # [doc = " the same scope and parent scopes, and returns `true` if at least one"] # [doc = " error occurs."] fn late_check (& self , cx : & Context , attrs : & [(& AttrDef , Meta)]) -> bool { let mut has_error = false ; for (def , meta) in attrs { if def . name != self . name && self . conflicts_with . contains (& def . name) { let msg = format ! ("#[{0}({1})] may not be used together with #[{0}({2})]" , ATTR_NAME , self . name , def . name) ; cx . error (format_err ! (meta . path () , msg)) ; has_error = true ; } } has_error } }
};
}
