// Generated macro for from_channel (function)
macro_rules! Depcrate_connectionfrom_channel {
() => {
// Module: crate::connection
// Provides: {"from_channel"}
// Dependencies: {}
# [doc = " Create a connection from channel, you may need to invoke `channel.register()?` to make sure the"] # [doc = " channel is usable."] # [doc = ""] # [doc = " # Example"] # [doc = ""] # [doc = " ```no_run"] # [doc = " use std::sync::Arc;"] # [doc = ""] # [doc = " use dbus::channel::Channel;"] # [doc = " use dbus_tokio::connection;"] # [doc = " use dbus_tokio::connection::IOResource;"] # [doc = " use dbus::nonblock::SyncConnection;"] # [doc = ""] # [doc = " # tokio::runtime::Builder::new_multi_thread().enable_all().build().unwrap().block_on(async {"] # [doc = " let mut channel = Channel::open_private(\"unix:path=/run/user/1000/bus\").expect(\"open private channel failed\");"] # [doc = ""] # [doc = " channel.register().expect(\"register channel failed\");"] # [doc = ""] # [doc = " let (resource, conn): (IOResource<SyncConnection>, Arc<SyncConnection>) = connection::from_channel(channel).expect(\"create connection failed\");"] # [doc = ""] # [doc = " tokio::spawn(resource);"] # [doc = " # })"] # [doc = ""] # [doc = " // do anything with the conn"] # [doc = " ```"] pub fn from_channel < C : From < Channel > + NonblockReply > (mut channel : Channel) -> Result < (IOResource < C > , Arc < C >) , dbus :: Error > { channel . set_watch_enabled (true) ; let watch = channel . watch () ; let watch_fd = watch . fd ; let mut interest = tokio :: io :: Interest :: READABLE ; if watch . write { interest |= tokio :: io :: Interest :: WRITABLE ; } let mut conn = C :: from (channel) ; conn . set_timeout_maker (Some (make_timeout)) ; let wake = Arc :: new (Mutex :: new (WakeStatus :: Waiting { ready : false })) ; conn . set_waker (Some (Box :: new ({ let wake = wake . clone () ; move | | { let mut wake_status = wake . lock () . unwrap () ; let prev_status = std :: mem :: replace (& mut * wake_status , WakeStatus :: Waiting { ready : true }) ; match prev_status { WakeStatus :: Polled { waker } => { waker . wake () ; Ok (()) } WakeStatus :: Waiting { .. } => { Err (()) } } } }))) ; let conn = Arc :: new (conn) ; let res = IOResource { connection : conn . clone () , registration : IOResourceRegistration :: Unregistered (watch_fd , interest) , wake , write_pending : false , } ; Ok ((res , conn)) }
};
}
