// Generated macro for AsyncClient (trait)
macro_rules! DepcrateAsyncClient {
() => {
// Module: crate
// Provides: {"AsyncClient"}
// Dependencies: {}
pub trait AsyncClient { # [doc = " Send a signed transaction, but don't wait to see if the server accepted it."] fn async_send_transaction (& self , transaction : Transaction) -> Result < Signature > { self . async_send_versioned_transaction (transaction . into ()) } # [doc = " Send a batch of signed transactions without confirmation."] fn async_send_batch (& self , transactions : Vec < Transaction >) -> Result < () > { let transactions = transactions . into_iter () . map (Into :: into) . collect () ; self . async_send_versioned_transaction_batch (transactions) } # [doc = " Send a signed versioned transaction, but don't wait to see if the server accepted it."] fn async_send_versioned_transaction (& self , transaction : VersionedTransaction ,) -> Result < Signature > ; # [doc = " Send a batch of signed versioned transactions without confirmation."] fn async_send_versioned_transaction_batch (& self , transactions : Vec < VersionedTransaction > ,) -> Result < () > { for t in transactions { self . async_send_versioned_transaction (t) ? ; } Ok (()) } # [doc = " Create a transaction from the given message, and send it to the"] # [doc = " server, but don't wait for to see if the server accepted it."] fn async_send_message < T : Signers + ? Sized > (& self , keypairs : & T , message : Message , recent_blockhash : Hash ,) -> Result < Signature > { let transaction = Transaction :: new (keypairs , message , recent_blockhash) ; self . async_send_transaction (transaction) } # [doc = " Create a transaction from a single instruction that only requires"] # [doc = " a single signer. Then send it to the server, but don't wait for a reply."] fn async_send_instruction (& self , keypair : & Keypair , instruction : Instruction , recent_blockhash : Hash ,) -> Result < Signature > { let message = Message :: new (& [instruction] , Some (& keypair . pubkey ())) ; self . async_send_message (& [keypair] , message , recent_blockhash) } # [doc = " Attempt to transfer lamports from `keypair` to `pubkey`, but don't wait to confirm."] fn async_transfer (& self , lamports : u64 , keypair : & Keypair , pubkey : & Pubkey , recent_blockhash : Hash ,) -> Result < Signature > { let transfer_instruction = transfer (& keypair . pubkey () , pubkey , lamports) ; self . async_send_instruction (keypair , transfer_instruction , recent_blockhash) } }
};
}
