// Generated macro for print_panic_info (function)
macro_rules! Depcrate_configprint_panic_info {
() => {
// Module: crate::config
// Provides: {"print_panic_info"}
// Dependencies: {}
fn print_panic_info (report : & PanicReport < '_ > , f : & mut fmt :: Formatter < '_ >) -> fmt :: Result { report . hook . panic_message . display (report . panic_info , f) ? ; let v = panic_verbosity () ; let capture_bt = v != Verbosity :: Minimal ; let mut separated = f . header ("\n\n") ; if let Some (ref section) = report . hook . section { write ! (& mut separated . ready () , "{section}") ? ; } # [cfg (feature = "capture-spantrace")] { if let Some (span_trace) = report . span_trace . as_ref () { write ! (& mut separated . ready () , "{}" , crate :: writers :: FormattedSpanTrace (span_trace)) ? ; } } if let Some (bt) = report . backtrace . as_ref () { let fmted_bt = report . hook . format_backtrace (bt) ; write ! (indented (& mut separated . ready ()) . with_format (Format :: Uniform { indentation : "  " }) , "{fmted_bt}") ? ; } if report . hook . display_env_section { let env_section = EnvSection { bt_captured : & capture_bt , # [cfg (feature = "capture-spantrace")] span_trace : report . span_trace . as_ref () , } ; write ! (& mut separated . ready () , "{env_section}") ? ; } # [cfg (feature = "issue-url")] { let payload = report . panic_info . payload () ; if report . hook . issue_url . is_some () && (* report . hook . issue_filter) (crate :: ErrorKind :: NonRecoverable (payload)) { let url = report . hook . issue_url . as_ref () . unwrap () ; let payload = payload . downcast_ref :: < String > () . map (String :: as_str) . or_else (| | payload . downcast_ref :: < & str > () . cloned ()) . unwrap_or ("<non string panic payload>") ; let issue_section = crate :: section :: github :: IssueSection :: new (url , payload) . with_backtrace (report . backtrace . as_ref ()) . with_location (report . panic_info . location ()) . with_metadata (& report . hook . issue_metadata) ; # [cfg (feature = "capture-spantrace")] let issue_section = issue_section . with_span_trace (report . span_trace . as_ref ()) ; write ! (& mut separated . ready () , "{issue_section}") ? ; } } Ok (()) }
};
}
