// Generated macro for check_drop_impl (function)
macro_rules! Depcrate_check_always_applicablecheck_drop_impl {
() => {
// Module: crate::check::always_applicable
// Provides: {"check_drop_impl"}
// Dependencies: {}
# [doc = " This function confirms that the `Drop` implementation identified by"] # [doc = " `drop_impl_did` is not any more specialized than the type it is"] # [doc = " attached to (Issue #8142)."] # [doc = ""] # [doc = " This means:"] # [doc = ""] # [doc = " 1. The self type must be nominal (this is already checked during"] # [doc = "    coherence),"] # [doc = ""] # [doc = " 2. The generic region/type parameters of the impl's self type must"] # [doc = "    all be parameters of the Drop impl itself (i.e., no"] # [doc = "    specialization like `impl Drop for Foo<i32>`), and,"] # [doc = ""] # [doc = " 3. Any bounds on the generic parameters must be reflected in the"] # [doc = "    struct/enum definition for the nominal type itself (i.e."] # [doc = "    cannot do `struct S<T>; impl<T:Clone> Drop for S<T> { ... }`)."] pub (crate) fn check_drop_impl (tcx : TyCtxt < '_ > , drop_impl_did : LocalDefId ,) -> Result < () , ErrorGuaranteed > { match tcx . impl_polarity (drop_impl_did) { ty :: ImplPolarity :: Positive => { } ty :: ImplPolarity :: Negative => { return Err (tcx . dcx () . emit_err (errors :: DropImplPolarity :: Negative { span : tcx . def_span (drop_impl_did) , })) ; } ty :: ImplPolarity :: Reservation => { return Err (tcx . dcx () . emit_err (errors :: DropImplPolarity :: Reservation { span : tcx . def_span (drop_impl_did) , })) ; } } tcx . ensure_ok () . orphan_check_impl (drop_impl_did) ? ; let self_ty = tcx . type_of (drop_impl_did) . instantiate_identity () ; match self_ty . kind () { ty :: Adt (adt_def , adt_to_impl_args) => { ensure_impl_params_and_item_params_correspond (tcx , drop_impl_did , adt_def . did () , adt_to_impl_args ,) ? ; ensure_impl_predicates_are_implied_by_item_defn (tcx , drop_impl_did , adt_def . did () , adt_to_impl_args ,) } _ => { span_bug ! (tcx . def_span (drop_impl_did) , "incoherent impl of Drop") ; } } }
};
}
