// Generated macro for impl_492 (impl)
macro_rules! Depcrate_fmt_temporal_piecesimpl_492 {
() => {
// Module: crate::fmt::temporal::pieces
// Provides: {"impl_492"}
// Dependencies: {}
impl PiecesOffset { # [doc = " Converts this offset to a concrete numeric offset in all cases."] # [doc = ""] # [doc = " If this was a `Z` or a `-00:00` offset, then `Offset::UTC` is returned."] # [doc = " In all other cases, the underlying numeric offset is returned as-is."] # [doc = ""] # [doc = " # Example"] # [doc = ""] # [doc = " ```"] # [doc = " use jiff::{"] # [doc = "     fmt::temporal::{Pieces, PiecesNumericOffset, PiecesOffset},"] # [doc = "     tz::Offset,"] # [doc = " };"] # [doc = ""] # [doc = " let pieces = Pieces::parse(\"1970-01-01T00:00:00Z\")?;"] # [doc = " let off = pieces.offset().unwrap();"] # [doc = " // Parsed as Zulu."] # [doc = " assert_eq!(off, PiecesOffset::Zulu);"] # [doc = " // Gets converted from Zulu to UTC, i.e., just zero."] # [doc = " assert_eq!(off.to_numeric_offset(), Offset::UTC);"] # [doc = ""] # [doc = " let pieces = Pieces::parse(\"1970-01-01T00:00:00-00:00\")?;"] # [doc = " let off = pieces.offset().unwrap();"] # [doc = " // Parsed as a negative zero."] # [doc = " assert_eq!(off, PiecesOffset::from("] # [doc = "     PiecesNumericOffset::from(Offset::UTC).with_negative_zero(),"] # [doc = " ));"] # [doc = " // Gets converted from -00:00 to UTC, i.e., just zero."] # [doc = " assert_eq!(off.to_numeric_offset(), Offset::UTC);"] # [doc = ""] # [doc = " let pieces = Pieces::parse(\"1970-01-01T00:00:00+00:00\")?;"] # [doc = " let off = pieces.offset().unwrap();"] # [doc = " // Parsed as a positive zero."] # [doc = " assert_eq!(off, PiecesOffset::from("] # [doc = "     PiecesNumericOffset::from(Offset::UTC),"] # [doc = " ));"] # [doc = " // Gets converted from -00:00 to UTC, i.e., just zero."] # [doc = " assert_eq!(off.to_numeric_offset(), Offset::UTC);"] # [doc = ""] # [doc = " # Ok::<(), Box<dyn std::error::Error>>(())"] # [doc = " ```"] # [inline] pub fn to_numeric_offset (& self) -> Offset { match * self { PiecesOffset :: Zulu => Offset :: UTC , PiecesOffset :: Numeric (ref noffset) => noffset . offset () , } } }
};
}
