// Generated macro for Write (trait)
macro_rules! Depcrate_fmtWrite {
() => {
// Module: crate::fmt
// Provides: {"Write"}
// Dependencies: {}
# [doc = " A trait for printing datetimes or spans into Unicode-accepting buffers or"] # [doc = " streams."] # [doc = ""] # [doc = " The most useful implementations of this trait are for the `String` and"] # [doc = " `Vec<u8>` types. But any implementation of [`std::fmt::Write`] and"] # [doc = " [`std::io::Write`] can be used via the [`StdFmtWrite`] and [`StdIoWrite`]"] # [doc = " adapters, respectively."] # [doc = ""] # [doc = " Most users of Jiff should not need to interact with this trait directly."] # [doc = " Instead, printing is handled via the [`Display`](std::fmt::Display)"] # [doc = " implementation of the relevant type."] # [doc = ""] # [doc = " # Design"] # [doc = ""] # [doc = " This trait is a near-clone of the `std::fmt::Write` trait. It's also very"] # [doc = " similar to the `std::io::Write` trait, but like `std::fmt::Write`, this"] # [doc = " trait is limited to writing valid UTF-8. The UTF-8 restriction was adopted"] # [doc = " because we really want to support printing datetimes and spans to `String`"] # [doc = " buffers. If we permitted writing `&[u8]` data, then writing to a `String`"] # [doc = " buffer would always require a costly UTF-8 validation check."] # [doc = ""] # [doc = " The `std::fmt::Write` trait wasn't used itself because:"] # [doc = ""] # [doc = " 1. Using a custom trait allows us to require using Jiff's error type."] # [doc = " (Although this extra flexibility isn't currently used, since printing only"] # [doc = " fails when writing to the underlying buffer or stream fails.)"] # [doc = " 2. Using a custom trait allows us more control over the implementations of"] # [doc = " the trait. For example, a custom trait means we can format directly into"] # [doc = " a `Vec<u8>` buffer, which isn't possible with `std::fmt::Write` because"] # [doc = " there is no `std::fmt::Write` trait implementation for `Vec<u8>`."] pub trait Write { # [doc = " Write the given string to this writer, returning whether the write"] # [doc = " succeeded or not."] fn write_str (& mut self , string : & str) -> Result < () , Error > ; # [doc = " Write the given character to this writer, returning whether the write"] # [doc = " succeeded or not."] # [inline] fn write_char (& mut self , char : char) -> Result < () , Error > { self . write_str (char . encode_utf8 (& mut [0 ; 4])) } }
};
}
