// Generated macro for impl_1155 (impl)
macro_rules! Depcrate_tz_zicimpl_1155 {
() => {
// Module: crate::tz::zic
// Provides: {"impl_1155"}
// Dependencies: {}
impl ZoneUntilP { fn parse (fields : & [& str]) -> Result < ZoneUntilP , Error > { if fields . is_empty () { return Err (err ! ("expected at least a year")) ; } let (year_field , fields) = (fields [0] , & fields [1 ..]) ; let year = parse_year (year_field) . map_err (| e | e . context ("failed to parse year")) ? ; if fields . is_empty () { return Ok (ZoneUntilP :: Year { year }) ; } let (month_field , fields) = (fields [0] , & fields [1 ..]) ; let month = month_field . parse :: < RuleInP > () . map_err (| e | e . context ("failed to parse month")) ? ; if fields . is_empty () { return Ok (ZoneUntilP :: YearMonth { year , month }) ; } let (day_field , fields) = (fields [0] , & fields [1 ..]) ; let day = day_field . parse :: < RuleOnP > () . map_err (| e | e . context ("failed to parse day")) ? ; if fields . is_empty () { return Ok (ZoneUntilP :: YearMonthDay { year , month , day }) ; } let (duration_field , fields) = (fields [0] , & fields [1 ..]) ; let duration = duration_field . parse :: < RuleAtP > () . map_err (| e | e . context ("failed to parse time duration")) ? ; if ! fields . is_empty () { return Err (err ! ("expected no more fields after time of day, \
                 but found: {fields:?}" , fields = fields . join (" ") ,)) ; } Ok (ZoneUntilP :: YearMonthDayTime { year , month , day , duration }) } fn to_datetime (& self) -> Result < DateTime , Error > { let date = self . on () . date (self . year () , self . month ()) ? ; let dt = date . to_datetime (Time :: midnight ()) . checked_add (self . at () . span . 0) ? ; Ok (dt) } fn year (& self) -> t :: Year { use self :: ZoneUntilP :: * ; match * self { Year { year } | YearMonth { year , .. } | YearMonthDay { year , .. } | YearMonthDayTime { year , .. } => year , } } fn month (& self) -> t :: Month { use self :: ZoneUntilP :: * ; match * self { Year { .. } => t :: Month :: N :: < 1 > () , YearMonth { month , .. } | YearMonthDay { month , .. } | YearMonthDayTime { month , .. } => month . month , } } fn on (& self) -> RuleOnP { use self :: ZoneUntilP :: * ; match * self { Year { .. } | YearMonth { .. } => { RuleOnP :: Day { day : t :: Day :: N :: < 1 > () } } YearMonthDay { day , .. } | YearMonthDayTime { day , .. } => day , } } fn at (& self) -> RuleAtP { use self :: ZoneUntilP :: * ; match * self { Year { .. } | YearMonth { .. } | YearMonthDay { .. } => { RuleAtP { span : Span :: new () . fieldwise () , suffix : None } } YearMonthDayTime { duration , .. } => duration , } } }
};
}
