// Generated macro for TimeRound (struct)
macro_rules! Depcrate_civil_timeTimeRound {
() => {
// Module: crate::civil::time
// Provides: {"TimeRound"}
// Dependencies: {}
# [doc = " Options for [`Time::round`]."] # [doc = ""] # [doc = " This type provides a way to configure the rounding of a civil time."] # [doc = " In particular, `Time::round` accepts anything that implements the"] # [doc = " `Into<TimeRound>` trait. There are some trait implementations that"] # [doc = " therefore make calling `Time::round` in some common cases more ergonomic:"] # [doc = ""] # [doc = " * `From<Unit> for TimeRound` will construct a rounding configuration that"] # [doc = " rounds to the unit given. Specifically, `TimeRound::new().smallest(unit)`."] # [doc = " * `From<(Unit, i64)> for TimeRound` is like the one above, but also"] # [doc = " specifies the rounding increment for [`TimeRound::increment`]."] # [doc = ""] # [doc = " Note that in the default configuration, no rounding occurs."] # [doc = ""] # [doc = " # Example"] # [doc = ""] # [doc = " This example shows how to round a time to the nearest second:"] # [doc = ""] # [doc = " ```"] # [doc = " use jiff::{civil::{Time, time}, Unit};"] # [doc = ""] # [doc = " let t: Time = \"16:24:59.5\".parse()?;"] # [doc = " assert_eq!("] # [doc = "     t.round(Unit::Second)?,"] # [doc = "     // The second rounds up and causes minutes to increase."] # [doc = "     time(16, 25, 0, 0),"] # [doc = " );"] # [doc = ""] # [doc = " # Ok::<(), Box<dyn std::error::Error>>(())"] # [doc = " ```"] # [doc = ""] # [doc = " The above makes use of the fact that `Unit` implements"] # [doc = " `Into<TimeRound>`. If you want to change the rounding mode to, say,"] # [doc = " truncation, then you'll need to construct a `TimeRound` explicitly"] # [doc = " since there are no convenience `Into` trait implementations for"] # [doc = " [`RoundMode`]."] # [doc = ""] # [doc = " ```"] # [doc = " use jiff::{civil::{Time, TimeRound, time}, RoundMode, Unit};"] # [doc = ""] # [doc = " let t: Time = \"2024-06-20 16:24:59.5\".parse()?;"] # [doc = " assert_eq!("] # [doc = "     t.round("] # [doc = "         TimeRound::new().smallest(Unit::Second).mode(RoundMode::Trunc),"] # [doc = "     )?,"] # [doc = "     // The second just gets truncated as if it wasn't there."] # [doc = "     time(16, 24, 59, 0),"] # [doc = " );"] # [doc = ""] # [doc = " # Ok::<(), Box<dyn std::error::Error>>(())"] # [doc = " ```"] # [derive (Clone , Copy , Debug)] pub struct TimeRound { smallest : Unit , mode : RoundMode , increment : i64 , }
};
}
