// Generated macro for layer_fn (function)
macro_rules! Depcrate_layer_fnlayer_fn {
() => {
// Module: crate::layer_fn
// Provides: {"layer_fn"}
// Dependencies: {}
# [doc = " Returns a new [`LayerFn`] that implements [`Layer`] by calling the"] # [doc = " given function."] # [doc = ""] # [doc = " The [`Layer::layer()`] method takes a type implementing [`Service`] and"] # [doc = " returns a different type implementing [`Service`]. In many cases, this can"] # [doc = " be implemented by a function or a closure. The [`LayerFn`] helper allows"] # [doc = " writing simple [`Layer`] implementations without needing the boilerplate of"] # [doc = " a new struct implementing [`Layer`]."] # [doc = ""] # [doc = " [`Service`]: https://docs.rs/tower-service/latest/tower_service/trait.Service.html"] # [doc = " [`Layer::layer()`]: crate::Layer::layer"] # [doc = ""] # [doc = " # Examples"] # [doc = ""] # [doc = " ```rust"] # [doc = " # use tower::Service;"] # [doc = " # use core::task::{Poll, Context};"] # [doc = " # use tower_layer::{Layer, layer_fn};"] # [doc = " # use core::fmt;"] # [doc = " # use core::convert::Infallible;"] # [doc = " #"] # [doc = " // A middleware that logs requests before forwarding them to another service"] # [doc = " pub struct LogService<S> {"] # [doc = "     target: &'static str,"] # [doc = "     service: S,"] # [doc = " }"] # [doc = ""] # [doc = " impl<S, Request> Service<Request> for LogService<S>"] # [doc = " where"] # [doc = "     S: Service<Request>,"] # [doc = "     Request: fmt::Debug,"] # [doc = " {"] # [doc = "     type Response = S::Response;"] # [doc = "     type Error = S::Error;"] # [doc = "     type Future = S::Future;"] # [doc = ""] # [doc = "     fn poll_ready(&mut self, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {"] # [doc = "         self.service.poll_ready(cx)"] # [doc = "     }"] # [doc = ""] # [doc = "     fn call(&mut self, request: Request) -> Self::Future {"] # [doc = "         // Log the request"] # [doc = "         println!(\"request = {:?}, target = {:?}\", request, self.target);"] # [doc = ""] # [doc = "         self.service.call(request)"] # [doc = "     }"] # [doc = " }"] # [doc = ""] # [doc = " // A `Layer` that wraps services in `LogService`"] # [doc = " let log_layer = layer_fn(|service| {"] # [doc = "     LogService {"] # [doc = "         service,"] # [doc = "         target: \"tower-docs\","] # [doc = "     }"] # [doc = " });"] # [doc = ""] # [doc = " // An example service. This one uppercases strings"] # [doc = " let uppercase_service = tower::service_fn(|request: String| async move {"] # [doc = "     Ok::<_, Infallible>(request.to_uppercase())"] # [doc = " });"] # [doc = ""] # [doc = " // Wrap our service in a `LogService` so requests are logged."] # [doc = " let wrapped_service = log_layer.layer(uppercase_service);"] # [doc = " ```"] pub fn layer_fn < T > (f : T) -> LayerFn < T > { LayerFn { f } }
};
}
