// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_digest_decls_module_not_found_dev,
    wrapped_digest_decls_module_not_found_block_api,
    wrapped_digest_decls_module_not_found_buffer_macros,
    wrapped_digest_decls_module_not_found_digest,
    wrapped_digest_decls_module_not_found_mac,
    wrapped_digest_decls_module_not_found_xof_fixed,
    wrapped_digest_decls_Update,
    wrapped_digest_decls_FixedOutput,
    wrapped_digest_decls_FixedOutputReset,
    wrapped_digest_decls_XofReader,
    wrapped_digest_decls_ExtendableOutput,
    wrapped_digest_decls_ExtendableOutputReset,
    wrapped_digest_decls_CustomizedInit,
    wrapped_digest_decls_CollisionResistance,
    wrapped_digest_decls_InvalidOutputSize,
    wrapped_digest_decls_impl_for_fmt_Display,
    wrapped_digest_decls_impl_for_core_error_Error,
    wrapped_digest_decls_InvalidBufferSize,
    wrapped_digest_decls_impl_for_fmt_Display,
    wrapped_digest_decls_impl_for_core_error_Error
);
