// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Trait for hash functions with extendable-output (XOF)."]
pub trait ExtendableOutput: Sized + Update {
    #[doc = " Reader"]
    type Reader: XofReader;
    #[doc = " Retrieve XOF reader and consume hasher instance."]
    fn finalize_xof(self) -> Self::Reader;
    #[doc = " Finalize XOF and write result into `out`."]
    fn finalize_xof_into(self, out: &mut [u8]) {
        self.finalize_xof().read(out);
    }
    #[doc = " Compute hash of `data` and write it into `output`."]
    fn digest_xof(input: impl AsRef<[u8]>, output: &mut [u8])
    where
        Self: Default,
    {
        let mut hasher = Self::default();
        hasher.update(input.as_ref());
        hasher.finalize_xof().read(output);
    }
    #[doc = " Retrieve result into a boxed slice of the specified size and consume"]
    #[doc = " the hasher."]
    #[doc = ""]
    #[doc = " `Box<[u8]>` is used instead of `Vec<u8>` to save stack space, since"]
    #[doc = " they have size of 2 and 3 words respectively."]
    #[cfg(feature = "alloc")]
    fn finalize_boxed(self, output_size: usize) -> Box<[u8]> {
        let mut buf = vec![0u8; output_size].into_boxed_slice();
        self.finalize_xof().read(&mut buf);
        buf
    }
}
