// Generated macro for other_1457 (other)
macro_rules! Depcrate_features_gen_DateTimeValueother_1457 {
() => {
// Module: crate::features::gen_DateTimeValue
// Provides: {"other_1457"}
// Dependencies: {}
# [wasm_bindgen] extern "C" { # [wasm_bindgen (extends = :: js_sys :: Object , js_name = DateTimeValue)] # [derive (Debug , Clone , PartialEq , Eq)] # [doc = "The `DateTimeValue` dictionary."] # [doc = ""] # [doc = "*This API requires the following crate features to be activated: `DateTimeValue`*"] pub type DateTimeValue ; # [doc = "Get the `day` field of this object."] # [doc = ""] # [doc = "*This API requires the following crate features to be activated: `DateTimeValue`*"] # [wasm_bindgen (method , getter = "day")] pub fn get_day (this : & DateTimeValue) -> Option < i32 > ; # [doc = "Change the `day` field of this object."] # [doc = ""] # [doc = "*This API requires the following crate features to be activated: `DateTimeValue`*"] # [wasm_bindgen (method , setter = "day")] pub fn set_day (this : & DateTimeValue , val : i32) ; # [doc = "Get the `hour` field of this object."] # [doc = ""] # [doc = "*This API requires the following crate features to be activated: `DateTimeValue`*"] # [wasm_bindgen (method , getter = "hour")] pub fn get_hour (this : & DateTimeValue) -> Option < i32 > ; # [doc = "Change the `hour` field of this object."] # [doc = ""] # [doc = "*This API requires the following crate features to be activated: `DateTimeValue`*"] # [wasm_bindgen (method , setter = "hour")] pub fn set_hour (this : & DateTimeValue , val : i32) ; # [doc = "Get the `minute` field of this object."] # [doc = ""] # [doc = "*This API requires the following crate features to be activated: `DateTimeValue`*"] # [wasm_bindgen (method , getter = "minute")] pub fn get_minute (this : & DateTimeValue) -> Option < i32 > ; # [doc = "Change the `minute` field of this object."] # [doc = ""] # [doc = "*This API requires the following crate features to be activated: `DateTimeValue`*"] # [wasm_bindgen (method , setter = "minute")] pub fn set_minute (this : & DateTimeValue , val : i32) ; # [doc = "Get the `month` field of this object."] # [doc = ""] # [doc = "*This API requires the following crate features to be activated: `DateTimeValue`*"] # [wasm_bindgen (method , getter = "month")] pub fn get_month (this : & DateTimeValue) -> Option < i32 > ; # [doc = "Change the `month` field of this object."] # [doc = ""] # [doc = "*This API requires the following crate features to be activated: `DateTimeValue`*"] # [wasm_bindgen (method , setter = "month")] pub fn set_month (this : & DateTimeValue , val : i32) ; # [doc = "Get the `year` field of this object."] # [doc = ""] # [doc = "*This API requires the following crate features to be activated: `DateTimeValue`*"] # [wasm_bindgen (method , getter = "year")] pub fn get_year (this : & DateTimeValue) -> Option < i32 > ; # [doc = "Change the `year` field of this object."] # [doc = ""] # [doc = "*This API requires the following crate features to be activated: `DateTimeValue`*"] # [wasm_bindgen (method , setter = "year")] pub fn set_year (this : & DateTimeValue , val : i32) ; }
};
}
