// Generated macro for other_2570 (other)
macro_rules! Depcrate_features_gen_GpuBindGroupLayoutDescriptorother_2570 {
() => {
// Module: crate::features::gen_GpuBindGroupLayoutDescriptor
// Provides: {"other_2570"}
// Dependencies: {}
# [cfg (web_sys_unstable_apis)] # [wasm_bindgen] extern "C" { # [wasm_bindgen (extends = :: js_sys :: Object , js_name = GPUBindGroupLayoutDescriptor)] # [derive (Debug , Clone , PartialEq , Eq)] # [doc = "The `GpuBindGroupLayoutDescriptor` dictionary."] # [doc = ""] # [doc = "*This API requires the following crate features to be activated: `GpuBindGroupLayoutDescriptor`*"] # [doc = ""] # [doc = "*This API is unstable and requires `--cfg=web_sys_unstable_apis` to be activated, as"] # [doc = "[described in the `wasm-bindgen` guide](https://wasm-bindgen.github.io/wasm-bindgen/web-sys/unstable-apis.html)*"] pub type GpuBindGroupLayoutDescriptor ; # [cfg (web_sys_unstable_apis)] # [doc = "Get the `label` field of this object."] # [doc = ""] # [doc = "*This API requires the following crate features to be activated: `GpuBindGroupLayoutDescriptor`*"] # [doc = ""] # [doc = "*This API is unstable and requires `--cfg=web_sys_unstable_apis` to be activated, as"] # [doc = "[described in the `wasm-bindgen` guide](https://wasm-bindgen.github.io/wasm-bindgen/web-sys/unstable-apis.html)*"] # [wasm_bindgen (method , getter = "label")] pub fn get_label (this : & GpuBindGroupLayoutDescriptor) -> Option < :: alloc :: string :: String > ; # [cfg (web_sys_unstable_apis)] # [doc = "Change the `label` field of this object."] # [doc = ""] # [doc = "*This API requires the following crate features to be activated: `GpuBindGroupLayoutDescriptor`*"] # [doc = ""] # [doc = "*This API is unstable and requires `--cfg=web_sys_unstable_apis` to be activated, as"] # [doc = "[described in the `wasm-bindgen` guide](https://wasm-bindgen.github.io/wasm-bindgen/web-sys/unstable-apis.html)*"] # [wasm_bindgen (method , setter = "label")] pub fn set_label (this : & GpuBindGroupLayoutDescriptor , val : & str) ; # [cfg (web_sys_unstable_apis)] # [doc = "Get the `entries` field of this object."] # [doc = ""] # [doc = "*This API requires the following crate features to be activated: `GpuBindGroupLayoutDescriptor`*"] # [doc = ""] # [doc = "*This API is unstable and requires `--cfg=web_sys_unstable_apis` to be activated, as"] # [doc = "[described in the `wasm-bindgen` guide](https://wasm-bindgen.github.io/wasm-bindgen/web-sys/unstable-apis.html)*"] # [wasm_bindgen (method , getter = "entries")] pub fn get_entries (this : & GpuBindGroupLayoutDescriptor) -> :: js_sys :: Array ; # [cfg (web_sys_unstable_apis)] # [doc = "Change the `entries` field of this object."] # [doc = ""] # [doc = "*This API requires the following crate features to be activated: `GpuBindGroupLayoutDescriptor`*"] # [doc = ""] # [doc = "*This API is unstable and requires `--cfg=web_sys_unstable_apis` to be activated, as"] # [doc = "[described in the `wasm-bindgen` guide](https://wasm-bindgen.github.io/wasm-bindgen/web-sys/unstable-apis.html)*"] # [wasm_bindgen (method , setter = "entries")] pub fn set_entries (this : & GpuBindGroupLayoutDescriptor , val : & :: wasm_bindgen :: JsValue) ; }
};
}
