// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
trait SrcToken<Ctx, S> {
    fn kind(&self, ctx: &Ctx) -> SyntaxKind;
    fn to_char(&self, ctx: &Ctx) -> Option<char>;
    fn to_text(&self, ctx: &Ctx) -> SmolStr;
    fn as_leaf(&self) -> Option<&tt::Leaf<S>> {
        None
    }
}
