[package]
name = "rustc_expand_base_lib_custom_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
synstructure = "0.13.0"
rustc_macros = { workspace = true } # Dependency to call the original rustc_macros
