// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_prettyplease_decls_module_not_found_algorithm,
    wrapped_prettyplease_decls_module_not_found_attr,
    wrapped_prettyplease_decls_module_not_found_classify,
    wrapped_prettyplease_decls_module_not_found_convenience,
    wrapped_prettyplease_decls_module_not_found_data,
    wrapped_prettyplease_decls_module_not_found_expr,
    wrapped_prettyplease_decls_module_not_found_file,
    wrapped_prettyplease_decls_module_not_found_fixup,
    wrapped_prettyplease_decls_module_not_found_generics,
    wrapped_prettyplease_decls_module_not_found_item,
    wrapped_prettyplease_decls_module_not_found_iter,
    wrapped_prettyplease_decls_module_not_found_lifetime,
    wrapped_prettyplease_decls_module_not_found_lit,
    wrapped_prettyplease_decls_module_not_found_mac,
    wrapped_prettyplease_decls_module_not_found_pat,
    wrapped_prettyplease_decls_module_not_found_path,
    wrapped_prettyplease_decls_module_not_found_precedence,
    wrapped_prettyplease_decls_module_not_found_ring,
    wrapped_prettyplease_decls_module_not_found_stmt,
    wrapped_prettyplease_decls_module_not_found_token,
    wrapped_prettyplease_decls_module_not_found_ty,
    wrapped_prettyplease_decls_MARGIN,
    wrapped_prettyplease_decls_INDENT,
    wrapped_prettyplease_decls_MIN_SPACE,
    wrapped_prettyplease_decls_unparse
);
