// Generated macro for impl_100 (impl)
macro_rules! Depcrate_stream_buf_readerimpl_100 {
() => {
// Module: crate::stream::buf_reader
// Provides: {"impl_100"}
// Dependencies: {}
impl < R > BufReader < R > { # [doc = " Creates a new `BufReader` with a default buffer capacity. The default is currently 8 KB,"] # [doc = " but may change in the future."] pub fn new (inner : R) -> Self { Self :: with_capacity (8096 , inner) } # [doc = " Creates a new `BufReader` with the specified buffer capacity."] pub fn with_capacity (capacity : usize , inner : R) -> Self { let buf = BytesMut :: with_capacity (capacity) ; Self { inner , buf } } # [doc = " Gets a reference to the underlying reader."] # [doc = ""] # [doc = " It is inadvisable to directly read from the underlying reader."] pub fn get_ref (& self) -> & R { & self . inner } # [doc = " Gets a mutable reference to the underlying reader."] # [doc = ""] # [doc = " It is inadvisable to directly read from the underlying reader."] pub fn get_mut (& mut self) -> & mut R { & mut self . inner } # [cfg (feature = "pin-project-lite")] # [doc = " Gets a pinned mutable reference to the underlying reader."] # [doc = ""] # [doc = " It is inadvisable to directly read from the underlying reader."] pub fn get_pin_mut (self : Pin < & mut Self >) -> Pin < & mut R > { self . project () . inner } # [doc = " Consumes this `BufWriter`, returning the underlying reader."] # [doc = ""] # [doc = " Note that any leftover data in the internal buffer is lost."] pub fn into_inner (self) -> R { self . inner } # [doc = " Returns a reference to the internally buffered data."] # [doc = ""] # [doc = " Unlike `fill_buf`, this will not attempt to fill the buffer if it is empty."] pub fn buffer (& self) -> & [u8] { & self . buf } # [doc = " Invalidates all data in the internal buffer."] # [inline] # [cfg (any (feature = "tokio-02" , feature = "tokio-03" , feature = "tokio"))] fn discard_buffer (self : Pin < & mut Self >) { let me = self . project () ; me . buf . clear () ; } }
};
}
