// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35 
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros :: decl_module ; decl_module ! (wrapped_cpufeatures_decls_module_not_found_aarch64 , wrapped_cpufeatures_decls_module_not_found_loongarch64 , wrapped_cpufeatures_decls_module_not_found_x86 , wrapped_cpufeatures_decls_module_not_found_miri , wrapped_cpufeatures_decls_compile_error , wrapped_cpufeatures_decls_macro_rules) ;