// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_gemini_rustc_data_structures_decls_thread_local,
    wrapped_gemini_rustc_data_structures_decls_SerializableDiagnostic,
    wrapped_gemini_rustc_data_structures_decls_SerializableSpan,
    wrapped_gemini_rustc_data_structures_decls_add_diagnostic,
    wrapped_gemini_rustc_data_structures_decls_clear_diagnostics,
    wrapped_gemini_rustc_data_structures_decls_get_diagnostics
);
