// Generated macro for impl_9807 (impl)
macro_rules! Depcrate_swapimpl_9807 {
() => {
// Module: crate::swap
// Provides: {"impl_9807"}
// Dependencies: {}
impl < 'tcx > IndexBinding < '_ , 'tcx > { fn snippet_index_bindings (& mut self , exprs : & [& 'tcx Expr < 'tcx >]) -> String { let mut bindings = FxIndexSet :: default () ; for expr in exprs { bindings . insert (self . snippet_index_binding (expr)) ; } bindings . into_iter () . join ("") } fn snippet_index_binding (& mut self , expr : & 'tcx Expr < 'tcx >) -> String { match expr . kind { ExprKind :: Binary (_ , lhs , rhs) => { if matches ! (lhs . kind , ExprKind :: Lit (_)) && matches ! (rhs . kind , ExprKind :: Lit (_)) { return String :: new () ; } let lhs_snippet = self . snippet_index_binding (lhs) ; let rhs_snippet = self . snippet_index_binding (rhs) ; format ! ("{lhs_snippet}{rhs_snippet}") } , ExprKind :: Path (QPath :: Resolved (_ , path)) => { let Some (first_segment) = path . segments . first () else { return String :: new () ; } ; let init = self . cx . expr_or_init (expr) ; if ! self . suggest_span . contains (init . span) || path_to_local (expr) . is_some_and (| hir_id | ! self . suggest_span . contains (self . cx . tcx . hir_span (hir_id))) || ! self . is_used_other_than_swapping (first_segment . ident) { return String :: new () ; } let init_str = snippet_with_context (self . cx , init . span , self . ctxt , "" , self . applicability) . 0 . to_string () ; let indent_str = snippet_indent (self . cx , init . span) ; let indent_str = indent_str . as_deref () . unwrap_or ("") ; format ! ("let {} = {init_str};\n{indent_str}" , first_segment . ident) } , _ => String :: new () , } } fn is_used_other_than_swapping (& self , idx_ident : Ident) -> bool { if Self :: is_used_slice_indexed (self . swap1_idx , idx_ident) || Self :: is_used_slice_indexed (self . swap2_idx , idx_ident) { return true ; } self . is_used_after_swap (idx_ident) } fn is_used_after_swap (& self , idx_ident : Ident) -> bool { let mut v = IndexBindingVisitor { idx : idx_ident , suggest_span : self . suggest_span , found_used : false , } ; for stmt in self . block . stmts { match stmt . kind { StmtKind :: Expr (expr) | StmtKind :: Semi (expr) => v . visit_expr (expr) , StmtKind :: Let (LetStmt { init , .. }) => { if let Some (init) = init . as_ref () { v . visit_expr (init) ; } } , StmtKind :: Item (_) => { } , } } v . found_used } fn is_used_slice_indexed (swap_index : & Expr < '_ > , idx_ident : Ident) -> bool { match swap_index . kind { ExprKind :: Binary (_ , lhs , rhs) => { if matches ! (lhs . kind , ExprKind :: Lit (_)) && matches ! (rhs . kind , ExprKind :: Lit (_)) { return false ; } Self :: is_used_slice_indexed (lhs , idx_ident) || Self :: is_used_slice_indexed (rhs , idx_ident) } , ExprKind :: Path (QPath :: Resolved (_ , path)) => path . segments . first () . is_some_and (| idx | idx . ident == idx_ident) , _ => false , } } }
};
}
