// Generated macro for check (function)
macro_rules! Depcrate_methods_unnecessary_filter_mapcheck {
() => {
// Module: crate::methods::unnecessary_filter_map
// Provides: {"check"}
// Dependencies: {}
pub (super) fn check < 'tcx > (cx : & LateContext < 'tcx > , expr : & 'tcx hir :: Expr < 'tcx > , arg : & 'tcx hir :: Expr < 'tcx > , call_span : Span , kind : Kind ,) { if ! cx . ty_based_def (expr) . opt_parent (cx) . is_diag_item (cx , sym :: Iterator) { return ; } if let hir :: ExprKind :: Closure (& hir :: Closure { body , .. }) = arg . kind { let body = cx . tcx . hir_body (body) ; let arg_id = body . params [0] . pat . hir_id ; let mutates_arg = mutated_variables (body . value , cx) . is_none_or (| used_mutably | used_mutably . contains (& arg_id)) ; let (clone_or_copy_needed , _) = clone_or_copy_needed (cx , body . params [0] . pat , body . value) ; let (mut found_mapping , mut found_filtering) = check_expression (cx , arg_id , body . value) ; let _ : Option < ! > = for_each_expr_without_closures (body . value , | e | { if let hir :: ExprKind :: Ret (Some (e)) = & e . kind { let (found_mapping_res , found_filtering_res) = check_expression (cx , arg_id , e) ; found_mapping |= found_mapping_res ; found_filtering |= found_filtering_res ; ControlFlow :: Continue (Descend :: No) } else { ControlFlow :: Continue (Descend :: Yes) } }) ; let in_ty = cx . typeck_results () . node_type (body . params [0] . hir_id) ; let sugg = if ! found_filtering { if kind . is_filter_map () && let Some (arg) = as_some_expr (cx , body . value) && let hir :: ExprKind :: Path (_) = arg . kind { span_lint (cx , UNNECESSARY_FILTER_MAP , call_span , String :: from ("this call to `.filter_map(..)` is unnecessary") ,) ; return ; } match kind { Kind :: FilterMap => "map(..)" , Kind :: FindMap => "map(..).next()" , } } else if ! found_mapping && ! mutates_arg && (! clone_or_copy_needed || is_copy (cx , in_ty)) { let ty = cx . typeck_results () . expr_ty (body . value) ; if option_arg_ty (cx , ty) . is_some_and (| t | t == in_ty) { match kind { Kind :: FilterMap => "filter(..)" , Kind :: FindMap => "find(..)" , } } else { return ; } } else { return ; } ; span_lint (cx , match kind { Kind :: FilterMap => UNNECESSARY_FILTER_MAP , Kind :: FindMap => UNNECESSARY_FIND_MAP , } , call_span , format ! ("this `.{kind}(..)` can be written more simply using `.{sugg}`") ,) ; } }
};
}
