// Generated macro for impl_616 (impl)
macro_rules! Depcrate_ule_multiimpl_616 {
() => {
// Module: crate::ule::multi
// Provides: {"impl_616"}
// Dependencies: {}
impl < const LEN : usize , Format : VarZeroVecFormat > MultiFieldsULE < LEN , Format > { # [doc = " Compute the amount of bytes needed to support elements with lengths `lengths`"] # [inline] # [expect (clippy :: expect_used)] pub fn compute_encoded_len_for (lengths : [usize ; LEN]) -> usize { let lengths = lengths . map (BlankSliceEncoder) ; crate :: varzerovec :: components :: compute_serializable_len_without_length :: < _ , _ , Format > (& lengths ,) . expect ("Too many bytes to encode") as usize } # [doc = " Construct a partially initialized MultiFieldsULE backed by a mutable byte buffer"] pub fn new_from_lengths_partially_initialized < 'a > (lengths : [usize ; LEN] , output : & 'a mut [u8] ,) -> & 'a mut Self { let lengths = lengths . map (BlankSliceEncoder) ; crate :: varzerovec :: components :: write_serializable_bytes_without_length :: < _ , _ , Format > (& lengths , output ,) ; debug_assert ! (< VarZeroLengthlessSlice < [u8] , Format >>:: parse_bytes (LEN as u32 , output) . is_ok () , "Encoded slice must be valid VarZeroSlice") ; unsafe { let slice = < VarZeroLengthlessSlice < [u8] , Format > > :: from_bytes_unchecked_mut (output) ; mem :: transmute :: < & mut VarZeroLengthlessSlice < [u8] , Format > , & mut Self > (slice) } } # [doc = " Given a buffer of size obtained by [`Self::compute_encoded_len_for()`], write element A to index idx"] # [doc = ""] # [doc = " # Safety"] # [doc = " - `idx` must be in range"] # [doc = " - `T` must be the appropriate type expected by the custom derive in this usage of this type"] # [inline] pub unsafe fn set_field_at < T : VarULE + ? Sized , A : EncodeAsVarULE < T > + ? Sized > (& mut self , idx : usize , value : & A ,) { value . encode_var_ule_write (self . 0 . get_bytes_at_mut (LEN as u32 , idx)) } # [doc = " Validate field at `index` to see if it is a valid `T` VarULE type"] # [doc = ""] # [doc = " # Safety"] # [doc = ""] # [doc = " - `index` must be in range"] # [inline] pub unsafe fn validate_field < T : VarULE + ? Sized > (& self , index : usize) -> Result < () , UleError > { T :: validate_bytes (self . 0 . get_unchecked (LEN as u32 , index)) } # [doc = " Get field at `index` as a value of type T"] # [doc = ""] # [doc = " # Safety"] # [doc = ""] # [doc = " - `index` must be in range"] # [doc = " - Element at `index` must have been created with the VarULE type T"] # [inline] pub unsafe fn get_field < T : VarULE + ? Sized > (& self , index : usize) -> & T { T :: from_bytes_unchecked (self . 0 . get_unchecked (LEN as u32 , index)) } # [doc = " Construct from a byte slice"] # [doc = ""] # [doc = " # Safety"] # [doc = " - byte slice must be a valid VarZeroLengthlessSlice<[u8], Format> with length LEN"] # [inline] pub unsafe fn from_bytes_unchecked (bytes : & [u8]) -> & Self { mem :: transmute (< VarZeroLengthlessSlice < [u8] , Format > > :: from_bytes_unchecked (bytes)) } # [doc = " Get the bytes behind this value"] pub fn as_bytes (& self) -> & [u8] { self . 0 . as_bytes () } }
};
}
