// Generated macro for UntaggedEnumVisitor (struct)
macro_rules! DepcrateUntaggedEnumVisitor {
() => {
// Module: crate
// Provides: {"UntaggedEnumVisitor"}
// Dependencies: {}
pub struct UntaggedEnumVisitor < 'closure , 'de , Value > { expecting : Option < Box < dyn Display + 'closure > > , visit_bool : Option < Box < dyn FnOnce (bool) -> Result < Value , Error > + 'closure > > , visit_i8 : Option < Box < dyn FnOnce (i8) -> Result < Value , Error > + 'closure > > , visit_i16 : Option < Box < dyn FnOnce (i16) -> Result < Value , Error > + 'closure > > , visit_i32 : Option < Box < dyn FnOnce (i32) -> Result < Value , Error > + 'closure > > , visit_i64 : Option < Box < dyn FnOnce (i64) -> Result < Value , Error > + 'closure > > , visit_i128 : Option < Box < dyn FnOnce (i128) -> Result < Value , Error > + 'closure > > , visit_u8 : Option < Box < dyn FnOnce (u8) -> Result < Value , Error > + 'closure > > , visit_u16 : Option < Box < dyn FnOnce (u16) -> Result < Value , Error > + 'closure > > , visit_u32 : Option < Box < dyn FnOnce (u32) -> Result < Value , Error > + 'closure > > , visit_u64 : Option < Box < dyn FnOnce (u64) -> Result < Value , Error > + 'closure > > , visit_u128 : Option < Box < dyn FnOnce (u128) -> Result < Value , Error > + 'closure > > , visit_f32 : Option < Box < dyn FnOnce (f32) -> Result < Value , Error > + 'closure > > , visit_f64 : Option < Box < dyn FnOnce (f64) -> Result < Value , Error > + 'closure > > , visit_char : Option < Box < dyn FnOnce (char) -> Result < Value , Error > + 'closure > > , visit_str : Option < Box < dyn FnOnce (& str) -> Result < Value , Error > + 'closure > > , visit_borrowed_str : Option < Box < dyn FnOnce (& 'de str) -> Result < Value , Error > + 'closure > > , visit_bytes : Option < Box < dyn FnOnce (& [u8]) -> Result < Value , Error > + 'closure > > , visit_borrowed_bytes : Option < Box < dyn FnOnce (& 'de [u8]) -> Result < Value , Error > + 'closure > > , visit_byte_buf : Option < Box < dyn FnOnce (Vec < u8 >) -> Result < Value , Error > + 'closure > > , visit_none : Option < Box < dyn FnOnce () -> Result < Value , Error > + 'closure > > , visit_unit : Option < Box < dyn FnOnce () -> Result < Value , Error > + 'closure > > , visit_seq : Option < Box < dyn for < 'access > FnOnce (Seq < 'access , 'de >) -> Result < Value , Error > + 'closure > > , visit_map : Option < Box < dyn for < 'access > FnOnce (Map < 'access , 'de >) -> Result < Value , Error > + 'closure > > , }
};
}
