// Generated macro for get_return_data (function)
macro_rules! Depcrate_cpiget_return_data {
() => {
// Module: crate::cpi
// Provides: {"get_return_data"}
// Dependencies: {}
# [doc = " Get the return data from an invoked program."] # [doc = ""] # [doc = " For every transaction there is a single buffer with maximum length"] # [doc = " [`MAX_RETURN_DATA`], paired with an [`Address`] representing the program ID of"] # [doc = " the program that most recently set the return data. Thus the return data is"] # [doc = " a global resource and care must be taken to ensure that it represents what"] # [doc = " is expected: called programs are free to set or not set the return data; and"] # [doc = " the return data may represent values set by programs multiple calls down the"] # [doc = " call stack, depending on the circumstances of transaction execution."] # [doc = ""] # [doc = " Return data is set by the callee with [`set_return_data`]."] # [doc = ""] # [doc = " Return data is cleared before every CPI invocation - a program that"] # [doc = " has invoked no other programs can expect the return data to be `None`; if no"] # [doc = " return data was set by the previous CPI invocation, then this function"] # [doc = " returns `None`."] # [doc = ""] # [doc = " Return data is not cleared after returning from CPI invocations. A"] # [doc = " program that has called another program may retrieve return data that was"] # [doc = " not set by the called program, but instead set by a program further down the"] # [doc = " call stack; or, if a program calls itself recursively, it is possible that"] # [doc = " the return data was not set by the immediate call to that program, but by a"] # [doc = " subsequent recursive call to that program. Likewise, an external RPC caller"] # [doc = " may see return data that was not set by the program it is directly calling,"] # [doc = " but by a program that program called."] # [doc = ""] # [doc = " For more about return data see the [documentation for the return data proposal][rdp]."] # [doc = ""] # [doc = " [rdp]: https://docs.solanalabs.com/proposals/return-data"] # [inline] pub fn get_return_data () -> Option < ReturnData > { # [cfg (any (target_os = "solana" , target_arch = "bpf"))] { const UNINIT_BYTE : MaybeUninit < u8 > = MaybeUninit :: < u8 > :: uninit () ; let mut data = [UNINIT_BYTE ; MAX_RETURN_DATA] ; let mut program_id = MaybeUninit :: < Address > :: uninit () ; let size = unsafe { sol_get_return_data (data . as_mut_ptr () as * mut u8 , data . len () as u64 , program_id . as_mut_ptr () as * mut _ as * mut u8 ,) } ; if size == 0 { None } else { Some (ReturnData { program_id : unsafe { program_id . assume_init () } , data , size : core :: cmp :: min (size as usize , MAX_RETURN_DATA) , }) } } # [cfg (not (any (target_os = "solana" , target_arch = "bpf")))] core :: hint :: black_box (None) }
};
}
