// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " A `syn::visit::Visit` implementation to extract `Declaration`s from a `syn::File`."]
#[derive(Debug, Default)]
struct AstDeclarationVisitor {
    declarations: Vec<Declaration>,
    current_file_path: PathBuf,
}
