// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_fluent_bundle_decls_module_not_found_args,
    wrapped_fluent_bundle_decls_module_not_found_builtins,
    wrapped_fluent_bundle_decls_module_not_found_bundle,
    wrapped_fluent_bundle_decls_module_not_found_concurrent,
    wrapped_fluent_bundle_decls_module_not_found_entry,
    wrapped_fluent_bundle_decls_module_not_found_errors,
    wrapped_fluent_bundle_decls_module_not_found_memoizer,
    wrapped_fluent_bundle_decls_module_not_found_message,
    wrapped_fluent_bundle_decls_module_not_found_resolver,
    wrapped_fluent_bundle_decls_module_not_found_resource,
    wrapped_fluent_bundle_decls_module_not_found_types,
    wrapped_fluent_bundle_decls_FluentBundle
);
