// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_base64ct_decls_module_not_found_alphabet,
    wrapped_base64ct_decls_module_not_found_decoder,
    wrapped_base64ct_decls_module_not_found_encoder,
    wrapped_base64ct_decls_module_not_found_encoding,
    wrapped_base64ct_decls_module_not_found_errors,
    wrapped_base64ct_decls_module_not_found_line_ending,
    wrapped_base64ct_decls_module_not_found_test_vectors,
    wrapped_base64ct_decls_MIN_LINE_WIDTH
);
