// Generated by unified_build.rs
#![feature(rustc_attrs)]
#![feature(dropck_eyepatch)]
#![feature(ascii_char_variants)]
#![feature(ascii_char)]
#![feature(auto_traits)]
#![feature(specialization)]
#![feature(never_type)]
#![feature(cfg_select)]
#![feature(ptr_alignment_type)]
#![feature(negative_impls)]

// tidy-alphabetical-start
// tidy-alphabetical-end

mod build;
mod errors;
// FIXME(Nilstrieb) Translate macro_rules diagnostics
#[allow(rustc::untranslatable_diagnostic)]
mod mbe;
mod placeholders;
mod proc_macro_server;
mod stats;

pub use mbe::macro_rules::{MacroRulesMacroExpander, compile_declarative_macro};
pub mod base;
pub mod config;
pub mod expand;
pub mod module;
// FIXME(Nilstrieb) Translate proc_macro diagnostics
#[allow(rustc::untranslatable_diagnostic)]
pub mod proc_macro;

rustc_fluent_macro::fluent_messages! { "messages.ftl" }