// SRC: compiler/rustc_ast_pretty/src/lib.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_ast_pretty/src/lib.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_ast_pretty/src/lib.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_ast_pretty/src/lib.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_ast_pretty/src/lib.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_ast_pretty/src/lib.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_ast_pretty/src/lib.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_ast_pretty/src/lib.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_ast_pretty/src/lib.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: ../rust/compiler/rustc_ast_pretty/src/lib.rs
// tidy-alphabetical-start
#![allow(internal_features)]
#![doc(rust_logo)]
#![feature(box_patterns)]
#![feature(negative_impls)]
#![feature(rustdoc_internals)]
// tidy-alphabetical-end

// MOD DECLARATION: helpers (from compiler/rustc_ast_pretty/src/lib.rs)
// REPLACED: mod helpers; -> use crate::helpers::*;
use crate::helpers::*;
pub mod pp;
pub mod pprust;