// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_rustc_parse_format_decls_ParseMode,
    wrapped_rustc_parse_format_decls_Piece,
    wrapped_rustc_parse_format_decls_Argument,
    wrapped_rustc_parse_format_decls_impl_for_Argument,
    wrapped_rustc_parse_format_decls_FormatSpec,
    wrapped_rustc_parse_format_decls_Position,
    wrapped_rustc_parse_format_decls_impl_for_Position,
    wrapped_rustc_parse_format_decls_Alignment,
    wrapped_rustc_parse_format_decls_Sign,
    wrapped_rustc_parse_format_decls_DebugHex,
    wrapped_rustc_parse_format_decls_Count,
    wrapped_rustc_parse_format_decls_ParseError,
    wrapped_rustc_parse_format_decls_Suggestion,
    wrapped_rustc_parse_format_decls_Parser,
    wrapped_rustc_parse_format_decls_impl_for_Iterator,
    wrapped_rustc_parse_format_decls_impl_for_Parser,
    wrapped_rustc_parse_format_decls_static_assert_size,
    wrapped_rustc_parse_format_decls_module_not_found_tests
);
