// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Enum describing where an argument for a format can be located."]
#[derive(Clone, Debug, PartialEq)]
pub enum Position<'input> {
    #[doc = " The argument is implied to be located at an index"]
    ArgumentImplicitlyIs(usize),
    #[doc = " The argument is located at a specific index given in the format,"]
    ArgumentIs(usize),
    #[doc = " The argument has a name."]
    ArgumentNamed(&'input str),
}
