macro_rules! AsyncKind {
    () => {
        # [doc = " The specific async code pattern that was detected"] enum AsyncKind < 'a > { # [doc = " Immediately-invoked async fn, as generated by `async-trait <= 0.1.43`:"] # [doc = " `async fn foo<...>(...) {...}; Box::pin(foo<...>(...))`"] Function (& 'a ItemFn) , # [doc = " A function returning an async (move) block, optionally `Box::pin`-ed,"] # [doc = " as generated by `async-trait >= 0.1.44`:"] # [doc = " `Box::pin(async move { ... })`"] Async { async_expr : & 'a ExprAsync , pinned_box : bool , } , }
    };
}

AsyncKind!();