// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter.rs:211 from submodules/split-decls-rs/src/eager_splitter.rs
// Do not edit this file by hand. Your changes will be overwritten.

#[llm_error_message(message = "Module file not found for: replace")]
#[llm_context(crate_name = "wrapped_unicode_normalization", module_name = "replace")]
pub struct wrapped_unicode_normalization_decls_module_not_found_replace;
