// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter.rs:211 from submodules/split-decls-rs/src/eager_splitter.rs
// Do not edit this file by hand. Your changes will be overwritten.

#[llm_error_message(message = "Module file not found for: small_c_str")]
#[llm_context(
    crate_name = "wrapped_rustc_data_structures",
    module_name = "small_c_str"
)]
pub struct wrapped_rustc_data_structures_decls_module_not_found_small_c_str;
