// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Removes all the color tags from the given string literal."]
#[doc = ""]
#[doc = " Accepts only one argument."]
#[doc = ""]
#[doc = " #### Example"]
#[doc = ""]
#[doc = " ```"]
#[doc = " # use color_print_proc_macro::untagged;"]
#[doc = " let s: &str = untagged!(\"A <g>normal</> word\");"]
#[doc = " assert_eq!(s, \"A normal word\");"]
#[doc = " ```"]
#[proc_macro]
pub fn untagged(input: TokenStream) -> TokenStream {
    crate::untagged::get_untagged(input)
        .unwrap_or_else(|err| err.to_token_stream())
        .into()
}
