// Generated macro for IxdtfParser (struct)
macro_rules! Depcrate_parsersIxdtfParser {
() => {
// Module: crate::parsers
// Provides: {"IxdtfParser"}
// Dependencies: {}
# [doc = " `IxdtfParser` is the primary parser implementation of `ixdtf`."] # [doc = ""] # [doc = " This parser provides various options for parsing date/time strings with the extended notation"] # [doc = " laid out in [RFC9557][rfc9557] along with other variations laid out in the [`Temporal`][temporal-proposal]."] # [doc = ""] # [doc = " ```rust"] # [doc = " use ixdtf::{"] # [doc = "     parsers::IxdtfParser,"] # [doc = "     records::{Sign, TimeZoneRecord, UtcOffsetRecord},"] # [doc = " };"] # [doc = ""] # [doc = " let ixdtf_str = \"2024-03-02T08:48:00-05:00[America/New_York]\";"] # [doc = ""] # [doc = " let result = IxdtfParser::from_str(ixdtf_str).parse().unwrap();"] # [doc = ""] # [doc = " let date = result.date.unwrap();"] # [doc = " let time = result.time.unwrap();"] # [doc = " let offset = result.offset.unwrap().resolve_rfc_9557();"] # [doc = " let tz_annotation = result.tz.unwrap();"] # [doc = ""] # [doc = " assert_eq!(date.year, 2024);"] # [doc = " assert_eq!(date.month, 3);"] # [doc = " assert_eq!(date.day, 2);"] # [doc = " assert_eq!(time.hour, 8);"] # [doc = " assert_eq!(time.minute, 48);"] # [doc = " assert_eq!(offset.sign(), Sign::Negative);"] # [doc = " assert_eq!(offset.hour(), 5);"] # [doc = " assert_eq!(offset.minute(), 0);"] # [doc = " assert_eq!(offset.second(), None);"] # [doc = " assert_eq!(offset.fraction(), None);"] # [doc = " assert!(!tz_annotation.critical);"] # [doc = " assert_eq!("] # [doc = "     tz_annotation.tz,"] # [doc = "     TimeZoneRecord::Name(\"America/New_York\".as_bytes())"] # [doc = " );"] # [doc = " ```"] # [doc = ""] # [doc = " [rfc9557]: https://datatracker.ietf.org/doc/rfc9557/"] # [doc = " [temporal-proposal]: https://tc39.es/proposal-temporal/"] # [derive (Debug)] pub struct IxdtfParser < 'a , T : EncodingType > { cursor : Cursor < 'a , T > , }
};
}
