// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Struct to hold data for BottPeriodicityTrait implementations."]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct BottPeriodicityData {
    pub period: String,
    pub phi_signature: u64,
    pub monster_element: u64,
}
