// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " A trait for checking the conformity of a Declaration to Monster Group properties."]
pub trait MonsterConformityChecker {
    #[doc = " Checks if a Declaration conforms to the specified Monster Group properties."]
    #[doc = " It can optionally use BottPeriodicityTrait for enhanced soundness checks."]
    fn check_conformity(
        &self,
        declaration: &Declaration,
        bott_periodicity_checker: Option<&dyn BottPeriodicityTrait>,
        constants: &dyn MonsterConstants,
    ) -> bool;
}
