// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_windows_future_decls_module_not_found_async,
    wrapped_windows_future_decls_module_not_found_bindings,
    wrapped_windows_future_decls_module_not_found_bindings_impl,
    wrapped_windows_future_decls_module_not_found_join,
    wrapped_windows_future_decls_module_not_found_waiter,
    wrapped_windows_future_decls_module_not_found_when,
    wrapped_windows_future_decls_module_not_found_async_ready,
    wrapped_windows_future_decls_module_not_found_async_spawn,
    wrapped_windows_future_decls_module_not_found_future
);
