// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " An iterator which applies a fallible transform to the elements of the"]
#[doc = " underlying iterator."]
#[derive(Clone)]
pub struct Map<T, F> {
    it: T,
    f: F,
}
