// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " An iterator which uses a fallible predicate to determine which values of the"]
#[doc = " underlying iterator should be yielded."]
#[derive(Clone, Debug)]
pub struct Filter<I, F> {
    it: I,
    f: F,
}
