// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " An iterator which maps each element to another iterator, yielding those iterator's elements."]
#[derive(Clone, Debug)]
pub struct FlatMap<I, U, F>
where
    U: IntoFallibleIterator,
{
    it: Map<I, F>,
    cur: Option<U::IntoFallibleIter>,
}
