// Auto-generated build.rs using symbol resolver for dependency analysis
use std::collections::{HashMap, HashSet};
use std::fs;
use std::io::Write;
use std::path::Path;
use syn::{visit::Visit, File, Item, ItemUse};
use walkdir::WalkDir;

struct SymbolResolver {
    dependencies: HashMap<String, HashSet<String>>,
    current_file: String,
}

impl SymbolResolver {
    fn new() -> Self {
        Self {
            dependencies: HashMap::new(),
            current_file: String::new(),
        }
    }
}

impl<'ast> Visit<'ast> for SymbolResolver {
    fn visit_item_use(&mut self, node: &'ast ItemUse) {
        let use_path = quote::ToTokens::to_token_stream(node).to_string();
        self.dependencies
            .entry(self.current_file.clone())
            .or_insert_with(HashSet::new)
            .insert(use_path);
        syn::visit::visit_item_use(self, node);
    }
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("🔧 Analyzing rustc dependencies with symbol resolver...");
    
    let mut resolver = SymbolResolver::new();
    let mut rustc_files = Vec::new();
    
    // Scan rustc compiler directory
    let rustc_path = "../rust/compiler";
    if Path::new(rustc_path).exists() {
        for entry in WalkDir::new(rustc_path).into_iter().filter_map(|e| e.ok()) {
            if entry.file_name().to_str() == Some("lib.rs") {
                let path = entry.path();
                if let Some(parent) = path.parent() {
                    if let Some(parent_parent) = parent.parent() {
                        if let Some(crate_name) = parent_parent.file_name() {
                            let crate_name = crate_name.to_string_lossy().to_string();
                            let file_path = path.to_string_lossy().to_string();
                            rustc_files.push((crate_name, file_path));
                        }
                    }
                }
            }
        }
    }
    
    // Analyze dependencies for each file
    for (crate_name, file_path) in &rustc_files {
        resolver.current_file = crate_name.clone();
        
        if let Ok(content) = fs::read_to_string(file_path) {
            if let Ok(syntax_tree) = syn::parse_file(&content) {
                resolver.visit_file(&syntax_tree);
            }
        }
    }
    
    // Simple topological sort based on rustc_ prefix dependencies
    let mut ordered_crates = Vec::new();
    let mut processed = HashSet::new();
    
    // Add crates with minimal dependencies first
    let base_crates = ["rustc_macros", "rustc_data_structures", "rustc_index", "rustc_span"];
    for &crate_name in &base_crates {
        if rustc_files.iter().any(|(name, _)| name == crate_name) {
            ordered_crates.push(crate_name.to_string());
            processed.insert(crate_name.to_string());
        }
    }
    
    // Add remaining crates
    for (crate_name, _) in &rustc_files {
        if !processed.contains(crate_name) {
            ordered_crates.push(crate_name.clone());
            processed.insert(crate_name.clone());
        }
    }
    
    // Generate include file
    generate_include_file(&ordered_crates, &rustc_files)?;
    
    Ok(())
}

fn generate_include_file(
    ordered_crates: &[String], 
    rustc_files: &[(String, String)]
) -> Result<(), Box<dyn std::error::Error>> {
    let mut include_file = fs::File::create("src/rustc_includes.rs")?;
    
    writeln!(include_file, "// Auto-generated rustc includes in dependency order")?;
    writeln!(include_file, "// Generated by build.rs using symbol resolver")?;
    writeln!(include_file)?;
    
    // Generate preprocessed module files
    for (i, crate_name) in ordered_crates.iter().enumerate() {
        if let Some((_, file_path)) = rustc_files.iter().find(|(name, _)| name == crate_name) {
            // Read and preprocess the file
            let content = fs::read_to_string(file_path)?;
            let processed_content = content.replace("crate::", &format!("{}::", crate_name.replace("-", "_")));
            
            // Write preprocessed file
            let processed_path = format!("src/processed_{}.rs", crate_name.replace("-", "_"));
            fs::write(&processed_path, processed_content)?;
            
            writeln!(include_file, "// {}: {}", i + 1, crate_name)?;
            writeln!(include_file, "#[allow(unused_imports, dead_code, internal_features)]")?;
            writeln!(include_file, "#[path = \"{}\"]", processed_path.replace("src/", ""))?;
            writeln!(include_file, "pub mod {};", crate_name.replace("-", "_"))?;
            writeln!(include_file)?;
        }
    }
    
    println!("✅ Generated src/rustc_includes.rs with {} preprocessed crates", ordered_crates.len());
    Ok(())
}
