[package]
name = "split-decls-rs"
version = "0.1.0"
edition = "2021"
authors = []
build = "build.rs"

[dependencies]
anyhow = "1.0"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "visit", "visit-mut", "extra-traits"] }
walkdir = "2.5"
split-decls-types = { path = "split-decls-types" }
proc-macro2 = "1.0"
tempfile = "3.0"
cargo-toml-generator-types = { path = "cargo-toml-generator-types" }
sha2 = "0.10"
clap = { version = "4.0", features = ["derive"] }
cargo-toml-generator-macros = { path = "cargo-toml-generator-macros" }
cargo-toml-parts = { path = "build_helpers/cargo_toml_parts" }

[build-dependencies]
cargo-toml-generator-macros = { path = "cargo-toml-generator-macros" }
cargo-toml-generator-types = { path = "cargo-toml-generator-types" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
cargo-toml-parts = { path = "build_helpers/cargo_toml_parts" }

[[bin]]
name = "rustmacrodoc"
path = "src/bin/rustmacrodoc.rs"

[[bin]]
name = "testbuild"
path = "src/bin/testbuild.rs"

[[bin]]
name = "macro_analyzer"
path = "src/bin/macro_analyzer.rs"
