[wrapping]
crates = [
    "cargo-toml-generator-types",
    "cargo-toml-generator-macros",
    "split-decls-types",
    "split-decls-rs",
    "workspace-merge",
    "rustmacrodoc",
    "pagerank_rs",
    "reson",
    "example_crate",
    "cargo-toml-parts",
    "lib-zos",
    "test_crate",
    "unimacro_derive",
    "my_test_project",
    "introspector_decl_common",
    "introspector_decl_core",
]