// Generated macro for CustomOpts (struct)
macro_rules! Depcrate_customCustomOpts {
() => {
// Module: crate::custom
// Provides: {"CustomOpts"}
// Dependencies: {}
# [derive (Default , Debug , Clone , Parser)] pub struct CustomOpts { # [doc = " Specifies how to compile programs not natively known to this executable."] # [doc = ""] # [doc = " For example `--custom foo=my-foo-script.sh` will register that files"] # [doc = " with the extension `foo` (e.g. `test.foo`) will be compiled with"] # [doc = " `my-foo-script.sh` by this program."] # [doc = ""] # [doc = " The script specified will be invoked with its first argument as one of"] # [doc = " three values:"] # [doc = ""] # [doc = " * `prepare` - this is used to perform any one-time setup for an entire"] # [doc = "   test run, such as downloading artifacts. This has the `PREP_DIR`"] # [doc = "   environment variable set."] # [doc = ""] # [doc = " * `bindgen` - this is used to perform bindings generation for the"] # [doc = "   program at-hand. This has the `WIT`, and `BINDINGS_DIR` env"] # [doc = "   vars set."] # [doc = ""] # [doc = " * `compile` - this is used to perform an actual compilation which"] # [doc = "   creates a component. This has the `SOURCE`, `KIND`, `PREP_DIR`,"] # [doc = "   `BINDINGS_DIR`, `ARTIFACTS_DIR`, and `OUTPUT` env vars set."] # [doc = ""] # [doc = " * `verify` - this is used to verify that generated bindings are valid,"] # [doc = "   but does not create an actual component necessarily.  This has the"] # [doc = "   `WIT`, `BINDINGS_DIR`, and `ARTIFACTS_DIR` env vars set."] # [doc = ""] # [doc = " Environment variables are used to communicate various bits and pieces of"] # [doc = " data to scripts. Environment variables used are:"] # [doc = ""] # [doc = " * `PREP_DIR` - the output of the `prepare` step and also available"] # [doc = "   during the `compile` step. Used for once-per-test-run storage."] # [doc = ""] # [doc = " * `WIT` - path to a `*.wit` file during the `bindgen` step."] # [doc = ""] # [doc = " * `BINDINGS_DIR` - the output directory of `bindgen` and also inputs"] # [doc = "   to `compile`."] # [doc = ""] # [doc = " * `SOURCE` - the source file being compiled as part of `compile`."] # [doc = ""] # [doc = " * `KIND` - either `runner` or `test` as part of the `compile` step."] # [doc = ""] # [doc = " * `ARTIFACTS_DIR` - temporary directory which contains `BINDINGS_DIR`"] # [doc = "   where temporary artifacts can be stored. Part of the `compile` step."] # [doc = ""] # [doc = " * `OUTPUT` - where to place the final output component."] # [arg (long , value_name = "EXT=PATH" , value_parser = parse_custom)] pub custom : Vec < (String , String) > , }
};
}
