mkuse!{use std :: fmt :: { self , Debug } ;}
mkuse!{use rustc_abi :: { FieldIdx , VariantIdx } ;}
mkuse!{use rustc_data_structures :: fx :: FxIndexMap ;}
mkuse!{use rustc_errors :: ErrorGuaranteed ;}
mkuse!{use rustc_hir :: def_id :: LocalDefId ;}
mkuse!{use rustc_index :: IndexVec ;}
mkuse!{use rustc_index :: bit_set :: BitMatrix ;}
mkuse!{use rustc_macros :: { HashStable , TyDecodable , TyEncodable , TypeFoldable , TypeVisitable } ;}
mkuse!{use rustc_span :: { Span , Symbol } ;}
mkuse!{use super :: { ConstValue , SourceInfo } ;}
mkuse!{use crate :: ty :: { self , CoroutineArgsExt , OpaqueHiddenType , Ty } ;}
mkitem!{rustc_index :: newtype_index ! { # [derive (HashStable)] # [encodable] # [debug_format = "_{}"] pub struct CoroutineSavedLocal { } }}
mkitem!{mkstruct!{# [derive (Clone , Debug , PartialEq , Eq)] # [derive (TyEncodable , TyDecodable , HashStable , TypeFoldable , TypeVisitable)] pub struct CoroutineSavedTy < 'tcx > { pub ty : Ty < 'tcx > , # [doc = " Source info corresponding to the local in the original MIR body."] pub source_info : SourceInfo , # [doc = " Whether the local should be ignored for trait bound computations."] pub ignore_for_traits : bool , }}}
mkitem!{mkstruct!{# [doc = " The layout of coroutine state."] # [derive (Clone , PartialEq , Eq)] # [derive (TyEncodable , TyDecodable , HashStable , TypeFoldable , TypeVisitable)] pub struct CoroutineLayout < 'tcx > { # [doc = " The type of every local stored inside the coroutine."] pub field_tys : IndexVec < CoroutineSavedLocal , CoroutineSavedTy < 'tcx > > , # [doc = " The name for debuginfo."] pub field_names : IndexVec < CoroutineSavedLocal , Option < Symbol > > , # [doc = " Which of the above fields are in each variant. Note that one field may"] # [doc = " be stored in multiple variants."] pub variant_fields : IndexVec < VariantIdx , IndexVec < FieldIdx , CoroutineSavedLocal > > , # [doc = " The source that led to each variant being created (usually, a yield or"] # [doc = " await)."] pub variant_source_info : IndexVec < VariantIdx , SourceInfo > , # [doc = " Which saved locals are storage-live at the same time. Locals that do not"] # [doc = " have conflicts with each other are allowed to overlap in the computed"] # [doc = " layout."] # [type_foldable (identity)] # [type_visitable (ignore)] pub storage_conflicts : BitMatrix < CoroutineSavedLocal , CoroutineSavedLocal > , }}}
mkitem!{mkimpl!{impl Debug for CoroutineLayout < '_ > { fn fmt (& self , fmt : & mut fmt :: Formatter < '_ >) -> fmt :: Result { fmt . debug_struct ("CoroutineLayout") . field_with ("field_tys" , | fmt | { fmt . debug_map () . entries (self . field_tys . iter_enumerated ()) . finish () }) . field_with ("variant_fields" , | fmt | { let mut map = fmt . debug_map () ; for (idx , fields) in self . variant_fields . iter_enumerated () { map . key_with (| fmt | { let variant_name = ty :: CoroutineArgs :: variant_name (idx) ; if fmt . alternate () { write ! (fmt , "{variant_name:9}({idx:?})") } else { write ! (fmt , "{variant_name}") } }) ; map . value_with (| fmt | write ! (fmt , "{fields:?}")) ; } map . finish () }) . field ("storage_conflicts" , & self . storage_conflicts) . finish () } }}}
mkitem!{mkstruct!{# [doc = " All the opaque types that are restricted to concrete types"] # [doc = " by this function. Unlike the value in `TypeckResults`, this has"] # [doc = " unerased regions."] # [derive (Default , Debug , TyEncodable , TyDecodable , HashStable)] pub struct ConcreteOpaqueTypes < 'tcx > (pub FxIndexMap < LocalDefId , OpaqueHiddenType < 'tcx > >) ;}}
mkitem!{mkstruct!{# [doc = " The result of the `mir_const_qualif` query."] # [doc = ""] # [doc = " Each field (except `tainted_by_errors`) corresponds to an implementer of the `Qualif` trait in"] # [doc = " `rustc_const_eval/src/transform/check_consts/qualifs.rs`. See that file for more information on each"] # [doc = " `Qualif`."] # [derive (Clone , Copy , Debug , Default , TyEncodable , TyDecodable , HashStable)] pub struct ConstQualifs { pub has_mut_interior : bool , pub needs_drop : bool , pub needs_non_const_drop : bool , pub tainted_by_errors : Option < ErrorGuaranteed > , }}}
mkitem!{mkenum!{# [doc = " Outlives-constraints can be categorized to determine whether and why they"] # [doc = " are interesting (for error reporting). Order of variants indicates sort"] # [doc = " order of the category, thereby influencing diagnostic output."] # [doc = ""] # [doc = " See also `rustc_const_eval::borrow_check::constraints`."] # [derive (Copy , Clone , Debug , Eq , PartialEq , Hash)] # [derive (TyEncodable , TyDecodable , HashStable , TypeVisitable , TypeFoldable)] pub enum ConstraintCategory < 'tcx > { Return (ReturnConstraint) , Yield , UseAsConst , UseAsStatic , TypeAnnotation (AnnotationSource) , Cast { # [doc = " Whether this cast is a coercion that was automatically inserted by the compiler."] is_implicit_coercion : bool , # [doc = " Whether this is an unsizing coercion and if yes, this contains the target type."] # [doc = " Region variables are erased to ReErased."] unsize_to : Option < Ty < 'tcx > > , } , # [doc = " Contains the function type if available."] CallArgument (Option < Ty < 'tcx > >) , CopyBound , SizedBound , Assignment , # [doc = " A constraint that came from a usage of a variable (e.g. in an ADT expression"] # [doc = " like `Foo { field: my_val }`)"] Usage , OpaqueType , ClosureUpvar (FieldIdx) , # [doc = " A constraint from a user-written predicate"] # [doc = " with the provided span, written on the item"] # [doc = " with the given `DefId`"] Predicate (Span) , # [doc = " A \"boring\" constraint (caused by the given location) is one that"] # [doc = " the user probably doesn't want to see described in diagnostics,"] # [doc = " because it is kind of an artifact of the type system setup."] Boring , BoringNoLocation , # [doc = " A constraint that doesn't correspond to anything the user sees."] Internal , # [doc = " An internal constraint added when a region outlives a placeholder"] # [doc = " it cannot name and therefore has to outlive `'static`. The argument"] # [doc = " is the unnameable placeholder and the constraint is always between"] # [doc = " an SCC representative and `'static`."] OutlivesUnnameablePlaceholder (# [type_foldable (identity)] # [type_visitable (ignore)] ty :: RegionVid ,) , }}}
mkitem!{mkenum!{# [derive (Copy , Clone , Debug , Eq , PartialEq , Hash)] # [derive (TyEncodable , TyDecodable , HashStable , TypeVisitable , TypeFoldable)] pub enum ReturnConstraint { Normal , ClosureUpvar (FieldIdx) , }}}
mkitem!{mkenum!{# [derive (Copy , Clone , Debug , Eq , PartialEq , Hash)] # [derive (TyEncodable , TyDecodable , HashStable , TypeVisitable , TypeFoldable)] pub enum AnnotationSource { Ascription , Declaration , OpaqueCast , GenericArg , }}}
mkitem!{mkstruct!{# [doc = " The constituent parts of a mir constant of kind ADT or array."] # [derive (Copy , Clone , Debug , HashStable)] pub struct DestructuredConstant < 'tcx > { pub variant : Option < VariantIdx > , pub fields : & 'tcx [(ConstValue , Ty < 'tcx >)] , }}}