// Generated macro for use_141 (pub_use)
macro_rules! Depcrateuse_141 {
() => {
// Module: crate
// Provides: {"use_141"}
// Dependencies: {}
# [doc = " Derive [`Schema`] for a struct or enum"] # [doc = ""] # [doc = " # Examples"] # [doc = ""] # [doc = " ```"] # [doc = " use postcard_schema_ng::Schema;"] # [doc = ""] # [doc = " #[derive(Schema)]"] # [doc = " struct Point {"] # [doc = "     x: i32,"] # [doc = "     y: i32,"] # [doc = " }"] # [doc = " ```"] # [doc = ""] # [doc = " # Attributes"] # [doc = ""] # [doc = " ## `#[serde(rename = \"name\")]`"] # [doc = ""] # [doc = " The names of fields, containers, and variants in derived schemas respect `#[serde(rename = \"name\")]`"] # [doc = " attributes. Note that this does not include variants like `#[serde(rename(serialize = \"ser_name\"))]`"] # [doc = " or `#[serde(rename_all = \"...\")]`."] # [doc = ""] # [doc = " ## `#[postcard(crate = ...)]`"] # [doc = ""] # [doc = " The `#[postcard(crate = ...)]` attribute can be used to specify a path to the `postcard_schema`"] # [doc = " crate instance to use when referring to [`Schema`] and [schema types](schema) from generated"] # [doc = " code. This is normally only applicable when invoking re-exported derives from a different crate."] # [doc = ""] # [doc = " ```"] # [doc = " # use postcard_schema_ng::Schema;"] # [doc = " use postcard_schema_ng as reexported_postcard_schema;"] # [doc = ""] # [doc = " #[derive(Schema)]"] # [doc = " #[postcard(crate = reexported_postcard_schema)]"] # [doc = " struct Point {"] # [doc = "     x: i32,"] # [doc = "     y: i32,"] # [doc = " }"] # [doc = " ```"] # [doc = ""] # [doc = " ## `#[postcard(bound = ...)]`"] # [doc = ""] # [doc = " The `#[postcard(bound = ...)]` attribute can be used to overwrite the default bounds when"] # [doc = " deriving [`Schema`]. The default bounds are `T: Schema` for each type parameter `T`."] # [doc = ""] # [doc = " ```"] # [doc = " # use postcard_schema_ng::Schema;"] # [doc = " #[derive(Schema)]"] # [doc = " #[postcard(bound = \"\")]"] # [doc = " struct Foo<F: Bar, T: Schema>(F::Wrap<T>);"] # [doc = ""] # [doc = " trait Bar {"] # [doc = "     type Wrap<T: Schema>: Schema;"] # [doc = " }"] # [doc = ""] # [doc = " struct NoSchema;"] # [doc = " impl Bar for NoSchema {"] # [doc = "     type Wrap<T: Schema> = Option<T>;"] # [doc = " }"] # [doc = ""] # [doc = " Foo::<NoSchema, u8>::SCHEMA;"] # [doc = " ```"] # [cfg (feature = "derive")] pub use postcard_derive_ng :: Schema ;
};
}
