use anyhow::Result;
use std::collections::HashMap;
use std::path::Path;
use toml::Value;
use walkdir::WalkDir;

/// Generate workspace Cargo.toml with members and dependencies
pub fn generate_workspace_toml(
    members: &[String],
    dependencies: &HashMap<String, Value>,
    output_path: &Path,
) -> Result<()> {
    let mut content = String::new();
    content.push_str("[workspace]\nresolver = \"2\"\nmembers = [\n");
    
    for member in members {
        content.push_str(&format!("    \"{}\",\n", member));
    }
    
    content.push_str("]\n\n[workspace.dependencies]\n");
    
    for (name, value) in dependencies {
        content.push_str(&format!("{} = {}\n", name, value));
    }
    
    // Add generated header
    let header = format!(
        "# Generated by lib-cargo workspace generator\n# Do not edit this file by hand. Your changes will be overwritten.\n\n"
    );
    let final_content = header + &content;
    
    std::fs::write(output_path, final_content)?;
    Ok(())
}

/// Collect all workspace members from a directory
pub fn collect_workspace_members(dir: &Path) -> Result<Vec<String>> {
    let mut members = Vec::new();
    
    for entry in WalkDir::new(dir).max_depth(1) {
        let entry = entry?;
        let path = entry.path();
        
        if path.is_dir() && path != dir {
            if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
                if name.starts_with("wrapped-") && path.join("Cargo.toml").exists() {
                    members.push(name.to_string());
                }
            }
        }
    }
    
    members.sort();
    Ok(members)
}

/// Scan all Cargo.toml files in workspace and collect their dependencies
pub fn collect_all_workspace_dependencies(workspace_dir: &Path) -> Result<HashMap<String, Value>> {
    let mut all_deps = HashMap::new();
    
    for entry in WalkDir::new(workspace_dir).max_depth(2) {
        let entry = entry?;
        let path = entry.path();
        
        if path.file_name() == Some(std::ffi::OsStr::new("Cargo.toml")) && path != workspace_dir.join("Cargo.toml") {
            if let Ok(manifest) = crate::manifest::read_manifest(path) {
                let deps = crate::dependencies::collect_dependencies(&manifest);
                for (name, _value) in deps {
                    // Generate path to wrapped crate
                    let mut workspace_entry = toml::map::Map::new();
                    let wrapped_path = if name == "alloc" {
                        "./wrapped-rustc-std-workspace-alloc".to_string()
                    } else {
                        format!("./wrapped-{}", name)
                    };
                    workspace_entry.insert("path".to_string(), Value::String(wrapped_path));
                    all_deps.insert(name, Value::Table(workspace_entry));
                }
            }
        }
    }
    
    Ok(all_deps)
}
