// Generated macro for GENERATED_FILE_COMMENT (const)
macro_rules! Depcrate_update_lintsGENERATED_FILE_COMMENT {
() => {
// Module: crate::update_lints
// Provides: {"GENERATED_FILE_COMMENT"}
// Dependencies: {}
const GENERATED_FILE_COMMENT : & str = "// This file was generated by `cargo dev update_lints`.\n\
     // Use that command to update this file and do not edit by hand.\n\
     // Manual edits will be overwritten.\n\n" ;
};
}
