// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter.rs:211 from submodules/split-decls-rs/src/eager_splitter.rs
// Do not edit this file by hand. Your changes will be overwritten.

#[llm_error_message(message = "Module file not found for: http")]
#[llm_context(crate_name = "wrapped_tracing_tower", module_name = "http")]
pub struct wrapped_tracing_tower_decls_module_not_found_http;
