// Generated macro for hchacha (function)
macro_rules! Depcrate_xchachahchacha {
() => {
// Module: crate::xchacha
// Provides: {"hchacha"}
// Dependencies: {}
# [doc = " The HChaCha function: adapts the ChaCha core function in the same"] # [doc = " manner that HSalsa adapts the Salsa function."] # [doc = ""] # [doc = " HChaCha takes 512-bits of input:"] # [doc = ""] # [doc = " - Constants: `u32` x 4"] # [doc = " - Key: `u32` x 8"] # [doc = " - Nonce: `u32` x 4"] # [doc = ""] # [doc = " It produces 256-bits of output suitable for use as a ChaCha key"] # [doc = ""] # [doc = " For more information on HSalsa on which HChaCha is based, see:"] # [doc = ""] # [doc = " <http://cr.yp.to/snuffle/xsalsa-20110204.pdf>"] pub fn hchacha < R : Rounds > (key : & Key , input : & Array < u8 , U16 >) -> Array < u8 , U32 > { let mut state = [0u32 ; STATE_WORDS] ; state [.. 4] . copy_from_slice (& CONSTANTS) ; let key_chunks = key . chunks_exact (4) ; for (v , chunk) in state [4 .. 12] . iter_mut () . zip (key_chunks) { * v = u32 :: from_le_bytes (chunk . try_into () . unwrap ()) ; } let input_chunks = input . chunks_exact (4) ; for (v , chunk) in state [12 .. 16] . iter_mut () . zip (input_chunks) { * v = u32 :: from_le_bytes (chunk . try_into () . unwrap ()) ; } for _ in 0 .. R :: COUNT { quarter_round (0 , 4 , 8 , 12 , & mut state) ; quarter_round (1 , 5 , 9 , 13 , & mut state) ; quarter_round (2 , 6 , 10 , 14 , & mut state) ; quarter_round (3 , 7 , 11 , 15 , & mut state) ; quarter_round (0 , 5 , 10 , 15 , & mut state) ; quarter_round (1 , 6 , 11 , 12 , & mut state) ; quarter_round (2 , 7 , 8 , 13 , & mut state) ; quarter_round (3 , 4 , 9 , 14 , & mut state) ; } let mut output = Array :: default () ; for (chunk , val) in output [.. 16] . chunks_exact_mut (4) . zip (& state [.. 4]) { chunk . copy_from_slice (& val . to_le_bytes ()) ; } for (chunk , val) in output [16 ..] . chunks_exact_mut (4) . zip (& state [12 ..]) { chunk . copy_from_slice (& val . to_le_bytes ()) ; } output }
};
}
