// Generated by unified_build.rs
#![feature(rustc_attrs)]
#![feature(dropck_eyepatch)]
#![feature(ascii_char_variants)]
#![feature(ascii_char)]
#![feature(auto_traits)]
#![feature(specialization)]
#![feature(never_type)]
#![feature(cfg_select)]
#![feature(ptr_alignment_type)]
#![feature(negative_impls)]

//! Support code for encoding and decoding types.

// tidy-alphabetical-start
    html_root_url = "https://doc.rust-lang.org/nightly/nightly-rustc/",
    html_playground_url = "https://play.rust-lang.org/",
    test(attr(allow(unused_variables), deny(warnings)))
)]
// tidy-alphabetical-end

// Allows macros to refer to this crate as `::rustc_serialize`.
#[cfg(test)]
extern crate self as rustc_serialize;

pub use self::serialize::{Decodable, Decoder, Encodable, Encoder};

mod serialize;

pub mod int_overflow;
pub mod leb128;
pub mod opaque;