// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
pub fn process_decl2_attribute_logic(attr: TokenStream, item: TokenStream) -> TokenStream {
    let args = parse_decl_args!(attr);
    dispatch_wrap_logic!(item, args)
}
