// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
pub trait PipelineFunctor<Input: Send + 'static, Output: Send + 'static, Config> {
    fn map<'writer>(
        &'writer self,
        writer: &'writer mut (impl tokio::io::AsyncWriteExt + Unpin + Send),
        input: Input,
        _config: &'writer Option<Config>,
    ) -> Pin<Box<dyn Future<Output = Result<Output>> + Send + 'writer>>;
}
