// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35 
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros :: decl_module ; decl_module ! (wrapped_rustc_expand_patches_decls_quote_error) ;