// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_arrayvec_decls_LenUint,
    wrapped_arrayvec_decls_LenUint,
    wrapped_arrayvec_decls_macro_rules,
    wrapped_arrayvec_decls_macro_rules,
    wrapped_arrayvec_decls_module_not_found_array_string,
    wrapped_arrayvec_decls_module_not_found_arrayvec,
    wrapped_arrayvec_decls_module_not_found_arrayvec_impl,
    wrapped_arrayvec_decls_module_not_found_char,
    wrapped_arrayvec_decls_module_not_found_errors,
    wrapped_arrayvec_decls_module_not_found_utils
);
