// Generated macro for Retransmits (struct)
macro_rules! Depcrate_connection_spacesRetransmits {
() => {
// Module: crate::connection::spaces
// Provides: {"Retransmits"}
// Dependencies: {}
# [doc = " Retransmittable data queue"] # [allow (unreachable_pub)] # [derive (Debug , Default , Clone)] pub struct Retransmits { pub (super) max_data : bool , pub (super) max_stream_id : [bool ; 2] , pub (super) reset_stream : Vec < (StreamId , VarInt) > , pub (super) stop_sending : Vec < frame :: StopSending > , pub (super) max_stream_data : FxHashSet < StreamId > , pub (super) crypto : VecDeque < frame :: Crypto > , pub (super) new_cids : Vec < IssuedCid > , pub (super) retire_cids : Vec < u64 > , pub (super) ack_frequency : bool , pub (super) handshake_done : bool , # [doc = " For each enqueued NEW_TOKEN frame, a copy of the path's remote address"] # [doc = ""] # [doc = " There are 2 reasons this is unusual:"] # [doc = ""] # [doc = " - If the path changes, NEW_TOKEN frames bound for the old path are not retransmitted on the"] # [doc = "   new path. That is why this field stores the remote address: so that ones for old paths"] # [doc = "   can be filtered out."] # [doc = " - If a token is lost, a new randomly generated token is re-transmitted, rather than the"] # [doc = "   original. This is so that if both transmissions are received, the client won't risk"] # [doc = "   sending the same token twice. That is why this field does _not_ store any actual token."] # [doc = ""] # [doc = " It is true that a QUIC endpoint will only want to effectively have NEW_TOKEN frames"] # [doc = " enqueued for its current path at a given point in time. Based on that, we could conceivably"] # [doc = " change this from a vector to an `Option<(SocketAddr, usize)>` or just a `usize` or"] # [doc = " something. However, due to the architecture of Quinn, it is considerably simpler to not do"] # [doc = " that; consider what such a change would mean for implementing `BitOrAssign` on Self."] pub (super) new_tokens : Vec < SocketAddr > , }
};
}
