// Generated macro for stream_id_limit (function)
macro_rules! Depcrate_testsstream_id_limit {
() => {
// Module: crate::tests
// Provides: {"stream_id_limit"}
// Dependencies: {}
# [test] fn stream_id_limit () { let _guard = subscribe () ; let server = ServerConfig { transport : Arc :: new (TransportConfig { max_concurrent_uni_streams : 1u32 . into () , .. TransportConfig :: default () }) , .. server_config () } ; let mut pair = Pair :: new (Default :: default () , server) ; let (client_ch , server_ch) = pair . connect () ; let s = pair . client . connections . get_mut (& client_ch) . unwrap () . streams () . open (Dir :: Uni) . expect ("couldn't open first stream") ; assert_eq ! (pair . client_streams (client_ch) . open (Dir :: Uni) , None , "only one stream is permitted at a time") ; const MSG : & [u8] = b"hello" ; pair . client_send (client_ch , s) . write (MSG) . unwrap () ; pair . client_send (client_ch , s) . finish () . unwrap () ; pair . drive () ; assert_matches ! (pair . client_conn_mut (client_ch) . poll () , Some (Event :: Stream (StreamEvent :: Finished { id })) if id == s) ; assert_eq ! (pair . client_streams (client_ch) . open (Dir :: Uni) , None , "server does not immediately grant additional credit") ; assert_matches ! (pair . server_conn_mut (server_ch) . poll () , Some (Event :: Stream (StreamEvent :: Opened { dir : Dir :: Uni }))) ; assert_matches ! (pair . server_streams (server_ch) . accept (Dir :: Uni) , Some (stream) if stream == s) ; let mut recv = pair . server_recv (server_ch , s) ; let mut chunks = recv . read (false) . unwrap () ; assert_matches ! (chunks . next (usize :: MAX) , Ok (Some (chunk)) if chunk . offset == 0 && chunk . bytes == MSG) ; assert_eq ! (chunks . next (usize :: MAX) , Ok (None)) ; let _ = chunks . finalize () ; pair . drive () ; assert_matches ! (pair . client_conn_mut (client_ch) . poll () , Some (Event :: Stream (StreamEvent :: Available { dir : Dir :: Uni }))) ; assert_matches ! (pair . client_conn_mut (client_ch) . poll () , None) ; let s = pair . client . connections . get_mut (& client_ch) . unwrap () . streams () . open (Dir :: Uni) . expect ("didn't get stream id budget") ; pair . client_send (client_ch , s) . finish () . unwrap () ; pair . drive () ; assert_matches ! (pair . server_conn_mut (server_ch) . poll () , Some (Event :: Stream (StreamEvent :: Opened { dir : Dir :: Uni }))) ; assert_matches ! (pair . server_streams (server_ch) . accept (Dir :: Uni) , Some (stream) if stream == s) ; assert_matches ! (pair . server_conn_mut (server_ch) . poll () , None) ; let mut recv = pair . server_recv (server_ch , s) ; let mut chunks = recv . read (false) . unwrap () ; assert_matches ! (chunks . next (usize :: MAX) , Ok (None)) ; let _ = chunks . finalize () ; }
};
}
