// Generated macro for IntoDiscriminant (trait)
macro_rules! DepcrateIntoDiscriminant {
() => {
// Module: crate
// Provides: {"IntoDiscriminant"}
// Dependencies: {}
# [doc = " A trait for retrieving the enum generated by [`EnumDiscriminants`] from an associated"] # [doc = " Type on the original enumeration. This trait can be autoderived by `strum_macros`."] pub trait IntoDiscriminant { # [doc = " Enum listing the same variants as this enum but without any data fields"] type Discriminant ; fn discriminant (& self) -> Self :: Discriminant ; }
};
}
