// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter.rs:211 from submodules/split-decls-rs/src/eager_splitter.rs
// Do not edit this file by hand. Your changes will be overwritten.

#[llm_error_message(message = "Module file not found for: server_impl")]
#[llm_context(crate_name = "wrapped_proc_macro_srv", module_name = "server_impl")]
pub struct wrapped_proc_macro_srv_decls_module_not_found_server_impl;
