[package]
name = "expand_utils_test"
publish.workspace = true
description.workspace = true
categories.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition = "2024"
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
include.workspace = true

[dependencies]
# The macro crate we want to test
expand_utils_macros = { path = "../expand_utils_macros" }
# rustc_expand for types used by the macro output
rustc_expand = { path = "../rustc_expand" }
# For basic AST types like NodeId, etc.
rustc_ast = { workspace = true }
rustc_span = { workspace = true }

[lints]
workspace = true