// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
fn common_overlap(mut text1: Range, mut text2: Range) -> usize {
    if text1.is_empty() || text2.is_empty() {
        return 0;
    }
    if text1.len > text2.len {
        text1 = text1.substring(text1.len - text2.len..);
    } else if text1.len < text2.len {
        text2 = text2.substring(..text1.len);
    }
    if slice(text1) == slice(text2) {
        return text1.len;
    }
    let mut best = 0;
    let mut length = 1;
    loop {
        let pattern = text1.substring(text1.len - length..);
        let found = match text2.find(pattern) {
            Some(found) => found,
            None => return best,
        };
        length += found;
        if found == 0
            || slice(text1.substring(text1.len - length..)) == slice(text2.substring(..length))
        {
            best = length;
            length += 1;
        }
    }
}
