// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " The name of rustc's own place to organize libraries."]
#[doc = ""]
#[doc = " Used to be `rustc`, now the default is `rustlib`."]
const RUST_LIB_DIR: &str = "rustlib";
