// Generated macro for handle_field_modifier_core_prefix (function)
macro_rules! Depcrate_personnames_specifications_derive_core_prefixhandle_field_modifier_core_prefix {
() => {
// Module: crate::personnames::specifications::derive_core_prefix
// Provides: {"handle_field_modifier_core_prefix"}
// Dependencies: {}
# [doc = " Transform the request field in a list of requested field based on the available fields."] # [doc = " a single field can be transformed into 2 fields, or just be removed."] # [doc = " https://www.unicode.org/reports/tr35/tr35-personNames.html#handle-core-and-prefix"] pub fn handle_field_modifier_core_prefix (available_fields : & [& NameField] , requested_field : & NameField ,) -> Vec < NameField > { let is_core = requested_field . modifier . has_field (FieldModifier :: Core) ; let is_prefix = requested_field . modifier . has_field (FieldModifier :: Prefix) ; let is_plain = ! is_core && ! is_prefix ; let mut has_prefix_version_available = false ; let mut has_core_version_available = false ; let mut has_plain_version_available = false ; for & field in available_fields { if field . kind == requested_field . kind { has_plain_version_available |= field . modifier == requested_field . modifier . with_part (FieldPart :: Auto) ; has_prefix_version_available |= field . modifier == requested_field . modifier . with_part (FieldPart :: Prefix) ; has_core_version_available |= field . modifier == requested_field . modifier . with_part (FieldPart :: Core) ; } } let mut result = vec ! [] ; match (has_prefix_version_available , has_core_version_available , has_plain_version_available ,) { (true , true , true) | (false , false , false) => result . push (* requested_field) , (true , false , true) => { if is_core { result . push (NameField { kind : requested_field . kind , modifier : requested_field . modifier . with_part (FieldPart :: Auto) , }) } else if is_plain { result . push (* requested_field) } } (false , true , true) | (false , false , true) => { if is_core { result . push (NameField { kind : requested_field . kind , modifier : requested_field . modifier . with_part (FieldPart :: Auto) , }) } else { result . push (* requested_field) } } (true , true , false) => { if is_plain { result . push (NameField { kind : requested_field . kind , modifier : requested_field . modifier . with_part (FieldPart :: Prefix) , }) ; result . push (NameField { kind : requested_field . kind , modifier : requested_field . modifier . with_part (FieldPart :: Core) , }) } else { result . push (* requested_field) } } (false , true , false) => { if is_plain { result . push (NameField { kind : requested_field . kind , modifier : requested_field . modifier . with_part (FieldPart :: Core) , }) } else { result . push (* requested_field) } } (true , false , false) => { if ! & is_prefix { result . push (* requested_field) } } } result }
};
}
