// Generated macro for Diagnostic (struct)
macro_rules! Depcrate_format_diagnosticDiagnostic {
() => {
// Module: crate::format::diagnostic
// Provides: {"Diagnostic"}
// Dependencies: {}
# [doc = " A diagnostic message generated by rustc"] # [derive (Debug , Clone , PartialEq , Eq , Serialize , Deserialize)] # [cfg_attr (feature = "strict_unstable" , serde (deny_unknown_fields))] # [non_exhaustive] pub struct Diagnostic < 'a > { # [doc = " Can be used to distinguish the different formats."] # [doc = ""] # [doc = " When parsing, care should be taken to be forwards-compatible with future changes to the format."] # [serde (borrow , rename = "$message_type")] pub message_type : Option < CowStr < 'a > > , # [doc = " The error message of this diagnostic."] # [serde (borrow)] pub message : CowStr < 'a > , # [doc = " The associated error code for this diagnostic"] # [serde (borrow)] pub code : Option < DiagnosticCode < 'a > > , # [doc = " The severity of the diagnostic."] pub level : DiagnosticLevel , # [doc = " A list of source code spans this diagnostic is associated with."] # [serde (borrow)] pub spans : Vec < DiagnosticSpan < 'a > > , # [doc = " Associated diagnostic messages."] # [serde (borrow)] pub children : Vec < Diagnostic < 'a > > , # [doc = " The message as rustc would render it"] # [serde (borrow)] pub rendered : Option < CowStr < 'a > > , }
};
}
