// Generated macro for Timestamptz (struct)
macro_rules! Depcrate_sqlite_typesTimestamptz {
() => {
// Module: crate::sqlite::types
// Provides: {"Timestamptz"}
// Dependencies: {}
# [doc = " The SQLite timestamp with time zone type"] # [doc = ""] # [doc = " ### [`ToSql`] impls"] # [doc = ""] # [doc = " - [`chrono::NaiveDateTime`] with `feature = \"chrono\"`"] # [doc = " - [`chrono::DateTime`] with `feature = \"chrono\"`"] # [doc = " - [`time::PrimitiveDateTime`] with `feature = \"time\"`"] # [doc = " - [`time::OffsetDateTime`] with `feature = \"time\"`"] # [doc = ""] # [doc = " ### [`FromSql`] impls"] # [doc = ""] # [doc = " - [`chrono::NaiveDateTime`] with `feature = \"chrono\"`"] # [doc = " - [`chrono::DateTime`] with `feature = \"chrono\"`"] # [doc = " - [`time::PrimitiveDateTime`] with `feature = \"time\"`"] # [doc = " - [`time::OffsetDateTime`] with `feature = \"time\"`"] # [doc = ""] # [doc = " [`ToSql`]: crate::serialize::ToSql"] # [doc = " [`FromSql`]: crate::deserialize::FromSql"] # [cfg_attr (feature = "chrono" , doc = " [`chrono::NaiveDateTime`]: chrono::naive::NaiveDateTime")] # [cfg_attr (not (feature = "chrono") , doc = " [`chrono::NaiveDateTime`]: https://docs.rs/chrono/0.4.19/chrono/naive/struct.NaiveDateTime.html")] # [cfg_attr (feature = "chrono" , doc = " [`chrono::DateTime`]: chrono::DateTime")] # [cfg_attr (not (feature = "chrono") , doc = " [`chrono::DateTime`]: https://docs.rs/chrono/0.4.19/chrono/struct.DateTime.html")] # [cfg_attr (feature = "time" , doc = " [`time::PrimitiveDateTime`]: time::PrimitiveDateTime")] # [cfg_attr (not (feature = "time") , doc = " [`time::PrimitiveDateTime`]: https://docs.rs/time/0.3.9/time/struct.PrimitiveDateTime.html")] # [cfg_attr (feature = "time" , doc = " [`time::OffsetDateTime`]: time::OffsetDateTime")] # [cfg_attr (not (feature = "time") , doc = " [`time::OffsetDateTime`]: https://docs.rs/time/0.3.9/time/struct.OffsetDateTime.html")] # [derive (Debug , Clone , Copy , Default , QueryId , SqlType)] # [diesel (sqlite_type (name = "Text"))] # [cfg (feature = "sqlite")] pub struct Timestamptz ;
};
}
