// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter.rs:211 from submodules/split-decls-rs/src/eager_splitter.rs
// Do not edit this file by hand. Your changes will be overwritten.

#[llm_error_message(
    message = "Module file not found for: macro_expr_fragment_specifier_2024_migration"
)]
#[llm_context(
    crate_name = "wrapped_rustc_lint",
    module_name = "macro_expr_fragment_specifier_2024_migration"
)]
pub struct wrapped_rustc_lint_decls_module_not_found_macro_expr_fragment_specifier_2024_migration;
