// Generated macro for impl_1246 (impl)
macro_rules! Depcrate_style_shapeimpl_1246 {
() => {
// Module: crate::style::shape
// Provides: {"impl_1246"}
// Dependencies: {}
impl ShapeStyle { # [doc = "\n    Returns a filled style with the same color and stroke width.\n\n    # Example\n\n    ```\n    use plotters::prelude::*;\n    let original_style = ShapeStyle {\n        color: BLUE.mix(0.6),\n        filled: false,\n        stroke_width: 2,\n    };\n    let filled_style = original_style.filled();\n    let drawing_area = SVGBackend::new(\"shape_style_filled.svg\", (400, 200)).into_drawing_area();\n    drawing_area.fill(&WHITE).unwrap();\n    drawing_area.draw(&Circle::new((150, 100), 90, original_style));\n    drawing_area.draw(&Circle::new((250, 100), 90, filled_style));\n    ```\n\n    The result is a figure with two circles, one of them filled:\n\n    ![](https://cdn.jsdelivr.net/gh/facorread/plotters-doc-data@b0b94d5/apidoc/shape_style_filled.svg)\n    "] pub fn filled (& self) -> Self { Self { color : self . color . to_rgba () , filled : true , stroke_width : self . stroke_width , } } # [doc = "\n    Returns a new style with the same color and the specified stroke width.\n\n    # Example\n\n    ```\n    use plotters::prelude::*;\n    let original_style = ShapeStyle {\n        color: BLUE.mix(0.6),\n        filled: false,\n        stroke_width: 2,\n    };\n    let new_style = original_style.stroke_width(5);\n    let drawing_area = SVGBackend::new(\"shape_style_stroke_width.svg\", (400, 200)).into_drawing_area();\n    drawing_area.fill(&WHITE).unwrap();\n    drawing_area.draw(&Circle::new((150, 100), 90, original_style));\n    drawing_area.draw(&Circle::new((250, 100), 90, new_style));\n    ```\n\n    The result is a figure with two circles, one of them thicker than the other:\n\n    ![](https://cdn.jsdelivr.net/gh/facorread/plotters-doc-data@b0b94d5/apidoc/shape_style_stroke_width.svg)\n    "] pub fn stroke_width (& self , width : u32) -> Self { Self { color : self . color . to_rgba () , filled : self . filled , stroke_width : width , } } }
};
}
