// Generated macro for crate_name (function)
macro_rules! Depcratecrate_name {
() => {
// Module: crate
// Provides: {"crate_name"}
// Dependencies: {}
# [doc = " Find the crate name for the given `orig_name` in the current `Cargo.toml`."] # [doc = ""] # [doc = " `orig_name` should be the original name of the searched crate."] # [doc = ""] # [doc = " The current `Cargo.toml` is determined by taking `CARGO_MANIFEST_DIR/Cargo.toml`."] # [doc = ""] # [doc = " # Returns"] # [doc = ""] # [doc = " - `Ok(FoundCrate::Itself)` the searched crate is the current crate being compiled."] # [doc = " - `Ok(FoundCrate::Name(new_name))` the searched create was found with the given name in the"] # [doc = "   `Cargo.toml`."] # [doc = " - `Err` if an error occurred. See [`Error`]."] # [doc = ""] # [doc = " The returned crate name is sanitized in such a way that it is a valid rust identifier. Thus,"] # [doc = " it is ready to be used in `extern crate` as identifier."] pub fn crate_name (orig_name : & str) -> Result < FoundCrate , Error > { let manifest_dir = env :: var ("CARGO_MANIFEST_DIR") . map_err (| _ | Error :: CargoManifestDirNotSet) ? ; let manifest_path = Path :: new (& manifest_dir) . join ("Cargo.toml") ; let manifest_ts = cargo_toml_timestamp (& manifest_path) ? ; static CACHE : Mutex < Cache > = Mutex :: new (BTreeMap :: new ()) ; let mut cache = CACHE . lock () . unwrap () ; let crate_names = match cache . entry (manifest_dir) { btree_map :: Entry :: Occupied (entry) => { let cache_entry = entry . into_mut () ; let workspace_manifest_path = cache_entry . workspace_manifest_path . as_path () ; let workspace_manifest_ts = cargo_toml_timestamp (& workspace_manifest_path) ? ; if manifest_ts != cache_entry . manifest_ts || workspace_manifest_ts != cache_entry . workspace_manifest_ts { * cache_entry = read_cargo_toml (& manifest_path , & workspace_manifest_path , manifest_ts , workspace_manifest_ts ,) ? ; } & cache_entry . crate_names } , btree_map :: Entry :: Vacant (entry) => { let workspace_manifest_path = workspace_manifest_path (& manifest_path) ? . unwrap_or_else (| | manifest_path . clone ()) ; let workspace_manifest_ts = cargo_toml_timestamp (& workspace_manifest_path) ? ; let cache_entry = entry . insert (read_cargo_toml (& manifest_path , & workspace_manifest_path , manifest_ts , workspace_manifest_ts ,) ?) ; & cache_entry . crate_names } , } ; Ok (crate_names . get (orig_name) . ok_or_else (| | Error :: CrateNotFound { crate_name : orig_name . to_owned () , path : manifest_path , }) ? . clone ()) }
};
}
