// Generated macro for find_middle_snake (function)
macro_rules! Depcrate_algorithms_myersfind_middle_snake {
() => {
// Module: crate::algorithms::myers
// Provides: {"find_middle_snake"}
// Dependencies: {}
# [doc = " A `Snake` is a sequence of diagonal edges in the edit graph.  Normally"] # [doc = " a snake has a start end end point (and it is possible for a snake to have"] # [doc = " a length of zero, meaning the start and end points are the same) however"] # [doc = " we do not need the end point which is why it's not implemented here."] # [doc = ""] # [doc = " The divide part of a divide-and-conquer strategy. A D-path has D+1 snakes"] # [doc = " some of which may be empty. The divide step requires finding the ceil(D/2) +"] # [doc = " 1 or middle snake of an optimal D-path. The idea for doing so is to"] # [doc = " simultaneously run the basic algorithm in both the forward and reverse"] # [doc = " directions until furthest reaching forward and reverse paths starting at"] # [doc = " opposing corners 'overlap'."] fn find_middle_snake < Old , New > (old : & Old , old_range : Range < usize > , new : & New , new_range : Range < usize > , vf : & mut V , vb : & mut V , deadline : Option < Instant > ,) -> Option < (usize , usize) > where Old : Index < usize > + ? Sized , New : Index < usize > + ? Sized , New :: Output : PartialEq < Old :: Output > , { let n = old_range . len () ; let m = new_range . len () ; let delta = n as isize - m as isize ; let odd = delta & 1 == 1 ; vf [1] = 0 ; vb [1] = 0 ; let d_max = max_d (n , m) ; assert ! (vf . len () >= d_max) ; assert ! (vb . len () >= d_max) ; for d in 0 .. d_max as isize { if deadline_exceeded (deadline) { break ; } for k in (- d ..= d) . rev () . step_by (2) { let mut x = if k == - d || (k != d && vf [k - 1] < vf [k + 1]) { vf [k + 1] } else { vf [k - 1] + 1 } ; let y = (x as isize - k) as usize ; let (x0 , y0) = (x , y) ; if x < old_range . len () && y < new_range . len () { let advance = common_prefix_len (old , old_range . start + x .. old_range . end , new , new_range . start + y .. new_range . end ,) ; x += advance ; } vf [k] = x ; if odd && (k - delta) . abs () <= (d - 1) { if vf [k] + vb [- (k - delta)] >= n { return Some ((x0 + old_range . start , y0 + new_range . start)) ; } } } for k in (- d ..= d) . rev () . step_by (2) { let mut x = if k == - d || (k != d && vb [k - 1] < vb [k + 1]) { vb [k + 1] } else { vb [k - 1] + 1 } ; let mut y = (x as isize - k) as usize ; if x < n && y < m { let advance = common_suffix_len (old , old_range . start .. old_range . start + n - x , new , new_range . start .. new_range . start + m - y ,) ; x += advance ; y += advance ; } vb [k] = x ; if ! odd && (k - delta) . abs () <= d { if vb [k] + vf [- (k - delta)] >= n { return Some ((n - x + old_range . start , m - y + new_range . start)) ; } } } } None }
};
}
