// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35 
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros :: decl_module ; decl_module ! (wrapped_futures_executor_decls_module_not_found_local_pool , wrapped_futures_executor_decls_module_not_found_thread_pool , wrapped_futures_executor_decls_module_not_found_unpark_mutex , wrapped_futures_executor_decls_module_not_found_enter) ;