// Generated macro for options (function)
macro_rules! Depcrate_renderoptions {
() => {
// Module: crate::render
// Provides: {"options"}
// Dependencies: {}
pub (crate) fn options (roff : & mut Roff , items : & [& Arg]) { let mut sorted_items = items . to_vec () ; sorted_items . sort_by_key (| opt | option_sort_key (opt)) ; for opt in sorted_items . iter () . filter (| a | ! a . is_positional ()) { let mut header = match (opt . get_short () , opt . get_long ()) { (Some (short) , Some (long)) => { vec ! [short_option (short) , roman (", ") , long_option (long)] } (Some (short) , None) => vec ! [short_option (short)] , (None , Some (long)) => vec ! [long_option (long)] , (None , None) => vec ! [] , } ; let arg_range = opt . get_num_args () . expect ("built") ; if arg_range . takes_values () { if let Some (value_names) = & opt . get_value_names () { let (lhs , rhs) = option_value_markers (opt) ; header . push (roman (lhs)) ; for (i , name) in value_names . iter () . enumerate () { if i > 0 { header . push (italic (" ")) ; } let mut val = format ! ("<{name}>") ; let is_last = i == value_names . len () - 1 ; if is_last && arg_range . max_values () > value_names . len () { val . push_str ("...") ; } header . push (italic (val)) ; } header . push (roman (rhs)) ; } } if let Some (defs) = option_default_values (opt) { header . push (roman (" ")) ; header . push (roman (defs)) ; } let mut body = vec ! [] ; let mut arg_help_written = false ; if let Some (help) = option_help (opt) { arg_help_written = true ; body . push (roman (help . to_string ())) ; } roff . control ("TP" , []) ; roff . text (header) ; roff . text (body) ; possible_options (roff , opt , arg_help_written) ; if let Some (env) = option_environment (opt) { roff . control ("RS" , []) ; roff . text (env) ; roff . control ("RE" , []) ; } } for pos in items . iter () . filter (| a | a . is_positional ()) { let mut header = vec ! [] ; let (lhs , rhs) = option_markers (pos) ; header . push (roman (lhs)) ; if let Some (value) = pos . get_value_names () { header . push (italic (value . join (" "))) ; } else { header . push (italic (pos . get_id () . as_str ())) ; } ; header . push (roman (rhs)) ; if let Some (defs) = option_default_values (pos) { header . push (roman (format ! (" {defs}"))) ; } let mut body = vec ! [] ; let mut arg_help_written = false ; if let Some (help) = option_help (pos) { body . push (roman (help . to_string ())) ; arg_help_written = true ; } roff . control ("TP" , []) ; roff . text (header) ; roff . text (body) ; if let Some (env) = option_environment (pos) { roff . control ("RS" , []) ; roff . text (env) ; roff . control ("RE" , []) ; } possible_options (roff , pos , arg_help_written) ; } }
};
}
