[package]
name = "reson"
version = "1.3.3"
edition = "2021"

[dependencies]
blake3 = "1.5.5"
dashmap = "6.1.0"
env_logger = "0.11.5"
glob = "0.3"
indicatif = "0.17.9"
log = "0.4.22"
rayon = "1.10.0"
serde_json = "1.0"
tempfile = "3.15.0"
tree-sitter = "0.20"
tree-sitter-c = "0.20"
tree-sitter-cpp = "0.20"
tree-sitter-go = "0.20"
tree-sitter-java = "0.20"
tree-sitter-javascript = "0.20"
tree-sitter-python = "0.20"
tree-sitter-rust = "0.20"
tree-sitter-typescript = "0.20"
walkdir = "2.5.0"

[dependencies.clap]
features = ["derive"]
version = "4.5.23"

[dependencies.introspector_decl2_macros]
workspace = true

[dependencies.quick-xml]
features = ["serialize"]
version = "0.37.2"

[dependencies.serde]
features = ["derive"]
version = "1.0"

[dependencies.uuid]
features = ["v4"]
version = "1.14.0"

[dev-dependencies]

[build-dependencies.anyhow]
workspace = true

[build-dependencies.serde]
features = ["derive"]
workspace = true

[build-dependencies.syn]
features = ["full", "visit"]
workspace = true

[build-dependencies.toml]
workspace = true

[patch]
