// Generated macro for supported_sanitizers (function)
macro_rules! Depcrate_core_build_steps_llvmsupported_sanitizers {
() => {
// Module: crate::core::build_steps::llvm
// Provides: {"supported_sanitizers"}
// Dependencies: {}
# [doc = " Returns sanitizers available on a given target."] fn supported_sanitizers (out_dir : & Path , target : TargetSelection , channel : & str ,) -> Vec < SanitizerRuntime > { let darwin_libs = | os : & str , components : & [& str] | -> Vec < SanitizerRuntime > { components . iter () . map (move | c | SanitizerRuntime { cmake_target : format ! ("clang_rt.{c}_{os}_dynamic") , path : out_dir . join (format ! ("build/lib/darwin/libclang_rt.{c}_{os}_dynamic.dylib")) , name : format ! ("librustc-{channel}_rt.{c}.dylib") , }) . collect () } ; let common_libs = | os : & str , arch : & str , components : & [& str] | -> Vec < SanitizerRuntime > { components . iter () . map (move | c | SanitizerRuntime { cmake_target : format ! ("clang_rt.{c}-{arch}") , path : out_dir . join (format ! ("build/lib/{os}/libclang_rt.{c}-{arch}.a")) , name : format ! ("librustc-{channel}_rt.{c}.a") , }) . collect () } ; match & * target . triple { "aarch64-apple-darwin" => darwin_libs ("osx" , & ["asan" , "lsan" , "tsan"]) , "aarch64-apple-ios" => darwin_libs ("ios" , & ["asan" , "tsan"]) , "aarch64-apple-ios-sim" => darwin_libs ("iossim" , & ["asan" , "tsan"]) , "aarch64-apple-ios-macabi" => darwin_libs ("osx" , & ["asan" , "lsan" , "tsan"]) , "aarch64-unknown-fuchsia" => common_libs ("fuchsia" , "aarch64" , & ["asan"]) , "aarch64-unknown-linux-gnu" => { common_libs ("linux" , "aarch64" , & ["asan" , "lsan" , "msan" , "tsan" , "hwasan"]) } "aarch64-unknown-linux-ohos" => { common_libs ("linux" , "aarch64" , & ["asan" , "lsan" , "msan" , "tsan" , "hwasan"]) } "loongarch64-unknown-linux-gnu" | "loongarch64-unknown-linux-musl" => { common_libs ("linux" , "loongarch64" , & ["asan" , "lsan" , "msan" , "tsan"]) } "x86_64-apple-darwin" => darwin_libs ("osx" , & ["asan" , "lsan" , "tsan"]) , "x86_64-unknown-fuchsia" => common_libs ("fuchsia" , "x86_64" , & ["asan"]) , "x86_64-apple-ios" => darwin_libs ("iossim" , & ["asan" , "tsan"]) , "x86_64-apple-ios-macabi" => darwin_libs ("osx" , & ["asan" , "lsan" , "tsan"]) , "x86_64-unknown-freebsd" => common_libs ("freebsd" , "x86_64" , & ["asan" , "msan" , "tsan"]) , "x86_64-unknown-netbsd" => { common_libs ("netbsd" , "x86_64" , & ["asan" , "lsan" , "msan" , "tsan"]) } "x86_64-unknown-illumos" => common_libs ("illumos" , "x86_64" , & ["asan"]) , "x86_64-pc-solaris" => common_libs ("solaris" , "x86_64" , & ["asan"]) , "x86_64-unknown-linux-gnu" => { common_libs ("linux" , "x86_64" , & ["asan" , "dfsan" , "lsan" , "msan" , "safestack" , "tsan"]) } "x86_64-unknown-linux-musl" => { common_libs ("linux" , "x86_64" , & ["asan" , "lsan" , "msan" , "tsan"]) } "s390x-unknown-linux-gnu" => { common_libs ("linux" , "s390x" , & ["asan" , "lsan" , "msan" , "tsan"]) } "s390x-unknown-linux-musl" => { common_libs ("linux" , "s390x" , & ["asan" , "lsan" , "msan" , "tsan"]) } "x86_64-unknown-linux-ohos" => { common_libs ("linux" , "x86_64" , & ["asan" , "lsan" , "msan" , "tsan"]) } _ => Vec :: new () , } }
};
}
