// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs:29 from submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs 
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros :: decl_module ; decl_module ! (wrapped_trait_fixer_rules_real_decls_Config , wrapped_trait_fixer_rules_real_decls_impl_for_ConfigTrait) ;