// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter.rs:211 from submodules/split-decls-rs/src/eager_splitter.rs
// Do not edit this file by hand. Your changes will be overwritten.

#[llm_error_message(message = "Module file not found for: merge_operator")]
#[llm_context(crate_name = "wrapped_rocksdb", module_name = "merge_operator")]
pub struct wrapped_rocksdb_decls_module_not_found_merge_operator;
