[package]
name = "bootstrap3"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
paste = "1.0"
anyhow = "1.0"
module-wrapper-macros = { path = "../module-wrapper-macros" }
toml = "0.8"

[lib]
name = "bootstrap3"
path = "src/lib.rs"

[[bin]]
name = "bootstrap3"
path = "src/main.rs"
