// SRC: compiler/rustc_trait_selection/src/solve.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_trait_selection/src/solve.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_trait_selection/src/solve.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_trait_selection/src/solve.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_trait_selection/src/solve.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_trait_selection/src/solve.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_trait_selection/src/solve.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_trait_selection/src/solve.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: ../rust/compiler/rustc_trait_selection/src/solve.rs
pub use rustc_next_trait_solver::solve::*;

// MOD DECLARATION: delegate (from compiler/rustc_trait_selection/src/solve.rs)
// REPLACED: mod delegate; -> use crate::delegate::*;
use crate::delegate::*;
// MOD DECLARATION: fulfill (from compiler/rustc_trait_selection/src/solve.rs)
// REPLACED: mod fulfill; -> use crate::fulfill::*;
use crate::fulfill::*;
pub mod inspect;
// MOD DECLARATION: normalize (from compiler/rustc_trait_selection/src/solve.rs)
// REPLACED: mod normalize; -> use crate::normalize::*;
use crate::normalize::*;
// MOD DECLARATION: select (from compiler/rustc_trait_selection/src/solve.rs)
// REPLACED: mod select; -> use crate::select::*;
use crate::select::*;

pub(crate) use delegate::SolverDelegate;
pub use fulfill::{FulfillmentCtxt, NextSolverError, StalledOnCoroutines};
pub(crate) use normalize::deeply_normalize_for_diagnostics;
pub use normalize::{
    deeply_normalize, deeply_normalize_with_skipped_universes,
    deeply_normalize_with_skipped_universes_and_ambiguous_coroutine_goals,
};
use rustc_middle::query::Providers;
use rustc_middle::ty::TyCtxt;
pub use select::InferCtxtSelectExt;

fn evaluate_root_goal_for_proof_tree_raw<'tcx>(
    tcx: TyCtxt<'tcx>,
    canonical_input: CanonicalInput<TyCtxt<'tcx>>,
) -> (QueryResult<TyCtxt<'tcx>>, &'tcx inspect::Probe<TyCtxt<'tcx>>) {
    evaluate_root_goal_for_proof_tree_raw_provider::<SolverDelegate<'tcx>, TyCtxt<'tcx>>(
        tcx,
        canonical_input,
    )
}

pub fn provide(providers: &mut Providers) {
    *providers = Providers { evaluate_root_goal_for_proof_tree_raw, ..*providers };
}