// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Report whether this is running in CI"]
#[doc = ""]
#[doc = " CI is a common environment where, despite being piped, ansi color codes are supported"]
#[doc = ""]
#[doc = " This is not as exhaustive as you'd find in a crate like `is_ci` but it should work in enough"]
#[doc = " cases."]
#[inline]
pub fn is_ci() -> bool {
    std::env::var_os("CI").is_some()
}
