// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Check `TERM` for ANSI color support"]
#[doc = ""]
#[doc = " On Windows, you might need to also check [`windows::enable_ansi_colors`] as ANSI color support"]
#[doc = " is opt-in, rather than assumed."]
#[inline]
pub fn term_supports_ansi_color() -> bool {
    #[cfg(not(windows))]
    {
        term_supports_color()
    }
    #[cfg(windows)]
    {
        match std::env::var_os("TERM") {
            None => return false,
            Some(k) => {
                if k == "dumb" || k == "cygwin" {
                    return false;
                }
            }
        }
        true
    }
}
