// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Check [CLICOLOR_FORCE] status"]
#[doc = ""]
#[doc = " ANSI colors should be enabled no matter what."]
#[doc = ""]
#[doc = " [CLICOLOR_FORCE]: https://bixense.com/clicolors/"]
#[inline]
pub fn clicolor_force() -> bool {
    non_empty(std::env::var_os("CLICOLOR_FORCE").as_deref())
}
