// Generated macro for main (function)
macro_rules! Depcratemain {
() => {
// Module: crate
// Provides: {"main"}
// Dependencies: {}
pub fn main () { let (encode , decode) = load_table () ; println ! ("// !!! DO NOT EDIT !!! Generated by util/genhuff/src/main.rs") ; println ! () ; println ! ("// (num-bits, bits)") ; println ! ("pub const ENCODE_TABLE: [(usize, u64); 257] = [") ; for (nbits , val) in encode { println ! ("    ({}, 0x{})," , nbits , val) ; } println ! ("];") ; println ! () ; println ! ("// (next-state, byte, flags)") ; println ! ("pub const DECODE_TABLE: [[(usize, u8, u8); 16]; 256] = [") ; decode . print () ; println ! ("];") ; }
};
}
