// Generated macro for test (module)
macro_rules! Depcrate_output_render_blockstest {
() => {
// Module: crate::output::render::blocks
// Provides: {"test"}
// Dependencies: {}
# [cfg (test)] pub mod test { use nu_ansi_term :: Color :: * ; use nu_ansi_term :: Style ; use super :: Colours ; use crate :: fs :: fields as f ; use crate :: output :: cell :: { DisplayWidth , TextCell } ; use crate :: output :: table :: SizeFormat ; use locale :: Numeric as NumericLocale ; use number_prefix :: Prefix ; struct TestColours ; # [rustfmt :: skip] impl Colours for TestColours { fn blocksize (& self , _prefix : Option < Prefix >) -> Style { Fixed (66) . normal () } fn unit (& self , _prefix : Option < Prefix >) -> Style { Fixed (77) . bold () } fn no_blocksize (& self) -> Style { Black . italic () } } # [test] fn directory () { let directory = f :: Blocksize :: None ; let expected = TextCell :: blank (Black . italic ()) ; assert_eq ! (expected , directory . render (& TestColours , SizeFormat :: JustBytes , & NumericLocale :: english ())) ; } # [test] fn file_decimal () { let directory = f :: Blocksize :: Some (2_100_000) ; let expected = TextCell { width : DisplayWidth :: from (4) , contents : vec ! [Fixed (66) . paint ("2.1") , Fixed (77) . bold () . paint ("M")] . into () , } ; assert_eq ! (expected , directory . render (& TestColours , SizeFormat :: DecimalBytes , & NumericLocale :: english ())) ; } # [test] fn file_binary () { let directory = f :: Blocksize :: Some (1_048_576) ; let expected = TextCell { width : DisplayWidth :: from (5) , contents : vec ! [Fixed (66) . paint ("1.0") , Fixed (77) . bold () . paint ("Mi")] . into () , } ; assert_eq ! (expected , directory . render (& TestColours , SizeFormat :: BinaryBytes , & NumericLocale :: english ())) ; } # [test] fn file_bytes () { let directory = f :: Blocksize :: Some (1_048_576) ; let expected = TextCell { width : DisplayWidth :: from (9) , contents : vec ! [Fixed (66) . paint ("1,048,576")] . into () , } ; assert_eq ! (expected , directory . render (& TestColours , SizeFormat :: JustBytes , & NumericLocale :: english ())) ; } }
};
}
