// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " A timestamp with timezone."]
#[derive(Default, PartialEq, Eq, Debug, Hash, Ord, PartialOrd, Clone, Copy)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Time {
    #[doc = " The seconds that have passed since UNIX epoch. This makes it UTC, or `<seconds>+0000`."]
    pub seconds: SecondsSinceUnixEpoch,
    #[doc = " The time's offset in seconds, which may be negative to match the `sign` field."]
    pub offset: OffsetInSeconds,
}
