// Generated macro for check_private_key_components (function)
macro_rules! Depcrate_backend_rsacheck_private_key_components {
() => {
// Module: crate::backend::rsa
// Provides: {"check_private_key_components"}
// Dependencies: {}
# [allow (clippy :: too_many_arguments)] fn check_private_key_components (p : & pyo3 :: Bound < '_ , pyo3 :: types :: PyInt > , q : & pyo3 :: Bound < '_ , pyo3 :: types :: PyInt > , private_exponent : & pyo3 :: Bound < '_ , pyo3 :: types :: PyInt > , dmp1 : & pyo3 :: Bound < '_ , pyo3 :: types :: PyInt > , dmq1 : & pyo3 :: Bound < '_ , pyo3 :: types :: PyInt > , iqmp : & pyo3 :: Bound < '_ , pyo3 :: types :: PyInt > , public_exponent : & pyo3 :: Bound < '_ , pyo3 :: types :: PyInt > , modulus : & pyo3 :: Bound < '_ , pyo3 :: types :: PyInt > ,) -> CryptographyResult < () > { if modulus . lt (3) ? { return Err (CryptographyError :: from (pyo3 :: exceptions :: PyValueError :: new_err ("modulus must be >= 3.") ,)) ; } if p . ge (modulus) ? { return Err (CryptographyError :: from (pyo3 :: exceptions :: PyValueError :: new_err ("p must be < modulus.") ,)) ; } if q . ge (modulus) ? { return Err (CryptographyError :: from (pyo3 :: exceptions :: PyValueError :: new_err ("q must be < modulus.") ,)) ; } if dmp1 . ge (modulus) ? { return Err (CryptographyError :: from (pyo3 :: exceptions :: PyValueError :: new_err ("dmp1 must be < modulus.") ,)) ; } if dmq1 . ge (modulus) ? { return Err (CryptographyError :: from (pyo3 :: exceptions :: PyValueError :: new_err ("dmq1 must be < modulus.") ,)) ; } if iqmp . ge (modulus) ? { return Err (CryptographyError :: from (pyo3 :: exceptions :: PyValueError :: new_err ("iqmp must be < modulus.") ,)) ; } if private_exponent . ge (modulus) ? { return Err (CryptographyError :: from (pyo3 :: exceptions :: PyValueError :: new_err ("private_exponent must be < modulus.") ,)) ; } if public_exponent . lt (3) ? || public_exponent . ge (modulus) ? { return Err (CryptographyError :: from (pyo3 :: exceptions :: PyValueError :: new_err ("public_exponent must be >= 3 and < modulus.") ,)) ; } if public_exponent . bitand (1) ? . eq (0) ? { return Err (CryptographyError :: from (pyo3 :: exceptions :: PyValueError :: new_err ("public_exponent must be odd.") ,)) ; } if dmp1 . bitand (1) ? . eq (0) ? { return Err (CryptographyError :: from (pyo3 :: exceptions :: PyValueError :: new_err ("dmp1 must be odd.") ,)) ; } if dmq1 . bitand (1) ? . eq (0) ? { return Err (CryptographyError :: from (pyo3 :: exceptions :: PyValueError :: new_err ("dmq1 must be odd.") ,)) ; } if p . mul (q) ? . ne (modulus) ? { return Err (CryptographyError :: from (pyo3 :: exceptions :: PyValueError :: new_err ("p*q must equal modulus.") ,)) ; } Ok (()) }
};
}
