// Generated macro for macro_22 (macro)
macro_rules! Depcrate_generatedmacro_22 {
() => {
// Module: crate::generated
// Provides: {"macro_22"}
// Dependencies: {}
extern_class ! (# [doc = " An entry generated by an activity event."] # [doc = ""] # [doc = " See also [Apple's documentation](https://developer.apple.com/documentation/oslog/oslogentryactivity?language=objc)"] # [unsafe (super (OSLogEntry , NSObject))] # [derive (Debug , PartialEq , Eq , Hash)] pub struct OSLogEntryActivity ;) ;
};
}
