// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_rustc_mir_dataflow_decls_module_not_found_debuginfo,
    wrapped_rustc_mir_dataflow_decls_module_not_found_drop_flag_effects,
    wrapped_rustc_mir_dataflow_decls_module_not_found_errors,
    wrapped_rustc_mir_dataflow_decls_module_not_found_framework,
    wrapped_rustc_mir_dataflow_decls_module_not_found_impls,
    wrapped_rustc_mir_dataflow_decls_module_not_found_move_paths,
    wrapped_rustc_mir_dataflow_decls_module_not_found_points,
    wrapped_rustc_mir_dataflow_decls_module_not_found_rustc_peek,
    wrapped_rustc_mir_dataflow_decls_module_not_found_un_derefer,
    wrapped_rustc_mir_dataflow_decls_module_not_found_value_analysis,
    wrapped_rustc_mir_dataflow_decls_fluent_messages,
    wrapped_rustc_mir_dataflow_decls_MoveDataTypingEnv
);
