// Generated macro for parse_repr_tt (function)
macro_rules! Depcrate_attrparse_repr_tt {
() => {
// Module: crate::attr
// Provides: {"parse_repr_tt"}
// Dependencies: {}
fn parse_repr_tt (tt : & crate :: tt :: TopSubtree) -> Option < ReprOptions > { use crate :: builtin_type :: { BuiltinInt , BuiltinUint } ; use rustc_abi :: { Align , Integer , IntegerType , ReprFlags , ReprOptions } ; match tt . top_subtree () . delimiter { tt :: Delimiter { kind : DelimiterKind :: Parenthesis , .. } => { } _ => return None , } let mut acc = ReprOptions :: default () ; let mut tts = tt . iter () ; while let Some (tt) = tts . next () { let TtElement :: Leaf (tt :: Leaf :: Ident (ident)) = tt else { continue ; } ; let repr = match & ident . sym { s if * s == sym :: packed => { let pack = if let Some (TtElement :: Subtree (_ , mut tt_iter)) = tts . peek () { tts . next () ; if let Some (TtElement :: Leaf (tt :: Leaf :: Literal (lit))) = tt_iter . next () { lit . symbol . as_str () . parse () . unwrap_or_default () } else { 0 } } else { 0 } ; let pack = Some (Align :: from_bytes (pack) . unwrap_or (Align :: ONE)) ; ReprOptions { pack , .. Default :: default () } } s if * s == sym :: align => { let mut align = None ; if let Some (TtElement :: Subtree (_ , mut tt_iter)) = tts . peek () { tts . next () ; if let Some (TtElement :: Leaf (tt :: Leaf :: Literal (lit))) = tt_iter . next () && let Ok (a) = lit . symbol . as_str () . parse () { align = Align :: from_bytes (a) . ok () ; } } ReprOptions { align , .. Default :: default () } } s if * s == sym :: C => ReprOptions { flags : ReprFlags :: IS_C , .. Default :: default () } , s if * s == sym :: transparent => { ReprOptions { flags : ReprFlags :: IS_TRANSPARENT , .. Default :: default () } } s if * s == sym :: simd => ReprOptions { flags : ReprFlags :: IS_SIMD , .. Default :: default () } , repr => { let mut int = None ; if let Some (builtin) = BuiltinInt :: from_suffix_sym (repr) . map (Either :: Left) . or_else (| | BuiltinUint :: from_suffix_sym (repr) . map (Either :: Right)) { int = Some (match builtin { Either :: Left (bi) => match bi { BuiltinInt :: Isize => IntegerType :: Pointer (true) , BuiltinInt :: I8 => IntegerType :: Fixed (Integer :: I8 , true) , BuiltinInt :: I16 => IntegerType :: Fixed (Integer :: I16 , true) , BuiltinInt :: I32 => IntegerType :: Fixed (Integer :: I32 , true) , BuiltinInt :: I64 => IntegerType :: Fixed (Integer :: I64 , true) , BuiltinInt :: I128 => IntegerType :: Fixed (Integer :: I128 , true) , } , Either :: Right (bu) => match bu { BuiltinUint :: Usize => IntegerType :: Pointer (false) , BuiltinUint :: U8 => IntegerType :: Fixed (Integer :: I8 , false) , BuiltinUint :: U16 => IntegerType :: Fixed (Integer :: I16 , false) , BuiltinUint :: U32 => IntegerType :: Fixed (Integer :: I32 , false) , BuiltinUint :: U64 => IntegerType :: Fixed (Integer :: I64 , false) , BuiltinUint :: U128 => IntegerType :: Fixed (Integer :: I128 , false) , } , }) ; } ReprOptions { int , .. Default :: default () } } } ; merge_repr (& mut acc , repr) ; } Some (acc) }
};
}
