// Generated macro for impl_11 (impl)
macro_rules! Depcrate_dynamic_storeimpl_11 {
() => {
// Module: crate::dynamic_store
// Provides: {"impl_11"}
// Dependencies: {}
impl < T > SCDynamicStoreBuilder < T > { # [doc = " Set whether or not the created [`SCDynamicStore`] should have session keys or not."] # [doc = " See [`SCDynamicStoreCreateWithOptions`] for details."] # [doc = ""] # [doc = " Defaults to `false`."] # [doc = ""] # [doc = " [`SCDynamicStore`]: struct.SCDynamicStore.html"] # [doc = " [`SCDynamicStoreCreateWithOptions`]: https://developer.apple.com/documentation/systemconfiguration/1437818-scdynamicstorecreatewithoptions?language=objc"] pub fn session_keys (mut self , session_keys : bool) -> Self { self . session_keys = session_keys ; self } # [doc = " Set a callback context (callback function and data to pass to each callback call)."] # [doc = ""] # [doc = " Defaults to having callbacks disabled."] pub fn callback_context < T2 > (self , callback_context : SCDynamicStoreCallBackContext < T2 > ,) -> SCDynamicStoreBuilder < T2 > { SCDynamicStoreBuilder { name : self . name , session_keys : self . session_keys , callback_context : Some (callback_context) , } } # [doc = " Create the dynamic store session."] pub fn build (mut self) -> Option < SCDynamicStore > { let store_options = self . create_store_options () ; if let Some (callback_context) = self . callback_context . take () { SCDynamicStore :: create (& self . name , & store_options , Some (convert_callback :: < T >) , & mut self . create_context (callback_context) ,) } else { SCDynamicStore :: create (& self . name , & store_options , None , ptr :: null_mut ()) } } fn create_store_options (& self) -> CFDictionary { let key = unsafe { CFString :: wrap_under_create_rule (kSCDynamicStoreUseSessionKeys) } ; let value = CFBoolean :: from (self . session_keys) ; let typed_dict = CFDictionary :: from_CFType_pairs (& [(key , value)]) ; unsafe { CFDictionary :: wrap_under_get_rule (typed_dict . as_concrete_TypeRef ()) } } fn create_context (& self , callback_context : SCDynamicStoreCallBackContext < T > ,) -> SCDynamicStoreContext { let info_ptr = Box :: into_raw (Box :: new (callback_context)) ; SCDynamicStoreContext { version : 0 , info : info_ptr as * mut _ as * mut c_void , retain : None , release : Some (release_callback_context :: < T >) , copyDescription : None , } } }
};
}
