// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[proc_macro_attribute]
pub fn wrap_fn(_attr: ProcMacroTokenStream, item_ts: ProcMacroTokenStream) -> ProcMacroTokenStream {
    let item_fn: ItemFn = parse_macro_input!(item_ts as ItemFn);
    let mut output_tokens = TokenStream::new();
    if is_public(&item_fn.vis) {
        let hook_macro_def =
            generate_item_hook_macro("fn", &Item::Fn(item_fn.clone()), Some(&item_fn.sig.ident));
        output_tokens.extend(hook_macro_def);
    }
    output_tokens.extend(item_fn.to_token_stream());
    output_tokens.into()
}
