// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[proc_macro_attribute]
pub fn wrap_use(
    _attr: ProcMacroTokenStream,
    item_ts: ProcMacroTokenStream,
) -> ProcMacroTokenStream {
    let item_use: ItemUse = parse_macro_input!(item_ts as ItemUse);
    let mut output_tokens = TokenStream::new();
    let hook_macro_def = generate_item_hook_macro("use", &Item::Use(item_use.clone()), None);
    output_tokens.extend(hook_macro_def);
    output_tokens.extend(item_use.to_token_stream());
    output_tokens.into()
}
