// Generated macro for impl_86 (impl)
macro_rules! Depcrate_asmimpl_86 {
() => {
// Module: crate::asm
// Provides: {"impl_86"}
// Dependencies: {}
impl < 'gcc , 'tcx > AsmCodegenMethods < 'tcx > for CodegenCx < 'gcc , 'tcx > { fn codegen_global_asm (& mut self , template : & [InlineAsmTemplatePiece] , operands : & [GlobalAsmOperandRef < 'tcx >] , options : InlineAsmOptions , _line_spans : & [Span] ,) { let asm_arch = self . tcx . sess . asm_arch . unwrap () ; let att_dialect = matches ! (asm_arch , InlineAsmArch :: X86 | InlineAsmArch :: X86_64) && options . contains (InlineAsmOptions :: ATT_SYNTAX) ; let mut template_str = ".pushsection .text\n" . to_owned () ; if att_dialect { template_str . push_str (".att_syntax\n") ; } for piece in template { match * piece { InlineAsmTemplatePiece :: String (ref string) => { let mut index = 0 ; while index < string . len () { let comment_index = string [index ..] . find ("//") . map (| comment_index | comment_index + index) . unwrap_or (string . len ()) ; template_str . push_str (& string [index .. comment_index]) ; index = string [comment_index ..] . find ('\n') . map (| index | index + comment_index) . unwrap_or (string . len ()) ; } } InlineAsmTemplatePiece :: Placeholder { operand_idx , modifier : _ , span : _ } => { match operands [operand_idx] { GlobalAsmOperandRef :: Const { ref string } => { template_str . push_str (string) ; } GlobalAsmOperandRef :: SymFn { instance } => { let function = get_fn (self , instance) ; self . add_used_function (function) ; let name = self . tcx . symbol_name (instance) . name ; template_str . push_str (name) ; } GlobalAsmOperandRef :: SymStatic { def_id } => { let instance = Instance :: mono (self . tcx , def_id) ; let name = self . tcx . symbol_name (instance) . name ; template_str . push_str (name) ; } } } } } if att_dialect { template_str . push_str ("\n\t.intel_syntax noprefix") ; } template_str . push_str ("\n.popsection") ; self . context . add_top_level_asm (None , & template_str) ; } fn mangled_name (& self , instance : Instance < 'tcx >) -> String { self . tcx . symbol_name (instance) . name . to_string () } }
};
}
