// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_md5_decls_Digest,
    wrapped_md5_decls_impl_for_core_convert_From_Digest_,
    wrapped_md5_decls_impl_for_core_fmt_Debug,
    wrapped_md5_decls_impl_for_core_ops_Deref,
    wrapped_md5_decls_impl_for_core_ops_DerefMut,
    wrapped_md5_decls_macro_rules,
    wrapped_md5_decls_implement,
    wrapped_md5_decls_implement,
    wrapped_md5_decls_Context,
    wrapped_md5_decls_PADDING,
    wrapped_md5_decls_impl_for_Context,
    wrapped_md5_decls_impl_for_Default,
    wrapped_md5_decls_impl_for_core_convert_From_Context_,
    wrapped_md5_decls_impl_for_core_io_Write,
    wrapped_md5_decls_compute,
    wrapped_md5_decls_consume,
    wrapped_md5_decls_transform,
    wrapped_md5_decls_module_not_found_tests
);
