// Generated by unified_build.rs

// Adapted from rustc ui test suite (ui/type-alias-impl-trait/issue-72793.rs)


pub trait T {
    type Item;
}

pub type Alias<'a> = impl T<Item = &'a ()>;

struct S;
impl<'a> T for &'a S {
    type Item = &'a ();
}

#[define_opaque(Alias)]
pub fn filter_positive<'a>() -> Alias<'a> {
    &S
}

fn with_positive(fun: impl Fn(Alias<'_>)) {
    fun(filter_positive());
}

fn main() {
    with_positive(|_| ());
}