// Generated macro for impl_177 (impl)
macro_rules! Depcrate_sftpimpl_177 {
() => {
// Module: crate::sftp
// Provides: {"impl_177"}
// Dependencies: {}
impl FileStat { # [doc = " Returns the file type for this filestat."] pub fn file_type (& self) -> FileType { FileType :: from_perm (self . perm . unwrap_or (0) as c_ulong) } # [doc = " Returns whether this metadata is for a directory."] pub fn is_dir (& self) -> bool { self . file_type () . is_dir () } # [doc = " Returns whether this metadata is for a regular file."] pub fn is_file (& self) -> bool { self . file_type () . is_file () } # [doc = " Creates a new instance of a stat from a raw instance."] pub fn from_raw (raw : & raw :: LIBSSH2_SFTP_ATTRIBUTES) -> FileStat { fn val < T : Copy > (raw : & raw :: LIBSSH2_SFTP_ATTRIBUTES , t : & T , flag : c_ulong) -> Option < T > { if raw . flags & flag != 0 { Some (* t) } else { None } } FileStat { size : val (raw , & raw . filesize , raw :: LIBSSH2_SFTP_ATTR_SIZE) , uid : val (raw , & raw . uid , raw :: LIBSSH2_SFTP_ATTR_UIDGID) . map (| s | s as u32) , gid : val (raw , & raw . gid , raw :: LIBSSH2_SFTP_ATTR_UIDGID) . map (| s | s as u32) , perm : val (raw , & raw . permissions , raw :: LIBSSH2_SFTP_ATTR_PERMISSIONS) . map (| s | s as u32) , mtime : val (raw , & raw . mtime , raw :: LIBSSH2_SFTP_ATTR_ACMODTIME) . map (| s | s as u64) , atime : val (raw , & raw . atime , raw :: LIBSSH2_SFTP_ATTR_ACMODTIME) . map (| s | s as u64) , } } # [doc = " Convert this stat structure to its raw representation."] pub fn raw (& self) -> raw :: LIBSSH2_SFTP_ATTRIBUTES { fn flag < T > (o : & Option < T > , flag : c_ulong) -> c_ulong { if o . is_some () { flag } else { 0 } } raw :: LIBSSH2_SFTP_ATTRIBUTES { flags : flag (& self . size , raw :: LIBSSH2_SFTP_ATTR_SIZE) | flag (& self . uid , raw :: LIBSSH2_SFTP_ATTR_UIDGID) | flag (& self . gid , raw :: LIBSSH2_SFTP_ATTR_UIDGID) | flag (& self . perm , raw :: LIBSSH2_SFTP_ATTR_PERMISSIONS) | flag (& self . atime , raw :: LIBSSH2_SFTP_ATTR_ACMODTIME) | flag (& self . mtime , raw :: LIBSSH2_SFTP_ATTR_ACMODTIME) , filesize : self . size . unwrap_or (0) , uid : self . uid . unwrap_or (0) as c_ulong , gid : self . gid . unwrap_or (0) as c_ulong , permissions : self . perm . unwrap_or (0) as c_ulong , atime : self . atime . unwrap_or (0) as c_ulong , mtime : self . mtime . unwrap_or (0) as c_ulong , } } }
};
}
