// Generated macro for impl_70 (impl)
macro_rules! Depcrate_graphql_wsimpl_70 {
() => {
// Module: crate::graphql_ws
// Provides: {"impl_70"}
// Dependencies: {}
impl < S , I , T > Sink < T > for Connection < S , I > where T : TryInto < ClientMessage < S :: ScalarValue > > , T :: Error : Error , S : Schema , I : Init < S :: ScalarValue , S :: Context > + Send , { type Error = Infallible ; fn poll_ready (mut self : Pin < & mut Self > , cx : & mut Context) -> Poll < Result < () , Self :: Error > > { match & mut self . sink_state { ConnectionSinkState :: Ready { .. } => Poll :: Ready (Ok (())) , ConnectionSinkState :: HandlingMessage { result } => match Pin :: new (result) . poll (cx) { Poll :: Ready ((state , reactions)) => { self . reactions . push (reactions) ; self . sink_state = ConnectionSinkState :: Ready { state } ; Poll :: Ready (Ok (())) } Poll :: Pending => Poll :: Pending , } , ConnectionSinkState :: Closed => panic ! ("poll_ready called after close") , } } fn start_send (self : Pin < & mut Self > , item : T) -> Result < () , Self :: Error > { let s = self . get_mut () ; let state = & mut s . sink_state ; * state = match std :: mem :: replace (state , ConnectionSinkState :: Closed) { ConnectionSinkState :: Ready { state } => { match item . try_into () { Ok (msg) => ConnectionSinkState :: HandlingMessage { result : state . handle_message (msg) . boxed () , } , Err (e) => { s . reactions . push (Reaction :: ServerMessage (ServerMessage :: ConnectionError { payload : ConnectionErrorPayload { message : e . to_string () , } , }) . into_stream () ,) ; ConnectionSinkState :: Ready { state } } } } _ => panic ! ("start_send called when not ready") , } ; Ok (()) } fn poll_flush (self : Pin < & mut Self > , cx : & mut Context) -> Poll < Result < () , Self :: Error > > { < Self as Sink < T > > :: poll_ready (self , cx) } fn poll_close (mut self : Pin < & mut Self > , _cx : & mut Context) -> Poll < Result < () , Self :: Error > > { self . sink_state = ConnectionSinkState :: Closed ; if let Some (waker) = self . stream_waker . take () { waker . wake () ; } Poll :: Ready (Ok (())) } }
};
}
