// SRC: compiler/rustc_mir_dataflow/src/lib.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_mir_dataflow/src/lib.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_mir_dataflow/src/lib.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_mir_dataflow/src/lib.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_mir_dataflow/src/lib.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_mir_dataflow/src/lib.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_mir_dataflow/src/lib.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_mir_dataflow/src/lib.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: ../rust/compiler/rustc_mir_dataflow/src/lib.rs
// tidy-alphabetical-start
#![feature(assert_matches)]
#![feature(associated_type_defaults)]
#![feature(box_patterns)]
#![feature(exact_size_is_empty)]
#![feature(file_buffered)]
#![feature(never_type)]
#![feature(try_blocks)]
// tidy-alphabetical-end

use rustc_middle::ty;

// Please change the public `use` directives cautiously, as they might be used by external tools.
// See issue #120130.
pub use self::drop_flag_effects::{
    DropFlagState, drop_flag_effects_for_function_entry, drop_flag_effects_for_location,
    move_path_children_matching, on_all_children_bits, on_lookup_result_bits,
};
pub use self::framework::{
    Analysis, Backward, Direction, Forward, GenKill, JoinSemiLattice, MaybeReachable, Results,
    ResultsCursor, ResultsVisitor, fmt, graphviz, lattice, visit_reachable_results, visit_results,
};
use self::move_paths::MoveData;

pub mod debuginfo;
// MOD DECLARATION: drop_flag_effects (from compiler/rustc_mir_dataflow/src/lib.rs)
// REPLACED: mod drop_flag_effects; -> use crate::drop_flag_effects::*;
use crate::drop_flag_effects::*;
// MOD DECLARATION: errors (from compiler/rustc_mir_dataflow/src/lib.rs)
// REPLACED: mod errors; -> use crate::errors::*;
use crate::errors::*;
// MOD DECLARATION: framework (from compiler/rustc_mir_dataflow/src/lib.rs)
// REPLACED: mod framework; -> use crate::framework::*;
use crate::framework::*;
pub mod impls;
pub mod move_paths;
pub mod points;
pub mod rustc_peek;
// MOD DECLARATION: un_derefer (from compiler/rustc_mir_dataflow/src/lib.rs)
// REPLACED: mod un_derefer; -> use crate::un_derefer::*;
use crate::un_derefer::*;
pub mod value_analysis;

rustc_fluent_macro::fluent_messages! { "../messages.ftl" }

pub struct MoveDataTypingEnv<'tcx> {
    pub move_data: MoveData<'tcx>,
    pub typing_env: ty::TypingEnv<'tcx>,
}