// Generated macro for impl_352 (impl)
macro_rules! Depcrate_client_legacy_poolimpl_352 {
() => {
// Module: crate::client::legacy::pool
// Provides: {"impl_352"}
// Dependencies: {}
impl < T : Poolable , K : Key > Pool < T , K > { # [doc = " Returns a `Checkout` which is a future that resolves if an idle"] # [doc = " connection becomes available."] pub fn checkout (& self , key : K) -> Checkout < T , K > { Checkout { key , pool : self . clone () , waiter : None , } } # [doc = " Ensure that there is only ever 1 connecting task for HTTP/2"] # [doc = " connections. This does nothing for HTTP/1."] pub fn connecting (& self , key : & K , ver : Ver) -> Option < Connecting < T , K > > { if ver == Ver :: Http2 { if let Some (ref enabled) = self . inner { let mut inner = enabled . lock () . unwrap () ; return if inner . connecting . insert (key . clone ()) { let connecting = Connecting { key : key . clone () , pool : WeakOpt :: downgrade (enabled) , } ; Some (connecting) } else { trace ! ("HTTP/2 connecting already in progress for {:?}" , key) ; None } ; } } Some (Connecting { key : key . clone () , pool : WeakOpt :: none () , }) } # [cfg (test)] fn locked (& self) -> std :: sync :: MutexGuard < '_ , PoolInner < T , K > > { self . inner . as_ref () . expect ("enabled") . lock () . expect ("lock") } pub fn pooled (& self , # [cfg_attr (not (feature = "http2") , allow (unused_mut))] mut connecting : Connecting < T , K > , value : T ,) -> Pooled < T , K > { let (value , pool_ref) = if let Some (ref enabled) = self . inner { match value . reserve () { # [cfg (feature = "http2")] Reservation :: Shared (to_insert , to_return) => { let mut inner = enabled . lock () . unwrap () ; inner . put (connecting . key . clone () , to_insert , enabled) ; inner . connected (& connecting . key) ; connecting . pool = WeakOpt :: none () ; (to_return , WeakOpt :: none ()) } Reservation :: Unique (value) => { (value , WeakOpt :: downgrade (enabled)) } } } else { debug_assert ! (connecting . pool . upgrade () . is_none ()) ; (value , WeakOpt :: none ()) } ; Pooled { key : connecting . key . clone () , is_reused : false , pool : pool_ref , value : Some (value) , } } fn reuse (& self , key : & K , value : T) -> Pooled < T , K > { debug ! ("reuse idle connection for {:?}" , key) ; let mut pool_ref = WeakOpt :: none () ; if ! value . can_share () { if let Some (ref enabled) = self . inner { pool_ref = WeakOpt :: downgrade (enabled) ; } } Pooled { is_reused : true , key : key . clone () , pool : pool_ref , value : Some (value) , } } }
};
}
