// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter.rs:211 from submodules/split-decls-rs/src/eager_splitter.rs
// Do not edit this file by hand. Your changes will be overwritten.

#[llm_error_message(message = "Module file not found for: standard_library_imports")]
#[llm_context(
    crate_name = "wrapped_rustc_builtin_macros",
    module_name = "standard_library_imports"
)]
pub struct wrapped_rustc_builtin_macros_decls_module_not_found_standard_library_imports;
