// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Contains the sub-token-trees of a \"delimited\" token tree such as `(a b c)`."]
#[doc = " The delimiters are not represented explicitly in the `tts` vector."]
#[derive(PartialEq, Encodable, Decodable, Debug)]
pub struct Delimited {
    pub delim: Delimiter,
    #[doc = " FIXME: #67062 has details about why this is sub-optimal."]
    pub tts: Vec<TokenTree>,
}
