// Generated macro for other_28761 (other)
macro_rules! Depcrate_um_highlevelmonitorconfigurationapiother_28761 {
() => {
// Module: crate::um::highlevelmonitorconfigurationapi
// Provides: {"other_28761"}
// Dependencies: {}
extern "system" { pub fn GetMonitorCapabilities (hMonitor : HANDLE , pdwMonitorCapabilities : LPDWORD , pdwSupportedColorTemperature : LPDWORD ,) -> _BOOL ; pub fn SaveCurrentMonitorSettings (hMonitor : HANDLE ,) -> _BOOL ; pub fn GetMonitorTechnologyType (hMonitor : HANDLE , pdtyDisplayTechnologyType : LPMC_DISPLAY_TECHNOLOGY_TYPE ,) -> _BOOL ; pub fn GetMonitorBrightness (hMonitor : HANDLE , pdwMinimumBrightness : LPDWORD , pdwCurrentBrightness : LPDWORD , pdwMaximumBrightness : LPDWORD ,) -> _BOOL ; pub fn GetMonitorContrast (hMonitor : HANDLE , pdwMinimumContrast : LPDWORD , pdwCurrentContrast : LPDWORD , pdwMaximumContrast : LPDWORD ,) -> _BOOL ; pub fn GetMonitorColorTemperature (hMonitor : HANDLE , pctCurrentColorTemperature : LPMC_COLOR_TEMPERATURE ,) -> _BOOL ; pub fn GetMonitorRedGreenOrBlueDrive (hMonitor : HANDLE , dtDriveType : MC_DRIVE_TYPE , pdwMinimumDrive : LPDWORD , pdwCurrentDrive : LPDWORD , pdwMaximumDrive : LPDWORD ,) -> _BOOL ; pub fn GetMonitorRedGreenOrBlueGain (hMonitor : HANDLE , gtGainType : MC_GAIN_TYPE , pdwMinimumGain : LPDWORD , pdwCurrentGain : LPDWORD , pdwMaximumGain : LPDWORD ,) -> _BOOL ; pub fn SetMonitorBrightness (hMonitor : HANDLE , dwNewBrightness : DWORD ,) -> _BOOL ; pub fn SetMonitorContrast (hMonitor : HANDLE , dwNewContrast : DWORD ,) -> _BOOL ; pub fn SetMonitorColorTemperature (hMonitor : HANDLE , ctCurrentColorTemperature : MC_COLOR_TEMPERATURE ,) -> _BOOL ; pub fn SetMonitorRedGreenOrBlueDrive (hMonitor : HANDLE , dtDriveType : MC_DRIVE_TYPE , dwNewDrive : DWORD ,) -> _BOOL ; pub fn SetMonitorRedGreenOrBlueGain (hMonitor : HANDLE , gtGainType : MC_GAIN_TYPE , dwNewGain : DWORD ,) -> _BOOL ; pub fn DegaussMonitor (hMonitor : HANDLE ,) -> _BOOL ; pub fn GetMonitorDisplayAreaSize (hMonitor : HANDLE , stSizeType : MC_SIZE_TYPE , pdwMinimumWidthOrHeight : LPDWORD , pdwCurrentWidthOrHeight : LPDWORD , pdwMaximumWidthOrHeight : LPDWORD ,) -> _BOOL ; pub fn GetMonitorDisplayAreaPosition (hMonitor : HANDLE , ptPositionType : MC_POSITION_TYPE , pdwMinimumPosition : LPDWORD , pdwCurrentPosition : LPDWORD , pdwMaximumPosition : LPDWORD ,) -> _BOOL ; pub fn SetMonitorDisplayAreaSize (hMonitor : HANDLE , stSizeType : MC_SIZE_TYPE , dwNewDisplayAreaWidthOrHeight : DWORD ,) -> _BOOL ; pub fn SetMonitorDisplayAreaPosition (hMonitor : HANDLE , ptPositionType : MC_POSITION_TYPE , dwNewPosition : DWORD ,) -> _BOOL ; pub fn RestoreMonitorFactoryColorDefaults (hMonitor : HANDLE ,) -> _BOOL ; pub fn RestoreMonitorFactoryDefaults (hMonitor : HANDLE ,) -> _BOOL ; }
};
}
