// Generated macro for HID_USAGE_CONSUMER_IMPLEMENTED_KEYBOARD_INPUT_ASSIST_CONTROLS (const)
macro_rules! Depcrate_shared_hidusageHID_USAGE_CONSUMER_IMPLEMENTED_KEYBOARD_INPUT_ASSIST_CONTROLS {
() => {
// Module: crate::shared::hidusage
// Provides: {"HID_USAGE_CONSUMER_IMPLEMENTED_KEYBOARD_INPUT_ASSIST_CONTROLS"}
// Dependencies: {}
pub const HID_USAGE_CONSUMER_IMPLEMENTED_KEYBOARD_INPUT_ASSIST_CONTROLS : USAGE = 0x2C6 ;
};
}
