// Generated macro for WLAN_REASON_CODE_MSMSEC_CAPABILITY_PROFILE (const)
macro_rules! Depcrate_um_wlanapiWLAN_REASON_CODE_MSMSEC_CAPABILITY_PROFILE {
() => {
// Module: crate::um::wlanapi
// Provides: {"WLAN_REASON_CODE_MSMSEC_CAPABILITY_PROFILE"}
// Dependencies: {}
pub const WLAN_REASON_CODE_MSMSEC_CAPABILITY_PROFILE : WLAN_REASON_CODE = WLAN_REASON_CODE_MSMSEC_BASE + 20 ;
};
}
