// Generated macro for BLUETOOTH_GATT_FLAG_VALID_MASK (const)
macro_rules! Depcrate_um_bthledefBLUETOOTH_GATT_FLAG_VALID_MASK {
() => {
// Module: crate::um::bthledef
// Provides: {"BLUETOOTH_GATT_FLAG_VALID_MASK"}
// Dependencies: {}
pub const BLUETOOTH_GATT_FLAG_VALID_MASK : ULONG = BLUETOOTH_GATT_FLAG_NONE | BLUETOOTH_GATT_FLAG_CONNECTION_ENCRYPTED | BLUETOOTH_GATT_FLAG_CONNECTION_AUTHENTICATED | BLUETOOTH_GATT_FLAG_FORCE_READ_FROM_DEVICE | BLUETOOTH_GATT_FLAG_FORCE_READ_FROM_CACHE | BLUETOOTH_GATT_FLAG_SIGNED_WRITE | BLUETOOTH_GATT_FLAG_WRITE_WITHOUT_RESPONSE | BLUETOOTH_GATT_FLAG_RETURN_ALL ;
};
}
