// Generated macro for macro_28412 (macro)
macro_rules! Depcrate_um_eaptypesmacro_28412 {
() => {
// Module: crate::um::eaptypes
// Provides: {"macro_28412"}
// Dependencies: {}
ENUM ! { enum EAP_ATTRIBUTE_TYPE { eatMinimum = 0 , eatUserName = 1 , eatUserPassword = 2 , eatMD5CHAPPassword = 3 , eatNASIPAddress = 4 , eatNASPort = 5 , eatServiceType = 6 , eatFramedProtocol = 7 , eatFramedIPAddress = 8 , eatFramedIPNetmask = 9 , eatFramedRouting = 10 , eatFilterId = 11 , eatFramedMTU = 12 , eatFramedCompression = 13 , eatLoginIPHost = 14 , eatLoginService = 15 , eatLoginTCPPort = 16 , eatUnassigned17 = 17 , eatReplyMessage = 18 , eatCallbackNumber = 19 , eatCallbackId = 20 , eatUnassigned21 = 21 , eatFramedRoute = 22 , eatFramedIPXNetwork = 23 , eatState = 24 , eatClass = 25 , eatVendorSpecific = 26 , eatSessionTimeout = 27 , eatIdleTimeout = 28 , eatTerminationAction = 29 , eatCalledStationId = 30 , eatCallingStationId = 31 , eatNASIdentifier = 32 , eatProxyState = 33 , eatLoginLATService = 34 , eatLoginLATNode = 35 , eatLoginLATGroup = 36 , eatFramedAppleTalkLink = 37 , eatFramedAppleTalkNetwork = 38 , eatFramedAppleTalkZone = 39 , eatAcctStatusType = 40 , eatAcctDelayTime = 41 , eatAcctInputOctets = 42 , eatAcctOutputOctets = 43 , eatAcctSessionId = 44 , eatAcctAuthentic = 45 , eatAcctSessionTime = 46 , eatAcctInputPackets = 47 , eatAcctOutputPackets = 48 , eatAcctTerminateCause = 49 , eatAcctMultiSessionId = 50 , eatAcctLinkCount = 51 , eatAcctEventTimeStamp = 55 , eatMD5CHAPChallenge = 60 , eatNASPortType = 61 , eatPortLimit = 62 , eatLoginLATPort = 63 , eatTunnelType = 64 , eatTunnelMediumType = 65 , eatTunnelClientEndpoint = 66 , eatTunnelServerEndpoint = 67 , eatARAPPassword = 70 , eatARAPFeatures = 71 , eatARAPZoneAccess = 72 , eatARAPSecurity = 73 , eatARAPSecurityData = 74 , eatPasswordRetry = 75 , eatPrompt = 76 , eatConnectInfo = 77 , eatConfigurationToken = 78 , eatEAPMessage = 79 , eatSignature = 80 , eatARAPChallengeResponse = 84 , eatAcctInterimInterval = 85 , eatNASIPv6Address = 95 , eatFramedInterfaceId = 96 , eatFramedIPv6Prefix = 97 , eatLoginIPv6Host = 98 , eatFramedIPv6Route = 99 , eatFramedIPv6Pool = 100 , eatARAPGuestLogon = 8096 , eatCertificateOID = 8097 , eatEAPConfiguration = 8098 , eatPEAPEmbeddedEAPTypeId = 8099 , eatPEAPFastRoamedSession = 8100 , eatFastRoamedSession = 8100 , eatEAPTLV = 8102 , eatCredentialsChanged = 8103 , eatInnerEapMethodType = 8104 , eatClearTextPassword = 8107 , eatQuarantineSoH = 8150 , eatCertificateThumbprint = 8250 , eatPeerId = 9000 , eatServerId = 9001 , eatMethodId = 9002 , eatEMSK = 9003 , eatSessionId = 9004 , eatReserved = 0xFFFFFFFF , } }
};
}
