// Generated macro for PERF_COUNTERSET_SINGLE_AGGREGATE_HISTORY (const)
macro_rules! Depcrate_um_perflibPERF_COUNTERSET_SINGLE_AGGREGATE_HISTORY {
() => {
// Module: crate::um::perflib
// Provides: {"PERF_COUNTERSET_SINGLE_AGGREGATE_HISTORY"}
// Dependencies: {}
pub const PERF_COUNTERSET_SINGLE_AGGREGATE_HISTORY : ULONG = PERF_COUNTERSET_FLAG_HISTORY | PERF_COUNTERSET_SINGLE_AGGREGATE ;
};
}
