// Generated macro for other_29202 (other)
macro_rules! Depcrate_um_iphlpapiother_29202 {
() => {
// Module: crate::um::iphlpapi
// Provides: {"other_29202"}
// Dependencies: {}
extern "system" { pub fn NotifyIfTimestampConfigChange (CallerContext : PVOID , Callback : PINTERFACE_TIMESTAMP_CONFIG_CHANGE_CALLBACK , NotificationHandle : * mut HIFTIMESTAMPCHANGE ,) -> DWORD ; pub fn CancelIfTimestampConfigChange (NotificationHandle : HIFTIMESTAMPCHANGE ,) ; pub fn IpReleaseAddress (AdapterInfo : PIP_ADAPTER_INDEX_MAP ,) -> DWORD ; pub fn IpRenewAddress (AdapterInfo : PIP_ADAPTER_INDEX_MAP ,) -> DWORD ; pub fn SendARP (DestIP : IPAddr , SrcIP : IPAddr , pMacAddr : PVOID , PhyAddrLen : PULONG ,) -> DWORD ; pub fn GetRTTAndHopCount (DestIpAddress : IPAddr , HopCount : PULONG , MaxHops : ULONG , RTT : PULONG ,) -> BOOL ; pub fn GetFriendlyIfIndex (IfIndex : DWORD ,) -> DWORD ; pub fn EnableRouter (pHandle : * mut HANDLE , pOverlapped : * mut OVERLAPPED ,) -> DWORD ; pub fn UnenableRouter (pOverlapped : * mut OVERLAPPED , lpdwEnableCount : LPDWORD ,) -> DWORD ; pub fn DisableMediaSense (pHandle : * mut HANDLE , pOverLapped : * mut OVERLAPPED ,) -> DWORD ; pub fn RestoreMediaSense (pOverlapped : * mut OVERLAPPED , lpdwEnableCount : LPDWORD ,) -> DWORD ; pub fn GetIpErrorString (ErrorCode : IP_STATUS , Buffer : PWSTR , Size : PDWORD ,) -> DWORD ; pub fn ResolveNeighbor (NetworkAddress : * mut SOCKADDR , PhysicalAddress : PVOID , PhysicalAddressLength : PULONG ,) -> ULONG ; pub fn CreatePersistentTcpPortReservation (StartPort : USHORT , NumberOfPorts : USHORT , Token : PULONG64 ,) -> ULONG ; pub fn CreatePersistentUdpPortReservation (StartPort : USHORT , NumberOfPorts : USHORT , Token : PULONG64 ,) -> ULONG ; pub fn DeletePersistentTcpPortReservation (StartPort : USHORT , NumberOfPorts : USHORT ,) -> ULONG ; pub fn DeletePersistentUdpPortReservation (StartPort : USHORT , NumberOfPorts : USHORT ,) -> ULONG ; pub fn LookupPersistentTcpPortReservation (StartPort : USHORT , NumberOfPorts : USHORT , Token : PULONG64 ,) -> ULONG ; pub fn LookupPersistentUdpPortReservation (StartPort : USHORT , NumberOfPorts : USHORT , Token : PULONG64 ,) -> ULONG ; }
};
}
