// Generated macro for macro_27984 (macro)
macro_rules! Depcrate_um_dwrite_1macro_27984 {
() => {
// Module: crate::um::dwrite_1
// Provides: {"macro_27984"}
// Dependencies: {}
ENUM ! { enum DWRITE_PANOSE_CONTRAST { DWRITE_PANOSE_CONTRAST_ANY = 0x0 , DWRITE_PANOSE_CONTRAST_NO_FIT = 0x1 , DWRITE_PANOSE_CONTRAST_NONE = 0x2 , DWRITE_PANOSE_CONTRAST_VERY_LOW = 0x3 , DWRITE_PANOSE_CONTRAST_LOW = 0x4 , DWRITE_PANOSE_CONTRAST_MEDIUM_LOW = 0x5 , DWRITE_PANOSE_CONTRAST_MEDIUM = 0x6 , DWRITE_PANOSE_CONTRAST_MEDIUM_HIGH = 0x7 , DWRITE_PANOSE_CONTRAST_HIGH = 0x8 , DWRITE_PANOSE_CONTRAST_VERY_HIGH = 0x9 , DWRITE_PANOSE_CONTRAST_HORIZONTAL_LOW = 0xA , DWRITE_PANOSE_CONTRAST_HORIZONTAL_MEDIUM = 0xB , DWRITE_PANOSE_CONTRAST_HORIZONTAL_HIGH = 0xC , DWRITE_PANOSE_CONTRAST_BROKEN = 0xD , } }
};
}
