// Generated macro for Lookahead1 (struct)
macro_rules! Depcrate_lookaheadLookahead1 {
() => {
// Module: crate::lookahead
// Provides: {"Lookahead1"}
// Dependencies: {}
# [doc = " Support for checking the next token in a stream to decide how to parse."] # [doc = ""] # [doc = " An important advantage over [`ParseStream::peek`] is that here we"] # [doc = " automatically construct an appropriate error message based on the token"] # [doc = " alternatives that get peeked. If you are producing your own error message,"] # [doc = " go ahead and use `ParseStream::peek` instead."] # [doc = ""] # [doc = " Use [`ParseStream::lookahead1`] to construct this object."] # [doc = ""] # [doc = " [`ParseStream::peek`]: crate::parse::ParseBuffer::peek"] # [doc = " [`ParseStream::lookahead1`]: crate::parse::ParseBuffer::lookahead1"] # [doc = ""] # [doc = " Consuming tokens from the source stream after constructing a lookahead"] # [doc = " object does not also advance the lookahead object."] # [doc = ""] # [doc = " # Example"] # [doc = ""] # [doc = " ```"] # [doc = " use syn::{ConstParam, Ident, Lifetime, LifetimeParam, Result, Token, TypeParam};"] # [doc = " use syn::parse::{Parse, ParseStream};"] # [doc = ""] # [doc = " // A generic parameter, a single one of the comma-separated elements inside"] # [doc = " // angle brackets in:"] # [doc = " //"] # [doc = " //     fn f<T: Clone, 'a, 'b: 'a, const N: usize>() { ... }"] # [doc = " //"] # [doc = " // On invalid input, lookahead gives us a reasonable error message."] # [doc = " //"] # [doc = " //     error: expected one of: identifier, lifetime, `const`"] # [doc = " //       |"] # [doc = " //     5 |     fn f<!Sized>() {}"] # [doc = " //       |          ^"] # [doc = " enum GenericParam {"] # [doc = "     Type(TypeParam),"] # [doc = "     Lifetime(LifetimeParam),"] # [doc = "     Const(ConstParam),"] # [doc = " }"] # [doc = ""] # [doc = " impl Parse for GenericParam {"] # [doc = "     fn parse(input: ParseStream) -> Result<Self> {"] # [doc = "         let lookahead = input.lookahead1();"] # [doc = "         if lookahead.peek(Ident) {"] # [doc = "             input.parse().map(GenericParam::Type)"] # [doc = "         } else if lookahead.peek(Lifetime) {"] # [doc = "             input.parse().map(GenericParam::Lifetime)"] # [doc = "         } else if lookahead.peek(Token![const]) {"] # [doc = "             input.parse().map(GenericParam::Const)"] # [doc = "         } else {"] # [doc = "             Err(lookahead.error())"] # [doc = "         }"] # [doc = "     }"] # [doc = " }"] # [doc = " ```"] pub struct Lookahead1 < 'a > { scope : Span , cursor : Cursor < 'a > , comparisons : RefCell < Vec < & 'static str > > , }
};
}
