// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
impl MacroDylib {
    #[doc = " Creates a new MacroDylib instance with the given path."]
    pub fn new(path: AbsPathBuf) -> MacroDylib {
        MacroDylib { path }
    }
}
