// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_ide_ssr_decls_module_not_found_fragments,
    wrapped_ide_ssr_decls_module_not_found_from_comment,
    wrapped_ide_ssr_decls_module_not_found_matching,
    wrapped_ide_ssr_decls_module_not_found_nester,
    wrapped_ide_ssr_decls_module_not_found_parsing,
    wrapped_ide_ssr_decls_module_not_found_replacing,
    wrapped_ide_ssr_decls_module_not_found_resolving,
    wrapped_ide_ssr_decls_module_not_found_search,
    wrapped_ide_ssr_decls_module_not_found_errors,
    wrapped_ide_ssr_decls_module_not_found_tests,
    wrapped_ide_ssr_decls_SsrRule,
    wrapped_ide_ssr_decls_SsrPattern,
    wrapped_ide_ssr_decls_SsrMatches,
    wrapped_ide_ssr_decls_MatchFinder,
    wrapped_ide_ssr_decls_impl_for_MatchFinder,
    wrapped_ide_ssr_decls_MatchDebugInfo,
    wrapped_ide_ssr_decls_impl_for_std_fmt_Debug,
    wrapped_ide_ssr_decls_impl_for_SsrMatches,
    wrapped_ide_ssr_decls_impl_for_Match,
    wrapped_ide_ssr_decls_impl_for_std_error_Error,
    wrapped_ide_ssr_decls_impl_for_MatchDebugInfo
);
