// Generated macro for B (function)
macro_rules! Depcrate_ext_sliceB {
() => {
// Module: crate::ext_slice
// Provides: {"B"}
// Dependencies: {}
# [doc = " A short-hand constructor for building a `&[u8]`."] # [doc = ""] # [doc = " This idiosyncratic constructor is useful for concisely building byte string"] # [doc = " slices. Its primary utility is in conveniently writing byte string literals"] # [doc = " in a uniform way. For example, consider this code that does not compile:"] # [doc = ""] # [doc = " ```ignore"] # [doc = " let strs = vec![b\"a\", b\"xy\"];"] # [doc = " ```"] # [doc = ""] # [doc = " The above code doesn't compile because the type of the byte string literal"] # [doc = " `b\"a\"` is `&'static [u8; 1]`, and the type of `b\"xy\"` is"] # [doc = " `&'static [u8; 2]`. Since their types aren't the same, they can't be stored"] # [doc = " in the same `Vec`. (This is dissimilar from normal Unicode string slices,"] # [doc = " where both `\"a\"` and `\"xy\"` have the same type of `&'static str`.)"] # [doc = ""] # [doc = " One way of getting the above code to compile is to convert byte strings to"] # [doc = " slices. You might try this:"] # [doc = ""] # [doc = " ```ignore"] # [doc = " let strs = vec![&b\"a\", &b\"xy\"];"] # [doc = " ```"] # [doc = ""] # [doc = " But this just creates values with type `& &'static [u8; 1]` and"] # [doc = " `& &'static [u8; 2]`. Instead, you need to force the issue like so:"] # [doc = ""] # [doc = " ```"] # [doc = " let strs = vec![&b\"a\"[..], &b\"xy\"[..]];"] # [doc = " // or"] # [doc = " let strs = vec![b\"a\".as_ref(), b\"xy\".as_ref()];"] # [doc = " ```"] # [doc = ""] # [doc = " But neither of these are particularly convenient to type, especially when"] # [doc = " it's something as common as a string literal. Thus, this constructor"] # [doc = " permits writing the following instead:"] # [doc = ""] # [doc = " ```"] # [doc = " use bstr::B;"] # [doc = ""] # [doc = " let strs = vec![B(\"a\"), B(b\"xy\")];"] # [doc = " ```"] # [doc = ""] # [doc = " Notice that this also lets you mix and match both string literals and byte"] # [doc = " string literals. This can be quite convenient!"] # [allow (non_snake_case)] # [inline] pub fn B < B : ? Sized + AsRef < [u8] > > (bytes : & B) -> & [u8] { bytes . as_ref () }
};
}
