macro_rules! deps {
    () => {
        InvalidGcFailed!();
        Ok!();
        FinalizedGcFailed!();
    };
}

macro_rules! garbage_collect_session_directories {
    () => {
        deps!();
        # [doc = " Runs garbage collection for the current session."] pub (crate) fn garbage_collect_session_directories (sess : & Session) -> io :: Result < () > { debug ! ("garbage_collect_session_directories() - begin") ; let session_directory = sess . incr_comp_session_dir () ; debug ! ("garbage_collect_session_directories() - session directory: {}" , session_directory . display ()) ; let crate_directory = session_directory . parent () . unwrap () ; debug ! ("garbage_collect_session_directories() - crate directory: {}" , crate_directory . display ()) ; let mut session_directories = FxIndexSet :: default () ; let mut lock_files = UnordSet :: default () ; for dir_entry in crate_directory . read_dir () ? { let Ok (dir_entry) = dir_entry else { continue ; } ; let entry_name = dir_entry . file_name () ; let Some (entry_name) = entry_name . to_str () else { continue ; } ; if is_session_directory_lock_file (& entry_name) { lock_files . insert (entry_name . to_string ()) ; } else if is_session_directory (& entry_name) { session_directories . insert (entry_name . to_string ()) ; } else { } } session_directories . sort () ; let lock_file_to_session_dir : UnordMap < String , Option < String > > = lock_files . into_items () . map (| lock_file_name | { assert ! (lock_file_name . ends_with (LOCK_FILE_EXT)) ; let dir_prefix_end = lock_file_name . len () - LOCK_FILE_EXT . len () ; let session_dir = { let dir_prefix = & lock_file_name [0 .. dir_prefix_end] ; session_directories . iter () . find (| dir_name | dir_name . starts_with (dir_prefix)) } ; (lock_file_name , session_dir . map (String :: clone)) }) . into () ; for (lock_file_name , directory_name) in lock_file_to_session_dir . items () . into_sorted_stable_ord () { if directory_name . is_none () { let Ok (timestamp) = extract_timestamp_from_session_dir (lock_file_name) else { debug ! ("found lock-file with malformed timestamp: {}" , crate_directory . join (& lock_file_name) . display ()) ; continue ; } ; let lock_file_path = crate_directory . join (& * lock_file_name) ; if is_old_enough_to_be_collected (timestamp) { debug ! ("garbage_collect_session_directories() - deleting \
                    garbage lock file: {}" , lock_file_path . display ()) ; delete_session_dir_lock_file (sess , & lock_file_path) ; } else { debug ! ("garbage_collect_session_directories() - lock file with \
                    no session dir not old enough to be collected: {}" , lock_file_path . display ()) ; } } } let lock_file_to_session_dir : UnordMap < String , String > = lock_file_to_session_dir . into_items () . filter_map (| (lock_file_name , directory_name) | directory_name . map (| n | (lock_file_name , n))) . into () ; for directory_name in session_directories { if ! lock_file_to_session_dir . items () . any (| (_ , dir) | * dir == directory_name) { let path = crate_directory . join (directory_name) ; if let Err (err) = std_fs :: remove_dir_all (& path) { sess . dcx () . emit_warn (errors :: InvalidGcFailed { path : & path , err }) ; } } } let deletion_candidates = lock_file_to_session_dir . items () . filter_map (| (lock_file_name , directory_name) | { debug ! ("garbage_collect_session_directories() - inspecting: {}" , directory_name) ; let Ok (timestamp) = extract_timestamp_from_session_dir (directory_name) else { debug ! ("found session-dir with malformed timestamp: {}" , crate_directory . join (directory_name) . display ()) ; return None ; } ; if is_finalized (directory_name) { let lock_file_path = crate_directory . join (lock_file_name) ; match flock :: Lock :: new (& lock_file_path , false , false , true ,) { Ok (lock) => { debug ! ("garbage_collect_session_directories() - \
                            successfully acquired lock") ; debug ! ("garbage_collect_session_directories() - adding \
                            deletion candidate: {}" , directory_name) ; return Some (((timestamp , crate_directory . join (directory_name)) , Some (lock) ,)) ; } Err (_) => { debug ! ("garbage_collect_session_directories() - \
                            not collecting, still in use") ; } } } else if is_old_enough_to_be_collected (timestamp) { let lock_file_path = crate_directory . join (lock_file_name) ; match flock :: Lock :: new (& lock_file_path , false , false , true ,) { Ok (lock) => { debug ! ("garbage_collect_session_directories() - \
                            successfully acquired lock") ; delete_old (sess , & crate_directory . join (directory_name)) ; drop (lock) ; } Err (_) => { debug ! ("garbage_collect_session_directories() - \
                            not collecting, still in use") ; } } } else { debug ! ("garbage_collect_session_directories() - not finalized, not \
                    old enough") ; } None }) ; let deletion_candidates = deletion_candidates . into () ; all_except_most_recent (deletion_candidates) . into_items () . all (| (path , lock) | { debug ! ("garbage_collect_session_directories() - deleting `{}`" , path . display ()) ; if let Err (err) = std_fs :: remove_dir_all (& path) { sess . dcx () . emit_warn (errors :: FinalizedGcFailed { path : & path , err }) ; } else { delete_session_dir_lock_file (sess , & lock_file_path (& path)) ; } drop (lock) ; true }) ; Ok (()) }
    };
}

garbage_collect_session_directories!()