// Generated macro for impl_302 (impl)
macro_rules! Depcrate_http3_driverimpl_302 {
() => {
// Module: crate::http3::driver
// Provides: {"impl_302"}
// Dependencies: {}
impl < H : DriverHooks > H3Driver < H > { # [doc = " Reads all buffered datagrams out of `qconn` and distributes them to"] # [doc = " their flow channels."] fn process_available_dgrams (& mut self , qconn : & mut QuicheConnection ,) -> H3ConnectionResult < () > { loop { match datagram :: receive_h3_dgram (qconn) { Ok ((flow_id , dgram)) => { self . get_or_insert_flow (flow_id) ? . send_best_effort (dgram) ; } , Err (quiche :: Error :: Done) => return Ok (()) , Err (err) => return Err (H3ConnectionError :: from (err)) , } } } # [doc = " Flushes any queued-up frames for `stream_id` into `qconn` until either"] # [doc = " there is no more capacity in `qconn` or no more frames to send."] fn process_writable_stream (& mut self , qconn : & mut QuicheConnection , stream_id : u64 ,) -> H3ConnectionResult < () > { let conn = self . conn . as_mut () . ok_or (Self :: connection_not_present ()) ? ; let Some (ctx) = self . stream_map . get_mut (& stream_id) else { return Ok (()) ; } ; loop { match Self :: process_write_frame (conn , qconn , ctx) { Ok (()) => ctx . queued_frame = None , Err (h3 :: Error :: StreamBlocked | h3 :: Error :: Done) => break , Err (h3 :: Error :: MessageError) => { return self . finish_stream (qconn , stream_id , Some (quiche :: h3 :: WireErrorCode :: MessageError as u64) , Some (quiche :: h3 :: WireErrorCode :: MessageError as u64) ,) ; } , Err (h3 :: Error :: TransportError (quiche :: Error :: StreamStopped (e ,))) => { ctx . handle_recvd_stop_sending (e) ; if ctx . both_directions_done () { return self . finish_stream (qconn , stream_id , None , None) ; } else { return Ok (()) ; } } , Err (h3 :: Error :: TransportError (quiche :: Error :: InvalidStreamState (stream) ,)) => { return self . finish_stream (qconn , stream , None , None) ; } , Err (_) => { return self . finish_stream (qconn , stream_id , None , None) ; } , } let Some (recv) = ctx . recv . as_mut () else { debug_assert ! (ctx . queued_frame . is_none () , "We MUST NOT have a queued frame if we are already waiting on 
                    more data from the channel") ; return Ok (()) ; } ; match recv . try_recv () { Ok (frame) => ctx . queued_frame = Some (frame) , Err (TryRecvError :: Disconnected) => { if ! ctx . fin_or_reset_sent && ctx . associated_dgram_flow_id . is_none () { let err = h3 :: WireErrorCode :: RequestCancelled as u64 ; let _ = qconn . stream_shutdown (stream_id , quiche :: Shutdown :: Write , err ,) ; ctx . handle_sent_reset (err) ; if ctx . both_directions_done () { return self . finish_stream (qconn , stream_id , None , None) ; } } break ; } , Err (TryRecvError :: Empty) => { self . waiting_streams . push (ctx . wait_for_recv (stream_id)) ; break ; } , } } Ok (()) } # [doc = " Tests `qconn` for either a local or peer error and increments"] # [doc = " the associated HTTP/3 or QUIC error counter."] fn record_quiche_error (qconn : & mut QuicheConnection , metrics : & impl Metrics) { if let Some (err) = qconn . local_error () { if err . is_app { metrics . local_h3_conn_close_error_count (err . error_code . into ()) } else { metrics . local_quic_conn_close_error_count (err . error_code . into ()) } . inc () ; } else if let Some (err) = qconn . peer_error () { if err . is_app { metrics . peer_h3_conn_close_error_count (err . error_code . into ()) } else { metrics . peer_quic_conn_close_error_count (err . error_code . into ()) } . inc () ; } } }
};
}
