// Generated macro for parse_weekday (function)
macro_rules! Depcrate_parsing_componentparse_weekday {
() => {
// Module: crate::parsing::component
// Provides: {"parse_weekday"}
// Dependencies: {}
# [doc = " Parse the \"weekday\" component of a `Date`."] pub (crate) fn parse_weekday (input : & [u8] , modifiers : modifier :: Weekday ,) -> Option < ParsedItem < '_ , Weekday > > { first_match (match (modifiers . repr , modifiers . one_indexed) { (modifier :: WeekdayRepr :: Short , _) => [(b"Mon" . as_slice () , Weekday :: Monday) , (b"Tue" . as_slice () , Weekday :: Tuesday) , (b"Wed" . as_slice () , Weekday :: Wednesday) , (b"Thu" . as_slice () , Weekday :: Thursday) , (b"Fri" . as_slice () , Weekday :: Friday) , (b"Sat" . as_slice () , Weekday :: Saturday) , (b"Sun" . as_slice () , Weekday :: Sunday) ,] , (modifier :: WeekdayRepr :: Long , _) => [(b"Monday" . as_slice () , Weekday :: Monday) , (b"Tuesday" . as_slice () , Weekday :: Tuesday) , (b"Wednesday" . as_slice () , Weekday :: Wednesday) , (b"Thursday" . as_slice () , Weekday :: Thursday) , (b"Friday" . as_slice () , Weekday :: Friday) , (b"Saturday" . as_slice () , Weekday :: Saturday) , (b"Sunday" . as_slice () , Weekday :: Sunday) ,] , (modifier :: WeekdayRepr :: Sunday , false) => [(b"1" . as_slice () , Weekday :: Monday) , (b"2" . as_slice () , Weekday :: Tuesday) , (b"3" . as_slice () , Weekday :: Wednesday) , (b"4" . as_slice () , Weekday :: Thursday) , (b"5" . as_slice () , Weekday :: Friday) , (b"6" . as_slice () , Weekday :: Saturday) , (b"0" . as_slice () , Weekday :: Sunday) ,] , (modifier :: WeekdayRepr :: Sunday , true) => [(b"2" . as_slice () , Weekday :: Monday) , (b"3" . as_slice () , Weekday :: Tuesday) , (b"4" . as_slice () , Weekday :: Wednesday) , (b"5" . as_slice () , Weekday :: Thursday) , (b"6" . as_slice () , Weekday :: Friday) , (b"7" . as_slice () , Weekday :: Saturday) , (b"1" . as_slice () , Weekday :: Sunday) ,] , (modifier :: WeekdayRepr :: Monday , false) => [(b"0" . as_slice () , Weekday :: Monday) , (b"1" . as_slice () , Weekday :: Tuesday) , (b"2" . as_slice () , Weekday :: Wednesday) , (b"3" . as_slice () , Weekday :: Thursday) , (b"4" . as_slice () , Weekday :: Friday) , (b"5" . as_slice () , Weekday :: Saturday) , (b"6" . as_slice () , Weekday :: Sunday) ,] , (modifier :: WeekdayRepr :: Monday , true) => [(b"1" . as_slice () , Weekday :: Monday) , (b"2" . as_slice () , Weekday :: Tuesday) , (b"3" . as_slice () , Weekday :: Wednesday) , (b"4" . as_slice () , Weekday :: Thursday) , (b"5" . as_slice () , Weekday :: Friday) , (b"6" . as_slice () , Weekday :: Saturday) , (b"7" . as_slice () , Weekday :: Sunday) ,] , } , modifiers . case_sensitive ,) (input) }
};
}
