// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_tinystr_decls_module_not_found_macros,
    wrapped_tinystr_decls_module_not_found_ascii,
    wrapped_tinystr_decls_module_not_found_asciibyte,
    wrapped_tinystr_decls_module_not_found_error,
    wrapped_tinystr_decls_module_not_found_int_ops,
    wrapped_tinystr_decls_module_not_found_unvalidated,
    wrapped_tinystr_decls_module_not_found_serde,
    wrapped_tinystr_decls_module_not_found_databake,
    wrapped_tinystr_decls_module_not_found_ule,
    wrapped_tinystr_decls_TinyStr4,
    wrapped_tinystr_decls_TinyStr8,
    wrapped_tinystr_decls_TinyStr16,
    wrapped_tinystr_decls_test_size
);
