// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_crypto_bigint_decls_module_not_found_macros,
    wrapped_crypto_bigint_decls_module_not_found_modular,
    wrapped_crypto_bigint_decls_module_not_found_array,
    wrapped_crypto_bigint_decls_module_not_found_checked,
    wrapped_crypto_bigint_decls_module_not_found_const_choice,
    wrapped_crypto_bigint_decls_module_not_found_int,
    wrapped_crypto_bigint_decls_module_not_found_jacobi,
    wrapped_crypto_bigint_decls_module_not_found_limb,
    wrapped_crypto_bigint_decls_module_not_found_non_zero,
    wrapped_crypto_bigint_decls_module_not_found_odd,
    wrapped_crypto_bigint_decls_module_not_found_primitives,
    wrapped_crypto_bigint_decls_module_not_found_traits,
    wrapped_crypto_bigint_decls_module_not_found_uint,
    wrapped_crypto_bigint_decls_module_not_found_wrapping,
    wrapped_crypto_bigint_decls_module_not_found_prelude
);
