// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_rustc_query_system_decls_module_not_found_cache,
    wrapped_rustc_query_system_decls_module_not_found_dep_graph,
    wrapped_rustc_query_system_decls_module_not_found_error,
    wrapped_rustc_query_system_decls_module_not_found_ich,
    wrapped_rustc_query_system_decls_module_not_found_query,
    wrapped_rustc_query_system_decls_module_not_found_values,
    wrapped_rustc_query_system_decls_fluent_messages
);
