// Generated macro for event (macro)
macro_rules! Depcrate_enabledevent {
() => {
// Module: crate::enabled
// Provides: {"event"}
// Dependencies: {}
# [doc = " Create an event with the given level."] # [macro_export] macro_rules ! event { (target : $ target : expr , $ lvl : expr , { $ ($ fields : tt) * }) => ({ static META : $ crate :: Metadata <'static > = { $ crate :: metadata ! { name : concat ! ("event " , file ! () , ":" , line ! ()) , target : $ target , level : $ lvl , fields : $ crate :: fieldset ! ($ ($ fields) *) , callsite : &$ crate :: MetaOnlyCallsite (& META) , kind : $ crate :: metadata :: Kind :: EVENT , } } ; $ crate :: Event :: dispatch (& META , &$ crate :: valueset ! (META . fields () , $ ($ fields) *)) ; }) ; (target : $ target : expr , $ lvl : expr , { $ ($ fields : tt) * } , $ ($ arg : tt) +) => ($ crate :: event ! (target : $ target , $ lvl , { message = format_args ! ($ ($ arg) +) , $ ($ fields) * })) ; (target : $ target : expr , $ lvl : expr , $ ($ k : ident) .+ = $ ($ fields : tt) *) => ($ crate :: event ! (target : $ target , $ lvl , { $ ($ k) .+ = $ ($ fields) * })) ; (target : $ target : expr , $ lvl : expr , $ ($ arg : tt) +) => ($ crate :: event ! (target : $ target , $ lvl , { $ ($ arg) + })) ; ($ lvl : expr , { $ ($ fields : tt) * } , $ ($ arg : tt) +) => ($ crate :: event ! (target : module_path ! () , $ lvl , { message = format_args ! ($ ($ arg) +) , $ ($ fields) * })) ; ($ lvl : expr , $ ($ k : ident) .+ = $ ($ field : tt) *) => ($ crate :: event ! (target : module_path ! () , $ lvl , { $ ($ k) .+ = $ ($ field) * })) ; ($ lvl : expr , $ ($ k : ident) .+, $ ($ field : tt) *) => ($ crate :: event ! (target : module_path ! () , $ lvl , { $ ($ k) .+, $ ($ field) * })) ; ($ lvl : expr , ?$ ($ k : ident) .+, $ ($ field : tt) *) => ($ crate :: event ! (target : module_path ! () , $ lvl , { ?$ ($ k) .+, $ ($ field) * })) ; ($ lvl : expr , %$ ($ k : ident) .+, $ ($ field : tt) *) => ($ crate :: event ! (target : module_path ! () , $ lvl , { %$ ($ k) .+, $ ($ field) * })) ; ($ lvl : expr , ?$ ($ k : ident) .+) => ($ crate :: event ! ($ lvl , ?$ ($ k) .+,)) ; ($ lvl : expr , %$ ($ k : ident) .+) => ($ crate :: event ! ($ lvl , %$ ($ k) .+,)) ; ($ lvl : expr , $ ($ k : ident) .+) => ($ crate :: event ! ($ lvl , $ ($ k) .+,)) ; ($ lvl : expr , $ ($ arg : tt) +) => ($ crate :: event ! (target : module_path ! () , $ lvl , { $ ($ arg) + })) ; }
};
}
