// Generated macro for parse_args (function)
macro_rules! Depcrate_formatparse_args {
() => {
// Module: crate::format
// Provides: {"parse_args"}
// Dependencies: {}
# [doc = " Parses the arguments from the given list of tokens, returning the diagnostic"] # [doc = " if there's a parse error so we can continue parsing other format!"] # [doc = " expressions."] # [doc = ""] # [doc = " If parsing succeeds, the return value is:"] # [doc = ""] # [doc = " ```text"] # [doc = " Ok((fmtstr, parsed arguments))"] # [doc = " ```"] fn parse_args < 'a > (ecx : & ExtCtxt < 'a > , sp : Span , tts : TokenStream) -> PResult < 'a , MacroInput > { let mut args = FormatArguments :: new () ; let mut p = ecx . new_parser_from_tts (tts) ; if p . token == token :: Eof { return Err (ecx . dcx () . create_err (errors :: FormatRequiresString { span : sp })) ; } let first_token = & p . token ; let fmtstr = if let token :: Literal (lit) = first_token . kind && matches ! (lit . kind , token :: Str | token :: StrRaw (_)) { p . parse_literal_maybe_minus () ? } else { p . parse_expr () ? } ; let is_direct_literal = matches ! (fmtstr . kind , ExprKind :: Lit (_)) ; let mut first = true ; while p . token != token :: Eof { if ! p . eat (exp ! (Comma)) { if first { p . clear_expected_token_types () ; } match p . expect (exp ! (Comma)) { Err (err) => { if token :: TokenKind :: Comma . similar_tokens () . contains (& p . token . kind) { err . emit () ; p . bump () ; } else { return Err (err) ; } } Ok (Recovered :: Yes (_)) => () , Ok (Recovered :: No) => unreachable ! () , } } first = false ; if p . token == token :: Eof { break ; } match p . token . ident () { Some ((ident , _)) if p . look_ahead (1 , | t | * t == token :: Eq) => { p . bump () ; p . expect (exp ! (Eq)) ? ; let expr = p . parse_expr () ? ; if let Some ((_ , prev)) = args . by_name (ident . name) { ecx . dcx () . emit_err (errors :: FormatDuplicateArg { span : ident . span , prev : prev . kind . ident () . unwrap () . span , duplicate : ident . span , ident , }) ; continue ; } args . add (FormatArgument { kind : FormatArgumentKind :: Named (ident) , expr }) ; } _ => { let expr = p . parse_expr () ? ; if ! args . named_args () . is_empty () { return Err (ecx . dcx () . create_err (errors :: PositionalAfterNamed { span : expr . span , args : args . named_args () . iter () . filter_map (| a | a . kind . ident () . map (| ident | (a , ident))) . map (| (arg , n) | n . span . to (arg . expr . span)) . collect () , })) ; } args . add (FormatArgument { kind : FormatArgumentKind :: Normal , expr }) ; } } } Ok (MacroInput { fmtstr , args , is_direct_literal }) }
};
}
