// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
impl<'a> AsSerde<'a> for FieldSet {
    type Serializable = SerializeFieldSet<'a>;
    fn as_serde(&'a self) -> Self::Serializable {
        SerializeFieldSet(self)
    }
}
