// Generated macro for Allocator (trait)
macro_rules! Depcrate_base_allocatorAllocator {
() => {
// Module: crate::base::allocator
// Provides: {"Allocator"}
// Dependencies: {}
# [doc = " A matrix allocator of a memory buffer that may contain `R::to_usize() * C::to_usize()`"] # [doc = " elements of type `T`."] # [doc = ""] # [doc = " An allocator is said to be:"] # [doc = "   − static:  if `R` and `C` both implement `DimName`."] # [doc = "   − dynamic: if either one (or both) of `R` or `C` is equal to `Dyn`."] # [doc = ""] # [doc = " Every allocator must be both static and dynamic. Though not all implementations may share the"] # [doc = " same `Buffer` type."] pub trait Allocator < R : Dim , C : Dim = U1 > : Any + Sized { # [doc = " The type of buffer this allocator can instantiate."] type Buffer < T : Scalar > : StorageMut < T , R , C > + IsContiguous + Clone + Debug ; # [doc = " The type of buffer with uninitialized components this allocator can instantiate."] type BufferUninit < T : Scalar > : RawStorageMut < MaybeUninit < T > , R , C > + IsContiguous ; # [doc = " Allocates a buffer with the given number of rows and columns without initializing its content."] fn allocate_uninit < T : Scalar > (nrows : R , ncols : C) -> Self :: BufferUninit < T > ; # [doc = " Assumes a data buffer to be initialized."] # [doc = ""] # [doc = " # Safety"] # [doc = " The user must make sure that every single entry of the buffer has been initialized,"] # [doc = " or Undefined Behavior will immediately occur.    "] unsafe fn assume_init < T : Scalar > (uninit : Self :: BufferUninit < T >) -> Self :: Buffer < T > ; # [doc = " Allocates a buffer initialized with the content of the given iterator."] fn allocate_from_iterator < T : Scalar , I : IntoIterator < Item = T > > (nrows : R , ncols : C , iter : I ,) -> Self :: Buffer < T > ; # [inline] # [doc = " Allocates a buffer initialized with the content of the given row-major order iterator."] fn allocate_from_row_iterator < T : Scalar , I : IntoIterator < Item = T > > (nrows : R , ncols : C , iter : I ,) -> Self :: Buffer < T > { let mut res = Self :: allocate_uninit (nrows , ncols) ; let mut count = 0 ; unsafe { let res_ptr = res . as_mut_slice_unchecked () ; for (k , e) in iter . into_iter () . take (ncols . value () * nrows . value ()) . enumerate () { let i = k / ncols . value () ; let j = k % ncols . value () ; * res_ptr . get_unchecked_mut (i + j * nrows . value ()) = MaybeUninit :: new (e) ; count += 1 ; } assert ! (count == nrows . value () * ncols . value () , "Matrix init. from row iterator: iterator not long enough.") ; < Self as Allocator < R , C > > :: assume_init (res) } } }
};
}
