// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_rustc_metadata_decls_module_not_found_dependency_format,
    wrapped_rustc_metadata_decls_module_not_found_foreign_modules,
    wrapped_rustc_metadata_decls_module_not_found_native_libs,
    wrapped_rustc_metadata_decls_module_not_found_rmeta,
    wrapped_rustc_metadata_decls_module_not_found_creader,
    wrapped_rustc_metadata_decls_module_not_found_errors,
    wrapped_rustc_metadata_decls_module_not_found_fs,
    wrapped_rustc_metadata_decls_module_not_found_locator,
    wrapped_rustc_metadata_decls_fluent_messages
);
