// feature_collector.rs - Collect all features from parsed code
// Generated by step4_bootstrap - Feature Collection

use split_decls_genesis::{
    find_rust_files_in_dependency_fast, extract_all_symbols_from_file_fast,
    get_rustc_dependencies
};
use std::collections::HashSet;
use serde_json;

fn main() {
    println!("🔍 Collecting all features from Rust source...");
    
    let rustc_deps = get_rustc_dependencies().unwrap_or_default();
    let mut features = HashSet::new();
    let mut cfg_features = HashSet::new();
    let mut stable_features = HashSet::new();
    
    for dep in &rustc_deps {
        let rust_files = find_rust_files_in_dependency_fast(&dep.path);
        println!("📦 {}: {} files", dep.name, rust_files.len());
        
        for file in rust_files {
            if let Ok(content) = std::fs::read_to_string(&file) {
                // Extract feature gates
                for line in content.lines() {
                    if line.contains("#[stable(feature") {
                        if let Some(start) = line.find("feature = \"") {
                            if let Some(end) = line[start + 11..].find("\"") {
                                let feature = &line[start + 11..start + 11 + end];
                                stable_features.insert(feature.to_string());
                            }
                        }
                    }
                    
                    if line.contains("#[unstable(feature") {
                        if let Some(start) = line.find("feature = \"") {
                            if let Some(end) = line[start + 11..].find("\"") {
                                let feature = &line[start + 11..start + 11 + end];
                                features.insert(feature.to_string());
                            }
                        }
                    }
                    
                    if line.contains("#[cfg(feature") {
                        if let Some(start) = line.find("feature = \"") {
                            if let Some(end) = line[start + 11..].find("\"") {
                                let feature = &line[start + 11..start + 11 + end];
                                cfg_features.insert(feature.to_string());
                            }
                        }
                    }
                }
            }
        }
    }
    
    println!("✅ Found {} stable features", stable_features.len());
    println!("✅ Found {} unstable features", features.len());
    println!("✅ Found {} cfg features", cfg_features.len());
    
    // Export all features
    let all_features = serde_json::json!({
        "stable_features": stable_features.into_iter().collect::<Vec<_>>(),
        "unstable_features": features.into_iter().collect::<Vec<_>>(),
        "cfg_features": cfg_features.into_iter().collect::<Vec<_>>()
    });
    
    let features_json = serde_json::to_string_pretty(&all_features).expect("Failed to serialize features");
    std::fs::write("features.json", features_json).expect("Failed to write features.json");
    
    println!("📄 Exported features.json");
    
    // Generate Cargo.toml features section
    let mut cargo_features = Vec::new();
    for feature in all_features["stable_features"].as_array().unwrap() {
        cargo_features.push(feature.as_str().unwrap().to_string());
    }
    for feature in all_features["unstable_features"].as_array().unwrap() {
        cargo_features.push(feature.as_str().unwrap().to_string());
    }
    
    println!("\n🔧 Add to Cargo.toml:");
    println!("[features]");
    println!("default = [{}]", 
        cargo_features.iter()
            .take(20)
            .map(|f| format!("\"{}\"", f))
            .collect::<Vec<_>>()
            .join(", ")
    );
    
    println!("\n📋 Key features found:");
    for feature in cargo_features.iter().take(10) {
        println!("  - {}", feature);
    }
}
