// test_path_resolution.rs - Debug qualified path resolution
// Generated by step4_bootstrap - Debug Path Resolution

use split_decls_genesis::{extract_all_symbols_from_file_fast, resolve_qualified_dependency};
use std::collections::HashMap;

fn main() {
    println!("🔍 Testing qualified path resolution for env::var...");
    
    let env_file = "../rust/library/std/src/env.rs";
    
    match extract_all_symbols_from_file_fast(env_file, "std") {
        Ok(symbols) => {
            let mut symbol_map = HashMap::new();
            for symbol in symbols {
                symbol_map.insert(symbol.name.clone(), symbol);
            }
            
            println!("✅ Loaded {} symbols from env.rs", symbol_map.len());
            
            // Test resolution of env::var
            println!("\n🔍 Testing resolution of 'env::var':");
            match resolve_qualified_dependency("env::var", &symbol_map) {
                Some(location) => {
                    println!("  ✅ Resolved: {}", location);
                },
                None => {
                    println!("  ❌ Not resolved");
                    
                    // Debug: show what we're looking for
                    println!("\n🔍 Debug info:");
                    println!("  Looking for function 'var' in module 'env'");
                    
                    if let Some(var_symbol) = symbol_map.get("var") {
                        println!("  Found 'var' symbol:");
                        println!("    File: {}", var_symbol.source_file);
                        println!("    Ends with '/env.rs': {}", var_symbol.source_file.ends_with("/env.rs"));
                        println!("    Contains '/env/': {}", var_symbol.source_file.contains("/env/"));
                    } else {
                        println!("  No 'var' symbol found");
                    }
                }
            }
            
            // Test other qualified paths
            println!("\n🔍 Testing other qualified paths:");
            let test_paths = vec!["std::env::var", "env::vars", "env::var_os"];
            for path in test_paths {
                match resolve_qualified_dependency(path, &symbol_map) {
                    Some(location) => println!("  ✅ {}: {}", path, location),
                    None => println!("  ❌ {}: not resolved", path),
                }
            }
        },
        Err(e) => {
            println!("❌ Failed to parse env.rs: {}", e);
        }
    }
}
