// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_globwalk_decls_GlobError,
    wrapped_globwalk_decls_WalkError,
    wrapped_globwalk_decls_DirEntry,
    wrapped_globwalk_decls_impl_for_From_std_io_Error_,
    wrapped_globwalk_decls_impl_for_From_GlobError_,
    wrapped_globwalk_decls_impl_for_std_fmt_Display,
    wrapped_globwalk_decls_impl_for_std_error_Error,
    wrapped_globwalk_decls_bitflags,
    wrapped_globwalk_decls_GlobWalkerBuilder,
    wrapped_globwalk_decls_impl_for_GlobWalkerBuilder,
    wrapped_globwalk_decls_GlobWalker,
    wrapped_globwalk_decls_impl_for_Iterator,
    wrapped_globwalk_decls_glob_builder,
    wrapped_globwalk_decls_glob,
    wrapped_globwalk_decls_module_not_found_tests
);
