// Generated macro for goto_implementation (function)
macro_rules! Depcrate_goto_implementationgoto_implementation {
() => {
// Module: crate::goto_implementation
// Provides: {"goto_implementation"}
// Dependencies: {}
pub (crate) fn goto_implementation (db : & RootDatabase , config : & GotoImplementationConfig , FilePosition { file_id , offset } : FilePosition ,) -> Option < RangeInfo < Vec < NavigationTarget > > > { let sema = Semantics :: new (db) ; let source_file = sema . parse_guess_edition (file_id) ; let syntax = source_file . syntax () . clone () ; let original_token = pick_best_token (syntax . token_at_offset (offset) , | kind | match kind { IDENT | T ! [self] | INT_NUMBER => 1 , _ => 0 , }) ? ; let range = original_token . text_range () ; let navs = sema . descend_into_macros_exact (original_token) . iter () . filter_map (| token | { token . parent () . and_then (ast :: NameLike :: cast) . and_then (| node | match & node { ast :: NameLike :: Name (name) => { NameClass :: classify (& sema , name) . and_then (| class | match class { NameClass :: Definition (it) | NameClass :: ConstReference (it) => Some (it) , NameClass :: PatFieldShorthand { .. } => None , }) } ast :: NameLike :: NameRef (name_ref) => NameRefClass :: classify (& sema , name_ref) . and_then (| class | match class { NameRefClass :: Definition (def , _) => Some (def) , NameRefClass :: FieldShorthand { .. } | NameRefClass :: ExternCrateShorthand { .. } => None , }) , ast :: NameLike :: Lifetime (_) => None , }) . and_then (| def | { let navs = match def { Definition :: Trait (trait_) => impls_for_trait (& sema , trait_) , Definition :: Adt (adt) => { let mut impls = Impl :: all_for_type (db , adt . ty (sema . db)) ; if config . filter_adjacent_derive_implementations { impls . retain (| impl_ | { sema . impl_generated_from_derive (* impl_) != Some (adt) }) ; } impls . into_iter () . filter_map (| imp | imp . try_to_nav (& sema)) . flatten () . collect () } Definition :: TypeAlias (alias) => impls_for_ty (& sema , alias . ty (sema . db)) , Definition :: BuiltinType (builtin) => { impls_for_ty (& sema , builtin . ty (sema . db)) } Definition :: Function (f) => { let assoc = f . as_assoc_item (sema . db) ? ; let name = assoc . name (sema . db) ? ; let trait_ = assoc . container_or_implemented_trait (sema . db) ? ; impls_for_trait_item (& sema , trait_ , name) } Definition :: Const (c) => { let assoc = c . as_assoc_item (sema . db) ? ; let name = assoc . name (sema . db) ? ; let trait_ = assoc . container_or_implemented_trait (sema . db) ? ; impls_for_trait_item (& sema , trait_ , name) } _ => return None , } ; Some (navs) }) }) . flatten () . collect () ; Some (RangeInfo { range , info : navs }) }
};
}
