// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
digest :: buffer_fixed ! (# [doc = " SHA-512/256 hasher."] pub struct Sha512_256 (CtOutWrapper < block_api :: Sha512VarCore , U32 >) ; oid : "2.16.840.1.101.3.4.2.6" ; impl : FixedHashTraits ;);
