// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[cfg(feature = "std-future")]
impl<'a, T> InstrumentedProjRef<'a, T> {
    #[doc = " Get a reference to the [`Span`] a pinned reference to the wrapped type."]
    fn span_and_inner_pin_ref(self) -> (&'a Span, Pin<&'a T>) {
        let inner = unsafe { self.inner.map_unchecked(|v| &**v) };
        (self.span, inner)
    }
}
