mkuse!{use rustc_hir :: LangItem ;}
mkuse!{use rustc_hir :: def_id :: DefId ;}
mkuse!{use rustc_span :: Span ;}
mkuse!{use rustc_target :: spec :: PanicStrategy ;}
mkuse!{use crate :: ty :: { self , TyCtxt } ;}
mkitem!{mkimpl!{impl < 'tcx > TyCtxt < 'tcx > { # [doc = " Returns the `DefId` for a given `LangItem`."] # [doc = " If not found, fatally aborts compilation."] pub fn require_lang_item (self , lang_item : LangItem , span : Span) -> DefId { self . lang_items () . get (lang_item) . unwrap_or_else (| | { self . dcx () . emit_fatal (crate :: error :: RequiresLangItem { span , name : lang_item . name () }) ; }) } pub fn is_lang_item (self , def_id : DefId , lang_item : LangItem) -> bool { self . lang_items () . get (lang_item) == Some (def_id) } pub fn as_lang_item (self , def_id : DefId) -> Option < LangItem > { self . lang_items () . from_def_id (def_id) } # [doc = " Given a [`DefId`] of one of the [`Fn`], [`FnMut`] or [`FnOnce`] traits,"] # [doc = " returns a corresponding [`ty::ClosureKind`]."] # [doc = " For any other [`DefId`] return `None`."] pub fn fn_trait_kind_from_def_id (self , id : DefId) -> Option < ty :: ClosureKind > { match self . as_lang_item (id) ? { LangItem :: Fn => Some (ty :: ClosureKind :: Fn) , LangItem :: FnMut => Some (ty :: ClosureKind :: FnMut) , LangItem :: FnOnce => Some (ty :: ClosureKind :: FnOnce) , _ => None , } } # [doc = " Given a [`DefId`] of one of the `AsyncFn`, `AsyncFnMut` or `AsyncFnOnce` traits,"] # [doc = " returns a corresponding [`ty::ClosureKind`]."] # [doc = " For any other [`DefId`] return `None`."] pub fn async_fn_trait_kind_from_def_id (self , id : DefId) -> Option < ty :: ClosureKind > { match self . as_lang_item (id) ? { LangItem :: AsyncFn => Some (ty :: ClosureKind :: Fn) , LangItem :: AsyncFnMut => Some (ty :: ClosureKind :: FnMut) , LangItem :: AsyncFnOnce => Some (ty :: ClosureKind :: FnOnce) , _ => None , } } # [doc = " Given a [`ty::ClosureKind`], get the [`DefId`] of its corresponding `Fn`-family"] # [doc = " trait, if it is defined."] pub fn fn_trait_kind_to_def_id (self , kind : ty :: ClosureKind) -> Option < DefId > { let items = self . lang_items () ; match kind { ty :: ClosureKind :: Fn => items . fn_trait () , ty :: ClosureKind :: FnMut => items . fn_mut_trait () , ty :: ClosureKind :: FnOnce => items . fn_once_trait () , } } # [doc = " Given a [`ty::ClosureKind`], get the [`DefId`] of its corresponding `Fn`-family"] # [doc = " trait, if it is defined."] pub fn async_fn_trait_kind_to_def_id (self , kind : ty :: ClosureKind) -> Option < DefId > { let items = self . lang_items () ; match kind { ty :: ClosureKind :: Fn => items . async_fn_trait () , ty :: ClosureKind :: FnMut => items . async_fn_mut_trait () , ty :: ClosureKind :: FnOnce => items . async_fn_once_trait () , } } # [doc = " Returns `true` if `id` is a `DefId` of [`Fn`], [`FnMut`] or [`FnOnce`] traits."] pub fn is_fn_trait (self , id : DefId) -> bool { self . fn_trait_kind_from_def_id (id) . is_some () } }}}

macro_rules! required_introspect {
    () => {
        emit_message!("📊 INTROSPECT: Function required in module {}", module_path!());
    };
}

mkfn!{
    required_introspect!();
    # [doc = " Returns `true` if the specified `lang_item` must be present for this"] # [doc = " compilation."] # [doc = ""] # [doc = " Not all lang items are always required for each compilation, particularly in"] # [doc = " the case of panic=abort. In these situations some lang items are injected by"] # [doc = " crates and don't actually need to be defined in libstd."] pub fn required (tcx : TyCtxt < '_ > , lang_item : LangItem) -> bool { match tcx . sess . panic_strategy () { PanicStrategy :: Abort => { lang_item != LangItem :: EhPersonality && lang_item != LangItem :: EhCatchTypeinfo } PanicStrategy :: Unwind => true , } }
}