// Generated macro for impl_1587 (impl)
macro_rules! Depcrate_process_waitimpl_1587 {
() => {
// Module: crate::process::wait
// Provides: {"impl_1587"}
// Dependencies: {}
impl WaitStatus { # [doc = " Creates a `WaitStatus` out of an integer."] # [inline] pub (crate) fn new (status : i32) -> Self { Self (status) } # [doc = " Converts a `WaitStatus` into its raw representation as an integer."] # [inline] pub const fn as_raw (self) -> i32 { self . 0 } # [doc = " Returns whether the process is currently stopped."] # [inline] # [doc (alias = "WIFSTOPPED")] pub fn stopped (self) -> bool { backend :: process :: wait :: WIFSTOPPED (self . 0) } # [doc = " Returns whether the process has exited normally."] # [inline] # [doc (alias = "WIFEXITED")] pub fn exited (self) -> bool { backend :: process :: wait :: WIFEXITED (self . 0) } # [doc = " Returns whether the process was terminated by a signal."] # [inline] # [doc (alias = "WIFSIGNALED")] pub fn signaled (self) -> bool { backend :: process :: wait :: WIFSIGNALED (self . 0) } # [doc = " Returns whether the process has continued from a job control stop."] # [inline] # [doc (alias = "WIFCONTINUED")] pub fn continued (self) -> bool { backend :: process :: wait :: WIFCONTINUED (self . 0) } # [doc = " Returns the number of the signal that stopped the process, if the"] # [doc = " process was stopped by a signal."] # [inline] # [doc (alias = "WSTOPSIG")] pub fn stopping_signal (self) -> Option < i32 > { if self . stopped () { Some (backend :: process :: wait :: WSTOPSIG (self . 0)) } else { None } } # [doc = " Returns the exit status number returned by the process, if it exited"] # [doc = " normally."] # [inline] # [doc (alias = "WEXITSTATUS")] pub fn exit_status (self) -> Option < i32 > { if self . exited () { Some (backend :: process :: wait :: WEXITSTATUS (self . 0)) } else { None } } # [doc = " Returns the number of the signal that terminated the process, if the"] # [doc = " process was terminated by a signal."] # [inline] # [doc (alias = "WTERMSIG")] pub fn terminating_signal (self) -> Option < i32 > { if self . signaled () { Some (backend :: process :: wait :: WTERMSIG (self . 0)) } else { None } } }
};
}
