// Generated macro for impl_751 (impl)
macro_rules! Depcrate_generatedimpl_751 {
() => {
// Module: crate::generated
// Provides: {"impl_751"}
// Dependencies: {}
impl NWTCPConnectionState { # [doc (alias = "NWTCPConnectionStateInvalid")] # [deprecated = "Use `nw_connection_state_t` in Network framework instead, see deprecation notice in <NetworkExtension/NWTCPConnection.h>"] pub const Invalid : Self = Self (0) ; # [doc (alias = "NWTCPConnectionStateConnecting")] # [deprecated = "Use `nw_connection_state_t` in Network framework instead, see deprecation notice in <NetworkExtension/NWTCPConnection.h>"] pub const Connecting : Self = Self (1) ; # [doc = " waiting for better condition(s) before trying again."] # [doc (alias = "NWTCPConnectionStateWaiting")] # [deprecated = "Use `nw_connection_state_t` in Network framework instead, see deprecation notice in <NetworkExtension/NWTCPConnection.h>"] pub const Waiting : Self = Self (2) ; # [doc = " to transfer data. If TLS is in use, the TLS handshake would have finished when the connection"] # [doc = " is in this state."] # [doc (alias = "NWTCPConnectionStateConnected")] # [deprecated = "Use `nw_connection_state_t` in Network framework instead, see deprecation notice in <NetworkExtension/NWTCPConnection.h>"] pub const Connected : Self = Self (3) ; # [doc = " possible to transfer data. The application should call cancellation method to clean up resources"] # [doc = " when the connection is in this state."] # [doc (alias = "NWTCPConnectionStateDisconnected")] # [deprecated = "Use `nw_connection_state_t` in Network framework instead, see deprecation notice in <NetworkExtension/NWTCPConnection.h>"] pub const Disconnected : Self = Self (4) ; # [doc = " the cancellation method."] # [doc (alias = "NWTCPConnectionStateCancelled")] # [deprecated = "Use `nw_connection_state_t` in Network framework instead, see deprecation notice in <NetworkExtension/NWTCPConnection.h>"] pub const Cancelled : Self = Self (5) ; }
};
}
