// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
bitflags::bitflags! { # [derive (Debug , Clone , Copy , PartialEq , Eq , Hash)] pub struct MacroRulesLocFlags : u8 { const ALLOW_INTERNAL_UNSAFE = 1 << 0 ; const LOCAL_INNER = 1 << 1 ; } }
