// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_futures_concurrency_decls_module_not_found_collections,
    wrapped_futures_concurrency_decls_module_not_found_utils,
    wrapped_futures_concurrency_decls_module_not_found_prelude,
    wrapped_futures_concurrency_decls_module_not_found_concurrent_stream,
    wrapped_futures_concurrency_decls_module_not_found_future,
    wrapped_futures_concurrency_decls_module_not_found_stream,
    wrapped_futures_concurrency_decls_module_not_found_array
);
