// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Checks that the `file` has the specified `contents`. If that is not the"]
#[doc = " case, updates the file and then fails the test."]
#[track_caller]
pub fn ensure_file_contents(file: &Path, contents: &str) {
    if let Err(()) = try_ensure_file_contents(file, contents) {
        panic!("Some files were not up-to-date");
    }
}
