// Generated macro for impl_48 (impl)
macro_rules! Depcrate_arcimpl_48 {
() => {
// Module: crate::arc
// Provides: {"impl_48"}
// Dependencies: {}
impl < T > Weak < T > { # [doc = " Returns a raw pointer to the object `T` pointed to by this `Weak<T>`."] # [doc = ""] # [doc = " The pointer is valid only if there are some strong references. The pointer may be dangling,"] # [doc = " unaligned or even [`null`] otherwise."] # [doc = ""] # [doc = " # Examples"] # [doc = ""] # [doc = " ```"] # [doc = " use portable_atomic_util::Arc;"] # [doc = " use std::ptr;"] # [doc = ""] # [doc = " let strong = Arc::new(\"hello\".to_owned());"] # [doc = " let weak = Arc::downgrade(&strong);"] # [doc = " // Both point to the same object"] # [doc = " assert!(ptr::eq(&*strong, weak.as_ptr()));"] # [doc = " // The strong here keeps it alive, so we can still access the object."] # [doc = " assert_eq!(\"hello\", unsafe { &*weak.as_ptr() });"] # [doc = ""] # [doc = " drop(strong);"] # [doc = " // But not any more. We can do weak.as_ptr(), but accessing the pointer would lead to"] # [doc = " // undefined behavior."] # [doc = " // assert_eq!(\"hello\", unsafe { &*weak.as_ptr() });"] # [doc = " ```"] # [doc = ""] # [doc = " [`null`]: core::ptr::null \"ptr::null\""] # [must_use] pub fn as_ptr (& self) -> * const T { let ptr : * mut ArcInner < T > = self . ptr . as_ptr () ; if is_dangling (ptr) { ptr as * const T } else { unsafe { let offset = data_offset_align (mem :: align_of :: < T > ()) ; strict :: byte_add (ptr , offset) as * const T } } } # [doc = " Consumes the `Weak<T>` and turns it into a raw pointer."] # [doc = ""] # [doc = " This converts the weak pointer into a raw pointer, while still preserving the ownership of"] # [doc = " one weak reference (the weak count is not modified by this operation). It can be turned"] # [doc = " back into the `Weak<T>` with [`from_raw`]."] # [doc = ""] # [doc = " The same restrictions of accessing the target of the pointer as with"] # [doc = " [`as_ptr`] apply."] # [doc = ""] # [doc = " # Examples"] # [doc = ""] # [doc = " ```"] # [doc = " use portable_atomic_util::{Arc, Weak};"] # [doc = ""] # [doc = " let strong = Arc::new(\"hello\".to_owned());"] # [doc = " let weak = Arc::downgrade(&strong);"] # [doc = " let raw = weak.into_raw();"] # [doc = ""] # [doc = " assert_eq!(1, Arc::weak_count(&strong));"] # [doc = " assert_eq!(\"hello\", unsafe { &*raw });"] # [doc = ""] # [doc = " drop(unsafe { Weak::from_raw(raw) });"] # [doc = " assert_eq!(0, Arc::weak_count(&strong));"] # [doc = " ```"] # [doc = ""] # [doc = " [`from_raw`]: Weak::from_raw"] # [doc = " [`as_ptr`]: Weak::as_ptr"] # [must_use = "losing the pointer will leak memory"] pub fn into_raw (self) -> * const T { ManuallyDrop :: new (self) . as_ptr () } }
};
}
