// Generated macro for copy (function)
macro_rules! Depcrate_filecopy {
() => {
// Module: crate::file
// Provides: {"copy"}
// Dependencies: {}
# [doc = " Copies the contents of one file to another. This function will also copy the permission"] # [doc = " bits of the original file to the destination file."] # [doc = ""] # [doc = " # Errors"] # [doc = ""] # [doc = " This function will return an error in the following situations, but is not limited to just"] # [doc = " these cases:"] # [doc = ""] # [doc = " * This `from` path is not a file."] # [doc = " * This `from` file does not exist."] # [doc = " * The current process does not have the permission to access `from` or write `to`."] # [doc = ""] # [doc = " # Example"] # [doc = ""] # [doc = " ```rust,ignore"] # [doc = " extern crate fs_extra;"] # [doc = " use fs_extra::file::copy;"] # [doc = ""] # [doc = " let options = CopyOptions::new(); //Initialize default values for CopyOptions"] # [doc = " copy(\"dir1/foo.txt\", \"dir2/bar.txt\", &options)?; // Copy dir1/foo.txt to dir2/bar.txt"] # [doc = ""] # [doc = " ```"] pub fn copy < P , Q > (from : P , to : Q , options : & CopyOptions) -> Result < u64 > where P : AsRef < Path > , Q : AsRef < Path > , { let from = from . as_ref () ; if ! from . exists () { if let Some (msg) = from . to_str () { let msg = format ! ("Path \"{}\" does not exist or you don't have access!" , msg) ; err ! (& msg , ErrorKind :: NotFound) ; } err ! ("Path does not exist or you don't have access!" , ErrorKind :: NotFound) ; } if ! from . is_file () { if let Some (msg) = from . to_str () { let msg = format ! ("Path \"{}\" is not a file!" , msg) ; err ! (& msg , ErrorKind :: InvalidFile) ; } err ! ("Path is not a file!" , ErrorKind :: InvalidFile) ; } if ! options . overwrite && to . as_ref () . exists () { if options . skip_exist { return Ok (0) ; } if let Some (msg) = to . as_ref () . to_str () { let msg = format ! ("Path \"{}\" exists" , msg) ; err ! (& msg , ErrorKind :: AlreadyExists) ; } } Ok (std :: fs :: copy (from , to) ?) }
};
}
