// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[proc_macro]
#[decl(fn, name = "compiler_type_check", vis = "pub", hash = "a74e17ed")]
pub fn compiler_type_check(input: TokenStream) -> TokenStream {
    macros::compiler_type_check::compiler_type_check_impl(input)
}
