// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[proc_macro]
#[decl(fn, name = "make_everything_a_macro", vis = "pub", hash = "69a030ad")]
pub fn make_everything_a_macro(input: TokenStream) -> TokenStream {
    macros::make_everything_a_macro::make_everything_a_macro_impl(input)
}
