// Generated macro for read_single_key_impl (function)
macro_rules! Depcrate_unix_termread_single_key_impl {
() => {
// Module: crate::unix_term
// Provides: {"read_single_key_impl"}
// Dependencies: {}
fn read_single_key_impl (fd : RawFd) -> Result < Key , io :: Error > { loop { match read_single_char (fd) ? { Some ('\x1b') => { break if let Some (c1) = read_single_char (fd) ? { if c1 == '[' { if let Some (c2) = read_single_char (fd) ? { match c2 { 'A' => Ok (Key :: ArrowUp) , 'B' => Ok (Key :: ArrowDown) , 'C' => Ok (Key :: ArrowRight) , 'D' => Ok (Key :: ArrowLeft) , 'H' => Ok (Key :: Home) , 'F' => Ok (Key :: End) , 'Z' => Ok (Key :: BackTab) , _ => { let c3 = read_single_char (fd) ? ; if let Some (c3) = c3 { if c3 == '~' { match c2 { '1' => Ok (Key :: Home) , '2' => Ok (Key :: Insert) , '3' => Ok (Key :: Del) , '4' => Ok (Key :: End) , '5' => Ok (Key :: PageUp) , '6' => Ok (Key :: PageDown) , '7' => Ok (Key :: Home) , '8' => Ok (Key :: End) , _ => Ok (Key :: UnknownEscSeq (vec ! [c1 , c2 , c3])) , } } else { Ok (Key :: UnknownEscSeq (vec ! [c1 , c2 , c3])) } } else { Ok (Key :: UnknownEscSeq (vec ! [c1 , c2])) } } } } else { Ok (Key :: UnknownEscSeq (vec ! [c1])) } } else { Ok (Key :: UnknownEscSeq (vec ! [c1])) } } else { Ok (Key :: Escape) } ; } Some (c) => { let byte = c as u8 ; let mut buf : [u8 ; 4] = [byte , 0 , 0 , 0] ; break if byte & 224u8 == 192u8 { read_bytes (fd , & mut buf [1 ..] , 1) ? ; Ok (key_from_utf8 (& buf [.. 2])) } else if byte & 240u8 == 224u8 { read_bytes (fd , & mut buf [1 ..] , 2) ? ; Ok (key_from_utf8 (& buf [.. 3])) } else if byte & 248u8 == 240u8 { read_bytes (fd , & mut buf [1 ..] , 3) ? ; Ok (key_from_utf8 (& buf [.. 4])) } else { Ok (match c { '\n' | '\r' => Key :: Enter , '\x7f' => Key :: Backspace , '\t' => Key :: Tab , '\x01' => Key :: Home , '\x05' => Key :: End , '\x08' => Key :: Backspace , _ => Key :: Char (c) , }) } ; } None => { match select_or_poll_term_fd (fd , - 1) { Ok (_) => continue , Err (_) => break Err (io :: Error :: last_os_error ()) , } } } } }
};
}
