// Auto-generated module tree for: rustc_codegen_gcc::volatile::main
// Dependencies resolved: 7

macro_rules! include_dep_0 { () => {
// SRC: ../rust/compiler/rustc_codegen_gcc/tests/run/volatile.rs
// SRC: compiler/rustc_codegen_gcc/tests/run/volatile.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_codegen_gcc/tests/run/volatile.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_codegen_gcc/tests/run/volatile.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_codegen_gcc/tests/run/volatile.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_codegen_gcc/tests/run/volatile.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_codegen_gcc/tests/run/volatile.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_codegen_gcc/tests/run/volatile.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_codegen_gcc/tests/run/volatile.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_codegen_gcc/tests/run/volatile.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: ../rust/compiler/rustc_codegen_gcc/tests/run/volatile.rs
// Compiler:
//
// Run-time:
//   status: 0

use std::mem::MaybeUninit;

#[allow(dead_code)]
#[derive(Debug)]
struct Struct {
    pointer: *const (),
    func: unsafe fn(*const ()),
}

fn func(_ptr: *const ()) {}

fn main() {
    let mut x = MaybeUninit::<&Struct>::uninit();
    x.write(&Struct { pointer: std::ptr::null(), func });
    let x = unsafe { x.assume_init() };
    let value = unsafe { (x as *const Struct).read_volatile() };
    println!("{:?}", value);
}
}}}

pub mod rustc_codegen_gcc {
    // rustc_codegen_gcc::volatile::main
    include_dep_0!();
}

pub mod std {
}

pub fn main() {
    rustc_codegen_gcc::volatile::main()
}
