// Auto-generated module tree for: rustc_codegen_gcc::abort1::main
// Dependencies resolved: 3

macro_rules! include_dep_0 { () => {
// SRC: ../rust/compiler/rustc_codegen_gcc/tests/run/abort1.rs
// SRC: compiler/rustc_codegen_gcc/tests/run/abort1.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_codegen_gcc/tests/run/abort1.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_codegen_gcc/tests/run/abort1.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_codegen_gcc/tests/run/abort1.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_codegen_gcc/tests/run/abort1.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_codegen_gcc/tests/run/abort1.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_codegen_gcc/tests/run/abort1.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_codegen_gcc/tests/run/abort1.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_codegen_gcc/tests/run/abort1.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: ../rust/compiler/rustc_codegen_gcc/tests/run/abort1.rs
// Compiler:
//
// Run-time:
//   status: signal

#![feature(no_core)]
#![no_std]
#![no_core]
#![no_main]

extern crate mini_core;
use mini_core::*;

fn test_fail() -> ! {
    unsafe { intrinsics::abort() };
}

#[no_mangle]
extern "C" fn main(argc: i32, _argv: *const *const u8) -> i32 {
    test_fail();
}
}}}

pub mod rustc_codegen_gcc {
    // rustc_codegen_gcc::abort1::main
    include_dep_0!();
}

pub fn main() {
    rustc_codegen_gcc::abort1::main()
}
