// Auto-generated module tree for: rustc_codegen_cranelift::issue-59326::main
// Dependencies resolved: 3

macro_rules! include_dep_0 { () => {
// SRC: ../rust/compiler/rustc_codegen_cranelift/example/issue-59326.rs
// SRC: compiler/rustc_codegen_cranelift/example/issue-59326.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_codegen_cranelift/example/issue-59326.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_codegen_cranelift/example/issue-59326.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_codegen_cranelift/example/issue-59326.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_codegen_cranelift/example/issue-59326.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_codegen_cranelift/example/issue-59326.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_codegen_cranelift/example/issue-59326.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_codegen_cranelift/example/issue-59326.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_codegen_cranelift/example/issue-59326.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: ../rust/compiler/rustc_codegen_cranelift/example/issue-59326.rs
// Based on https://github.com/rust-lang/rust/blob/689511047a75a30825e367d4fd45c74604d0b15e/tests/ui/issues/issue-59326.rs#L1
// check-pass
trait Service {
    type S;
}

trait Framing {
    type F;
}

impl Framing for () {
    type F = ();
}

trait HttpService<F: Framing>: Service<S = F::F> {}

type BoxService = Box<dyn HttpService<(), S = ()>>;

fn build_server<F: FnOnce() -> BoxService>(_: F) {}

fn make_server<F: Framing>() -> Box<dyn HttpService<F, S = F::F>> {
    unimplemented!()
}

fn main() {
    build_server(|| make_server())
}
}}}

pub mod rustc_codegen_cranelift {
    // rustc_codegen_cranelift::issue-59326::main
    include_dep_0!();
}

pub fn main() {
    rustc_codegen_cranelift::issue-59326::main()
}
