// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " A service builder, providing control over what commands the service supports before the service begins to run."]
pub struct Service<'a> {
    accept: u32,
    fallback: Option<Box<dyn FnOnce(&Service) + 'a>>,
    handle: RwLock<SERVICE_STATUS_HANDLE>,
    callback: RwLock<Option<Box<dyn FnMut(&Service, Command) + Send + Sync + 'a>>>,
    status: RwLock<SERVICE_STATUS>,
}
