// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " A command not specifically covered by the `Command` enum."]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct ExtendedCommand {
    #[doc = " The control code for the command."]
    pub control: u32,
    #[doc = " The event type, if any."]
    pub ty: u32,
    #[doc = " The event data, if any."]
    pub data: *const c_void,
}
