// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_derive_arbitrary_decls_module_not_found_container_attributes,
    wrapped_derive_arbitrary_decls_module_not_found_field_attributes,
    wrapped_derive_arbitrary_decls_module_not_found_variant_attributes,
    wrapped_derive_arbitrary_decls_ARBITRARY_ATTRIBUTE_NAME,
    wrapped_derive_arbitrary_decls_ARBITRARY_LIFETIME_NAME,
    wrapped_derive_arbitrary_decls_derive_arbitrary,
    wrapped_derive_arbitrary_decls_expand_derive_arbitrary,
    wrapped_derive_arbitrary_decls_build_arbitrary_lifetime,
    wrapped_derive_arbitrary_decls_apply_trait_bounds,
    wrapped_derive_arbitrary_decls_add_trait_bounds,
    wrapped_derive_arbitrary_decls_gen_arbitrary_method,
    wrapped_derive_arbitrary_decls_construct,
    wrapped_derive_arbitrary_decls_construct_take_rest,
    wrapped_derive_arbitrary_decls_gen_size_hint_method,
    wrapped_derive_arbitrary_decls_gen_constructor_for_field,
    wrapped_derive_arbitrary_decls_check_variant_attrs
);
