// Generated macro for relative_ref (function)
macro_rules! Depcrate_parser_validaterelative_ref {
() => {
// Module: crate::parser::validate
// Provides: {"relative_ref"}
// Dependencies: {}
# [doc = " Validates [relative reference][relative-ref]."] # [doc = ""] # [doc = " This validator corresponds to [`RiRelativeStr`] and [`RiRelativeString`] types."] # [doc = ""] # [doc = " # Valid values"] # [doc = ""] # [doc = " This type can have a relative IRI reference."] # [doc = ""] # [doc = " ```"] # [doc = " use iri_string::{spec::UriSpec, validate::relative_ref};"] # [doc = " assert!(relative_ref::<UriSpec>(\"foo\").is_ok());"] # [doc = " assert!(relative_ref::<UriSpec>(\"foo/bar\").is_ok());"] # [doc = " assert!(relative_ref::<UriSpec>(\"/foo\").is_ok());"] # [doc = " assert!(relative_ref::<UriSpec>(\"//foo/bar\").is_ok());"] # [doc = " assert!(relative_ref::<UriSpec>(\"?foo\").is_ok());"] # [doc = " assert!(relative_ref::<UriSpec>(\"#foo\").is_ok());"] # [doc = " assert!(relative_ref::<UriSpec>(\"foo/bar?baz#qux\").is_ok());"] # [doc = " // The first path component can have colon if the path is absolute."] # [doc = " assert!(relative_ref::<UriSpec>(\"/foo:bar/\").is_ok());"] # [doc = " // Second or following path components can have colon."] # [doc = " assert!(relative_ref::<UriSpec>(\"foo/bar://baz/\").is_ok());"] # [doc = " assert!(relative_ref::<UriSpec>(\"./foo://bar\").is_ok());"] # [doc = " ```"] # [doc = ""] # [doc = " Absolute form of a reference is not allowed."] # [doc = ""] # [doc = " ```"] # [doc = " use iri_string::{spec::UriSpec, validate::relative_ref};"] # [doc = " assert!(relative_ref::<UriSpec>(\"https://example.com/\").is_err());"] # [doc = " // The first path component cannot have colon, if the path is not absolute."] # [doc = " assert!(relative_ref::<UriSpec>(\"foo:bar\").is_err());"] # [doc = " assert!(relative_ref::<UriSpec>(\"foo:\").is_err());"] # [doc = " assert!(relative_ref::<UriSpec>(\"foo:/\").is_err());"] # [doc = " assert!(relative_ref::<UriSpec>(\"foo://\").is_err());"] # [doc = " assert!(relative_ref::<UriSpec>(\"foo:///\").is_err());"] # [doc = " assert!(relative_ref::<UriSpec>(\"foo:////\").is_err());"] # [doc = " assert!(relative_ref::<UriSpec>(\"foo://///\").is_err());"] # [doc = " ```"] # [doc = ""] # [doc = " Some characters and sequences cannot used in an IRI reference."] # [doc = ""] # [doc = " ```"] # [doc = " use iri_string::{spec::UriSpec, validate::relative_ref};"] # [doc = " // `<` and `>` cannot directly appear in a relative IRI reference."] # [doc = " assert!(relative_ref::<UriSpec>(\"<not allowed>\").is_err());"] # [doc = " // Broken percent encoding cannot appear in a relative IRI reference."] # [doc = " assert!(relative_ref::<UriSpec>(\"%\").is_err());"] # [doc = " assert!(relative_ref::<UriSpec>(\"%GG\").is_err());"] # [doc = " ```"] # [doc = ""] # [doc = " [relative-ref]: https://tools.ietf.org/html/rfc3986#section-4.2"] # [doc = " [`RiRelativeStr`]: ../types/struct.RiRelativeStr.html"] # [doc = " [`RiRelativeString`]: ../types/struct.RiRelativeString.html"] pub fn relative_ref < S : Spec > (s : & str) -> Result < () , Error > { parser :: validate_relative_ref :: < S > (s) }
};
}
