// Generated macro for impl_179 (impl)
macro_rules! Depcrate_normalizeimpl_179 {
() => {
// Module: crate::normalize
// Provides: {"impl_179"}
// Dependencies: {}
impl < 'a , T : ? Sized > Normalized < 'a , T > { # [doc = " Creates a new `Normalized` object from the given input."] # [inline] # [must_use] pub (crate) fn from_input (input : NormalizationInput < 'a >) -> Self { Self { input , _ty_str : PhantomData , } } # [doc = " Enables the normalization."] # [doc = ""] # [doc = " This lets the normalizer apply the case normalization, percent-encoding"] # [doc = " normalization, and dot segments removal."] # [inline] pub fn enable_normalization (& mut self) { self . input . op . mode = NormalizationMode :: Default ; } # [doc = " Enables the normalization that preserve relative path under some condition."] # [doc = ""] # [doc = " Note that this normalization algorithm is not compatible with RFC 3986"] # [doc = " algorithm for some inputs."] # [doc = ""] # [doc = " See [`RiStr::normalize_but_preserve_authorityless_relative_path()`]"] # [doc = " for detail."] # [inline] pub fn enable_normalization_preserving_authorityless_relative_path (& mut self) { self . input . op . mode = NormalizationMode :: PreserveAuthoritylessRelativePath ; } # [doc = " Returns `Self` with normalization enabled."] # [inline] # [must_use] pub fn and_normalize (mut self) -> Self { self . enable_normalization () ; self } # [doc = " Returns `Self` with special normalization enabled."] # [doc = ""] # [doc = " Note that this normalization algorithm is not compatible with RFC 3986"] # [doc = " algorithm for some inputs."] # [doc = ""] # [doc = " See [`RiStr::normalize_but_preserve_authorityless_relative_path()`]"] # [doc = " for detail."] # [inline] # [must_use] pub fn and_normalize_but_preserve_authorityless_relative_path (mut self) -> Self { self . enable_normalization_preserving_authorityless_relative_path () ; self } # [doc = " Checks if the path is normalizable by RFC 3986 algorithm."] # [doc = ""] # [doc = " Returns `Ok(())` when normalizable, returns `Err(_)` if not."] # [inline] pub fn ensure_rfc3986_normalizable (& self) -> Result < () , Error > { self . input . ensure_rfc3986_normalizable () } }
};
}
