// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub struct RegistryInfo<'a> {
    #[doc = " Registry index url"]
    pub index_url: &'a str,
    #[doc = " Name of the registry in configuration. May not be available."]
    #[doc = " The crates.io registry will be `crates-io` (`CRATES_IO_REGISTRY`)."]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<&'a str>,
    #[doc = " Headers from attempting to access a registry that resulted in a HTTP 401."]
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub headers: Vec<String>,
}
