// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_http_auth_decls_module_not_found_parser,
    wrapped_http_auth_decls_module_not_found_basic,
    wrapped_http_auth_decls_module_not_found_digest,
    wrapped_http_auth_decls_module_not_found_table,
    wrapped_http_auth_decls_ChallengeRef,
    wrapped_http_auth_decls_impl_for_ChallengeRef,
    wrapped_http_auth_decls_impl_for_std_fmt_Debug,
    wrapped_http_auth_decls_ChallengeParamRef,
    wrapped_http_auth_decls_ParamsPrinter,
    wrapped_http_auth_decls_impl_for_std_fmt_Debug,
    wrapped_http_auth_decls_PasswordClientBuilder,
    wrapped_http_auth_decls_ToStrError,
    wrapped_http_auth_decls_HeaderValue,
    wrapped_http_auth_decls_impl_for_HeaderValue,
    wrapped_http_auth_decls_impl_for_HeaderValue,
    wrapped_http_auth_decls_impl_for_PasswordClientBuilder,
    wrapped_http_auth_decls_PasswordClient,
    wrapped_http_auth_decls_impl_for_TryFrom_ChallengeRef_____,
    wrapped_http_auth_decls_impl_for_TryFrom_str_,
    wrapped_http_auth_decls_impl_for_TryFrom_http_HeaderValue_,
    wrapped_http_auth_decls_impl_for_TryFrom_http10_HeaderValue_,
    wrapped_http_auth_decls_impl_for_TryFrom_http_header_GetAll____http_HeaderValue__,
    wrapped_http_auth_decls_impl_for_TryFrom_http10_header_GetAll____http10_HeaderValue__,
    wrapped_http_auth_decls_impl_for_PasswordClient,
    wrapped_http_auth_decls_PasswordParams,
    wrapped_http_auth_decls_parse_challenges,
    wrapped_http_auth_decls_ParamValue,
    wrapped_http_auth_decls_impl_for_ParamValue,
    wrapped_http_auth_decls_impl_for_std_fmt_Debug,
    wrapped_http_auth_decls_module_not_found_tests
);
