// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter.rs:211 from submodules/split-decls-rs/src/eager_splitter.rs
// Do not edit this file by hand. Your changes will be overwritten.

#[llm_error_message(message = "Module file not found for: kernel_sigset")]
#[llm_context(crate_name = "wrapped_rustix", module_name = "kernel_sigset")]
pub struct wrapped_rustix_decls_module_not_found_kernel_sigset;
