// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_rustc_symbol_mangling_decls_module_not_found_export,
    wrapped_rustc_symbol_mangling_decls_module_not_found_hashed,
    wrapped_rustc_symbol_mangling_decls_module_not_found_legacy,
    wrapped_rustc_symbol_mangling_decls_module_not_found_v0,
    wrapped_rustc_symbol_mangling_decls_module_not_found_errors,
    wrapped_rustc_symbol_mangling_decls_module_not_found_test,
    wrapped_rustc_symbol_mangling_decls_symbol_name_for_instance_in_crate,
    wrapped_rustc_symbol_mangling_decls_provide,
    wrapped_rustc_symbol_mangling_decls_symbol_name_provider,
    wrapped_rustc_symbol_mangling_decls_typeid_for_trait_ref,
    wrapped_rustc_symbol_mangling_decls_compute_symbol_name,
    wrapped_rustc_symbol_mangling_decls_is_generic
);
