// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[derive(Debug, Clone)]
pub struct Feature {
    pub name: Symbol,
    #[doc = " For unstable features: the version the feature was added in."]
    #[doc = " For accepted features: the version the feature got stabilized in."]
    #[doc = " For removed features we are inconsistent; sometimes this is the"]
    #[doc = " version it got added, sometimes the version it got removed."]
    pub since: &'static str,
    issue: Option<NonZero<u32>>,
}
