// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
impl Hunk {
    #[doc = " Can be used instead of `Option::None` for better performance."]
    #[doc = " Because `imara-diff` does not support more then `i32::MAX` there is an unused bit pattern that can be used."]
    #[doc = " Has some nice properties where it usually is not necessary to check for `None` separately:"]
    #[doc = " Empty ranges fail contains checks and also fail smaller then checks."]
    pub const NONE: Hunk = Hunk {
        before: u32::MAX..u32::MAX,
        after: u32::MAX..u32::MAX,
    };
    #[doc = " Inverts a hunk so that it represents a change"]
    #[doc = " that would undo this hunk."]
    pub fn invert(&self) -> Hunk {
        Hunk {
            before: self.after.clone(),
            after: self.before.clone(),
        }
    }
    #[doc = " Returns whether tokens are only inserted and not removed in this hunk."]
    pub fn is_pure_insertion(&self) -> bool {
        self.before.is_empty()
    }
    #[doc = " Returns whether tokens are only removed and not inserted in this hunk."]
    pub fn is_pure_removal(&self) -> bool {
        self.after.is_empty()
    }
}
