// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Errors and warnings that can occur during string, char, and byte unescaping."]
#[doc = ""]
#[doc = " Mostly relating to malformed escape sequences, but also a few other problems."]
#[derive(Debug, PartialEq, Eq)]
pub enum EscapeError {
    #[doc = " Expected 1 char, but 0 were found."]
    ZeroChars,
    #[doc = " Expected 1 char, but more than 1 were found."]
    MoreThanOneChar,
    #[doc = " Escaped '\\' character without continuation."]
    LoneSlash,
    #[doc = " Invalid escape character (e.g. '\\z')."]
    InvalidEscape,
    #[doc = " Raw '\\r' encountered."]
    BareCarriageReturn,
    #[doc = " Raw '\\r' encountered in raw string."]
    BareCarriageReturnInRawString,
    #[doc = " Unescaped character that was expected to be escaped (e.g. raw '\\t')."]
    EscapeOnlyChar,
    #[doc = " Numeric character escape is too short (e.g. '\\x1')."]
    TooShortHexEscape,
    #[doc = " Invalid character in numeric escape (e.g. '\\xz')"]
    InvalidCharInHexEscape,
    #[doc = " Character code in numeric escape is non-ascii (e.g. '\\xFF')."]
    OutOfRangeHexEscape,
    #[doc = " '\\u' not followed by '{'."]
    NoBraceInUnicodeEscape,
    #[doc = " Non-hexadecimal value in '\\u{..}'."]
    InvalidCharInUnicodeEscape,
    #[doc = " '\\u{}'"]
    EmptyUnicodeEscape,
    #[doc = " No closing brace in '\\u{..}', e.g. '\\u{12'."]
    UnclosedUnicodeEscape,
    #[doc = " '\\u{_12}'"]
    LeadingUnderscoreUnicodeEscape,
    #[doc = " More than 6 characters in '\\u{..}', e.g. '\\u{10FFFF_FF}'"]
    OverlongUnicodeEscape,
    #[doc = " Invalid in-bound unicode character code, e.g. '\\u{DFFF}'."]
    LoneSurrogateUnicodeEscape,
    #[doc = " Out of bounds unicode character code, e.g. '\\u{FFFFFF}'."]
    OutOfRangeUnicodeEscape,
    #[doc = " Unicode escape code in byte literal."]
    UnicodeEscapeInByte,
    #[doc = " Non-ascii character in byte literal, byte string literal, or raw byte string literal."]
    NonAsciiCharInByte,
    #[doc = " `\\0` in a C string literal."]
    NulInCStr,
    #[doc = " After a line ending with '\\', the next line contains whitespace"]
    #[doc = " characters that are not skipped."]
    UnskippedWhitespaceWarning,
    #[doc = " After a line ending with '\\', multiple lines are skipped."]
    MultipleSkippedLinesWarning,
}
