// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Check a raw C string literal for validity"]
#[doc = ""]
#[doc = " Takes the contents of a raw C string literal (without quotes)"]
#[doc = " and produces a sequence of characters or errors,"]
#[doc = " which are returned by invoking `callback`."]
#[doc = " NOTE: Does no escaping, but produces errors for bare carriage return ('\\r')."]
pub fn check_raw_c_str(
    src: &str,
    callback: impl FnMut(Range<usize>, Result<NonZero<char>, EscapeError>),
) {
    CStr::check_raw(src, callback);
}
