// Generated macro for impl_441 (impl)
macro_rules! Depcrate_consteval_tests_method_resolutionimpl_441 {
() => {
// Module: crate::consteval::tests::method_resolution
// Provides: {"impl_441"}
// Dependencies: {}
impl InherentImpls { pub (crate) fn inherent_impls_in_crate_query (db : & dyn HirDatabase , krate : Crate) -> Arc < Self > { let _p = tracing :: info_span ! ("inherent_impls_in_crate_query" , ? krate) . entered () ; let mut impls = Self { map : FxHashMap :: default () , invalid_impls : Vec :: default () } ; let crate_def_map = crate_def_map (db , krate) ; impls . collect_def_map (db , crate_def_map) ; impls . shrink_to_fit () ; Arc :: new (impls) } pub (crate) fn inherent_impls_in_block_query (db : & dyn HirDatabase , block : BlockId ,) -> Option < Arc < Self > > { let _p = tracing :: info_span ! ("inherent_impls_in_block_query") . entered () ; let mut impls = Self { map : FxHashMap :: default () , invalid_impls : Vec :: default () } ; let block_def_map = block_def_map (db , block) ; impls . collect_def_map (db , block_def_map) ; impls . shrink_to_fit () ; if impls . map . is_empty () && impls . invalid_impls . is_empty () { None } else { Some (Arc :: new (impls)) } } fn shrink_to_fit (& mut self) { self . map . values_mut () . for_each (Vec :: shrink_to_fit) ; self . map . shrink_to_fit () ; } fn collect_def_map (& mut self , db : & dyn HirDatabase , def_map : & DefMap) { for (_module_id , module_data) in def_map . modules () { for impl_id in module_data . scope . impls () { let data = db . impl_signature (impl_id) ; if data . target_trait . is_some () { continue ; } let self_ty = db . impl_self_ty (impl_id) ; let self_ty = self_ty . skip_binders () ; match is_inherent_impl_coherent (db , def_map , impl_id , self_ty) { true => { if let Some (fp) = TyFingerprint :: for_inherent_impl (self_ty) { self . map . entry (fp) . or_default () . push (impl_id) ; } } false => self . invalid_impls . push (impl_id) , } } for konst in module_data . scope . unnamed_consts () { let body = db . body (konst . into ()) ; for (_ , block_def_map) in body . blocks (db) { self . collect_def_map (db , block_def_map) ; } } } } pub fn for_self_ty (& self , self_ty : & Ty) -> & [ImplId] { match TyFingerprint :: for_inherent_impl (self_ty) { Some (fp) => self . map . get (& fp) . map (| vec | vec . as_ref ()) . unwrap_or (& []) , None => & [] , } } pub fn all_impls (& self) -> impl Iterator < Item = ImplId > + '_ { self . map . values () . flat_map (| v | v . iter () . copied ()) } pub fn invalid_impls (& self) -> & [ImplId] { & self . invalid_impls } }
};
}
