// Generated macro for impl_135 (impl)
macro_rules! Depcrateimpl_135 {
() => {
// Module: crate
// Provides: {"impl_135"}
// Dependencies: {}
impl Async < TcpStream > { # [doc = " Creates a TCP connection to the specified address."] # [doc = ""] # [doc = " # Examples"] # [doc = ""] # [doc = " ```"] # [doc = " use async_io::Async;"] # [doc = " use std::net::{TcpStream, ToSocketAddrs};"] # [doc = ""] # [doc = " # futures_lite::future::block_on(async {"] # [doc = " let addr = \"example.com:80\".to_socket_addrs()?.next().unwrap();"] # [doc = " let stream = Async::<TcpStream>::connect(addr).await?;"] # [doc = " # std::io::Result::Ok(()) });"] # [doc = " ```"] pub async fn connect < A : Into < SocketAddr > > (addr : A) -> io :: Result < Async < TcpStream > > { let addr = addr . into () ; let (domain , sock_addr) = match addr { SocketAddr :: V4 (v4) => (rn :: AddressFamily :: INET , v4 . as_any ()) , SocketAddr :: V6 (v6) => (rn :: AddressFamily :: INET6 , v6 . as_any ()) , } ; let socket = connect (sock_addr , domain , Some (rn :: ipproto :: TCP)) ? ; let stream = Async :: new_nonblocking (TcpStream :: from (socket)) ? ; stream . writable () . await ? ; match stream . get_ref () . take_error () ? { None => Ok (stream) , Some (err) => Err (err) , } } # [doc = " Reads data from the stream without removing it from the buffer."] # [doc = ""] # [doc = " Returns the number of bytes read. Successive calls of this method read the same data."] # [doc = ""] # [doc = " # Examples"] # [doc = ""] # [doc = " ```"] # [doc = " use async_io::Async;"] # [doc = " use futures_lite::{io::AsyncWriteExt, stream::StreamExt};"] # [doc = " use std::net::{TcpStream, ToSocketAddrs};"] # [doc = ""] # [doc = " # futures_lite::future::block_on(async {"] # [doc = " let addr = \"example.com:80\".to_socket_addrs()?.next().unwrap();"] # [doc = " let mut stream = Async::<TcpStream>::connect(addr).await?;"] # [doc = ""] # [doc = " stream"] # [doc = "     .write_all(b\"GET / HTTP/1.1\\r\\nHost: example.com\\r\\n\\r\\n\")"] # [doc = "     .await?;"] # [doc = ""] # [doc = " let mut buf = [0u8; 1024];"] # [doc = " let len = stream.peek(&mut buf).await?;"] # [doc = " # std::io::Result::Ok(()) });"] # [doc = " ```"] pub async fn peek (& self , buf : & mut [u8]) -> io :: Result < usize > { self . read_with (| io | io . peek (buf)) . await } }
};
}
