// Generated macro for impl_124 (impl)
macro_rules! Depcrate_actor_spawnerimpl_124 {
() => {
// Module: crate::actor::spawner
// Provides: {"impl_124"}
// Dependencies: {}
impl < W , CODEC > WorkerSpawner < W , CODEC > where W : Worker + 'static , CODEC : Codec , { # [doc = " Creates a [WorkerSpawner]."] pub const fn new () -> Self { Self { _marker : PhantomData , callback : None , } } # [doc = " Sets a new message encoding."] pub fn encoding < C > (& mut self) -> WorkerSpawner < W , C > where C : Codec , { WorkerSpawner { _marker : PhantomData , callback : self . callback . clone () , } } # [doc = " Sets a callback."] pub fn callback < F > (& mut self , cb : F) -> & mut Self where F : 'static + Fn (W :: Output) , { self . callback = Some (Rc :: new (cb)) ; self } fn spawn_inner (& self , worker : DedicatedWorker) -> WorkerBridge < W > where W :: Input : Serialize + for < 'de > Deserialize < 'de > , W :: Output : Serialize + for < 'de > Deserialize < 'de > , { let pending_queue = Rc :: new (RefCell :: new (Some (Vec :: new ()))) ; let handler_id = HandlerId :: new () ; let mut callbacks = HashMap :: new () ; if let Some (m) = self . callback . as_ref () . map (Rc :: downgrade) { callbacks . insert (handler_id , m) ; } let callbacks : Shared < CallbackMap < W > > = Rc :: new (RefCell :: new (callbacks)) ; let handler = { let pending_queue = pending_queue . clone () ; let callbacks = callbacks . clone () ; let worker = worker . clone () ; move | msg : FromWorker < W > | match msg { FromWorker :: WorkerLoaded => { if let Some (pending_queue) = pending_queue . borrow_mut () . take () { for to_worker in pending_queue . into_iter () { worker . post_packed_message :: < _ , CODEC > (to_worker) ; } } } FromWorker :: ProcessOutput (id , output) => { let mut callbacks = callbacks . borrow_mut () ; if let Some (m) = callbacks . get (& id) { if let Some (m) = Weak :: upgrade (m) { m (output) ; } else { callbacks . remove (& id) ; } } } } } ; worker . set_on_packed_message :: < _ , CODEC , _ > (handler) ; WorkerBridge :: < W > :: new :: < CODEC > (handler_id , worker , pending_queue , callbacks , self . callback . clone () ,) } # [doc = " Spawns a Worker."] pub fn spawn (& self , path : & str) -> WorkerBridge < W > where W :: Input : Serialize + for < 'de > Deserialize < 'de > , W :: Output : Serialize + for < 'de > Deserialize < 'de > , { let worker = create_worker (path) ; self . spawn_inner (worker) } # [doc = " Spawns a Worker with a loader shim script."] pub fn spawn_with_loader (& self , loader_path : & str) -> WorkerBridge < W > where W :: Input : Serialize + for < 'de > Deserialize < 'de > , W :: Output : Serialize + for < 'de > Deserialize < 'de > , { let worker = DedicatedWorker :: new (loader_path) . expect ("failed to spawn worker") ; self . spawn_inner (worker) } }
};
}
