// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_vfs_decls_module_not_found_anchored_path,
    wrapped_vfs_decls_module_not_found_file_set,
    wrapped_vfs_decls_module_not_found_loader,
    wrapped_vfs_decls_module_not_found_path_interner,
    wrapped_vfs_decls_module_not_found_vfs_path,
    wrapped_vfs_decls_FileId,
    wrapped_vfs_decls_impl_for_FileId,
    wrapped_vfs_decls_impl_for_nohash_hasher_IsEnabled,
    wrapped_vfs_decls_Vfs,
    wrapped_vfs_decls_FileState,
    wrapped_vfs_decls_ChangedFile,
    wrapped_vfs_decls_impl_for_ChangedFile,
    wrapped_vfs_decls_Change,
    wrapped_vfs_decls_ChangeKind,
    wrapped_vfs_decls_FileExcluded,
    wrapped_vfs_decls_impl_for_Vfs,
    wrapped_vfs_decls_impl_for_fmt_Debug
);
