// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter.rs:211 from submodules/split-decls-rs/src/eager_splitter.rs
// Do not edit this file by hand. Your changes will be overwritten.

#[llm_error_message(message = "Module file not found for: trace_macro_note")]
#[llm_context(
    crate_name = "wrapped_rustc_expand_base_lib_errors",
    module_name = "trace_macro_note"
)]
pub struct wrapped_rustc_expand_base_lib_errors_decls_module_not_found_trace_macro_note;
