// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Error type for the `try_get_` methods of [`Buf`]."]
#[doc = " Indicates that there were not enough remaining"]
#[doc = " bytes in the buffer while attempting"]
#[doc = " to get a value from a [`Buf`] with one"]
#[doc = " of the `try_get_` methods."]
#[derive(Debug, PartialEq, Eq)]
pub struct TryGetError {
    #[doc = " The number of bytes necessary to get the value"]
    pub requested: usize,
    #[doc = " The number of bytes available in the buffer"]
    pub available: usize,
}
