// Generated macro for impl_10 (impl)
macro_rules! Depcrate_bundlesimpl_10 {
() => {
// Module: crate::bundles
// Provides: {"impl_10"}
// Dependencies: {}
impl < G > Bundles < G > where G : BundleGenerator , { pub fn new < P > (sync : bool , res_ids : FxHashSet < ResourceId > , generator : & G , provider : & P) -> Self where G : BundleGenerator < LocalesIter = P :: Iter > , P : LocalesProvider , { Self (if sync { BundlesInner :: Iter (Cache :: new (generator . bundles_iter (provider . locales () , res_ids) ,)) } else { BundlesInner :: Stream (AsyncCache :: new (generator . bundles_stream (provider . locales () , res_ids) ,)) }) } pub async fn format_value < 'l > (& 'l self , id : & 'l str , args : Option < & 'l FluentArgs < '_ > > , errors : & mut Vec < LocalizationError > ,) -> Option < Cow < 'l , str > > { match & self . 0 { BundlesInner :: Iter (cache) => Self :: format_value_from_iter (cache , id , args , errors) , BundlesInner :: Stream (stream) => { Self :: format_value_from_stream (stream , id , args , errors) . await } } } pub async fn format_values < 'l > (& 'l self , keys : & 'l [L10nKey < 'l >] , errors : & mut Vec < LocalizationError > ,) -> Vec < Option < Cow < 'l , str > > > { match & self . 0 { BundlesInner :: Iter (cache) => Self :: format_values_from_iter (cache , keys , errors) , BundlesInner :: Stream (stream) => { Self :: format_values_from_stream (stream , keys , errors) . await } } } pub async fn format_messages < 'l > (& 'l self , keys : & 'l [L10nKey < 'l >] , errors : & mut Vec < LocalizationError > ,) -> Vec < Option < L10nMessage < 'l > > > { match & self . 0 { BundlesInner :: Iter (cache) => Self :: format_messages_from_iter (cache , keys , errors) , BundlesInner :: Stream (stream) => { Self :: format_messages_from_stream (stream , keys , errors) . await } } } pub fn format_value_sync < 'l > (& 'l self , id : & 'l str , args : Option < & 'l FluentArgs > , errors : & mut Vec < LocalizationError > ,) -> Result < Option < Cow < 'l , str > > , LocalizationError > { match & self . 0 { BundlesInner :: Iter (cache) => Ok (Self :: format_value_from_iter (cache , id , args , errors)) , BundlesInner :: Stream (_) => Err (LocalizationError :: SyncRequestInAsyncMode) , } } pub fn format_values_sync < 'l > (& 'l self , keys : & 'l [L10nKey < 'l >] , errors : & mut Vec < LocalizationError > ,) -> Result < Vec < Option < Cow < 'l , str > > > , LocalizationError > { match & self . 0 { BundlesInner :: Iter (cache) => Ok (Self :: format_values_from_iter (cache , keys , errors)) , BundlesInner :: Stream (_) => Err (LocalizationError :: SyncRequestInAsyncMode) , } } pub fn format_messages_sync < 'l > (& 'l self , keys : & 'l [L10nKey < 'l >] , errors : & mut Vec < LocalizationError > ,) -> Result < Vec < Option < L10nMessage < 'l > > > , LocalizationError > { match & self . 0 { BundlesInner :: Iter (cache) => Ok (Self :: format_messages_from_iter (cache , keys , errors)) , BundlesInner :: Stream (_) => Err (LocalizationError :: SyncRequestInAsyncMode) , } } }
};
}
