// Generated macro for decode_utf8 (function)
macro_rules! Depcrate_utf8decode_utf8 {
() => {
// Module: crate::utf8
// Provides: {"decode_utf8"}
// Dependencies: {}
# [doc = " Decode a single UTF-8 sequence into a single Unicode codepoint from `src`."] # [doc = ""] # [doc = " If no valid UTF-8 sequence could be found, then `None` is returned."] # [doc = " Otherwise, the decoded codepoint and the number of bytes read is returned."] # [doc = " The number of bytes read (for a valid UTF-8 sequence) is guaranteed to be"] # [doc = " 1, 2, 3 or 4."] # [doc = ""] # [doc = " Note that a UTF-8 sequence is invalid if it is incorrect UTF-8, encodes a"] # [doc = " codepoint that is out of range (surrogate codepoints are out of range) or"] # [doc = " is not the shortest possible UTF-8 sequence for that codepoint."] # [inline] pub fn decode_utf8 (src : & [u8]) -> Option < (char , usize) > { let b0 = match src . get (0) { None => return None , Some (& b) if b <= 0x7F => return Some ((b as char , 1)) , Some (& b) => b , } ; match b0 { 0b110_00000 ..= 0b110_11111 => { if src . len () < 2 { return None ; } let b1 = src [1] ; let cp = ((b0 & ! TAG_TWO) as u32) << 6 | ((b1 & ! TAG_CONT) as u32) ; match cp { 0x80 ..= 0x7FF => char :: from_u32 (cp) . map (| cp | (cp , 2)) , _ => None , } } 0b1110_0000 ..= 0b1110_1111 => { if src . len () < 3 { return None ; } let (b1 , b2) = (src [1] , src [2]) ; let cp = ((b0 & ! TAG_THREE) as u32) << 12 | ((b1 & ! TAG_CONT) as u32) << 6 | ((b2 & ! TAG_CONT) as u32) ; match cp { 0x800 ..= 0xFFFF => char :: from_u32 (cp) . map (| cp | (cp , 3)) , _ => None , } } 0b11110_000 ..= 0b11110_111 => { if src . len () < 4 { return None ; } let (b1 , b2 , b3) = (src [1] , src [2] , src [3]) ; let cp = ((b0 & ! TAG_FOUR) as u32) << 18 | ((b1 & ! TAG_CONT) as u32) << 12 | ((b2 & ! TAG_CONT) as u32) << 6 | ((b3 & ! TAG_CONT) as u32) ; match cp { 0x10000 ..= 0x10FFFF => char :: from_u32 (cp) . map (| cp | (cp , 4)) , _ => None , } } _ => None , } }
};
}
