// Generated macro for panic_count (module)
macro_rules! Depcrate_panickingpanic_count {
() => {
// Module: crate::panicking
// Provides: {"panic_count"}
// Dependencies: {}
# [cfg (not (test))] # [doc (hidden)] # [cfg (not (feature = "panic_immediate_abort"))] # [unstable (feature = "update_panic_count" , issue = "none")] pub mod panic_count { use crate :: cell :: Cell ; use crate :: sync :: atomic :: { Atomic , AtomicUsize , Ordering } ; const ALWAYS_ABORT_FLAG : usize = 1 << (usize :: BITS - 1) ; # [doc = " A reason for forcing an immediate abort on panic."] # [derive (Debug)] pub enum MustAbort { AlwaysAbort , PanicInHook , } thread_local ! { static LOCAL_PANIC_COUNT : Cell < (usize , bool) > = const { Cell :: new ((0 , false)) } } static GLOBAL_PANIC_COUNT : Atomic < usize > = AtomicUsize :: new (0) ; pub fn increase (run_panic_hook : bool) -> Option < MustAbort > { let global_count = GLOBAL_PANIC_COUNT . fetch_add (1 , Ordering :: Relaxed) ; if global_count & ALWAYS_ABORT_FLAG != 0 { return Some (MustAbort :: AlwaysAbort) ; } LOCAL_PANIC_COUNT . with (| c | { let (count , in_panic_hook) = c . get () ; if in_panic_hook { return Some (MustAbort :: PanicInHook) ; } c . set ((count + 1 , run_panic_hook)) ; None }) } pub fn finished_panic_hook () { LOCAL_PANIC_COUNT . with (| c | { let (count , _) = c . get () ; c . set ((count , false)) ; }) ; } pub fn decrease () { GLOBAL_PANIC_COUNT . fetch_sub (1 , Ordering :: Relaxed) ; LOCAL_PANIC_COUNT . with (| c | { let (count , _) = c . get () ; c . set ((count - 1 , false)) ; }) ; } pub fn set_always_abort () { GLOBAL_PANIC_COUNT . fetch_or (ALWAYS_ABORT_FLAG , Ordering :: Relaxed) ; } # [must_use] pub fn get_count () -> usize { LOCAL_PANIC_COUNT . with (| c | c . get () . 0) } # [must_use] # [inline] pub fn count_is_zero () -> bool { if GLOBAL_PANIC_COUNT . load (Ordering :: Relaxed) & ! ALWAYS_ABORT_FLAG == 0 { true } else { is_zero_slow_path () } } # [inline (never)] # [cold] fn is_zero_slow_path () -> bool { LOCAL_PANIC_COUNT . with (| c | c . get () . 0 == 0) } }
};
}
