// Generated macro for create_dir_all (function)
macro_rules! Depcrate_fscreate_dir_all {
() => {
// Module: crate::fs
// Provides: {"create_dir_all"}
// Dependencies: {}
# [doc = " Recursively create a directory and all of its parent components if they"] # [doc = " are missing."] # [doc = ""] # [doc = " This function is not atomic. If it returns an error, any parent components it was able to create"] # [doc = " will remain."] # [doc = ""] # [doc = " If the empty path is passed to this function, it always succeeds without"] # [doc = " creating any directories."] # [doc = ""] # [doc = " # Platform-specific behavior"] # [doc = ""] # [doc = " This function currently corresponds to multiple calls to the `mkdir`"] # [doc = " function on Unix and the `CreateDirectoryW` function on Windows."] # [doc = ""] # [doc = " Note that, this [may change in the future][changes]."] # [doc = ""] # [doc = " [changes]: io#platform-specific-behavior"] # [doc = ""] # [doc = " # Errors"] # [doc = ""] # [doc = " The function will return an error if any directory specified in path does not exist and"] # [doc = " could not be created. There may be other error conditions; see [`fs::create_dir`] for specifics."] # [doc = ""] # [doc = " Notable exception is made for situations where any of the directories"] # [doc = " specified in the `path` could not be created as it was being created concurrently."] # [doc = " Such cases are considered to be successful. That is, calling `create_dir_all`"] # [doc = " concurrently from multiple threads or processes is guaranteed not to fail"] # [doc = " due to a race condition with itself."] # [doc = ""] # [doc = " [`fs::create_dir`]: create_dir"] # [doc = ""] # [doc = " # Examples"] # [doc = ""] # [doc = " ```no_run"] # [doc = " use std::fs;"] # [doc = ""] # [doc = " fn main() -> std::io::Result<()> {"] # [doc = "     fs::create_dir_all(\"/some/dir\")?;"] # [doc = "     Ok(())"] # [doc = " }"] # [doc = " ```"] # [stable (feature = "rust1" , since = "1.0.0")] pub fn create_dir_all < P : AsRef < Path > > (path : P) -> io :: Result < () > { DirBuilder :: new () . recursive (true) . create (path . as_ref ()) }
};
}
