// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
fn lint_severity_at(
    sema: &Semantics<'_, RootDatabase>,
    node: &InFile<SyntaxNode>,
    lint_groups: &LintGroups,
    edition: Edition,
) -> Option<Severity> {
    node.value
        .ancestors()
        .filter_map(ast::AnyHasAttrs::cast)
        .find_map(|ancestor| {
            lint_attrs(sema, ancestor, edition)
                .find_map(|(lint, severity)| lint_groups.contains(&lint).then_some(severity))
        })
        .or_else(|| {
            lint_severity_at(
                sema,
                &sema.find_parent_file(node.file_id)?,
                lint_groups,
                edition,
            )
        })
}
