// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_tera_decls_module_not_found_macros,
    wrapped_tera_decls_module_not_found_builtins,
    wrapped_tera_decls_module_not_found_context,
    wrapped_tera_decls_module_not_found_errors,
    wrapped_tera_decls_module_not_found_filter_utils,
    wrapped_tera_decls_module_not_found_parser,
    wrapped_tera_decls_module_not_found_renderer,
    wrapped_tera_decls_module_not_found_template,
    wrapped_tera_decls_module_not_found_tera,
    wrapped_tera_decls_module_not_found_utils,
    wrapped_tera_decls_module_not_found_helpers
);
