#![recursion_limit = "256"]
#![allow(internal_features)]
#![feature(rustc_private)]

include!("wrap_types.rs");

// Auto-generated module tree for: backtrace::build::main
// Dependencies resolved: 19

macro_rules! include_dep_0 { () => {
// SRC: ../rust/library/std/src/env.rs
// SRC: library/std/src/env.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: library/std/src/env.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: library/std/src/env.rs