// Generated macro for EvalContextExt (trait)
macro_rules! Depcrate_shims_unix_linux_like_eventfdEvalContextExt {
() => {
// Module: crate::shims::unix::linux_like::eventfd
// Provides: {"EvalContextExt"}
// Dependencies: {}
pub trait EvalContextExt < 'tcx > : crate :: MiriInterpCxExt < 'tcx > { # [doc = " This function creates an `Event` that is used as an event wait/notify mechanism by"] # [doc = " user-space applications, and by the kernel to notify user-space applications of events."] # [doc = " The `Event` contains an `u64` counter maintained by the kernel. The counter is initialized"] # [doc = " with the value specified in the `initval` argument."] # [doc = ""] # [doc = " A new file descriptor referring to the `Event` is returned. The `read`, `write`, `poll`,"] # [doc = " `select`, and `close` operations can be performed on the file descriptor. For more"] # [doc = " information on these operations, see the man page linked below."] # [doc = ""] # [doc = " The `flags` are not currently implemented for eventfd."] # [doc = " The `flags` may be bitwise ORed to change the behavior of `eventfd`:"] # [doc = " `EFD_CLOEXEC` - Set the close-on-exec (`FD_CLOEXEC`) flag on the new file descriptor."] # [doc = " `EFD_NONBLOCK` - Set the `O_NONBLOCK` file status flag on the new open file description."] # [doc = " `EFD_SEMAPHORE` - miri does not support semaphore-like semantics."] # [doc = ""] # [doc = " <https://linux.die.net/man/2/eventfd>"] fn eventfd (& mut self , val : & OpTy < 'tcx > , flags : & OpTy < 'tcx >) -> InterpResult < 'tcx , Scalar > { let this = self . eval_context_mut () ; let val = this . read_scalar (val) ? . to_u32 () ? ; let mut flags = this . read_scalar (flags) ? . to_i32 () ? ; let efd_cloexec = this . eval_libc_i32 ("EFD_CLOEXEC") ; let efd_nonblock = this . eval_libc_i32 ("EFD_NONBLOCK") ; let efd_semaphore = this . eval_libc_i32 ("EFD_SEMAPHORE") ; if flags & efd_semaphore == efd_semaphore { throw_unsup_format ! ("eventfd: EFD_SEMAPHORE is unsupported") ; } let mut is_nonblock = false ; if flags & efd_cloexec == efd_cloexec { flags &= ! efd_cloexec ; } if flags & efd_nonblock == efd_nonblock { flags &= ! efd_nonblock ; is_nonblock = true ; } if flags != 0 { throw_unsup_format ! ("eventfd: encountered unknown unsupported flags {:#x}" , flags) ; } let fds = & mut this . machine . fds ; let fd_value = fds . insert_new (EventFd { counter : Cell :: new (val . into ()) , is_nonblock , clock : RefCell :: new (VClock :: default ()) , blocked_read_tid : RefCell :: new (Vec :: new ()) , blocked_write_tid : RefCell :: new (Vec :: new ()) , }) ; interp_ok (Scalar :: from_i32 (fd_value)) } }
};
}
