// Generated macro for Thread (struct)
macro_rules! Depcrate_concurrency_threadThread {
() => {
// Module: crate::concurrency::thread
// Provides: {"Thread"}
// Dependencies: {}
# [doc = " A thread."] pub struct Thread < 'tcx > { state : ThreadState < 'tcx > , # [doc = " Name of the thread."] thread_name : Option < Vec < u8 > > , # [doc = " The virtual call stack."] stack : Vec < Frame < 'tcx , Provenance , FrameExtra < 'tcx > > > , # [doc = " The function to call when the stack ran empty, to figure out what to do next."] # [doc = " Conceptually, this is the interpreter implementation of the things that happen 'after' the"] # [doc = " Rust language entry point for this thread returns (usually implemented by the C or OS runtime)."] # [doc = " (`None` is an error, it means the callback has not been set up yet or is actively running.)"] pub (crate) on_stack_empty : Option < StackEmptyCallback < 'tcx > > , # [doc = " The index of the topmost user-relevant frame in `stack`. This field must contain"] # [doc = " the value produced by `get_top_user_relevant_frame`."] # [doc = " The `None` state here represents"] # [doc = " This field is a cache to reduce how often we call that method. The cache is manually"] # [doc = " maintained inside `MiriMachine::after_stack_push` and `MiriMachine::after_stack_pop`."] top_user_relevant_frame : Option < usize > , # [doc = " The join status."] join_status : ThreadJoinStatus , # [doc = " Stack of active unwind payloads for the current thread. Used for storing"] # [doc = " the argument of the call to `miri_start_unwind` (the payload) when unwinding."] # [doc = " This is pointer-sized, and matches the `Payload` type in `src/libpanic_unwind/miri.rs`."] # [doc = ""] # [doc = " In real unwinding, the payload gets passed as an argument to the landing pad,"] # [doc = " which then forwards it to 'Resume'. However this argument is implicit in MIR,"] # [doc = " so we have to store it out-of-band. When there are multiple active unwinds,"] # [doc = " the innermost one is always caught first, so we can store them as a stack."] pub (crate) unwind_payloads : Vec < ImmTy < 'tcx > > , # [doc = " Last OS error location in memory. It is a 32-bit integer."] pub (crate) last_error : Option < MPlaceTy < 'tcx > > , }
};
}
