// Generated macro for Options (struct)
macro_rules! Depcrate_treeOptions {
() => {
// Module: crate::tree
// Provides: {"Options"}
// Dependencies: {}
# [doc = " A way to configure [`tree()`](crate::tree())."] # [derive (Default , Debug , Clone)] pub struct Options { # [doc = " If *not* `None`, rename tracking will be performed when determining the changes of each side of the merge."] # [doc = ""] # [doc = " Note that [empty blobs](Rewrites::track_empty) should not be tracked for best results."] pub rewrites : Option < Rewrites > , # [doc = " Decide how blob-merges should be done. This relates to if conflicts can be resolved or not."] pub blob_merge : crate :: blob :: platform :: merge :: Options , # [doc = " The context to use when invoking merge-drivers."] pub blob_merge_command_ctx : gix_command :: Context , # [doc = " If `Some(what-is-unresolved)`, the first unresolved conflict will cause the entire merge to stop."] # [doc = " This is useful to see if there is any conflict, without performing the whole operation, something"] # [doc = " that can be very relevant during merges that would cause a lot of blob-diffs."] pub fail_on_conflict : Option < TreatAsUnresolved > , # [doc = " This value also affects the size of merge-conflict markers, to allow differentiating"] # [doc = " merge conflicts on each level, for any value greater than 0, with values `N` causing `N*2`"] # [doc = " markers to be added to the configured value."] # [doc = ""] # [doc = " This is used automatically when merging merge-bases recursively."] pub marker_size_multiplier : u8 , # [doc = " If `None`, when symlinks clash *ours* will be chosen and a conflict will occur."] # [doc = " Otherwise, the same logic applies as for the merge of binary resources."] pub symlink_conflicts : Option < crate :: blob :: builtin_driver :: binary :: ResolveWith > , # [doc = " If `None`, tree irreconcilable tree conflicts will result in [resolution failures](ResolutionFailure)."] # [doc = " Otherwise, one can choose a side. Note that it's still possible to determine that auto-resolution happened"] # [doc = " despite this choice, which allows carry forward the conflicting information, possibly for later resolution."] # [doc = " If `Some(…)`, irreconcilable conflicts are reconciled by making a choice."] # [doc = " Note that [`Conflict::entries()`] will still be set, to not degenerate information, even though they then represent"] # [doc = " the entries what would fit the index if no forced resolution was performed."] # [doc = " It's up to the caller to handle that information mindfully."] pub tree_conflicts : Option < ResolveWith > , }
};
}
