// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[track_caller]
pub fn assert_deterministic_mtime(path: impl AsRef<Path>) {
    const DETERMINISTIC_TIMESTAMP: u64 = 1153704088;
    let path = path.as_ref();
    let mtime = path.metadata().unwrap().modified().unwrap();
    let timestamp = mtime
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_secs();
    assert_eq!(
        timestamp, DETERMINISTIC_TIMESTAMP,
        "expected deterministic mtime for {path:?}, got {timestamp}"
    );
}
