// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Run `$bin` in the test's environment, see [`ProcessBuilder`]"]
#[doc = ""]
#[doc = " For more on the test environment, see"]
#[doc = " - [`paths::root`]"]
#[doc = " - [`TestEnvCommandExt`]"]
pub fn process<T: AsRef<OsStr>>(bin: T) -> ProcessBuilder {
    _process(bin.as_ref())
}
