// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module ! (wrapped_trait_fixer_core_mock_decls_MockTraitFixer , wrapped_trait_fixer_core_mock_decls_impl_for_MockTraitFixer , wrapped_trait_fixer_core_mock_decls_impl_for_CoreFixer__tcx_trait_fixer_rules_Config_TyCtxt__tcx__Item__tcx__DefId_DefId_Span_) ;
