// Generated macro for check_step (function)
macro_rules! Depcrate_statecheck_step {
() => {
// Module: crate::state
// Provides: {"check_step"}
// Dependencies: {}
# [doc = " Check a single proof step"] pub fn check_step < 'a > (mut ctx : partial ! (Context <'a >, mut CheckerStateP , mut ClauseHasherP , mut ClausesP , mut ProcessingP <'a >, mut RupCheckP , mut TmpDataP , mut VariablesP ,) , step : ProofStep ,) -> Result < () , CheckerError > { let mut result = match step { ProofStep :: SolverVarName { global , solver } => { ctx . part_mut (ClauseHasherP) . buffered_solver_var_names . push ((global , solver)) ; if solver . is_some () { ctx . part_mut (ClauseHasherP) . rename_in_buffered_solver_var_names = true ; } Ok (()) } ProofStep :: UserVarName { global , user } => { if let Some (user) = user { add_user_mapping (ctx . borrow () , global , user) ? ; } else { remove_user_mapping (ctx . borrow () , global) ? ; } Ok (()) } ProofStep :: DeleteVar { var } => check_delete_var_step (ctx . borrow () , var) , ProofStep :: ChangeSamplingMode { var , sample } => { check_change_sampling_mode (ctx . borrow () , var , sample) } ProofStep :: AddClause { clause } => add_clause (ctx . borrow () , clause) , ProofStep :: AtClause { redundant , clause , propagation_hashes , } => check_at_clause_step (ctx . borrow () , redundant , clause , propagation_hashes) , ProofStep :: DeleteClause { clause , proof } => { check_delete_clause_step (ctx . borrow () , clause , proof) } ProofStep :: UnitClauses { units } => check_unit_clauses_step (ctx . borrow () , units) , ProofStep :: ChangeHashBits { bits } => { ctx . part_mut (ClauseHasherP) . hash_bits = bits ; rehash (ctx . borrow ()) ; Ok (()) } ProofStep :: Model { assignment } => check_model_step (ctx . borrow () , assignment) , ProofStep :: Assumptions { assumptions } => { for & lit in assumptions . iter () { ensure_sampling_var (ctx . borrow () , lit . var ()) ? ; } copy_canonical (& mut ctx . part_mut (CheckerStateP) . assumptions , assumptions) ; let (state , mut ctx) = ctx . split_part (CheckerStateP) ; process_step (ctx . borrow () , & CheckedProofStep :: Assumptions { assumptions : & state . assumptions , } ,) ? ; Ok (()) } ProofStep :: FailedAssumptions { failed_core , propagation_hashes , } => check_failed_assumptions_step (ctx . borrow () , failed_core , propagation_hashes) , ProofStep :: End => { ctx . part_mut (CheckerStateP) . ended = true ; Ok (()) } } ; if let Err (CheckerError :: CheckFailed { ref mut debug_step , .. }) = result { * debug_step = format ! ("{:?}" , step) } result }
};
}
