// Generated macro for impl_313 (impl)
macro_rules! Depcrate_hazardous_mac_hmacimpl_313 {
() => {
// Module: crate::hazardous::mac::hmac
// Provides: {"impl_313"}
// Dependencies: {}
impl < S : HmacHashFunction , const BLOCKSIZE : usize > Hmac < S , BLOCKSIZE > { # [doc = " Construct a state from a `secret_key`. The `secret_key` may be pre-padded or not."] # [doc = ""] # [doc = " Ref: https://brycx.github.io/2018/08/06/hmac-and-precomputation-optimization.html"] fn _new (secret_key : & [u8]) -> Result < Self , UnknownCryptoError > { debug_assert_eq ! (S :: _BLOCKSIZE , BLOCKSIZE) ; let mut ipad = [IPAD ; BLOCKSIZE] ; if secret_key . len () > BLOCKSIZE { debug_assert ! (BLOCKSIZE > S :: _OUTSIZE) ; S :: _digest (secret_key , & mut ipad [.. S :: _OUTSIZE]) ? ; for elem in ipad . iter_mut () . take (S :: _OUTSIZE) { * elem ^= IPAD ; } } else { xor_slices ! (secret_key , & mut ipad) ; } let mut ih = S :: _new () ; ih . _update (& ipad) ? ; for elem in ipad . iter_mut () { * elem ^= IPAD ^ OPAD ; } let mut oh = S :: _new () ; oh . _update (& ipad) ? ; ipad . iter_mut () . zeroize () ; Ok (Self { working_hasher : ih . clone () , opad_hasher : oh , ipad_hasher : ih , is_finalized : false , }) } fn _update (& mut self , data : & [u8]) -> Result < () , UnknownCryptoError > { if self . is_finalized { Err (UnknownCryptoError) } else { self . working_hasher . _update (data) } } fn _finalize (& mut self , dest : & mut [u8]) -> Result < () , UnknownCryptoError > { debug_assert ! (! dest . is_empty ()) ; if self . is_finalized { return Err (UnknownCryptoError) ; } self . is_finalized = true ; let mut outer_hasher = self . opad_hasher . clone () ; self . working_hasher . _finalize (dest) ? ; outer_hasher . _update (dest) ? ; outer_hasher . _finalize (dest) } fn _reset (& mut self) { self . working_hasher = self . ipad_hasher . clone () ; self . is_finalized = false ; } # [cfg (test)] # [doc = " Compare two Hmac state objects to check if their fields"] # [doc = " are the same."] pub (crate) fn compare_state_to_other (& self , other : & Self) { self . working_hasher . compare_state_to_other (& other . working_hasher) ; self . opad_hasher . compare_state_to_other (& other . opad_hasher) ; self . ipad_hasher . compare_state_to_other (& other . ipad_hasher) ; assert_eq ! (self . is_finalized , other . is_finalized) ; } }
};
}
