[package]
name = "split-decls-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
sha2 = "0.10"

[dependencies.anyhow]
workspace = true

[dependencies.cargo-toml-generator-macros]
workspace = true

[dependencies.cargo-toml-generator-types]
workspace = true

[dependencies.cargo-toml-parts]
workspace = true

[dependencies.clap]
features = ["derive"]
workspace = true

[dependencies.introspector_decl2_macros]
workspace = true

[dependencies.pagerank_rs]
workspace = true

[dependencies.proc-macro2]
features = ["span-locations"]
workspace = true

[dependencies.quote]
workspace = true

[dependencies.rayon]
workspace = true

[dependencies.serde]
workspace = true

[dependencies.serde_derive]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.split-decls-types]
workspace = true

[dependencies.syn]
features = ["full", "visit", "visit-mut", "extra-traits"]
workspace = true

[dependencies.tempfile]
workspace = true

[dependencies.toml]
workspace = true

[dependencies.url]
workspace = true

[dependencies.walkdir]
workspace = true

[dev-dependencies]

[build-dependencies.anyhow]
workspace = true

[build-dependencies.cargo-toml-generator-macros]
workspace = true

[build-dependencies.cargo-toml-generator-types]
workspace = true

[build-dependencies.cargo-toml-parts]
workspace = true

[build-dependencies.serde]
features = ["derive"]
workspace = true

[build-dependencies.serde_json]
workspace = true

[build-dependencies.syn]
features = ["full", "visit"]
workspace = true

[build-dependencies.toml]
workspace = true

[[bin]]
name = "rustmacrodoc"
path = "src/bin/rustmacrodoc.rs"

[[bin]]
name = "testbuild"
path = "src/bin/testbuild.rs"

[[bin]]
name = "macro_analyzer"
path = "src/bin/macro_analyzer.rs"

[[bin]]
name = "test_splitter"
path = "src/bin/test_splitter.rs"

[[bin]]
name = "submodule_decl_report"
path = "src/bin/submodule_decl_report.rs"

[[bin]]
name = "eigenmatrix_analyzer"
path = "src/bin/eigenmatrix_analyzer.rs"

[patch]
