// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Grammatical tool for displaying messages to end users in a nice form."]
#[doc = ""]
#[doc = " Take a list of items and a function to turn those items into a `String`, and output a display"]
#[doc = " friendly comma separated list of those items."]
pub fn listify<T>(list: &[T], fmt: impl Fn(&T) -> String) -> Option<String> {
    Some(match list {
        [only] => fmt(&only),
        [others @ .., last] => format!(
            "{} and {}",
            others.iter().map(|i| fmt(i)).collect::<Vec<_>>().join(", "),
            fmt(&last),
        ),
        [] => return None,
    })
}
