// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Represents the generated patches, grouped by their repository URL."]
#[doc = " The key is the repository URL (e.g., \"https://github.com/meta-introspector/time-rs\")."]
#[doc = " The value is a vector of `PatchEntry` for that repository."]
pub type GeneratedPatches = HashMap<String, Vec<PatchEntry>>;
