// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:71 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Defines a single string replacement operation."]
#[derive(Debug, Default, Serialize, Deserialize, Clone)]
pub struct StringReplacement {
    pub old: String,
    pub new: String,
}
