// Generated macro for impl_2327 (impl)
macro_rules! Depcrate_setimpl_2327 {
() => {
// Module: crate::set
// Provides: {"impl_2327"}
// Dependencies: {}
# [doc = " Various accessor methods."] impl < ObjectType : Message > NSSet < ObjectType > { # [doc = " Returns the number of elements in the set."] # [doc = ""] # [doc = " # Examples"] # [doc = ""] # [doc = " ```"] # [doc = " use objc2_foundation::{ns_string, NSSet};"] # [doc = ""] # [doc = " let strs = [ns_string!(\"one\"), ns_string!(\"two\"), ns_string!(\"three\")];"] # [doc = " let set = NSSet::from_slice(&strs);"] # [doc = " assert_eq!(set.len(), 3);"] # [doc = " ```"] # [doc (alias = "count")] pub fn len (& self) -> usize { self . count () } # [doc = " Returns `true` if the set contains no elements."] # [doc = ""] # [doc = " # Examples"] # [doc = ""] # [doc = " ```"] # [doc = " use objc2_foundation::{NSSet, NSObject};"] # [doc = ""] # [doc = " let set = NSSet::<NSObject>::new();"] # [doc = " assert!(set.is_empty());"] # [doc = " ```"] pub fn is_empty (& self) -> bool { self . count () == 0 } # [doc = " An iterator visiting all elements in arbitrary order."] # [doc = ""] # [doc = " # Examples"] # [doc = ""] # [doc = " ```"] # [doc = " use objc2_foundation::{ns_string, NSSet};"] # [doc = ""] # [doc = " let set = NSSet::from_slice(&[ns_string!(\"one\"), ns_string!(\"two\"), ns_string!(\"three\")]);"] # [doc = " for s in set.iter() {"] # [doc = "     println!(\"{s}\");"] # [doc = " }"] # [doc = " ```"] # [cfg (feature = "NSEnumerator")] # [doc (alias = "objectEnumerator")] # [inline] pub fn iter (& self) -> Iter < '_ , ObjectType > { Iter (super :: iter :: Iter :: new (self)) } # [doc = " Returns a [`Vec`] containing the set's elements in arbitrary order."] # [doc = ""] # [doc = " # Examples"] # [doc = ""] # [doc = " ```"] # [doc = " use objc2_foundation::{NSSet, NSString};"] # [doc = ""] # [doc = " let strs = ["] # [doc = "     NSString::from_str(\"one\"),"] # [doc = "     NSString::from_str(\"two\"),"] # [doc = "     NSString::from_str(\"three\"),"] # [doc = " ];"] # [doc = " let set = NSSet::from_retained_slice(&strs);"] # [doc = " let vec = set.to_vec();"] # [doc = " assert_eq!(vec.len(), 3);"] # [doc = " ```"] # [cfg (feature = "NSEnumerator")] pub fn to_vec (& self) -> Vec < Retained < ObjectType > > { self . iter () . collect () } }
};
}
