// Generated macro for RuntimeAccount (struct)
macro_rules! DepcrateRuntimeAccount {
() => {
// Module: crate
// Provides: {"RuntimeAccount"}
// Dependencies: {}
# [doc = " Raw account data."] # [doc = ""] # [doc = " This struct is wrapped by [`AccountView`], which provides safe access"] # [doc = " to account information. At runtime, the account's data is serialized"] # [doc = " directly after the `Account` struct in memory, with its size specified"] # [doc = " by [`RuntimeAccount::data_len`]."] # [repr (C)] # [cfg_attr (feature = "copy" , derive (Copy))] # [derive (Clone , Default)] pub struct RuntimeAccount { # [doc = " Borrow state for account data."] # [doc = ""] # [doc = " This reuses the memory reserved for the duplicate flag in the"] # [doc = " account to track data borrows. It represents the numbers of"] # [doc = " borrows available. The value `0` indicates that the account"] # [doc = " data is mutably borrowed, while values between `2` and `255`"] # [doc = " indicate the number of immutable borrows that can still be"] # [doc = " allocated. An account's data can only be mutably borrowed"] # [doc = " when there are no other active borrows, i.e., when this value"] # [doc = " is equal to [`NOT_BORROWED`]."] pub borrow_state : u8 , # [doc = " Indicates whether the transaction was signed by this account."] pub is_signer : u8 , # [doc = " Indicates whether the account is writable."] pub is_writable : u8 , # [doc = " Indicates whether this account represents a program."] pub executable : u8 , # [doc = " Difference between the original data length and the current"] # [doc = " data length."] # [doc = ""] # [doc = " This is used to track the original data length of the account"] # [doc = " when the account is resized. The runtime guarantees that this"] # [doc = " value is zero at the start of the instruction."] pub resize_delta : i32 , # [doc = " Address of the account."] pub address : Address , # [doc = " Program that owns this account. Modifiable by programs."] pub owner : Address , # [doc = " The lamports in the account. Modifiable by programs."] pub lamports : u64 , # [doc = " Length of the data. Modifiable by programs."] pub data_len : u64 , }
};
}
