// Generated macro for impl_86 (impl)
macro_rules! Depcrate_signingimpl_86 {
() => {
// Module: crate::signing
// Provides: {"impl_86"}
// Dependencies: {}
impl < C > SigningKey < C > where C : EcdsaCurve + CurveArithmetic , Scalar < C > : Invert < Output = CtOption < Scalar < C > > > , SignatureSize < C > : ArraySize , { # [doc = " Generate a cryptographically random [`SigningKey`]."] # [doc = ""] # [doc = " # Panics"] # [doc = ""] # [doc = " If the system's cryptographically secure RNG has an internal error."] # [cfg (feature = "getrandom")] pub fn generate () -> Self { NonZeroScalar :: < C > :: generate () . into () } # [doc = " Generate a cryptographically random [`SigningKey`], returning underlying RNG errors."] pub fn try_from_rng < R : TryCryptoRng + ? Sized > (rng : & mut R ,) -> core :: result :: Result < Self , R :: Error > { Ok (NonZeroScalar :: < C > :: try_from_rng (rng) ? . into ()) } # [doc = " Initialize signing key from a raw scalar serialized as a byte array."] pub fn from_bytes (bytes : & FieldBytes < C >) -> Result < Self > { SecretKey :: < C > :: from_bytes (bytes) . map (Into :: into) . map_err (| _ | Error :: new ()) } # [doc = " Initialize signing key from a raw scalar serialized as a byte slice."] pub fn from_slice (bytes : & [u8]) -> Result < Self > { SecretKey :: < C > :: from_slice (bytes) . map (Into :: into) . map_err (| _ | Error :: new ()) } # [doc = " Serialize this [`SigningKey`] as bytes"] pub fn to_bytes (& self) -> FieldBytes < C > { self . secret_scalar . to_repr () } # [doc = " Borrow the secret [`NonZeroScalar`] value for this key."] # [doc = ""] # [doc = " # ⚠\u{fe0f} Warning"] # [doc = ""] # [doc = " This value is key material."] # [doc = ""] # [doc = " Please treat it with the care it deserves!"] pub fn as_nonzero_scalar (& self) -> & NonZeroScalar < C > { & self . secret_scalar } # [doc = " Get the [`VerifyingKey`] which corresponds to this [`SigningKey`]."] # [cfg (feature = "algorithm")] pub fn verifying_key (& self) -> & VerifyingKey < C > { & self . verifying_key } }
};
}
