// Generated macro for build_proptest (function)
macro_rules! Depcrate_proptest_fnbuild_proptest {
() => {
// Module: crate::proptest_fn
// Provides: {"build_proptest"}
// Dependencies: {}
pub fn build_proptest (attr : TokenStream , mut item_fn : ItemFn) -> Result < TokenStream > { let mut attr_args = None ; if ! attr . is_empty () { attr_args = Some (parse2 :: < Args > (attr) ?) ; } let mut dump = false ; item_fn . attrs . retain (| attr | { if attr . path () . is_ident ("proptest_dump") { dump = true ; false } else { true } }) ; let (mut attr_args , config_args) = TestFnAttrArgs :: from (attr_args . unwrap_or_default ()) ? ; dump |= attr_args . dump ; let args_type_str = format ! ("_{}Args" , to_camel_case (& item_fn . sig . ident . to_string ())) ; let args_type_ident : Ident = parse_str (& args_type_str) . unwrap () ; let args = item_fn . sig . inputs . iter () . map (TestFnArg :: from) . collect :: < Result < Vec < _ > > > () ? ; let args_pats = args . iter () . map (| arg | arg . pat ()) ; let block = & item_fn . block ; if item_fn . sig . asyncness . is_none () { attr_args . r#async = None ; } let output = replace (& mut item_fn . sig . output , ReturnType :: Default) ; let block = if let Some (a) = attr_args . r#async { item_fn . sig . asyncness = None ; a . apply (block , output) } else { match output { ReturnType :: Default => quote ! (# block) , ReturnType :: Type (_ , ty) => { let f = Ident :: new ("__test_body" , Span :: mixed_site ()) ; quote ! ({ let # f = move || -> # ty { # block } ; :: std :: result :: Result :: map_err (# f () , | e | :: proptest :: test_runner :: TestCaseError :: fail (:: std :: string :: ToString :: to_string (& e))) ?; }) } } } ; let block = quote ! { { let # args_type_ident { # (# args_pats ,) * } = input ; # block } } ; item_fn . sig . inputs = parse_quote ! { input : # args_type_ident } ; item_fn . block = Box :: new (parse2 (block) ?) ; if ! item_fn . attrs . iter () . any (is_test_attribute) { let test_attr : Attribute = parse_quote ! { # [:: core :: prelude :: v1 :: test] } ; item_fn . attrs . push (test_attr) ; } let args_fields = args . iter () . map (| arg | & arg . field) ; let config = to_proptest_config (config_args) ; let ts = quote ! { # [cfg (test)] # [derive (test_strategy :: Arbitrary , Debug)] struct # args_type_ident { # (# args_fields ,) * } # [cfg (test)] proptest :: proptest ! { # config # item_fn } } ; if dump { panic ! ("{}" , ts) ; } Ok (ts) }
};
}
