// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Nix's main error type."]
#[doc = ""]
#[doc = " It's a wrapper around Errno.  As such, it's very interoperable with"]
#[doc = " [`std::io::Error`], but it has the advantages of:"]
#[doc = " * `Clone`"]
#[doc = " * `Copy`"]
#[doc = " * `Eq`"]
#[doc = " * Small size"]
#[doc = " * Represents all of the system's errnos, instead of just the most common"]
#[doc = "   ones."]
pub type Error = Errno;
