// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_expect_test_decls_HELP,
    wrapped_expect_test_decls_update_expect,
    wrapped_expect_test_decls_macro_rules,
    wrapped_expect_test_decls_macro_rules,
    wrapped_expect_test_decls_Expect,
    wrapped_expect_test_decls_ExpectFile,
    wrapped_expect_test_decls_Position,
    wrapped_expect_test_decls_impl_for_fmt_Display,
    wrapped_expect_test_decls_StrLitKind,
    wrapped_expect_test_decls_impl_for_StrLitKind,
    wrapped_expect_test_decls_impl_for_Expect,
    wrapped_expect_test_decls_locate_end,
    wrapped_expect_test_decls_find_str_lit_len,
    wrapped_expect_test_decls_impl_for_ExpectFile,
    wrapped_expect_test_decls_Runtime,
    wrapped_expect_test_decls_RT,
    wrapped_expect_test_decls_impl_for_Runtime,
    wrapped_expect_test_decls_FileRuntime,
    wrapped_expect_test_decls_impl_for_FileRuntime,
    wrapped_expect_test_decls_Location,
    wrapped_expect_test_decls_Patchwork,
    wrapped_expect_test_decls_impl_for_Patchwork,
    wrapped_expect_test_decls_lit_kind_for_patch,
    wrapped_expect_test_decls_format_patch,
    wrapped_expect_test_decls_to_abs_ws_path,
    wrapped_expect_test_decls_trim_indent,
    wrapped_expect_test_decls_lines_with_ends,
    wrapped_expect_test_decls_LinesWithEnds,
    wrapped_expect_test_decls_impl_for_Iterator,
    wrapped_expect_test_decls_format_chunks,
    wrapped_expect_test_decls_module_not_found_tests
);
