// MINIMAL TEST CASE for parsing failure in: ../rust/library/backtrace/src/windows_sys.rs
// Error: expected square brackets
// Problematic line: line 3

// Bindings generated by `windows-bindgen` 0.58.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
