// Generated macro for NT_GO_BUILD_ID (const)
macro_rules! Depcrate_elfNT_GO_BUILD_ID {
() => {
// Module: crate::elf
// Provides: {"NT_GO_BUILD_ID"}
// Dependencies: {}
# [doc = " Build ID bits as generated by Go's gc compiler."] # [doc = ""] # [doc = " The descriptor consists of any nonzero number of bytes."] pub const NT_GO_BUILD_ID : u32 = 4 ;
};
}
