// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_powerfmt_macros_decls_module_not_found_smart_display,
    wrapped_powerfmt_macros_decls_macro_rules,
    wrapped_powerfmt_macros_decls_attribute,
    wrapped_powerfmt_macros_decls_attribute
);
