// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter.rs:211 from submodules/split-decls-rs/src/eager_splitter.rs
// Do not edit this file by hand. Your changes will be overwritten.

#[llm_error_message(message = "Module file not found for: typeck_root_ctxt")]
#[llm_context(
    crate_name = "wrapped_rustc_hir_typeck",
    module_name = "typeck_root_ctxt"
)]
pub struct wrapped_rustc_hir_typeck_decls_module_not_found_typeck_root_ctxt;
