// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[proc_macro_derive(
    Subdiagnostic,
    attributes(
        label,
        help,
        help_once,
        note,
        note_once,
        warning,
        subdiagnostic,
        suggestion,
        suggestion_short,
        suggestion_hidden,
        suggestion_verbose,
        multipart_suggestion,
        multipart_suggestion_short,
        multipart_suggestion_hidden,
        multipart_suggestion_verbose,
        skip_arg,
        primary_span,
        suggestion_part,
        applicability
    )
)]
pub fn subdiagnostic_derive(input: TokenStream) -> TokenStream {
    let s = parse_macro_input!(input as DeriveInput);
    subdiagnostic::subdiagnostic_derive(Structure::new(&s)).into()
}
