// Generated macro for parse_file (function)
macro_rules! Depcrateparse_file {
() => {
// Module: crate
// Provides: {"parse_file"}
// Dependencies: {}
# [doc = " Parse the content of a file of Rust code."] # [doc = ""] # [doc = " This is different from `syn::parse_str::<File>(content)` in two ways:"] # [doc = ""] # [doc = " - It discards a leading byte order mark `\\u{FEFF}` if the file has one."] # [doc = " - It preserves the shebang line of the file, such as `#!/usr/bin/env rustx`."] # [doc = ""] # [doc = " If present, either of these would be an error using `from_str`."] # [doc = ""] # [doc = " # Examples"] # [doc = ""] # [doc = " ```no_run"] # [doc = " use std::error::Error;"] # [doc = " use std::fs;"] # [doc = " use std::io::Read;"] # [doc = ""] # [doc = " fn run() -> Result<(), Box<dyn Error>> {"] # [doc = "     let content = fs::read_to_string(\"path/to/code.rs\")?;"] # [doc = "     let ast = syn::parse_file(&content)?;"] # [doc = "     if let Some(shebang) = ast.shebang {"] # [doc = "         println!(\"{}\", shebang);"] # [doc = "     }"] # [doc = "     println!(\"{} items\", ast.items.len());"] # [doc = ""] # [doc = "     Ok(())"] # [doc = " }"] # [doc = " #"] # [doc = " # run().unwrap();"] # [doc = " ```"] # [cfg (all (feature = "parsing" , feature = "full"))] # [cfg_attr (docsrs , doc (cfg (all (feature = "parsing" , feature = "full"))))] pub fn parse_file (mut content : & str) -> Result < File > { const BOM : & str = "\u{feff}" ; if content . starts_with (BOM) { content = & content [BOM . len () ..] ; } let mut shebang = None ; if content . starts_with ("#!") { let rest = whitespace :: skip (& content [2 ..]) ; if ! rest . starts_with ('[') { if let Some (idx) = content . find ('\n') { shebang = Some (content [.. idx] . to_string ()) ; content = & content [idx ..] ; } else { shebang = Some (content . to_string ()) ; content = "" ; } } } let mut file : File = parse_str (content) ? ; file . shebang = shebang ; Ok (file) }
};
}
