// Generated macro for impl_694 (impl)
macro_rules! Depcrate_conn_kernelimpl_694 {
() => {
// Module: crate::conn::kernel
// Provides: {"impl_694"}
// Dependencies: {}
impl < Side > KernelConnection < Side > { pub (crate) fn new (state : Box < dyn KernelState > , common : CommonState) -> Result < Self , Error > { Ok (Self { state , peer_identity : common . peer_identity , quic : common . quic , negotiated_version : common . negotiated_version . ok_or (Error :: HandshakeNotComplete) ? , protocol : common . protocol , suite : common . suite . ok_or (Error :: HandshakeNotComplete) ? , _side : PhantomData , }) } # [doc = " Retrieves the cipher suite agreed with the peer."] pub fn negotiated_cipher_suite (& self) -> SupportedCipherSuite { self . suite } # [doc = " Retrieves the protocol version agreed with the peer."] pub fn protocol_version (& self) -> ProtocolVersion { self . negotiated_version } # [doc = " Update the traffic secret used for encrypting messages sent to the peer."] # [doc = ""] # [doc = " Returns the new traffic secret and initial sequence number to use."] # [doc = ""] # [doc = " In order to use the new secret you should send a TLS 1.3 key update to"] # [doc = " the peer and then use the new traffic secrets to encrypt any future"] # [doc = " messages."] # [doc = ""] # [doc = " Note that it is only possible to update the traffic secrets on a TLS 1.3"] # [doc = " connection. Attempting to do so on a non-TLS 1.3 connection will result"] # [doc = " in an error."] pub fn update_tx_secret (& mut self) -> Result < (u64 , ConnectionTrafficSecrets) , Error > { self . state . update_secrets (Direction :: Transmit) . map (| secret | (0 , secret)) } # [doc = " Update the traffic secret used for decrypting messages received from the"] # [doc = " peer."] # [doc = ""] # [doc = " Returns the new traffic secret and initial sequence number to use."] # [doc = ""] # [doc = " You should call this method once you receive a TLS 1.3 key update message"] # [doc = " from the peer."] # [doc = ""] # [doc = " Note that it is only possible to update the traffic secrets on a TLS 1.3"] # [doc = " connection. Attempting to do so on a non-TLS 1.3 connection will result"] # [doc = " in an error."] pub fn update_rx_secret (& mut self) -> Result < (u64 , ConnectionTrafficSecrets) , Error > { self . state . update_secrets (Direction :: Receive) . map (| secret | (0 , secret)) } }
};
}
