// Generated macro for impl_1545 (impl)
macro_rules! Depcrate_crypto_signerimpl_1545 {
() => {
// Module: crate::crypto::signer
// Provides: {"impl_1545"}
// Dependencies: {}
impl Credentials { # [doc = " Create a new [`Credentials`] from a certificate chain and DER-encoded private key."] # [doc = ""] # [doc = " Attempt to parse the private key with the given [`CryptoProvider`]'s [`KeyProvider`] and"] # [doc = " verify that it matches the public key in the first certificate of the `identity`"] # [doc = " if possible (if it is an `X509` identity)."] # [doc = ""] # [doc = " [`KeyProvider`]: crate::crypto::KeyProvider"] pub fn from_der (identity : Arc < Identity < 'static > > , key : PrivateKeyDer < 'static > , provider : & CryptoProvider ,) -> Result < Self , Error > { Self :: new (identity , provider . key_provider . load_private_key (key) ? ,) } # [doc = " Make a new [`Credentials`], with the given identity and key."] # [doc = ""] # [doc = " Yields [`Error::InconsistentKeys`] if the `identity` is `X509` and the end-entity certificate's subject"] # [doc = " public key info does not match that of the `key`'s public key, or if the `key` does not"] # [doc = " have a public key."] # [doc = ""] # [doc = " This constructor should be used with all [`SigningKey`] implementations"] # [doc = " that can provide a public key, including those provided by rustls itself."] pub fn new (identity : Arc < Identity < 'static > > , key : Box < dyn SigningKey >) -> Result < Self , Error > { if let Identity :: X509 (CertificateIdentity { end_entity , .. }) = & * identity { let parsed = ParsedCertificate :: try_from (end_entity) ? ; match (key . public_key () , parsed . subject_public_key_info ()) { (None , _) => return Err (Error :: InconsistentKeys (InconsistentKeys :: Unknown)) , (Some (key_spki) , cert_spki) if key_spki != cert_spki => { return Err (Error :: InconsistentKeys (InconsistentKeys :: KeyMismatch)) ; } _ => { } } } ; Ok (Self { identity , key , ocsp : None , }) } # [doc = " Make a new `Credentials` from a raw private key."] # [doc = ""] # [doc = " Unlike [`Credentials::new()`], this does not check that the end-entity certificate's"] # [doc = " subject key matches `key`'s public key."] # [doc = ""] # [doc = " This avoids parsing the end-entity certificate, which is useful when using client"] # [doc = " certificates that are not fully standards compliant, but known to usable by the peer."] pub fn new_unchecked (identity : Arc < Identity < 'static > > , key : Box < dyn SigningKey >) -> Self { Self { identity , key , ocsp : None , } } # [doc = " Attempt to produce a `SelectedCredential` using one of the given signature schemes."] # [doc = ""] # [doc = " Calls [`SigningKey::choose_scheme()`] and propagates `cert_chain` and `ocsp`."] pub fn signer (& self , sig_schemes : & [SignatureScheme]) -> Option < SelectedCredential > { Some (SelectedCredential { identity : self . identity . clone () , signer : self . key . choose_scheme (sig_schemes) ? , ocsp : self . ocsp . clone () , }) } }
};
}
