// Generated macro for GENERATED_BY (const)
macro_rules! Depcrate_capi_datetimeGENERATED_BY {
() => {
// Module: crate::capi_datetime
// Provides: {"GENERATED_BY"}
// Dependencies: {}
const GENERATED_BY : & str = std :: concat ! ("@generated by " , std :: file ! ()) ;
};
}
