[package]
name = "lib-metavar-expr"
version = "0.1.0"
edition = "2024"

[dependencies]
rustc_ast = { workspace = true }
rustc_ast_pretty = { workspace = true }
rustc_errors = { workspace = true }
rustc_macros = { workspace = true }
rustc_session = { workspace = true }
rustc_span = { workspace = true }
rustc_serialize = { workspace = true }
introspector_core = { workspace = true }
serde_json = { workspace = true }
