// Generated macro for other_871 (other)
macro_rules! Depcrate_user_notificationother_871 {
() => {
// Module: crate::user_notification
// Provides: {"other_871"}
// Dependencies: {}
unsafe extern "C" { pub static kCFUserNotificationIconURLKey : CFStringRef ; pub static kCFUserNotificationSoundURLKey : CFStringRef ; pub static kCFUserNotificationLocalizationURLKey : CFStringRef ; pub static kCFUserNotificationAlertHeaderKey : CFStringRef ; pub static kCFUserNotificationAlertMessageKey : CFStringRef ; pub static kCFUserNotificationDefaultButtonTitleKey : CFStringRef ; pub static kCFUserNotificationAlternateButtonTitleKey : CFStringRef ; pub static kCFUserNotificationOtherButtonTitleKey : CFStringRef ; pub static kCFUserNotificationProgressIndicatorValueKey : CFStringRef ; pub static kCFUserNotificationPopUpTitlesKey : CFStringRef ; pub static kCFUserNotificationTextFieldTitlesKey : CFStringRef ; pub static kCFUserNotificationCheckBoxTitlesKey : CFStringRef ; pub static kCFUserNotificationTextFieldValuesKey : CFStringRef ; pub static kCFUserNotificationPopUpSelectionKey : CFStringRef ; pub static kCFUserNotificationAlertTopMostKey : CFStringRef ; pub static kCFUserNotificationKeyboardTypesKey : CFStringRef ; pub fn CFUserNotificationCancel (userNotification : CFUserNotificationRef) -> SInt32 ; pub fn CFUserNotificationCreate (allocator : CFAllocatorRef , timeout : CFTimeInterval , flags : CFOptionFlags , error : * mut SInt32 , dictionary : CFDictionaryRef ,) -> CFUserNotificationRef ; pub fn CFUserNotificationCreateRunLoopSource (allocator : CFAllocatorRef , userNotification : CFUserNotificationRef , callout : CFUserNotificationCallBack , order : CFIndex ,) -> CFRunLoopSourceRef ; pub fn CFUserNotificationDisplayAlert (timeout : CFTimeInterval , flags : CFOptionFlags , iconURL : CFURLRef , soundURL : CFURLRef , localizationURL : CFURLRef , alertHeader : CFStringRef , alertMessage : CFStringRef , defaultButtonTitle : CFStringRef , alternateButtonTitle : CFStringRef , otherButtonTitle : CFStringRef , responseFlags : * mut CFOptionFlags ,) -> SInt32 ; pub fn CFUserNotificationDisplayNotice (timeout : CFTimeInterval , flags : CFOptionFlags , iconURL : CFURLRef , soundURL : CFURLRef , localizationURL : CFURLRef , alertHeader : CFStringRef , alertMessage : CFStringRef , defaultButtonTitle : CFStringRef ,) -> SInt32 ; pub fn CFUserNotificationGetTypeID () -> CFTypeID ; pub fn CFUserNotificationGetResponseDictionary (userNotification : CFUserNotificationRef ,) -> CFDictionaryRef ; pub fn CFUserNotificationGetResponseValue (userNotification : CFUserNotificationRef , key : CFStringRef , idx : CFIndex ,) -> CFStringRef ; pub fn CFUserNotificationReceiveResponse (userNotification : CFUserNotificationRef , timeout : CFTimeInterval , responseFlags : * mut CFOptionFlags ,) -> SInt32 ; pub fn CFUserNotificationUpdate (userNotification : CFUserNotificationRef , timeout : CFTimeInterval , flags : CFOptionFlags , dictionary : CFDictionaryRef ,) -> SInt32 ; }
};
}
