// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter.rs:211 from submodules/split-decls-rs/src/eager_splitter.rs
// Do not edit this file by hand. Your changes will be overwritten.

#[llm_error_message(message = "Module file not found for: index")]
#[llm_context(crate_name = "wrapped_cargo_util_schemas", module_name = "index")]
pub struct wrapped_cargo_util_schemas_decls_module_not_found_index;
