// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Trait implemented for supported block sizes, i.e. for types from `U1` to `U255`."]
pub trait BlockSizes: ArraySize + sealed::BlockSizes {}
