// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Types which use another type for initialization."]
#[doc = ""]
#[doc = " Generally it's used indirectly via [`InnerInit`] or [`InnerIvInit`]."]
pub trait InnerUser {
    #[doc = " Inner type."]
    type Inner;
}
