// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Types which can be initialized from another type (usually block ciphers)."]
#[doc = ""]
#[doc = " Usually used for initializing types from block ciphers."]
pub trait InnerInit: InnerUser + Sized {
    #[doc = " Initialize value from the `inner`."]
    fn inner_init(inner: Self::Inner) -> Self;
}
