// Generated macro for Args (struct)
macro_rules! Depcrate_wasm_bindgenArgs {
() => {
// Module: crate::wasm_bindgen
// Provides: {"Args"}
// Dependencies: {}
# [derive (Debug , Parser)] # [command (name = "wasm-bindgen" , version , about , after_help = "Additional documentation: https://wasm-bindgen.github.io/wasm-bindgen/reference/cli.html")] struct Args { input : PathBuf , # [arg (long , value_name = "TARGET" , value_enum , default_value_t = Target :: Bundler , help = "What type of output to generate" , group = "target-group")] target : Target , # [arg (long , value_name = "DIR" , help = "Output directory")] out_dir : PathBuf , # [arg (long , help = "Hint that JS should only be compatible with a browser" , group = "target-group")] browser : bool , # [arg (long , help = "Don't emit a *.d.ts file" , conflicts_with = "typescript")] no_typescript : bool , # [arg (long , help = "Don't emit imports in generated JavaScript")] omit_imports : bool , # [arg (long , value_name = "VAR" , help = "Set a custom output filename (Without extension. Defaults to crate name)")] out_name : Option < String > , # [arg (long , help = "Include otherwise-extraneous debug checks in output")] debug : bool , # [arg (long , help = "Don't demangle Rust symbol names")] no_demangle : bool , # [arg (long , value_name = "VAR" , help = "Name of the global variable to initialize")] no_modules_global : Option < String > , # [arg (long , help = "Remove the debugging `name` section of the file")] remove_name_section : bool , # [arg (long , help = "Remove the telemetry `producers` section")] remove_producers_section : bool , # [arg (long , help = "Keep exports synthesized by LLD")] keep_lld_exports : bool , # [arg (long , help = "Keep debug sections in Wasm files")] keep_debug : bool , # [arg (long , value_name = "MODE" , help = "Whether or not to use TextEncoder#encodeInto" , value_parser = ["test" , "always" , "never"])] encode_into : Option < String > , # [arg (long , help = "Don't add WebAssembly fallback imports in generated JavaScript")] omit_default_module_path : bool , # [arg (long , help = "Split linked modules out into their own files. Recommended if possible.\n\
                If a bundler is used, it needs to be set up accordingly.")] split_linked_modules : bool , # [arg (long = "experimental-reset-state-function" , help = "Generate __wbg_reset_state function for WASM reinitialization (experimental)")] generate_reset_state : bool , # [arg (long , hide = true)] # [deprecated (note = "implied default, only `--no-typescript` is needed")] typescript : bool , # [arg (long , hide = true , group = "target-group")] # [deprecated (note = "use `Args::target` instead")] nodejs : bool , # [arg (long , hide = true , group = "target-group")] # [deprecated (note = "use `Args::target` instead")] web : bool , # [arg (long , hide = true , group = "target-group")] # [deprecated (note = "use `Args::target` instead")] no_modules : bool , # [arg (long , hide = true)] # [deprecated (note = "runtime-detected")] # [allow (dead_code)] weak_refs : bool , # [arg (long , hide = true)] # [deprecated (note = "automatically inferred from the Wasm features")] reference_types : bool , }
};
}
