// Generated macro for methods (macro)
macro_rules! Depcrate_parsermethods {
() => {
// Module: crate::parser
// Provides: {"methods"}
// Dependencies: {}
macro_rules ! methods { ($ (($ name : ident , $ invalid_unused : literal , $ variant : ident ($ ($ contents : tt) *)) ,) *) => { $ (methods ! (@ method $ name , $ variant ($ ($ contents) *)) ;) * fn enforce_used (self) -> Result < () , Diagnostic > { ATTRS . with (| state | state . checks . set (state . checks . get () + 1)) ; let mut errors = Vec :: new () ; for (used , attr) in self . attrs . iter () { if used . get () { continue } let span = match attr { $ (BindgenAttr ::$ variant (span , ..) => span ,) * } ; errors . push (Diagnostic :: span_error (* span , "unused wasm_bindgen attribute")) ; } Diagnostic :: from_vec (errors) } fn check_used (self) { ATTRS . with (| state | { state . checks . set (state . checks . get () + 1) ; state . unused_attrs . borrow_mut () . extend (self . attrs . iter () . filter_map (| (used , attr) | if used . get () { None } else { Some (attr) }) . map (| attr | { match attr { $ (BindgenAttr ::$ variant (span , ..) => { UnusedState { error : $ invalid_unused , ident : syn :: parse_quote_spanned ! (* span => $ name) } }) * } })) ; }) ; } } ; (@ method $ name : ident , $ variant : ident (Span , String , Span)) => { pub (crate) fn $ name (& self) -> Option < (& str , Span) > { self . attrs . iter () . find_map (| a | match & a . 1 { BindgenAttr ::$ variant (_ , s , span) => { a . 0 . set (true) ; Some ((& s [..] , * span)) } _ => None , }) } } ; (@ method $ name : ident , $ variant : ident (Span , JsNamespace , Vec < Span >)) => { pub (crate) fn $ name (& self) -> Option < (JsNamespace , & [Span]) > { self . attrs . iter () . find_map (| a | match & a . 1 { BindgenAttr ::$ variant (_ , ss , spans) => { a . 0 . set (true) ; Some ((ss . clone () , & spans [..])) } _ => None , }) } } ; (@ method $ name : ident , $ variant : ident (Span , $ ($ other : tt) *)) => { # [allow (unused)] pub (crate) fn $ name (& self) -> Option <&$ ($ other) *> { self . attrs . iter () . find_map (| a | match & a . 1 { BindgenAttr ::$ variant (_ , s) => { a . 0 . set (true) ; Some (s) } _ => None , }) } } ; (@ method $ name : ident , $ variant : ident ($ ($ other : tt) *)) => { # [allow (unused)] pub (crate) fn $ name (& self) -> Option <&$ ($ other) *> { self . attrs . iter () . find_map (| a | match & a . 1 { BindgenAttr ::$ variant (s) => { a . 0 . set (true) ; Some (s) } _ => None , }) } } ; }
};
}
