[package]
name = "lib-matcher-loc"
version = "0.1.0"
edition = "2024"

[dependencies]
rustc_span = { workspace = true }
rustc_ast = { workspace = true } # For Token, TokenKind, NonterminalKind
rustc_data_structures = { workspace = true } # For FxHashMap and static_assert_size
rustc_serialize = { workspace = true }
lib-kleene-op = { path = "../lib-kleene-op" }
lib-token-tree = { path = "../lib-token-tree" }
