// Generated macro for impl_108 (impl)
macro_rules! Depcrate_crypt_provimpl_108 {
() => {
// Module: crate::crypt_prov
// Provides: {"impl_108"}
// Dependencies: {}
impl < 'a > ImportOptions < 'a > { # [doc = " Imports a DER-encoded PKCS1 private key."] pub fn import (& mut self , der : & [u8]) -> io :: Result < CryptKey > { unsafe { assert ! (der . len () <= u32 :: max_value () as usize) ; let mut buf = ptr :: null_mut () ; let mut len = 0 ; let res = Cryptography :: CryptDecodeObjectEx (Cryptography :: X509_ASN_ENCODING | Cryptography :: PKCS_7_ASN_ENCODING , Cryptography :: PKCS_RSA_PRIVATE_KEY , der . as_ptr () , der . len () as u32 , Cryptography :: CRYPT_DECODE_ALLOC_FLAG , ptr :: null_mut () , & mut buf as * mut _ as * mut c_void , & mut len ,) ; if res == 0 { return Err (io :: Error :: last_os_error ()) ; } let mut key = 0 ; let res = Cryptography :: CryptImportKey (self . prov . 0 , buf , len , 0 , self . flags , & mut key) ; Foundation :: LocalFree (buf as * mut _) ; if res != 0 { Ok (CryptKey :: from_inner (key)) } else { Err (io :: Error :: last_os_error ()) } } } # [doc = " Imports a DER-encoded PKCS8 private key."] pub fn import_pkcs8 (& mut self , der : & [u8]) -> io :: Result < CryptKey > { unsafe { assert ! (der . len () <= u32 :: max_value () as usize) ; let mut buf = ptr :: null_mut () ; let mut len = 0 ; let res = Cryptography :: CryptDecodeObjectEx (Cryptography :: X509_ASN_ENCODING | Cryptography :: PKCS_7_ASN_ENCODING , Cryptography :: PKCS_PRIVATE_KEY_INFO , der . as_ptr () , der . len () as u32 , Cryptography :: CRYPT_DECODE_ALLOC_FLAG , ptr :: null_mut () , & mut buf as * mut _ as * mut c_void , & mut len ,) ; if res == 0 { return Err (io :: Error :: last_os_error ()) ; } let pkey : Cryptography :: CRYPT_PRIVATE_KEY_INFO = * buf ; let pkey = pkey . PrivateKey ; let res = self . import (slice :: from_raw_parts (pkey . pbData , pkey . cbData as usize)) ; Foundation :: LocalFree (buf as * mut _) ; res } } # [doc = " Imports a PEM-encoded PKCS8 private key."] # [doc = " This functions decodes PEM blocks with or without \"-----BEGIN PRIVATE KEY-----\""] # [doc = " and \"-----END PRIVATE KEY-----\" headers, but if PEM guards are present they must be exactly"] # [doc = " these."] pub fn import_pkcs8_pem (& mut self , pem : & [u8]) -> io :: Result < CryptKey > { let pem_str = std :: str :: from_utf8 (pem) . map_err (| _ | io :: Error :: new (io :: ErrorKind :: InvalidData , "invalid utf-8")) ? . trim () ; if pem_str . starts_with ("-----") && (! pem_str . starts_with ("-----BEGIN PRIVATE KEY-----") || ! pem_str . ends_with ("-----END PRIVATE KEY-----")) { return Err (io :: Error :: new (io :: ErrorKind :: InvalidData , "expected '-----BEGIN PRIVATE KEY-----'\
                                          and '-----END PRIVATE KEY-----' PEM guards" ,)) ; } unsafe { assert ! (pem . len () <= u32 :: max_value () as usize) ; let mut len = 0 ; let res = Cryptography :: CryptStringToBinaryA (pem . as_ptr () , pem . len () as u32 , Cryptography :: CRYPT_STRING_BASE64_ANY , ptr :: null_mut () , & mut len , ptr :: null_mut () , ptr :: null_mut () ,) ; if res == 0 { return Err (io :: Error :: last_os_error ()) ; } let mut der_buf = vec ! [0 ; len as usize] ; let res = Cryptography :: CryptStringToBinaryA (pem . as_ptr () , pem . len () as u32 , Cryptography :: CRYPT_STRING_BASE64_ANY , der_buf . as_mut_ptr () , & mut len , ptr :: null_mut () , ptr :: null_mut () ,) ; if res == 0 { return Err (io :: Error :: last_os_error ()) ; } self . import_pkcs8 (& der_buf) } } }
};
}
