[package]
name = "cargo-toml-generator-types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace=true, features = ["derive"] }
toml = { workspace = true }
serde_json =  { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace=true, features = ["full", "extra-traits"] }

[build-dependencies]
anyhow = { workspace = true }
syn = { workspace = true, features = ["full", "visit"] }
serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }