// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs:29 from submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs 
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros :: decl_module ; decl_module ! (wrapped_serde_core_decls_crate_root , wrapped_serde_core_decls_module_not_found_crate_root , wrapped_serde_core_decls_macros , wrapped_serde_core_decls_module_not_found_macros , wrapped_serde_core_decls_crate_root , wrapped_serde_core_decls_macro_rules) ;