// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter.rs:211 from submodules/split-decls-rs/src/eager_splitter.rs
// Do not edit this file by hand. Your changes will be overwritten.

#[llm_error_message(message = "Module file not found for: t_define_expansion_context_types_exts")]
#[llm_context(
    crate_name = "wrapped_rustc_expand_base_lib",
    module_name = "t_define_expansion_context_types_exts"
)]
pub struct wrapped_rustc_expand_base_lib_decls_module_not_found_t_define_expansion_context_types_exts;
