// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter.rs:211 from submodules/split-decls-rs/src/eager_splitter.rs
// Do not edit this file by hand. Your changes will be overwritten.

#[llm_error_message(message = "Module file not found for: lint_store_expand_dyn_def")]
#[llm_context(
    crate_name = "wrapped_rustc_expand_base_lib",
    module_name = "lint_store_expand_dyn_def"
)]
pub struct wrapped_rustc_expand_base_lib_decls_module_not_found_lint_store_expand_dyn_def;
