// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
impl Interface {
    #[doc = " Generates all the code needed for a COM interface"]
    fn gen_tokens(&self, guid: &Guid) -> syn::Result<proc_macro2::TokenStream> {
        let vis = &self.visibility;
        let name = &self.name;
        let docs = &self.docs;
        let parent = self.parent_type();
        let vtable_name = quote::format_ident!("{}_Vtbl", name);
        let guid = guid.to_tokens()?;
        let implementation = self.gen_implementation();
        let com_trait = self.get_com_trait();
        let vtable = self.gen_vtable(&vtable_name);
        let conversions = self.gen_conversions();
        Ok(
            quote! { # [repr (transparent)] # (# docs) * # vis struct # name (# parent) ; # implementation unsafe impl :: windows_core :: Interface for # name { type Vtable = # vtable_name ; const IID : :: windows_core :: GUID = # guid ; } impl :: windows_core :: RuntimeName for # name { } impl :: core :: ops :: Deref for # name { type Target = # parent ; fn deref (& self) -> & Self :: Target { unsafe { :: core :: mem :: transmute (self) } } } # com_trait # vtable # conversions },
        )
    }
    #[doc = " Generates the methods users can call on the COM interface pointer"]
    fn gen_implementation(&self) -> proc_macro2::TokenStream {
        let name = &self.name;
        let methods = self . methods . iter () . map (| m | { let vis = & m . visibility ; let name = & m . name ; let generics = m . gen_consume_generics () ; let params = m . gen_consume_params () ; let args = m . gen_consume_args () ; let ret = & m . ret ; if m . is_result () { quote ! { # [inline (always)] # vis unsafe fn # name <# (# generics) ,*> (& self , # (# params) ,*) # ret { (:: windows_core :: Interface :: vtable (self) .# name) (:: windows_core :: Interface :: as_raw (self) , # (# args) ,*) . ok () } } } else { quote ! { # [inline (always)] # vis unsafe fn # name <# (# generics) ,*> (& self , # (# params) ,*) # ret { (:: windows_core :: Interface :: vtable (self) .# name) (:: windows_core :: Interface :: as_raw (self) , # (# args) ,*) } } } }) . collect :: < Vec < _ > > () ;
        quote! { impl # name { # (# methods) * } }
    }
    fn get_com_trait(&self) -> proc_macro2::TokenStream {
        let name = quote::format_ident!("{}_Impl", self.name);
        let vis = &self.visibility;
        let methods = self
            .methods
            .iter()
            .map(|m| {
                let name = &m.name;
                let docs = &m.docs;
                let args = m.gen_args();
                let ret = &m.ret;
                quote! { # (# docs) * unsafe fn # name (& self , # (# args) ,*) # ret ; }
            })
            .collect::<Vec<_>>();
        let parent = self.parent_trait_constraint();
        quote! { # [allow (non_camel_case_types)] # vis trait # name : Sized + # parent { # (# methods) * } }
    }
    #[doc = " Generates the vtable for a COM interface"]
    fn gen_vtable(&self, vtable_name: &syn::Ident) -> proc_macro2::TokenStream {
        let vis = &self.visibility;
        let name = &self.name;
        let trait_name = quote::format_ident!("{}_Impl", name);
        let implvtbl_name = quote::format_ident!("{}_ImplVtbl", name);
        let vtable_entries = self . methods . iter () . map (| m | { let name = & m . name ; let ret = & m . ret ; let args = m . gen_args () ; if m . is_result () { quote ! { pub # name : unsafe extern "system" fn (this : * mut :: core :: ffi :: c_void , # (# args) ,*) -> :: windows_core :: HRESULT , } } else { quote ! { pub # name : unsafe extern "system" fn (this : * mut :: core :: ffi :: c_void , # (# args) ,*) # ret , } } }) . collect :: < Vec < _ > > () ;
        let parent_vtable_generics = quote!(Identity, OFFSET);
        let parent_vtable = self.parent_vtable();
        let or_parent_matches = match parent_vtable.as_ref() {
            Some(parent) if !self.parent_is_iunknown() => quote ! (|| <# parent >:: matches (iid)),
            _ => quote!(),
        };
        let functions = self . methods . iter () . map (| m | { let name = & m . name ; let args = m . gen_args () ; let params = & m . args . iter () . map (| a | { let pat = & a . pat ; quote ! { # pat } }) . collect :: < Vec < _ > > () ; let ret = & m . ret ; let ret = if m . is_result () { quote ! { -> :: windows_core :: HRESULT } } else { quote ! { # ret } } ; if parent_vtable . is_some () { quote ! { unsafe extern "system" fn # name < Identity : :: windows_core :: IUnknownImpl , const OFFSET : isize > (this : * mut :: core :: ffi :: c_void , # (# args) ,*) # ret where Identity : # trait_name { let this_outer : & Identity = &* ((this as * const * const ()) . offset (OFFSET) as * const Identity) ; < Identity as # trait_name >::# name (this_outer , # (# params) ,*) . into () } } } else { quote ! { unsafe extern "system" fn # name < Impl : # trait_name > (this : * mut :: core :: ffi :: c_void , # (# args) ,*) # ret { let this = (this as * mut * mut :: core :: ffi :: c_void) as * const :: windows_core :: ScopedHeap ; let this = (* this) . this as * const Impl ; (* this) .# name (# (# params) ,*) . into () } } } }) . collect :: < Vec < _ > > () ;
        if let Some(parent_vtable) = parent_vtable {
            let entries = self
                .methods
                .iter()
                .map(|m| {
                    let name = &m.name;
                    quote ! (# name : # name ::< Identity , OFFSET >)
                })
                .collect::<Vec<_>>();
            quote! { # [repr (C)] # [doc (hidden)] # vis struct # vtable_name { pub base__ : # parent_vtable , # (# vtable_entries) * } impl # vtable_name { pub const fn new < Identity : :: windows_core :: IUnknownImpl , const OFFSET : isize , > () -> Self where Identity : # trait_name { # (# functions) * Self { base__ : # parent_vtable :: new ::<# parent_vtable_generics > () , # (# entries) ,* } } # [inline (always)] pub fn matches (iid : &:: windows_core :: GUID) -> bool { * iid == <# name as :: windows_core :: Interface >:: IID # or_parent_matches } } }
        } else {
            let entries = self
                .methods
                .iter()
                .map(|m| {
                    let name = &m.name;
                    quote ! (# name : # name ::< Impl >)
                })
                .collect::<Vec<_>>();
            quote! { # [repr (C)] # [doc (hidden)] # vis struct # vtable_name { # (# vtable_entries) * } impl # vtable_name { pub const fn new < Impl : # trait_name > () -> Self { # (# functions) * Self { # (# entries) ,* } } } struct # implvtbl_name < T : # trait_name > (:: core :: marker :: PhantomData < T >) ; impl < T : # trait_name > # implvtbl_name < T > { const VTABLE : # vtable_name = # vtable_name :: new ::< T > () ; } impl # name { fn new <'a , T : # trait_name > (this : &'a T) -> :: windows_core :: ScopedInterface <'a , # name > { let this = :: windows_core :: ScopedHeap { vtable : &# implvtbl_name ::< T >:: VTABLE as * const _ as * const _ , this : this as * const _ as * const _ } ; let this = :: core :: mem :: ManuallyDrop :: new (:: windows_core :: imp :: Box :: new (this)) ; unsafe { :: windows_core :: ScopedInterface :: new (:: core :: mem :: transmute (& this . vtable)) } } } }
        }
    }
    #[doc = " Generates various conversions such as from and to `IUnknown`"]
    fn gen_conversions(&self) -> proc_macro2::TokenStream {
        let name = &self.name;
        let name_string = format!("{name}");
        quote! { impl :: core :: convert :: From <# name > for :: windows_core :: IUnknown { fn from (value : # name) -> Self { unsafe { :: core :: mem :: transmute (value) } } } impl :: core :: convert :: From <&# name > for :: windows_core :: IUnknown { fn from (value : &# name) -> Self { :: core :: convert :: From :: from (:: core :: clone :: Clone :: clone (value)) } } impl :: core :: clone :: Clone for # name { fn clone (& self) -> Self { Self (self . 0 . clone ()) } } impl :: core :: cmp :: PartialEq for # name { fn eq (& self , other : & Self) -> bool { self . 0 == other . 0 } } impl :: core :: cmp :: Eq for # name { } impl :: core :: fmt :: Debug for # name { fn fmt (& self , f : & mut :: core :: fmt :: Formatter) -> :: core :: fmt :: Result { f . debug_tuple (# name_string) . field (&:: windows_core :: Interface :: as_raw (self)) . finish () } } }
    }
    fn parent_type(&self) -> proc_macro2::TokenStream {
        if let Some(parent) = &self.parent {
            quote ! (# parent)
        } else {
            quote!(::core::ptr::NonNull<::core::ffi::c_void>)
        }
    }
    fn parent_vtable(&self) -> Option<proc_macro2::TokenStream> {
        if let Some((ident, path)) = self.parent_path().split_last() {
            let ident = quote::format_ident!("{}_Vtbl", ident);
            Some(quote! { # (# path ::) * # ident })
        } else {
            None
        }
    }
    fn parent_is_iunknown(&self) -> bool {
        if let Some(ident) = self.parent_path().last() {
            ident == "IUnknown"
        } else {
            false
        }
    }
    fn parent_path(&self) -> Vec<syn::Ident> {
        if let Some(parent) = &self.parent {
            parent
                .segments
                .iter()
                .map(|segment| segment.ident.clone())
                .collect()
        } else {
            vec![]
        }
    }
    #[doc = " Gets the parent trait constraint which is nothing if the parent is IUnknown"]
    fn parent_trait_constraint(&self) -> proc_macro2::TokenStream {
        if let Some((ident, path)) = self.parent_path().split_last() {
            if ident != "IUnknown" {
                let ident = quote::format_ident!("{}_Impl", ident);
                return quote! { # (# path ::) * # ident };
            }
        }
        quote! {}
    }
}
