// Generated macro for Length (enum)
macro_rules! Depcrate_optionsLength {
() => {
// Module: crate::options
// Provides: {"Length"}
// Dependencies: {}
# [doc = " The length of a formatted date/time string."] # [doc = ""] # [doc = " Length settings are always a hint, not a guarantee. For example, certain locales and"] # [doc = " calendar systems do not define numeric names, so spelled-out names could occur even if a"] # [doc = " short length was requested, and likewise with numeric names with a medium or long length."] # [doc = ""] # [doc = " # Examples"] # [doc = ""] # [doc = " ```"] # [doc = " use icu::calendar::Gregorian;"] # [doc = " use icu::datetime::fieldsets::YMD;"] # [doc = " use icu::datetime::input::Date;"] # [doc = " use icu::datetime::FixedCalendarDateTimeFormatter;"] # [doc = " use icu::locale::locale;"] # [doc = " use writeable::assert_writeable_eq;"] # [doc = ""] # [doc = " let short_formatter = FixedCalendarDateTimeFormatter::try_new("] # [doc = "     locale!(\"en-US\").into(),"] # [doc = "     YMD::short(),"] # [doc = " )"] # [doc = " .unwrap();"] # [doc = ""] # [doc = " let medium_formatter = FixedCalendarDateTimeFormatter::try_new("] # [doc = "     locale!(\"en-US\").into(),"] # [doc = "     YMD::medium(),"] # [doc = " )"] # [doc = " .unwrap();"] # [doc = ""] # [doc = " let long_formatter = FixedCalendarDateTimeFormatter::try_new("] # [doc = "     locale!(\"en-US\").into(),"] # [doc = "     YMD::long(),"] # [doc = " )"] # [doc = " .unwrap();"] # [doc = ""] # [doc = " assert_writeable_eq!("] # [doc = "     short_formatter.format(&Date::try_new_gregorian(2000, 1, 1).unwrap()),"] # [doc = "     \"1/1/00\""] # [doc = " );"] # [doc = ""] # [doc = " assert_writeable_eq!("] # [doc = "     medium_formatter.format(&Date::try_new_gregorian(2000, 1, 1).unwrap()),"] # [doc = "     \"Jan 1, 2000\""] # [doc = " );"] # [doc = ""] # [doc = " assert_writeable_eq!("] # [doc = "     long_formatter.format(&Date::try_new_gregorian(2000, 1, 1).unwrap()),"] # [doc = "     \"January 1, 2000\""] # [doc = " );"] # [doc = " ```"] # [derive (Debug , Copy , Clone , PartialEq , Eq , Hash , Default)] # [cfg_attr (all (feature = "serde" , feature = "experimental") , derive (serde :: Serialize , serde :: Deserialize))] # [cfg_attr (all (feature = "serde" , feature = "experimental") , serde (rename_all = "lowercase"))] # [non_exhaustive] pub enum Length { # [doc = " A long date; typically spelled-out, as in “January 1, 2000”."] Long , # [doc = " A medium-sized date; typically abbreviated, as in “Jan. 1, 2000”."] # [doc = ""] # [doc = " This is the default."] # [default] Medium , # [doc = " A short date; typically numeric, as in “1/1/2000”."] Short , }
};
}
