// Generated macro for hex_digit1 (function)
macro_rules! Depcrate_asciihex_digit1 {
() => {
// Module: crate::ascii
// Provides: {"hex_digit1"}
// Dependencies: {}
# [doc = " Recognizes one or more ASCII hexadecimal numerical characters: `'0'..='9'`, `'A'..='F'`,"] # [doc = " `'a'..='f'`"] # [doc = ""] # [doc = " *Complete version*: Will return an error if there's not enough input data,"] # [doc = " or the whole input if no terminating token is found (a non hexadecimal digit character)."] # [doc = ""] # [doc = " *[Partial version][crate::_topic::partial]*: Will return `Err(winnow::error::ErrMode::Incomplete(_))` if there's not enough input data,"] # [doc = " or if no terminating token is found (a non hexadecimal digit character)."] # [doc = ""] # [doc = " # Effective Signature"] # [doc = ""] # [doc = " Assuming you are parsing a `&str` [Stream]:"] # [doc = " ```rust"] # [doc = " # use winnow::prelude::*;;"] # [doc = " pub fn hex_digit1<'i>(input: &mut &'i str) -> ModalResult<&'i str>"] # [doc = " # {"] # [doc = " #     winnow::ascii::hex_digit1.parse_next(input)"] # [doc = " # }"] # [doc = " ```"] # [doc = ""] # [doc = " # Example"] # [doc = ""] # [doc = " ```rust"] # [doc = " # use winnow::prelude::*;"] # [doc = " # use winnow::ascii::hex_digit1;"] # [doc = " fn parser<'s>(input: &mut &'s str) -> ModalResult<&'s str> {"] # [doc = "     hex_digit1.parse_next(input)"] # [doc = " }"] # [doc = ""] # [doc = " assert_eq!(parser.parse_peek(\"21cZ\"), Ok((\"Z\", \"21c\")));"] # [doc = " assert!(parser.parse_peek(\"H2\").is_err());"] # [doc = " assert!(parser.parse_peek(\"\").is_err());"] # [doc = " ```"] # [doc = ""] # [doc = " ```rust"] # [doc = " # use winnow::prelude::*;"] # [doc = " # use winnow::{error::ErrMode, error::ContextError, error::Needed};"] # [doc = " # use winnow::Partial;"] # [doc = " # use winnow::ascii::hex_digit1;"] # [doc = " assert_eq!(hex_digit1::<_, ErrMode<ContextError>>.parse_peek(Partial::new(\"21cZ\")), Ok((Partial::new(\"Z\"), \"21c\")));"] # [doc = " assert!(hex_digit1::<_, ErrMode<ContextError>>.parse_peek(Partial::new(\"H2\")).is_err());"] # [doc = " assert_eq!(hex_digit1::<_, ErrMode<ContextError>>.parse_peek(Partial::new(\"\")), Err(ErrMode::Incomplete(Needed::new(1))));"] # [doc = " ```"] # [inline (always)] pub fn hex_digit1 < Input , Error > (input : & mut Input) -> Result < < Input as Stream > :: Slice , Error > where Input : StreamIsPartial + Stream , < Input as Stream > :: Token : AsChar , Error : ParserError < Input > , { trace ("hex_digit1" , take_while (1 .. , AsChar :: is_hex_digit)) . parse_next (input) }
};
}
