// Generated macro for length_take (function)
macro_rules! Depcrate_binarylength_take {
() => {
// Module: crate::binary
// Provides: {"length_take"}
// Dependencies: {}
# [doc = " Get a length-prefixed slice ([TLV](https://en.wikipedia.org/wiki/Type-length-value))"] # [doc = ""] # [doc = " To apply a parser to the returned slice, see [`length_and_then`]."] # [doc = ""] # [doc = " If the count is for something besides tokens, see [`length_repeat`]."] # [doc = ""] # [doc = " *Complete version*: Returns an error if there is not enough input data."] # [doc = ""] # [doc = " *[Partial version][crate::_topic::partial]*: Will return `Err(winnow::error::ErrMode::Incomplete(_))` if there is not enough data."] # [doc = ""] # [doc = " # Example"] # [doc = ""] # [doc = " ```rust"] # [doc = " # use winnow::{error::ErrMode, error::Needed, stream::Partial};"] # [doc = " # use winnow::prelude::*;"] # [doc = " use winnow::Bytes;"] # [doc = " use winnow::binary::be_u16;"] # [doc = " use winnow::binary::length_take;"] # [doc = ""] # [doc = " type Stream<'i> = Partial<&'i Bytes>;"] # [doc = ""] # [doc = " fn stream(b: &[u8]) -> Stream<'_> {"] # [doc = "     Partial::new(Bytes::new(b))"] # [doc = " }"] # [doc = ""] # [doc = " fn parser<'i>(s: &mut Stream<'i>) -> ModalResult<&'i [u8]> {"] # [doc = "   length_take(be_u16).parse_next(s)"] # [doc = " }"] # [doc = ""] # [doc = " assert_eq!(parser.parse_peek(stream(b\"\\x00\\x03abcefg\")), Ok((stream(&b\"efg\"[..]), &b\"abc\"[..])));"] # [doc = " assert_eq!(parser.parse_peek(stream(b\"\\x00\\x03a\")), Err(ErrMode::Incomplete(Needed::new(2))));"] # [doc = " ```"] pub fn length_take < Input , Count , Error , CountParser > (mut count : CountParser ,) -> impl Parser < Input , < Input as Stream > :: Slice , Error > where Input : StreamIsPartial + Stream , Count : ToUsize , CountParser : Parser < Input , Count , Error > , Error : ParserError < Input > , { trace ("length_take" , move | i : & mut Input | { let length = count . parse_next (i) ? ; crate :: token :: take (length) . parse_next (i) }) }
};
}
