// Generated macro for be_f32 (function)
macro_rules! Depcrate_binarybe_f32 {
() => {
// Module: crate::binary
// Provides: {"be_f32"}
// Dependencies: {}
# [doc = " Recognizes a big endian 4 bytes floating point number."] # [doc = ""] # [doc = " *Complete version*: Returns an error if there is not enough input data."] # [doc = ""] # [doc = " *[Partial version][crate::_topic::partial]*: Will return `Err(winnow::error::ErrMode::Incomplete(_))` if there is not enough data."] # [doc = ""] # [doc = " # Example"] # [doc = ""] # [doc = " ```rust"] # [doc = " # use winnow::{error::ErrMode, error::InputError, error::Needed};"] # [doc = " # use winnow::prelude::*;"] # [doc = " # use winnow::prelude::*;"] # [doc = " # use winnow::error::Needed::Size;"] # [doc = " use winnow::binary::be_f32;"] # [doc = ""] # [doc = " fn parser(s: &mut &[u8]) -> ModalResult<f32> {"] # [doc = "       be_f32.parse_next(s)"] # [doc = " }"] # [doc = ""] # [doc = " assert_eq!(parser.parse_peek(&[0x41, 0x48, 0x00, 0x00][..]), Ok((&b\"\"[..], 12.5)));"] # [doc = " assert!(parser.parse_peek(&b\"abc\"[..]).is_err());"] # [doc = " ```"] # [doc = ""] # [doc = " ```rust"] # [doc = " # use winnow::{error::ErrMode, error::InputError, error::Needed};"] # [doc = " # use winnow::prelude::*;"] # [doc = " # use winnow::Partial;"] # [doc = " use winnow::binary::be_f32;"] # [doc = ""] # [doc = " fn parser(s: &mut Partial<&[u8]>) -> ModalResult<f32> {"] # [doc = "       be_f32.parse_next(s)"] # [doc = " }"] # [doc = ""] # [doc = " assert_eq!(parser.parse_peek(Partial::new(&[0x40, 0x29, 0x00, 0x00][..])), Ok((Partial::new(&b\"\"[..]), 2.640625)));"] # [doc = " assert_eq!(parser.parse_peek(Partial::new(&[0x01][..])), Err(ErrMode::Incomplete(Needed::new(3))));"] # [doc = " ```"] # [inline (always)] pub fn be_f32 < Input , Error > (input : & mut Input) -> Result < f32 , Error > where Input : StreamIsPartial + Stream < Token = u8 > , Error : ParserError < Input > , { trace ("be_f32" , move | input : & mut Input | { be_uint :: < _ , u32 , _ > (input , 4) . map (f32 :: from_bits) }) . parse_next (input) }
};
}
