// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Flags for incoming messages."]
#[doc = ""]
#[doc = " Flags provide additional information about incoming messages."]
#[cfg(not(target_os = "redox"))]
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct RecvFlags(c_int);
