// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Protocol specification used for creating sockets via `Socket::new`."]
#[doc = ""]
#[doc = " This is a newtype wrapper around an integer which provides a nicer API in"]
#[doc = " addition to an injection point for documentation."]
#[doc = ""]
#[doc = " This type is freely interconvertible with C's `int` type, however, if a raw"]
#[doc = " value needs to be provided."]
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct Protocol(c_int);
