// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
impl<'a> MaybeUninitSlice<'a> {
    #[doc = " Creates a new `MaybeUninitSlice` wrapping a byte slice."]
    #[doc = ""]
    #[doc = " # Panics"]
    #[doc = ""]
    #[doc = " Panics on Windows if the slice is larger than 4GB."]
    pub fn new(buf: &'a mut [MaybeUninit<u8>]) -> MaybeUninitSlice<'a> {
        MaybeUninitSlice(sys::MaybeUninitSlice::new(buf))
    }
}
