// Generated macro for BorderType (enum)
macro_rules! Depcrate_bordersBorderType {
() => {
// Module: crate::borders
// Provides: {"BorderType"}
// Dependencies: {}
# [doc = " The type of border of a [`Block`](crate::block::Block)."] # [doc = ""] # [doc = " See the [`borders`](crate::block::Block::borders) method of `Block` to configure its borders."] # [derive (Debug , Default , Display , EnumString , Clone , Copy , Eq , PartialEq , Hash)] # [cfg_attr (feature = "serde" , derive (serde :: Serialize , serde :: Deserialize))] pub enum BorderType { # [doc = " A plain, simple border."] # [doc = ""] # [doc = " This is the default"] # [doc = ""] # [doc = " # Example"] # [doc = ""] # [doc = " ```plain"] # [doc = " ┌───────┐"] # [doc = " │       │"] # [doc = " └───────┘"] # [doc = " ```"] # [default] Plain , # [doc = " A plain border with rounded corners."] # [doc = ""] # [doc = " # Example"] # [doc = ""] # [doc = " ```plain"] # [doc = " ╭───────╮"] # [doc = " │       │"] # [doc = " ╰───────╯"] # [doc = " ```"] Rounded , # [doc = " A doubled border."] # [doc = ""] # [doc = " Note this uses one character that draws two lines."] # [doc = ""] # [doc = " # Example"] # [doc = ""] # [doc = " ```plain"] # [doc = " ╔═══════╗"] # [doc = " ║       ║"] # [doc = " ╚═══════╝"] # [doc = " ```"] Double , # [doc = " A thick border."] # [doc = ""] # [doc = " # Example"] # [doc = ""] # [doc = " ```plain"] # [doc = " ┏━━━━━━━┓"] # [doc = " ┃       ┃"] # [doc = " ┗━━━━━━━┛"] # [doc = " ```"] Thick , # [doc = " A light double-dashed border."] # [doc = ""] # [doc = " ```plain"] # [doc = " ┌╌╌╌╌╌╌╌┐"] # [doc = " ╎       ╎"] # [doc = " └╌╌╌╌╌╌╌┘"] # [doc = " ```"] LightDoubleDashed , # [doc = " A heavy double-dashed border."] # [doc = ""] # [doc = " ```plain"] # [doc = " ┏╍╍╍╍╍╍╍┓"] # [doc = " ╏       ╏"] # [doc = " ┗╍╍╍╍╍╍╍┛"] # [doc = " ```"] HeavyDoubleDashed , # [doc = " A light triple-dashed border."] # [doc = ""] # [doc = " ```plain"] # [doc = " ┌┄┄┄┄┄┄┄┐"] # [doc = " ┆       ┆"] # [doc = " └┄┄┄┄┄┄┄┘"] # [doc = " ```"] LightTripleDashed , # [doc = " A heavy triple-dashed border."] # [doc = ""] # [doc = " ```plain"] # [doc = " ┏┅┅┅┅┅┅┅┓"] # [doc = " ┇       ┇"] # [doc = " ┗┅┅┅┅┅┅┅┛"] # [doc = " ```"] HeavyTripleDashed , # [doc = " A light quadruple-dashed border."] # [doc = ""] # [doc = " ```plain"] # [doc = " ┌┈┈┈┈┈┈┈┐"] # [doc = " ┊       ┊"] # [doc = " └┈┈┈┈┈┈┈┘"] # [doc = " ```"] LightQuadrupleDashed , # [doc = " A heavy quadruple-dashed border."] # [doc = ""] # [doc = " ```plain"] # [doc = " ┏┉┉┉┉┉┉┉┓"] # [doc = " ┋       ┋"] # [doc = " ┗┉┉┉┉┉┉┉┛"] # [doc = " ```"] HeavyQuadrupleDashed , # [doc = " A border with a single line on the inside of a half block."] # [doc = ""] # [doc = " # Example"] # [doc = ""] # [doc = " ```plain"] # [doc = " ▗▄▄▄▄▄▄▄▖"] # [doc = " ▐       ▌"] # [doc = " ▐       ▌"] # [doc = " ▝▀▀▀▀▀▀▀▘"] QuadrantInside , # [doc = " A border with a single line on the outside of a half block."] # [doc = ""] # [doc = " # Example"] # [doc = ""] # [doc = " ```plain"] # [doc = " ▛▀▀▀▀▀▀▀▜"] # [doc = " ▌       ▐"] # [doc = " ▌       ▐"] # [doc = " ▙▄▄▄▄▄▄▄▟"] QuadrantOutside , }
};
}
