// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs:29 from submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs 
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros :: decl_module ; decl_module ! (wrapped_rand_pcg_decls_pcg128 , wrapped_rand_pcg_decls_module_not_found_pcg128 , wrapped_rand_pcg_decls_pcg128cm , wrapped_rand_pcg_decls_module_not_found_pcg128cm , wrapped_rand_pcg_decls_pcg64 , wrapped_rand_pcg_decls_module_not_found_pcg64) ;