// Generated macro for create_signed_pattern (function)
macro_rules! Depcrate_percentcreate_signed_pattern {
() => {
// Module: crate::percent
// Provides: {"create_signed_pattern"}
// Dependencies: {}
# [doc = " Used to create a percent pattern for negative, approximate, or explicit plus."] fn create_signed_pattern < 'a > (pattern : & str , localized_percent_sign : & str ,) -> Result < VarZeroCow < 'a , Pattern < DoublePlaceholder > > , DataError > { let percent_pattern_index = pattern . find ('%') . unwrap () ; let first_num_pattern_index = pattern . find (['0' , '#']) . unwrap () ; let last_num_pattern_index = pattern . rfind (['0' , '#']) . unwrap () ; let sign_pattern_index = pattern . rfind (['-']) . unwrap () ; let mut symbol_indexes = [sign_pattern_index , percent_pattern_index , first_num_pattern_index ,] ; symbol_indexes . sort () ; let percent_prefix = if percent_pattern_index == 0 { "" } else if percent_pattern_index < first_num_pattern_index || percent_pattern_index < sign_pattern_index { let next_symbol_index = std :: cmp :: min (first_num_pattern_index , sign_pattern_index) ; & pattern [0 .. next_symbol_index] } else { & pattern [last_num_pattern_index + 1 .. percent_pattern_index] } ; let precent_symbol_index = symbol_indexes . iter () . position (| & i | i == percent_pattern_index) . unwrap () ; let percent_suffix : & str = if symbol_indexes . len () > precent_symbol_index + 1 { let next_symbol_index = symbol_indexes . get (precent_symbol_index + 1) . unwrap () ; & pattern [percent_pattern_index + 1 .. next_symbol_index . to_owned ()] } else { & pattern [(percent_pattern_index + 1) ..] } ; let percent_symbol = format ! ("{percent_prefix}{localized_percent_sign}{percent_suffix}") ; let pattern_vec : Vec < & str > = symbol_indexes . into_iter () . map (| index | { if index == percent_pattern_index { return percent_symbol . as_str () ; } if index == sign_pattern_index { return "{1}" ; } "{0}" }) . collect () ; let pattern = DoublePlaceholderPattern :: try_from_str (& pattern_vec . concat () , Default :: default ()) . map_err (| e | DataError :: custom ("Could not parse pattern") . with_display_context (& e)) ? ; Ok (VarZeroCow :: new_owned (pattern)) }
};
}
