// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_num_conv_decls_module_not_found_prelude,
    wrapped_num_conv_decls_module_not_found_sealed,
    wrapped_num_conv_decls_ExtendTarget,
    wrapped_num_conv_decls_TruncateTarget,
    wrapped_num_conv_decls_Extend,
    wrapped_num_conv_decls_impl_for_Extend,
    wrapped_num_conv_decls_Truncate,
    wrapped_num_conv_decls_impl_for_Truncate,
    wrapped_num_conv_decls_macro_rules,
    wrapped_num_conv_decls_macro_rules,
    wrapped_num_conv_decls_impl_extend,
    wrapped_num_conv_decls_impl_truncate
);
