// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
impl_extend! { u8 => u8 , u16 , u32 , u64 , u128 , usize ; u16 => u16 , u32 , u64 , u128 , usize ; u32 => u32 , u64 , u128 ; u64 => u64 , u128 ; u128 => u128 ; usize => usize ; i8 => i8 , i16 , i32 , i64 , i128 , isize ; i16 => i16 , i32 , i64 , i128 , isize ; i32 => i32 , i64 , i128 ; i64 => i64 , i128 ; i128 => i128 ; isize => isize ; }
