// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs 
// Do not edit this file by hand. Your changes will be overwritten.

 use serde :: { Deserialize , Serialize } ; use std :: collections :: HashMap ; # [cfg (any (feature = "no_simd" , miri , not (target_arch = "x86_64") , all (target_arch = "x86_64" , not (target_feature = "sse2"))))] pub mod generic ;