// Generated macro for impl_129 (impl)
macro_rules! Depcrate_astimpl_129 {
() => {
// Module: crate::ast
// Provides: {"impl_129"}
// Dependencies: {}
impl Parse for UnqualifiedName { fn parse < 'a , 'b > (ctx : & 'a ParseContext , subs : & 'a mut SubstitutionTable , input : IndexStr < 'b > ,) -> Result < (UnqualifiedName , IndexStr < 'b >) > { try_begin_parse ! ("UnqualifiedName" , ctx , input) ; let operator_name_input = consume (b"on" , input) . unwrap_or (input) ; if let Ok ((op , tail)) = try_recurse ! (OperatorName :: parse (ctx , subs , operator_name_input)) { let (abi_tags , tail) = AbiTags :: parse (ctx , subs , tail) ? ; return Ok ((UnqualifiedName :: Operator (op , abi_tags) , tail)) ; } if let Ok ((ctor_dtor , tail)) = try_recurse ! (CtorDtorName :: parse (ctx , subs , input)) { let (abi_tags , tail) = AbiTags :: parse (ctx , subs , tail) ? ; return Ok ((UnqualifiedName :: CtorDtor (ctor_dtor , abi_tags) , tail)) ; } if let Ok (tail) = consume (b"L" , input) { let (name , tail) = SourceName :: parse (ctx , subs , tail) ? ; let (discr , tail) = if let Ok ((d , t)) = try_recurse ! (Discriminator :: parse (ctx , subs , tail)) { (Some (d) , t) } else { (None , tail) } ; let (abi_tags , tail) = AbiTags :: parse (ctx , subs , tail) ? ; return Ok ((UnqualifiedName :: LocalSourceName (name , discr , abi_tags) , tail ,)) ; } if let Ok ((source , tail)) = try_recurse ! (SourceName :: parse (ctx , subs , input)) { let (abi_tags , tail) = AbiTags :: parse (ctx , subs , tail) ? ; return Ok ((UnqualifiedName :: Source (source , abi_tags) , tail)) ; } if let Ok ((closure , tail)) = try_recurse ! (ClosureTypeName :: parse (ctx , subs , input)) { let (abi_tags , tail) = AbiTags :: parse (ctx , subs , tail) ? ; return Ok ((UnqualifiedName :: ClosureType (closure , abi_tags) , tail)) ; } let (unnamed , tail) = UnnamedTypeName :: parse (ctx , subs , input) ? ; let (abi_tags , tail) = AbiTags :: parse (ctx , subs , tail) ? ; Ok ((UnqualifiedName :: UnnamedType (unnamed , abi_tags) , tail)) } }
};
}
