[package]
name = "expand_utils_macros"
publish.workspace = true
description.workspace = true
categories.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition = "2024" # Set explicit edition for proc-macro crate
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
include.workspace = true



[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }

# Depending on rustc_expand (main crate we are trying to fix)

# Depending on our helper library
rustc_expand_base_lib = { path = "../rustc_expand_base_lib" }
rustc_ast = { workspace = true }
rustc_span = { workspace = true }
rustc_errors = { workspace = true }
smallvec = { workspace = true }
rustc_ast_pretty = { workspace = true }

[lints]
workspace = true