// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum RawStrError {
    #[doc = " Non `#` characters exist between `r` and `\"`, e.g. `r##~\"abcde\"##`"]
    InvalidStarter { bad_char: char },
    #[doc = " The string was not terminated, e.g. `r###\"abcde\"##`."]
    #[doc = " `possible_terminator_offset` is the number of characters after `r` or"]
    #[doc = " `br` where they may have intended to terminate it."]
    NoTerminator {
        expected: u32,
        found: u32,
        possible_terminator_offset: Option<u32>,
    },
    #[doc = " More than 255 `#`s exist."]
    TooManyDelimiters { found: u32 },
}
