// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " A possible error value while converting a [`OsString`] to a [`Utf8PathBuf`]."]
#[doc = ""]
#[doc = " Produced by the `TryFrom<OsString>` implementation for [`Utf8PathBuf`]."]
#[doc = ""]
#[doc = " # Examples"]
#[doc = ""]
#[doc = " ```"]
#[doc = " # #[cfg(osstring_from_str)] {"]
#[doc = " use camino::{Utf8PathBuf, FromOsStringError};"]
#[doc = " use std::convert::{TryFrom, TryInto};"]
#[doc = " use std::ffi::OsStr;"]
#[doc = " use std::str::FromStr;"]
#[doc = " use std::ffi::OsString;"]
#[doc = " # #[cfg(unix)]"]
#[doc = " use std::os::unix::ffi::OsStrExt;"]
#[doc = ""]
#[doc = " let unicode_string = OsString::from_str(\"/valid/unicode\").unwrap();"]
#[doc = " let utf8_path_buf: Utf8PathBuf = unicode_string.try_into()"]
#[doc = "     .expect(\"valid Unicode path succeeded\");"]
#[doc = ""]
#[doc = " // Paths on Unix can be non-UTF-8."]
#[doc = " # #[cfg(unix)]"]
#[doc = " let non_unicode_string = OsStr::from_bytes(b\"\\xFF\\xFF\\xFF\").to_owned();"]
#[doc = " # #[cfg(unix)]"]
#[doc = " let err: FromOsStringError = Utf8PathBuf::try_from(non_unicode_string.clone())"]
#[doc = "     .expect_err(\"non-Unicode path failed\");"]
#[doc = " # #[cfg(unix)]"]
#[doc = " assert_eq!(err.as_os_str(), &non_unicode_string);"]
#[doc = " # #[cfg(unix)]"]
#[doc = " assert_eq!(err.into_os_string(), non_unicode_string);"]
#[doc = " # }"]
#[doc = " ```"]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct FromOsStringError {
    os_string: OsString,
    error: FromOsStrError,
}
