// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_mio_decls_compile_error,
    wrapped_mio_decls_module_not_found_macros,
    wrapped_mio_decls_module_not_found_interest,
    wrapped_mio_decls_module_not_found_poll,
    wrapped_mio_decls_module_not_found_sys,
    wrapped_mio_decls_module_not_found_token,
    wrapped_mio_decls_module_not_found_waker,
    wrapped_mio_decls_module_not_found_event,
    wrapped_mio_decls_cfg_io_source,
    wrapped_mio_decls_cfg_net,
    wrapped_mio_decls_module_not_found_unix,
    wrapped_mio_decls_module_not_found_hermit,
    wrapped_mio_decls_module_not_found_windows,
    wrapped_mio_decls_module_not_found_features,
    wrapped_mio_decls_module_not_found_guide
);
