// Generated macro for printing (module)
macro_rules! Depcrate_opprinting {
() => {
// Module: crate::op
// Provides: {"printing"}
// Dependencies: {}
# [cfg (feature = "printing")] mod printing { use super :: * ; use quote :: { Tokens , ToTokens } ; impl ToTokens for BinOp { fn to_tokens (& self , tokens : & mut Tokens) { match * self { BinOp :: Add (ref t) => t . to_tokens (tokens) , BinOp :: Sub (ref t) => t . to_tokens (tokens) , BinOp :: Mul (ref t) => t . to_tokens (tokens) , BinOp :: Div (ref t) => t . to_tokens (tokens) , BinOp :: Rem (ref t) => t . to_tokens (tokens) , BinOp :: And (ref t) => t . to_tokens (tokens) , BinOp :: Or (ref t) => t . to_tokens (tokens) , BinOp :: BitXor (ref t) => t . to_tokens (tokens) , BinOp :: BitAnd (ref t) => t . to_tokens (tokens) , BinOp :: BitOr (ref t) => t . to_tokens (tokens) , BinOp :: Shl (ref t) => t . to_tokens (tokens) , BinOp :: Shr (ref t) => t . to_tokens (tokens) , BinOp :: Eq (ref t) => t . to_tokens (tokens) , BinOp :: Lt (ref t) => t . to_tokens (tokens) , BinOp :: Le (ref t) => t . to_tokens (tokens) , BinOp :: Ne (ref t) => t . to_tokens (tokens) , BinOp :: Ge (ref t) => t . to_tokens (tokens) , BinOp :: Gt (ref t) => t . to_tokens (tokens) , BinOp :: AddEq (ref t) => t . to_tokens (tokens) , BinOp :: SubEq (ref t) => t . to_tokens (tokens) , BinOp :: MulEq (ref t) => t . to_tokens (tokens) , BinOp :: DivEq (ref t) => t . to_tokens (tokens) , BinOp :: RemEq (ref t) => t . to_tokens (tokens) , BinOp :: BitXorEq (ref t) => t . to_tokens (tokens) , BinOp :: BitAndEq (ref t) => t . to_tokens (tokens) , BinOp :: BitOrEq (ref t) => t . to_tokens (tokens) , BinOp :: ShlEq (ref t) => t . to_tokens (tokens) , BinOp :: ShrEq (ref t) => t . to_tokens (tokens) , } } } impl ToTokens for UnOp { fn to_tokens (& self , tokens : & mut Tokens) { match * self { UnOp :: Deref (ref t) => t . to_tokens (tokens) , UnOp :: Not (ref t) => t . to_tokens (tokens) , UnOp :: Neg (ref t) => t . to_tokens (tokens) , } } } }
};
}
