// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:71 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs at 2025-12-23T20:00:22.353828771+00:00
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Generates a new workspace containing \"wrapped\" versions of the target crates."]
#[doc = " Each wrapped crate will have its declarations eagerly split and patched."]
#[allow(clippy::too_many_arguments)]
pub fn generate_wrapped_crate(
    wrapped_workspace_root: &Path,
    original_crate_name: &str,
    original_crate_path: &Path,
    global_config: &SplitDeclsConfig,
    patch_config: &patch_config::PatchConfig,
    dry_run: bool,
) -> Result<()> {
    let wrapped_crate_name = format!("wrapped-{}", original_crate_name);
    println!("\n=== Generating wrapped crate: {} ===", wrapped_crate_name);
    let wrapped_crate_path = wrapped_workspace_root.join(&wrapped_crate_name);
    if !dry_run {
        fs::create_dir_all(&wrapped_crate_path).context(format!(
            "Failed to create wrapped crate directory: {}",
            wrapped_crate_path.display()
        ))?;
        fs::create_dir_all(&wrapped_crate_path.join("src")).context(format!(
            "Failed to create src directory for wrapped crate: {}",
            wrapped_crate_path.display()
        ))?;
        copy_dir_recursive::copy_dir_recursive(
            original_crate_path,
            &wrapped_crate_path,
            &[
                "Cargo.toml".to_string(),
                "src/lib.rs".to_string(),
                "target".to_string(),
            ],
            true,
        )
        .context(format!(
            "Failed to copy original crate contents from {} to {}",
            original_crate_path.display(),
            wrapped_crate_path.display()
        ))?;
    }
    let wrapped_crate_paths = setup_crate_paths(&wrapped_crate_path)?;
    let original_lib_rs_path = original_crate_path.join("src").join("lib.rs");
    let original_cargo_toml_path = original_crate_path.join("Cargo.toml");
    let mut old_lib_rs_content = if original_lib_rs_path.exists() {
        fs::read_to_string(&original_lib_rs_path).context(format!(
            "Failed to read original lib.rs at {}",
            original_lib_rs_path.display()
        ))?
    } else {
        String::new()
    };
    generate_new_cargotoml(
        &original_cargo_toml_path,
        &wrapped_crate_paths.cargo_toml_path,
        original_crate_path,
        global_config,
        patch_config,
        dry_run,
    )?;
    generate_new_lib_rs(&wrapped_crate_paths, dry_run)?;
    if !dry_run {
        format_rust_file(&wrapped_crate_paths.lib_rs_path)?;
    }
    let mut crate_config = SplitDeclsConfig::default();
    crate_config.active_overlay_modules = global_config.active_overlay_modules.clone();
    crate_config.custom_prelude_overlay = global_config.custom_prelude_overlay.clone();
    crate_config.string_replacements = global_config.string_replacements.clone();
    crate_config.crates_io_patches = global_config.crates_io_patches.clone();
    let crate_name_str = original_crate_name.to_string();
    if let Some(global_patches_map) = &global_config.patches {
        if let Some(patches_for_crate) = global_patches_map.get(&crate_name_str) {
            let mut new_patches_map = HashMap::new();
            new_patches_map.insert(crate_name_str.clone(), patches_for_crate.clone());
            crate_config.patches = Some(new_patches_map);
        }
    }
    let serialized_config = toml::to_string(&crate_config)
        .context("Failed to serialize SplitDeclsConfig for wrapped crate")?;
    if !dry_run {
        fs::write(&wrapped_crate_paths.target_config_path, serialized_config).context(format!(
            "Failed to write .split-decls-config.toml to {}",
            wrapped_crate_paths.target_config_path.display()
        ))?;
    }
    println!(
        "Wrote config to {}",
        wrapped_crate_paths.target_config_path.display()
    );
    if let Some(replacements) = &global_config.string_replacements {
        for sr in replacements {
            old_lib_rs_content = old_lib_rs_content.replace(&sr.old, &sr.new);
            println!("Applied string replacement: '{}' -> '{}'", sr.old, sr.new);
        }
    }
    let mut syntax_tree = syn::parse_file(&old_lib_rs_content)
        .context("Failed to parse .rs content for eager splitting in wrapped crate")?;
    apply_patches_to_syntax_tree(
        &mut syntax_tree,
        &wrapped_crate_name.replace("-", "_"),
        &crate_config,
    )?;
    eager_splitter::split_and_generate_decls(
        &syntax_tree,
        &wrapped_crate_paths,
        &crate_config,
        dry_run,
    )?;
    generate_new_build_rs(&wrapped_crate_paths, dry_run)?;
    if !dry_run {
        format_rust_file(&wrapped_crate_paths.build_rs_path)?;
    }
    Ok(())
}
