// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:71 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Extracts declarations from a crate's lib.rs and returns them as a map."]
pub fn extract_declarations_to_map(paths: &CratePaths) -> Result<HashMap<String, TokenStream>> {
    let lib_content = fs::read_to_string(&paths.lib_rs_path)
        .context(format!("Failed to read {}", paths.lib_rs_path.display()))?;
    let syntax_tree: syn::File =
        syn::parse_file(&lib_content).context("Failed to parse lib.rs as Rust code")?;
    let mut extracted_decls: HashMap<String, TokenStream> = HashMap::new();
    let mut item_count = 0;
    for item in &syntax_tree.items {
        if let Some(decl) = declaration_extractor::extract_single_declaration(item, item_count) {
            extracted_decls.insert(decl.name, decl.content);
            item_count += 1;
        }
    }
    Ok(extracted_decls)
}
