// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:71 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs at 2025-12-23T20:00:20.969414218+00:00
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
pub fn format_generated_rust_files(output_dir: &Path, verbose: bool) -> Result<()> {
    if verbose {
        println!(
            "DEBUG: Formatting generated Rust files in {}",
            output_dir.display()
        );
    }
    for entry in WalkDir::new(output_dir).into_iter().filter_map(|e| e.ok()) {
        let path = entry.path();
        if path.is_file() && path.extension().map_or(false, |ext| ext == "rs") {
            if verbose {
                println!("DEBUG: Running rustfmt on {}", path.display());
            }
            let output = Command::new("rustfmt")
                .arg(path)
                .output()
                .context(format!("Failed to execute rustfmt on {}", path.display()))?;
            if !output.status.success() {
                eprintln!("WARNING: rustfmt failed on {}:", path.display());
                eprintln!("{}", String::from_utf8_lossy(&output.stderr));
            }
        }
    }
    Ok(())
}
