// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:71 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs at 2025-12-23T19:48:59.178738544+00:00
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Main entry point for eager splitting of a crate"]
pub fn eager_split_crate(paths: &CratePaths, config: &SplitDeclsConfig) -> Result<()> {
    println!("📖 Parsing lib.rs...");
    let lib_content = fs::read_to_string(&paths.lib_rs_path)
        .context(format!("Failed to read {}", paths.lib_rs_path.display()))?;
    println!("🔧 Parsing {} bytes of Rust code...", lib_content.len());
    let syntax_tree: syn::File = match syn::parse_file(&lib_content) {
        Ok(ast) => ast,
        Err(e) => {
            let file_path_display = paths.lib_rs_path.display();
            let error_message = e.to_string();
            let error_line = e.span().start().line;
            let error_column = e.span().start().column;
            return Err (anyhow :: anyhow ! ("Failed to parse lib.rs as Rust code: {}\nFile: {}\nLine: {}, Column: {}\nError: {}" , file_path_display , paths . lib_rs_path . to_string_lossy () , error_line , error_column , error_message)) ;
        }
    };
    split_and_generate_decls(&syntax_tree, paths, config, false)?;
    generate_output_lib_rs(paths)?;
    generate_new_lib_rs(paths)?;
    generate_new_build_rs(paths)?;
    println!("Eager splitting completed for crate: {}", paths.crate_name);
    println!(
        "Output generated in: {}",
        paths.decls_output_dir.parent().unwrap().display()
    );
    Ok(())
}
