// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:71 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[derive(Serialize, Deserialize, Debug)]
pub struct MacroAnalysisOutput {
    pub total_module_terms: usize,
    pub total_global_terms: usize,
    pub module_frequencies: HashMap<String, usize>,
    pub global_frequencies: HashMap<String, usize>,
    pub term_scores_by_macro: HashMap<String, HashMap<String, f64>>,
    pub global_module_term_scores: HashMap<String, (f64, f64)>,
}
