// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:71 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs at 2025-12-23T20:00:21.067756661+00:00
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Recursively finds all .rs files in src directory that cargo would build"]
fn find_all_rust_files(src_dir: &std::path::Path) -> Result<Vec<std::path::PathBuf>> {
    let mut rust_files = Vec::new();
    if !src_dir.exists() {
        return Ok(rust_files);
    }
    for entry in std::fs::read_dir(src_dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_file() && path.extension().map_or(false, |ext| ext == "rs") {
            rust_files.push(path);
        } else if path.is_dir() {
            rust_files.extend(find_all_rust_files(&path)?);
        }
    }
    Ok(rust_files)
}
