// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:71 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs at 2025-12-23T20:00:21.573185620+00:00
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[derive(Debug, Deserialize, Serialize, Clone)]
pub struct LoopOperation {
    #[serde(rename = "type")]
    pub op_type: String,
    pub over: String,
    pub loop_var: String,
    pub tasks: Vec<Task>,
}
