// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:71 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs at 2025-12-23T19:49:00.346181568+00:00
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
pub fn parse_args() -> Result<CliArgs> {
    let mut args: Vec<String> = std::env::args().collect();
    let dry_run_index = args.iter().position(|arg| arg == "--dry-run");
    let dry_run = dry_run_index.is_some();
    if let Some(index) = dry_run_index {
        args.remove(index);
    }
    let verbose_index = args.iter().position(|arg| arg == "--verbose");
    let verbose = verbose_index.is_some();
    if let Some(index) = verbose_index {
        args.remove(index);
    }
    let mut wrapped_workspace_output_dir = PathBuf::from("output");
    let mut generate_wrapped_workspace_mode = true;
    if let Some(index) = args.iter().position(|arg| arg == "--no-wrapped-workspace") {
        generate_wrapped_workspace_mode = false;
        args.remove(index);
    }
    if let Some(index) = args.iter().position(|arg| arg == "--output-dir") {
        args.remove(index);
        if let Some(output_path_str) = args.get(index) {
            wrapped_workspace_output_dir = PathBuf::from(output_path_str);
            args.remove(index);
        } else {
            anyhow::bail!("--output-dir requires a path.");
        }
    }
    if let Some(index) = args
        .iter()
        .position(|arg| arg == "--generate-wrapped-workspace")
    {
        generate_wrapped_workspace_mode = true;
        args.remove(index);
        if let Some(output_path_str) = args.get(index) {
            wrapped_workspace_output_dir = PathBuf::from(output_path_str);
            args.remove(index);
        } else {
        }
    }
    let patch_config_path_str = args
        .get(1)
        .map_or("patch.toml".to_string(), |s| s.to_string());
    Ok(CliArgs {
        dry_run,
        verbose,
        wrapped_workspace_output_dir,
        patch_config_path_str,
        generate_wrapped_workspace_mode,
    })
}
