// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:71 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs at 2025-12-23T20:00:21.168411680+00:00
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Generate new lib.rs that re-exports the split declarations in the output directory"]
fn generate_output_lib_rs(paths: &CratePaths) -> Result<()> {
    let output_lib_path = paths.decls_output_dir.parent().unwrap().join("lib.rs");
    let new_lib_content = format!(
        r#"// Generated by split-decls-rs
// Re-exports all split declarations

pub mod decls {{
    include!("decls/_decl_module_invocation.rs");
}}
pub use decls::*;

// Re-export prelude macros if available

pub use introspector_decl2_macros::*;
"#
    );
    fs::create_dir_all(output_lib_path.parent().unwrap())
        .context("Failed to create output src directory")?;
    fs::write(&output_lib_path, new_lib_content).context(format!(
        "Failed to write output lib.rs at {}",
        output_lib_path.display()
    ))?;
    println!("Generated output lib.rs at {}", output_lib_path.display());
    Ok(())
}
