// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:71 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs at 2025-12-23T20:00:20.983711313+00:00
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Generates a new workspace containing \"wrapped\" versions of the target crates."]
#[doc = " Each wrapped crate will have its declarations eagerly split and patched."]
pub fn generate_wrapped_workspace(
    output_dir: &Path,
    patch_config: &patch_config::PatchConfig,
    global_config: &SplitDeclsConfig,
    scan_root: &Path,
    dry_run: bool,
    verbose: bool,
) -> Result<()> {
    if verbose {
        println!(
            "DEBUG: generate_wrapped_workspace called with output_dir: {}",
            output_dir.display()
        );
        println!(
            "DEBUG: Scanning root for Cargo.tomls: {}",
            scan_root.display()
        );
        println!(
            "DEBUG: patch_config.generated_workspace_member.is_empty(): {}",
            patch_config.generated_workspace_member.is_empty()
        );
    }
    if !dry_run {
        fs::create_dir_all(output_dir).context(format!(
            "Failed to create wrapped workspace directory: {}",
            output_dir.display()
        ))?;
    }
    if verbose {
        println!("Wrapped workspace directory: {}", output_dir.display());
    }
    let workspace_cargo_toml_path = output_dir.join("Cargo.toml");
    let final_cargo_toml_content;
    let main_crate_cargo_toml_path = scan_root.join("Cargo.toml");
    final_cargo_toml_content = multi_crate::handle_multi_crate_wrapping(
        output_dir,
        patch_config,
        global_config,
        scan_root,
        dry_run,
        verbose,
    )?;
    if !dry_run {
        add_generated_header!(
            &workspace_cargo_toml_path,
            final_cargo_toml_content.as_str(),
            file!(),
            line!()
        )
        .context(format!(
            "Failed to write Cargo.toml for workspace: {}",
            workspace_cargo_toml_path.display()
        ))?;
        format_generated_rust_files(output_dir, verbose)?;
    }
    if verbose {
        println!(
            "Generated Cargo.toml at: {}",
            workspace_cargo_toml_path.display()
        );
        println!("DEBUG: Exiting generate_wrapped_workspace.");
    }
    Ok(())
}
