// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:71 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs at 2025-12-23T19:49:00.708262647+00:00
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
pub fn handle_multi_crate_wrapping(
    output_dir: &Path,
    patch_config: &patch_config::PatchConfig,
    global_config: &SplitDeclsConfig,
    scan_root: &Path,
    dry_run: bool,
    verbose: bool,
) -> Result<String> {
    let mut final_cargo_toml_content = String::new();
    let mut workspace_members_content = Vec::new();
    let mut workspace_dependencies_content_str = String::new();
    let mut patch_crates_io_content_str = String::new();
    let consolidated_workspace_deps_map =
        collect_and_format_workspace_dependencies(global_config, output_dir, scan_root)?;
    for (dep_name, dep_value) in consolidated_workspace_deps_map.iter() {
        workspace_dependencies_content_str.push_str(&format!(
            "{} = {}
",
            dep_name,
            dep_value.to_string()
        ));
    }
    if verbose {
        println!(
            "Calling find_all_cargo_tomls in scan root: {}",
            scan_root.display()
        );
    }
    if let Ok(cargo_tomls) = find_all_cargo_tomls(scan_root, verbose) {
        if verbose {
            println!("Found {} Cargo.toml files in scan root", cargo_tomls.len());
        }
        for cargo_path in cargo_tomls.iter() {
            if verbose {
                println!("  Extracting crate info from: {}", cargo_path.display());
            }
            if let Ok(Some(crate_info)) = extract_crate_info_simple(&cargo_path) {
                let relative_path = cargo_path
                    .parent()
                    .unwrap()
                    .strip_prefix(scan_root)
                    .unwrap_or(Path::new("."))
                    .to_string_lossy();
                workspace_members_content.push(format!("\"{}\"", relative_path));
                if verbose {
                    println!(
                        "    Added crate {} as workspace member and dependency candidate.",
                        crate_info.name
                    );
                }
            }
        }
        if verbose {
            println!(
                "Generated {} workspace members from scan root",
                workspace_members_content.len()
            );
        }
    } else {
        if verbose {
            println!(
                "Failed to find any Cargo.toml files in scan root: {}",
                scan_root.display()
            );
        }
    }
    for member in &patch_config.generated_workspace_member {
        if verbose {
            println!("Processing generated workspace member: {}", member.name);
        }
        let original_crate_location = scan_root.join(&member.path);
        let relative_to_output = path_diff::path_diff(output_dir, &original_crate_location)
            .context(format!(
                "Failed to calculate relative path for workspace member '{}'",
                member.name
            ))?;
        workspace_members_content.push(format!("\"{}\"", relative_to_output.display()));
        if verbose {
            println!(
                "  Calling generate_wrapped_crate for member '{}' at '{}'",
                member.name,
                original_crate_location.display()
            );
        }
        generate_wrapped_crate::generate_wrapped_crate(
            output_dir,
            &member.name,
            &original_crate_location,
            global_config,
            patch_config,
            dry_run,
        )?;
        if verbose {
            println!(
                "  Finished generate_wrapped_crate for member: {}",
                member.name
            );
        }
    }
    for dep in &patch_config.generated_workspace_dependency {
        if verbose {
            println!("Processing generated workspace dependency: {}", dep.name);
        }
        let mut dep_string = format!("{} = {{ ", dep.name);
        let mut parts = Vec::new();
        if let Some(version) = &dep.version {
            parts.push(format!("version = \"{}\"", version));
        }
        if let Some(project_root_path) = &dep.project_root_path {
            let full_dep_path = scan_root.join(project_root_path);
            let relative_path = match path_diff::path_diff(output_dir, &full_dep_path) {
                Some(p) => p,
                None => anyhow::bail!(format!(
                    "Failed to calculate relative path for workspace dep '{}'",
                    dep.name
                )),
            };
            parts.push(format!("path = \"{}\"", relative_path.display()));
        }
        if let Some(features) = &dep.features {
            parts.push(format!("features = [\"{}\"]", features.join("\", \"")));
        }
        if let Some(package) = &dep.package {
            parts.push(format!("package = \"{}\"", package));
        }
        dep_string.push_str(&parts.join(", "));
        dep_string.push_str(" }\n");
        if dep.is_patch.unwrap_or(false) {
            patch_crates_io_content_str.push_str(&dep_string);
        } else {
        }
    }
    final_cargo_toml_content = format!(
        r#"[workspace]
resolver = "2"
members = [
    {}
]

[workspace.dependencies]
{}"#,
        workspace_members_content.join(",\n    "),
        workspace_dependencies_content_str
    );
    if !patch_crates_io_content_str.is_empty() {
        final_cargo_toml_content.push_str("\n[patch.crates-io]\n");
        final_cargo_toml_content.push_str(&patch_crates_io_content_str);
    }
    Ok(final_cargo_toml_content)
}
