// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:71 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[derive(Debug, Deserialize, Serialize)]
pub struct GeneratedCrateDependency {
    pub crate_name: String,
    pub section: String,
    pub name: String,
    pub workspace: bool,
    pub version: Option<String>,
    pub features: Option<Vec<String>>,
    pub package: Option<String>,
}
