// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " This has to be the max length of an NCR instead of max"]
#[doc = " minus one, because we can't rely on getting the minus"]
#[doc = " one from the space reserved for the current unmappable,"]
#[doc = " because the ISO-2022-JP encoder can fill up that space"]
#[doc = " with a state transition escape."]
const NCR_EXTRA: usize = 10;
