// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter.rs:211 from submodules/split-decls-rs/src/eager_splitter.rs
// Do not edit this file by hand. Your changes will be overwritten.

#[llm_error_message(message = "Module file not found for: test_labels_names")]
#[llm_context(crate_name = "wrapped_encoding_rs", module_name = "test_labels_names")]
pub struct wrapped_encoding_rs_decls_module_not_found_test_labels_names;
