// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter.rs:211 from submodules/split-decls-rs/src/eager_splitter.rs
// Do not edit this file by hand. Your changes will be overwritten.

#[llm_error_message(message = "Module file not found for: def_path_hash_map")]
#[llm_context(crate_name = "wrapped_rustc_hir", module_name = "def_path_hash_map")]
pub struct wrapped_rustc_hir_decls_module_not_found_def_path_hash_map;
