// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_minimal_lexical_decls_module_not_found_bellerophon,
    wrapped_minimal_lexical_decls_module_not_found_bigint,
    wrapped_minimal_lexical_decls_module_not_found_extended_float,
    wrapped_minimal_lexical_decls_module_not_found_fpu,
    wrapped_minimal_lexical_decls_module_not_found_heapvec,
    wrapped_minimal_lexical_decls_module_not_found_lemire,
    wrapped_minimal_lexical_decls_module_not_found_libm,
    wrapped_minimal_lexical_decls_module_not_found_mask,
    wrapped_minimal_lexical_decls_module_not_found_num,
    wrapped_minimal_lexical_decls_module_not_found_number,
    wrapped_minimal_lexical_decls_module_not_found_parse,
    wrapped_minimal_lexical_decls_module_not_found_rounding,
    wrapped_minimal_lexical_decls_module_not_found_slow,
    wrapped_minimal_lexical_decls_module_not_found_stackvec,
    wrapped_minimal_lexical_decls_module_not_found_table,
    wrapped_minimal_lexical_decls_module_not_found_table_bellerophon,
    wrapped_minimal_lexical_decls_module_not_found_table_lemire,
    wrapped_minimal_lexical_decls_module_not_found_table_small
);
