// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[cfg(feature = "internals")]
pub mod internals {
    #![doc = " Very unsafe internal functionality."]
    #![doc = ""]
    #![doc = " These are used internally for building and consuming generic arrays. When used correctly,"]
    #![doc = " they can ensure elements are correctly dropped if something panics while using them."]
    #![doc = ""]
    #![doc = " The API of these is not guaranteed to be stable, as they are not intended for general use."]
    pub use crate::internal::{ArrayBuilder, ArrayConsumer};
    pub use crate::internal::{IntrusiveArrayBuilder, IntrusiveArrayConsumer};
}
