// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Configuration for how pruning is done on a fetch"]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum FetchPrune {
    #[doc = " Use the setting from the configuration"]
    Unspecified,
    #[doc = " Force pruning on"]
    On,
    #[doc = " Force pruning off"]
    Off,
}
