// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " An enumeration all possible kinds objects may have."]
#[derive(PartialEq, Eq, Copy, Clone, Debug)]
pub enum ObjectType {
    #[doc = " Any kind of git object"]
    Any,
    #[doc = " An object which corresponds to a git commit"]
    Commit,
    #[doc = " An object which corresponds to a git tree"]
    Tree,
    #[doc = " An object which corresponds to a git blob"]
    Blob,
    #[doc = " An object which corresponds to a git tag"]
    Tag,
}
