// Generated macro for macro_85 (macro)
macro_rules! Depcrate_builtinmacro_85 {
() => {
// Module: crate::builtin
// Provides: {"macro_85"}
// Dependencies: {}
declare_lint ! { # [doc = " The `lossy_provenance_casts` lint detects an `as` cast between a pointer"] # [doc = " and an integer."] # [doc = ""] # [doc = " ### Example"] # [doc = ""] # [doc = " ```rust"] # [doc = " #![feature(strict_provenance_lints)]"] # [doc = " #![warn(lossy_provenance_casts)]"] # [doc = ""] # [doc = " fn main() {"] # [doc = "     let x: u8 = 37;"] # [doc = "     let _addr: usize = &x as *const u8 as usize;"] # [doc = " }"] # [doc = " ```"] # [doc = ""] # [doc = " {{produces}}"] # [doc = ""] # [doc = " ### Explanation"] # [doc = ""] # [doc = " This lint is part of the strict provenance effort, see [issue #95228]."] # [doc = " Casting a pointer to an integer is a lossy operation, because beyond"] # [doc = " just an *address* a pointer may be associated with a particular"] # [doc = " *provenance*. This information is used by the optimiser and for dynamic"] # [doc = " analysis/dynamic program verification (e.g. Miri or CHERI platforms)."] # [doc = ""] # [doc = " Since this cast is lossy, it is considered good style to use the"] # [doc = " [`ptr::addr`] method instead, which has a similar effect, but doesn't"] # [doc = " \"expose\" the pointer provenance. This improves optimisation potential."] # [doc = " See the docs of [`ptr::addr`] and [`ptr::expose_provenance`] for more information"] # [doc = " about exposing pointer provenance."] # [doc = ""] # [doc = " If your code can't comply with strict provenance and needs to expose"] # [doc = " the provenance, then there is [`ptr::expose_provenance`] as an escape hatch,"] # [doc = " which preserves the behaviour of `as usize` casts while being explicit"] # [doc = " about the semantics."] # [doc = ""] # [doc = " [issue #95228]: https://github.com/rust-lang/rust/issues/95228"] # [doc = " [`ptr::addr`]: https://doc.rust-lang.org/core/primitive.pointer.html#method.addr"] # [doc = " [`ptr::expose_provenance`]: https://doc.rust-lang.org/core/primitive.pointer.html#method.expose_provenance"] pub LOSSY_PROVENANCE_CASTS , Allow , "a lossy pointer to integer cast is used" , @ feature_gate = strict_provenance_lints ; }
};
}
