// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Marks async function to be executed by runtime, suitable to test environment"]
#[doc = ""]
#[doc = " ## Usage"]
#[doc = ""]
#[doc = " ```no_run"]
#[doc = " #[tokio::test]"]
#[doc = " async fn my_test() {"]
#[doc = "     assert!(true);"]
#[doc = " }"]
#[doc = " ```"]
#[proc_macro_attribute]
pub fn test_rt(args: TokenStream, item: TokenStream) -> TokenStream {
    entry::test(args.into(), item.into(), false).into()
}
