// Generated macro for impl_679 (impl)
macro_rules! Depcrate_util_alphabetimpl_679 {
() => {
// Module: crate::util::alphabet
// Provides: {"impl_679"}
// Dependencies: {}
impl Unit { # [doc = " Create a new haystack unit from a byte value."] # [doc = ""] # [doc = " All possible byte values are legal. However, when creating a haystack"] # [doc = " unit for a specific DFA, one should be careful to only construct units"] # [doc = " that are in that DFA's alphabet. Namely, one way to compact a DFA's"] # [doc = " in-memory representation is to collapse its transitions to a set of"] # [doc = " equivalence classes into a set of all possible byte values. If a DFA"] # [doc = " uses equivalence classes instead of byte values, then the byte given"] # [doc = " here should be the equivalence class."] pub fn u8 (byte : u8) -> Unit { Unit (UnitKind :: U8 (byte)) } # [doc = " Create a new \"end of input\" haystack unit."] # [doc = ""] # [doc = " The value given is the sentinel value used by this unit to represent"] # [doc = " the \"end of input.\" The value should be the total number of equivalence"] # [doc = " classes in the corresponding alphabet. Its maximum value is `256`,"] # [doc = " which occurs when every byte is its own equivalence class."] # [doc = ""] # [doc = " # Panics"] # [doc = ""] # [doc = " This panics when `num_byte_equiv_classes` is greater than `256`."] pub fn eoi (num_byte_equiv_classes : usize) -> Unit { assert ! (num_byte_equiv_classes <= 256 , "max number of byte-based equivalent classes is 256, but got \
             {num_byte_equiv_classes}" ,) ; Unit (UnitKind :: EOI (u16 :: try_from (num_byte_equiv_classes) . unwrap ())) } # [doc = " If this unit is not an \"end of input\" sentinel, then returns its"] # [doc = " underlying byte value. Otherwise return `None`."] pub fn as_u8 (self) -> Option < u8 > { match self . 0 { UnitKind :: U8 (b) => Some (b) , UnitKind :: EOI (_) => None , } } # [doc = " If this unit is an \"end of input\" sentinel, then return the underlying"] # [doc = " sentinel value that was given to [`Unit::eoi`]. Otherwise return"] # [doc = " `None`."] pub fn as_eoi (self) -> Option < u16 > { match self . 0 { UnitKind :: U8 (_) => None , UnitKind :: EOI (sentinel) => Some (sentinel) , } } # [doc = " Return this unit as a `usize`, regardless of whether it is a byte value"] # [doc = " or an \"end of input\" sentinel. In the latter case, the underlying"] # [doc = " sentinel value given to [`Unit::eoi`] is returned."] pub fn as_usize (self) -> usize { match self . 0 { UnitKind :: U8 (b) => usize :: from (b) , UnitKind :: EOI (eoi) => usize :: from (eoi) , } } # [doc = " Returns true if and only of this unit is a byte value equivalent to the"] # [doc = " byte given. This always returns false when this is an \"end of input\""] # [doc = " sentinel."] pub fn is_byte (self , byte : u8) -> bool { self . as_u8 () . map_or (false , | b | b == byte) } # [doc = " Returns true when this unit represents an \"end of input\" sentinel."] pub fn is_eoi (self) -> bool { self . as_eoi () . is_some () } # [doc = " Returns true when this unit corresponds to an ASCII word byte."] # [doc = ""] # [doc = " This always returns false when this unit represents an \"end of input\""] # [doc = " sentinel."] pub fn is_word_byte (self) -> bool { self . as_u8 () . map_or (false , crate :: util :: utf8 :: is_word_byte) } }
};
}
