// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_crossbeam_channel_decls_module_not_found_channel,
    wrapped_crossbeam_channel_decls_module_not_found_context,
    wrapped_crossbeam_channel_decls_module_not_found_counter,
    wrapped_crossbeam_channel_decls_module_not_found_err,
    wrapped_crossbeam_channel_decls_module_not_found_flavors,
    wrapped_crossbeam_channel_decls_module_not_found_select,
    wrapped_crossbeam_channel_decls_module_not_found_select_macro,
    wrapped_crossbeam_channel_decls_module_not_found_utils,
    wrapped_crossbeam_channel_decls_module_not_found_waker,
    wrapped_crossbeam_channel_decls_module_not_found_internal
);
