// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
rustc_index::newtype_index! { # [doc = " An `ItemLocalId` uniquely identifies something within a given \"item-like\";"] # [doc = " that is, within a `hir::Item`, `hir::TraitItem`, or `hir::ImplItem`. There is no"] # [doc = " guarantee that the numerical value of a given `ItemLocalId` corresponds to"] # [doc = " the node's position within the owning item in any way, but there is a"] # [doc = " guarantee that the `ItemLocalId`s within an owner occupy a dense range of"] # [doc = " integers starting at zero, so a mapping that maps all or most nodes within"] # [doc = " an \"item-like\" to something else can be implemented by a `Vec` instead of a"] # [doc = " tree or hash map."] # [derive (HashStable_Generic)] # [encodable] # [orderable] pub struct ItemLocalId { } }
