// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Uniquely identifies a node in the HIR of the current crate. It is"]
#[doc = " composed of the `owner`, which is the `LocalDefId` of the directly enclosing"]
#[doc = " `hir::Item`, `hir::TraitItem`, or `hir::ImplItem` (i.e., the closest \"item-like\"),"]
#[doc = " and the `local_id` which is unique within the given owner."]
#[doc = ""]
#[doc = " This two-level structure makes for more stable values: One can move an item"]
#[doc = " around within the source code, or add or remove stuff before it, without"]
#[doc = " the `local_id` part of the `HirId` changing, which is a very useful property in"]
#[doc = " incremental compilation where we have to persist things through changes to"]
#[doc = " the code base."]
#[derive(Copy, Clone, PartialEq, Eq, Hash, Encodable, Decodable, HashStable_Generic)]
#[rustc_pass_by_value]
pub struct HirId {
    pub owner: OwnerId,
    pub local_id: ItemLocalId,
}
