// Generated macro for externref_heap_live_count (function)
macro_rules! Depcrateexternref_heap_live_count {
() => {
// Module: crate
// Provides: {"externref_heap_live_count"}
// Dependencies: {}
# [doc = " Get the count of live `externref`s / `JsValue`s in `wasm-bindgen`'s heap."] # [doc = ""] # [doc = " ## Usage"] # [doc = ""] # [doc = " This is intended for debugging and writing tests."] # [doc = ""] # [doc = " To write a test that asserts against unnecessarily keeping `anref`s /"] # [doc = " `JsValue`s alive:"] # [doc = ""] # [doc = " * get an initial live count,"] # [doc = ""] # [doc = " * perform some series of operations or function calls that should clean up"] # [doc = "   after themselves, and should not keep holding onto `externref`s / `JsValue`s"] # [doc = "   after completion,"] # [doc = ""] # [doc = " * get the final live count,"] # [doc = ""] # [doc = " * and assert that the initial and final counts are the same."] # [doc = ""] # [doc = " ## What is Counted"] # [doc = ""] # [doc = " Note that this only counts the *owned* `externref`s / `JsValue`s that end up in"] # [doc = " `wasm-bindgen`'s heap. It does not count borrowed `externref`s / `JsValue`s"] # [doc = " that are on its stack."] # [doc = ""] # [doc = " For example, these `JsValue`s are accounted for:"] # [doc = ""] # [doc = " ```ignore"] # [doc = " #[wasm_bindgen]"] # [doc = " pub fn my_function(this_is_counted: JsValue) {"] # [doc = "     let also_counted = JsValue::from_str(\"hi\");"] # [doc = "     assert!(wasm_bindgen::externref_heap_live_count() >= 2);"] # [doc = " }"] # [doc = " ```"] # [doc = ""] # [doc = " While this borrowed `JsValue` ends up on the stack, not the heap, and"] # [doc = " therefore is not accounted for:"] # [doc = ""] # [doc = " ```ignore"] # [doc = " #[wasm_bindgen]"] # [doc = " pub fn my_other_function(this_is_not_counted: &JsValue) {"] # [doc = "     // ..."] # [doc = " }"] # [doc = " ```"] pub fn externref_heap_live_count () -> u32 { __wbindgen_externref_heap_live_count () }
};
}
