// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProjectJsonFromCommand {
    #[doc = " The data describing this project, such as its dependencies."]
    pub data: ProjectJsonData,
    #[doc = " The build system specific file that describes this project,"]
    #[doc = " such as a `my-project/BUCK` file."]
    pub buildfile: AbsPathBuf,
}
