// Generated macro for validate_struct (function)
macro_rules! Depcratevalidate_struct {
() => {
// Module: crate
// Provides: {"validate_struct"}
// Dependencies: {}
# [doc = " Checks that `body` contains `pub [u64; limbs]`."] fn validate_struct (ast : & syn :: DeriveInput , limbs : usize) -> Option < proc_macro2 :: TokenStream > { let variant_data = match & ast . data { syn :: Data :: Struct (x) => x , _ => { return Some (syn :: Error :: new_spanned (ast , "PrimeField derive only works for structs.") . to_compile_error () ,) } } ; let fields = match & variant_data . fields { syn :: Fields :: Unnamed (x) if x . unnamed . len () == 1 => x , _ => { return Some (syn :: Error :: new_spanned (& ast . ident , format ! ("The struct must contain an array of limbs. Change this to `{}([u64; {}])`" , ast . ident , limbs ,) ,) . to_compile_error () ,) } } ; let field = & fields . unnamed [0] ; let arr = match & field . ty { syn :: Type :: Array (x) => x , _ => { return Some (syn :: Error :: new_spanned (field , format ! ("The inner field must be an array of limbs. Change this to `[u64; {}]`" , limbs ,) ,) . to_compile_error () ,) } } ; if match arr . elem . as_ref () { syn :: Type :: Path (path) => path . path . get_ident () . map (| x | x . to_string () != "u64") . unwrap_or (true) , _ => true , } { return Some (syn :: Error :: new_spanned (arr , format ! ("PrimeField derive requires 64-bit limbs. Change this to `[u64; {}]" , limbs) ,) . to_compile_error () ,) ; } let expr_lit = match & arr . len { syn :: Expr :: Lit (expr_lit) => Some (& expr_lit . lit) , syn :: Expr :: Group (expr_group) => match & * expr_group . expr { syn :: Expr :: Lit (expr_lit) => Some (& expr_lit . lit) , _ => None , } , _ => None , } ; let lit_int = match match expr_lit { Some (syn :: Lit :: Int (lit_int)) => Some (lit_int) , _ => None , } { Some (x) => x , _ => { return Some (syn :: Error :: new_spanned (arr , format ! ("To derive PrimeField, change this to `[u64; {}]`." , limbs) ,) . to_compile_error () ,) } } ; if lit_int . base10_digits () != limbs . to_string () { return Some (syn :: Error :: new_spanned (lit_int , format ! ("The given modulus requires {} limbs." , limbs) ,) . to_compile_error () ,) ; } match & field . vis { syn :: Visibility :: Inherited => () , _ => { return Some (syn :: Error :: new_spanned (& field . vis , "Field must not be public.") . to_compile_error () ,) } } None }
};
}
