// Generated macro for IVector_Vtbl (struct)
macro_rules! Depcrate_interface_iterableIVector_Vtbl {
() => {
// Module: crate::interface_iterable
// Provides: {"IVector_Vtbl"}
// Dependencies: {}
# [repr (C)] # [doc (hidden)] pub struct IVector_Vtbl < T > where T : windows_core :: RuntimeType + 'static , { pub base__ : windows_core :: IInspectable_Vtbl , pub GetAt : unsafe extern "system" fn (* mut core :: ffi :: c_void , u32 , * mut windows_core :: AbiType < T > ,) -> windows_core :: HRESULT , pub Size : unsafe extern "system" fn (* mut core :: ffi :: c_void , * mut u32) -> windows_core :: HRESULT , GetView : usize , pub IndexOf : unsafe extern "system" fn (* mut core :: ffi :: c_void , windows_core :: AbiType < T > , * mut u32 , * mut bool ,) -> windows_core :: HRESULT , pub SetAt : unsafe extern "system" fn (* mut core :: ffi :: c_void , u32 , windows_core :: AbiType < T > ,) -> windows_core :: HRESULT , pub InsertAt : unsafe extern "system" fn (* mut core :: ffi :: c_void , u32 , windows_core :: AbiType < T > ,) -> windows_core :: HRESULT , pub RemoveAt : unsafe extern "system" fn (* mut core :: ffi :: c_void , u32) -> windows_core :: HRESULT , pub Append : unsafe extern "system" fn (* mut core :: ffi :: c_void , windows_core :: AbiType < T > ,) -> windows_core :: HRESULT , pub RemoveAtEnd : unsafe extern "system" fn (* mut core :: ffi :: c_void) -> windows_core :: HRESULT , pub Clear : unsafe extern "system" fn (* mut core :: ffi :: c_void) -> windows_core :: HRESULT , pub GetMany : unsafe extern "system" fn (* mut core :: ffi :: c_void , u32 , u32 , * mut T , * mut u32 ,) -> windows_core :: HRESULT , pub ReplaceAll : unsafe extern "system" fn (* mut core :: ffi :: c_void , u32 , * const T) -> windows_core :: HRESULT , T : core :: marker :: PhantomData < T > , }
};
}
