// Generated macro for other_4811 (other)
macro_rules! Depcrate_generatedother_4811 {
() => {
// Module: crate::generated
// Provides: {"other_4811"}
// Dependencies: {}
extern "C-unwind" { # [doc = " A request to create a connection to an IOService."] # [doc = ""] # [doc = " A non kernel client may request a connection be opened via the IOServiceOpen() library function, which will call IOService::newUserClient in the kernel. The rules"] # [doc = " &"] # [doc = " capabilities of user level clients are family dependent, the default IOService implementation returns kIOReturnUnsupported."] # [doc = ""] # [doc = " Parameter `service`: The IOService object to open a connection to, usually obtained via the IOServiceGetMatchingServices or IOServiceAddNotification APIs."] # [doc = ""] # [doc = " Parameter `owningTask`: The mach task requesting the connection."] # [doc = ""] # [doc = " Parameter `type`: A constant specifying the type of connection to be created,  interpreted only by the IOService's family."] # [doc = ""] # [doc = " Parameter `connect`: An io_connect_t handle is returned on success, to be used with the IOConnectXXX APIs. It should be destroyed with IOServiceClose()."] # [doc = ""] # [doc = " Returns: A return code generated by IOService::newUserClient."] # [doc = ""] # [doc = " # Safety"] # [doc = ""] # [doc = " `connect` must be a valid pointer."] # [cfg (feature = "libc")] pub fn IOServiceOpen (service : io_service_t , owning_task : task_port_t , r#type : u32 , connect : * mut io_connect_t ,) -> libc :: kern_return_t ; }
};
}
