// Generated macro for macro_930 (macro)
macro_rules! Depcrate_ssl_biomacro_930 {
() => {
// Module: crate::ssl::bio
// Provides: {"macro_930"}
// Dependencies: {}
cfg_if ! { if # [cfg (any (ossl110 , libressl , boringssl))] { use ffi :: { BIO_get_data , BIO_set_data , BIO_set_flags , BIO_set_init } ; use crate :: cvt ; # [allow (bad_style)] unsafe fn BIO_set_num (_bio : * mut ffi :: BIO , _num : c_int) { } # [allow (bad_style , clippy :: upper_case_acronyms)] struct BIO_METHOD (* mut ffi :: BIO_METHOD) ; impl BIO_METHOD { fn new < S : Read + Write > () -> Result < BIO_METHOD , ErrorStack > { # [cfg (not (boringssl))] use ffi :: { BIO_meth_set_write__fixed_rust as BIO_meth_set_write , BIO_meth_set_read__fixed_rust as BIO_meth_set_read , BIO_meth_set_puts__fixed_rust as BIO_meth_set_puts , BIO_meth_set_ctrl__fixed_rust as BIO_meth_set_ctrl , BIO_meth_set_create__fixed_rust as BIO_meth_set_create , BIO_meth_set_destroy__fixed_rust as BIO_meth_set_destroy , } ; # [cfg (boringssl)] use ffi :: { BIO_meth_set_write , BIO_meth_set_read , BIO_meth_set_puts , BIO_meth_set_ctrl , BIO_meth_set_create , BIO_meth_set_destroy , } ; unsafe { let ptr = cvt_p (ffi :: BIO_meth_new (ffi :: BIO_TYPE_NONE , b"rust\0" . as_ptr () as * const _)) ?; let method = BIO_METHOD (ptr) ; cvt (BIO_meth_set_write (method . 0 , Some (bwrite ::< S >))) ?; cvt (BIO_meth_set_read (method . 0 , Some (bread ::< S >))) ?; cvt (BIO_meth_set_puts (method . 0 , Some (bputs ::< S >))) ?; cvt (BIO_meth_set_ctrl (method . 0 , Some (ctrl ::< S >))) ?; cvt (BIO_meth_set_create (method . 0 , Some (create))) ?; cvt (BIO_meth_set_destroy (method . 0 , Some (destroy ::< S >))) ?; Ok (method) } } fn get (& self) -> * mut ffi :: BIO_METHOD { self . 0 } } impl Drop for BIO_METHOD { fn drop (& mut self) { unsafe { ffi :: BIO_meth_free (self . 0) ; } } } } else { # [allow (bad_style , clippy :: upper_case_acronyms)] struct BIO_METHOD (* mut ffi :: BIO_METHOD) ; impl BIO_METHOD { fn new < S : Read + Write > () -> Result < BIO_METHOD , ErrorStack > { let ptr = Box :: new (ffi :: BIO_METHOD { type_ : ffi :: BIO_TYPE_NONE , name : b"rust\0" . as_ptr () as * const _ , bwrite : Some (bwrite ::< S >) , bread : Some (bread ::< S >) , bputs : Some (bputs ::< S >) , bgets : None , ctrl : Some (ctrl ::< S >) , create : Some (create) , destroy : Some (destroy ::< S >) , callback_ctrl : None , }) ; Ok (BIO_METHOD (Box :: into_raw (ptr))) } fn get (& self) -> * mut ffi :: BIO_METHOD { self . 0 } } impl Drop for BIO_METHOD { fn drop (& mut self) { unsafe { let _ = Box ::< ffi :: BIO_METHOD >:: from_raw (self . 0) ; } } } # [allow (bad_style)] unsafe fn BIO_set_init (bio : * mut ffi :: BIO , init : c_int) { (* bio) . init = init ; } # [allow (bad_style)] unsafe fn BIO_set_flags (bio : * mut ffi :: BIO , flags : c_int) { (* bio) . flags = flags ; } # [allow (bad_style)] unsafe fn BIO_get_data (bio : * mut ffi :: BIO) -> * mut c_void { (* bio) . ptr } # [allow (bad_style)] unsafe fn BIO_set_data (bio : * mut ffi :: BIO , data : * mut c_void) { (* bio) . ptr = data ; } # [allow (bad_style)] unsafe fn BIO_set_num (bio : * mut ffi :: BIO , num : c_int) { (* bio) . num = num ; } } }
};
}
