// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
impl Clone for SmolStr {
    #[inline]
    fn clone(&self) -> Self {
        #[cold]
        #[inline(never)]
        fn cold_clone(v: &SmolStr) -> SmolStr {
            SmolStr(v.0.clone())
        }
        if self.is_heap_allocated() {
            return cold_clone(self);
        }
        unsafe { core::ptr::read(self as *const SmolStr) }
    }
}
