// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
impl<'a> TryFrom<&'a [u8]> for &'a ObjectIdentifierRef {
    type Error = Error;
    fn try_from(ber_bytes: &'a [u8]) -> Result<Self> {
        ObjectIdentifierRef::from_bytes(ber_bytes)
    }
}
