macro_rules! NT_GO_BUILD_ID {
    () => {
        # [doc = " Build ID bits as generated by Go's gc compiler."] # [doc = ""] # [doc = " The descriptor consists of any nonzero number of bytes."] pub const NT_GO_BUILD_ID : u32 = 4 ;
    };
}

NT_GO_BUILD_ID!()