// Generated macro for detect (module)
macro_rules! Depcrate_ditdetect {
() => {
// Module: crate::dit
// Provides: {"detect"}
// Dependencies: {}
# [cfg (not (all (target_feature = "dit" , target_feature = "sb")))] mod detect { use super :: Features ; use core :: mem :: transmute ; use core :: sync :: atomic :: { AtomicU8 , Ordering } ; static FEATURES : AtomicU8 = AtomicU8 :: new (0) ; # [doc = " Determines whether `FEAT_DIT` and `FEAT_SB` are known to be implemented."] # [inline] pub fn get_aarch64_dit_sb_features () -> Features { let features = FEATURES . load (Ordering :: Relaxed) ; if features > 0 { unsafe { transmute :: < u8 , Features > (features) } } else { detect_aarch64_dit_sb_features () } } # [doc = " Records whether `FEAT_DIT` and `FEAT_SB` are known to be implemented."] # [doc = ""] # [doc = " # Safety"] # [doc = ""] # [doc = " Either parameter must not be set to true if the corresponding feature"] # [doc = " is not implemented."] pub unsafe fn set_aarch64_dit_sb_features (dit : bool , sb : bool) -> Features { let dit = dit || cfg ! (target_feature = "dit") ; let sb = sb || cfg ! (target_feature = "sb") ; let features = match (dit , sb) { (true , true) => Features :: DitSb , (true , false) => Features :: DitOnly , _ => Features :: Neither , } ; let _ = FEATURES . compare_exchange (0 , features as u8 , Ordering :: Relaxed , Ordering :: Relaxed) ; features } # [doc = " Detects whether `FEAT_DIT` and `FEAT_SB` are known to be implemented."] # [cfg (feature = "std")] # [cold] fn detect_aarch64_dit_sb_features () -> Features { use std :: arch :: is_aarch64_feature_detected ; unsafe { set_aarch64_dit_sb_features (is_aarch64_feature_detected ! ("dit") , is_aarch64_feature_detected ! ("sb") ,) } } # [doc = " Detects whether `FEAT_DIT` and `FEAT_SB` are known to be implemented."] # [cfg (not (feature = "std"))] # [cold] fn detect_aarch64_dit_sb_features () -> Features { unsafe { set_aarch64_dit_sb_features (cfg ! (target_feature = "dit") , cfg ! (target_feature = "sb")) } } }
};
}
