// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[derive(Copy, Clone, Debug)]
enum AllowReturnTypeNotation {
    #[doc = " Only in types, since RTN is denied later during HIR lowering."]
    Yes,
    #[doc = " All other positions (path expr, method, use tree)."]
    No,
}
