// crate_loader.rs - Load and wrap external crates from ../../.gitmodules
// Generated by step4_bootstrap - Crate Integration System

use std::fs;
use std::path::Path;
use anyhow::Result;

pub struct CrateInfo {
    pub name: String,
    pub path: String,
    pub declarations: Vec<String>,
    pub names: Vec<String>,
}

pub fn discover_available_crates() -> Result<Vec<String>> {
    let gitmodules_path = Path::new("../../.gitmodules");
    if !gitmodules_path.exists() {
        return Ok(vec!["anyhow".to_string(), "serde".to_string()]); // fallback
    }
    
    let content = fs::read_to_string(gitmodules_path)?;
    let crates: Vec<String> = content
        .lines()
        .filter(|line| line.contains("path = "))
        .map(|line| {
            line.split("path = ")
                .nth(1)
                .unwrap_or("")
                .trim_matches('"')
                .split('/')
                .last()
                .unwrap_or("unknown")
                .to_string()
        })
        .collect();
    
    Ok(crates)
}

pub fn load_crate_source(crate_name: &str) -> Result<String> {
    let crate_path = format!("../../{}", crate_name);
    let lib_path = format!("{}/src/lib.rs", crate_path);
    
    if Path::new(&lib_path).exists() {
        Ok(fs::read_to_string(lib_path)?)
    } else {
        Ok(format!("// Placeholder for {}", crate_name))
    }
}

pub fn extract_declarations(source: &str) -> Vec<String> {
    let mut declarations = Vec::new();
    
    for line in source.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("pub fn ") ||
           trimmed.starts_with("fn ") ||
           trimmed.starts_with("pub struct ") ||
           trimmed.starts_with("struct ") ||
           trimmed.starts_with("pub enum ") ||
           trimmed.starts_with("enum ") ||
           trimmed.starts_with("pub trait ") ||
           trimmed.starts_with("trait ") ||
           trimmed.starts_with("pub mod ") ||
           trimmed.starts_with("mod ") ||
           trimmed.starts_with("pub type ") ||
           trimmed.starts_with("type ") ||
           trimmed.starts_with("pub const ") ||
           trimmed.starts_with("const ") ||
           trimmed.starts_with("pub static ") ||
           trimmed.starts_with("static ") ||
           trimmed.starts_with("macro_rules!") ||
           trimmed.starts_with("impl ") ||
           trimmed.starts_with("use ") ||
           trimmed.contains("#[derive(") ||
           trimmed.contains("#[macro_export]") {
            declarations.push(trimmed.to_string());
        }
    }
    
    declarations
}

pub fn extract_names(declarations: &[String]) -> Vec<String> {
    declarations
        .iter()
        .filter_map(|decl| {
            if let Some(name_part) = decl.split_whitespace().nth(2) {
                Some(name_part.split('(').next().unwrap_or(name_part).to_string())
            } else {
                None
            }
        })
        .collect()
}

pub fn wrap_crate_as_macro(crate_info: &CrateInfo) -> String {
    format!(
        r#"// Wrapped crate: {}
#[macro_export]
macro_rules! mk{} {{
    () => {{
        println!("Loading crate: {}", "{}");
    }};
}}
"#,
        crate_info.name,
        crate_info.name,
        crate_info.name,
        crate_info.name
    )
}
