/* FP:solve.rs-0001 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_hir_analysis_src_variance_solve_USE_0001
/* FP:solve.rs-0002 */ use crate :: rustc_complete :: def_id :: DefIdMap ;
/* FP:solve.rs-0003 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_hir_analysis_src_variance_solve_USE_0002
/* FP:solve.rs-0004 */ use crate :: rustc_complete :: ty ;
/* FP:solve.rs-0005 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_hir_analysis_src_variance_solve_USE_0003
/* FP:solve.rs-0006 */ use tracing :: debug ;
/* FP:solve.rs-0007 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_hir_analysis_src_variance_solve_USE_0004
/* FP:solve.rs-0008 */ use super :: constraints :: * ;
/* FP:solve.rs-0009 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_hir_analysis_src_variance_solve_USE_0005
/* FP:solve.rs-0010 */ use super :: terms :: VarianceTerm :: * ;
/* FP:solve.rs-0011 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_hir_analysis_src_variance_solve_USE_0006
/* FP:solve.rs-0012 */ use super :: terms :: * ;
/* FP:solve.rs-0013 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_hir_analysis_src_variance_solve_FN_0007
/* FP:solve.rs-0014 */ fn glb (v1 : ty :: Variance , v2 : ty :: Variance) -> ty :: Variance { match (v1 , v2) { (ty :: Invariant , _) | (_ , ty :: Invariant) => ty :: Invariant , (ty :: Covariant , ty :: Contravariant) => ty :: Invariant , (ty :: Contravariant , ty :: Covariant) => ty :: Invariant , (ty :: Covariant , ty :: Covariant) => ty :: Covariant , (ty :: Contravariant , ty :: Contravariant) => ty :: Contravariant , (x , ty :: Bivariant) | (ty :: Bivariant , x) => x , } }
/* FP:solve.rs-0015 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_hir_analysis_src_variance_solve_STRUCT_0008
/* FP:solve.rs-0016 */ struct SolveContext < 'a , 'tcx > { terms_cx : TermsContext < 'a , 'tcx > , constraints : Vec < Constraint < 'a > > , solutions : Vec < ty :: Variance > , }
/* FP:solve.rs-0017 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_hir_analysis_src_variance_solve_FN_0009
/* FP:solve.rs-0018 */ pub (crate) fn solve_constraints < 'tcx > (constraints_cx : ConstraintContext < '_ , 'tcx > ,) -> ty :: CrateVariancesMap < 'tcx > { let ConstraintContext { terms_cx , constraints , .. } = constraints_cx ; let mut solutions = vec ! [ty :: Bivariant ; terms_cx . inferred_terms . len ()] ; for (id , variances) in & terms_cx . lang_items { let InferredIndex (start) = terms_cx . inferred_starts [id] ; for (i , & variance) in variances . iter () . enumerate () { solutions [start + i] = variance ; } } let mut solutions_cx = SolveContext { terms_cx , constraints , solutions } ; solutions_cx . solve () ; let variances = solutions_cx . create_map () ; ty :: CrateVariancesMap { variances } }
/* FP:solve.rs-0019 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_hir_analysis_src_variance_solve_IMPL_0010
/* FP:solve.rs-0020 */ impl < 'a , 'tcx > SolveContext < 'a , 'tcx > { fn solve (& mut self) { let mut changed = true ; while changed { changed = false ; for constraint in & self . constraints { let Constraint { inferred , variance : term } = * constraint ; let InferredIndex (inferred) = inferred ; let variance = self . evaluate (term) ; let old_value = self . solutions [inferred] ; let new_value = glb (variance , old_value) ; if old_value != new_value { debug ! ("updating inferred {} \
/* FP:solve.rs-0021 */                             from {:?} to {:?} due to {:?}" , inferred , old_value , new_value , term) ; self . solutions [inferred] = new_value ; changed = true ; } } } } fn enforce_const_invariance (& self , generics : & ty :: Generics , variances : & mut [ty :: Variance]) { let tcx = self . terms_cx . tcx ; for param in generics . own_params . iter () { if let ty :: GenericParamDefKind :: Const { .. } = param . kind { variances [param . index as usize] = ty :: Invariant ; } } if let Some (def_id) = generics . parent { self . enforce_const_invariance (tcx . generics_of (def_id) , variances) ; } } fn create_map (& self) -> DefIdMap < & 'tcx [ty :: Variance] > { let tcx = self . terms_cx . tcx ; let solutions = & self . solutions ; DefIdMap :: from (self . terms_cx . inferred_starts . items () . map (| (& def_id , & InferredIndex (start)) | { let generics = tcx . generics_of (def_id) ; let count = generics . count () ; let variances = tcx . arena . alloc_slice (& solutions [start .. (start + count)]) ; self . enforce_const_invariance (generics , variances) ; if let ty :: FnDef (..) = tcx . type_of (def_id) . instantiate_identity () . kind () { for variance in variances . iter_mut () { if * variance == ty :: Bivariant { * variance = ty :: Invariant ; } } } (def_id . to_def_id () , & * variances) } ,)) } fn evaluate (& self , term : VarianceTermPtr < 'a >) -> ty :: Variance { match * term { ConstantTerm (v) => v , TransformTerm (t1 , t2) => { let v1 = self . evaluate (t1) ; let v2 = self . evaluate (t2) ; v1 . xform (v2) } InferredTerm (InferredIndex (index)) => self . solutions [index] , } } }