/* FP:consts.rs-0001 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_USE_0001
/* FP:consts.rs-0002 */ use std :: ops :: Range ;
/* FP:consts.rs-0003 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_USE_0002
/* FP:consts.rs-0004 */ use crate :: rustc_abi :: { Align , HasDataLayout , Primitive , Scalar , Size , WrappingRange } ;
/* FP:consts.rs-0005 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_USE_0003
/* FP:consts.rs-0006 */ use crate :: rustc_codegen_ssa :: common ;
/* FP:consts.rs-0007 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_USE_0004
/* FP:consts.rs-0008 */ use crate :: rustc_codegen_ssa :: traits :: * ;
/* FP:consts.rs-0009 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_USE_0005
/* FP:consts.rs-0010 */ use crate :: rustc_complete :: LangItem ;
/* FP:consts.rs-0011 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_USE_0006
/* FP:consts.rs-0012 */ use crate :: rustc_complete :: attrs :: Linkage ;
/* FP:consts.rs-0013 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_USE_0007
/* FP:consts.rs-0014 */ use crate :: rustc_complete :: def :: DefKind ;
/* FP:consts.rs-0015 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_USE_0008
/* FP:consts.rs-0016 */ use crate :: rustc_complete :: def_id :: { DefId , LOCAL_CRATE } ;
/* FP:consts.rs-0017 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_USE_0009
/* FP:consts.rs-0018 */ use crate :: rustc_complete :: middle :: codegen_fn_attrs :: { CodegenFnAttrFlags , CodegenFnAttrs } ;
/* FP:consts.rs-0019 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_USE_0010
/* FP:consts.rs-0020 */ use crate :: rustc_complete :: mir :: interpret :: { Allocation , ConstAllocation , ErrorHandled , InitChunk , Pointer , Scalar as InterpScalar , read_target_uint , } ;
/* FP:consts.rs-0021 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_USE_0011
/* FP:consts.rs-0022 */ use crate :: rustc_complete :: mir :: mono :: MonoItem ;
/* FP:consts.rs-0023 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_USE_0012
/* FP:consts.rs-0024 */ use crate :: rustc_complete :: ty :: layout :: { HasTypingEnv , LayoutOf } ;
/* FP:consts.rs-0025 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_USE_0013
/* FP:consts.rs-0026 */ use crate :: rustc_complete :: ty :: { self , Instance } ;
/* FP:consts.rs-0027 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_USE_0014
/* FP:consts.rs-0028 */ use crate :: rustc_complete :: { bug , span_bug } ;
/* FP:consts.rs-0029 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_USE_0015
/* FP:consts.rs-0030 */ use tracing :: { debug , instrument , trace } ;
/* FP:consts.rs-0031 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_USE_0016
/* FP:consts.rs-0032 */ use crate :: common :: CodegenCx ;
/* FP:consts.rs-0033 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_USE_0017
/* FP:consts.rs-0034 */ use crate :: errors :: SymbolAlreadyDefined ;
/* FP:consts.rs-0035 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_USE_0018
/* FP:consts.rs-0036 */ use crate :: type_ :: Type ;
/* FP:consts.rs-0037 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_USE_0019
/* FP:consts.rs-0038 */ use crate :: type_of :: LayoutLlvmExt ;
/* FP:consts.rs-0039 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_USE_0020
/* FP:consts.rs-0040 */ use crate :: value :: Value ;
/* FP:consts.rs-0041 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_USE_0021
/* FP:consts.rs-0042 */ use crate :: { base , debuginfo , llvm } ;
/* FP:consts.rs-0043 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_FN_0022
/* FP:consts.rs-0044 */ pub (crate) fn const_alloc_to_llvm < 'll > (cx : & CodegenCx < 'll , '_ > , alloc : & Allocation , is_static : bool ,) -> & 'll Value { if ! is_static { assert ! (alloc . len () != 0) ; } let mut llvals = Vec :: with_capacity (alloc . provenance () . ptrs () . len () + 1) ; let dl = cx . data_layout () ; let pointer_size = dl . pointer_size () ; let pointer_size_bytes = pointer_size . bytes () as usize ; fn append_chunks_of_init_and_uninit_bytes < 'll , 'a , 'b > (llvals : & mut Vec < & 'll Value > , cx : & 'a CodegenCx < 'll , 'b > , alloc : & 'a Allocation , range : Range < usize > ,) { let chunks = alloc . init_mask () . range_as_init_chunks (range . clone () . into ()) ; let chunk_to_llval = move | chunk | match chunk { InitChunk :: Init (range) => { let range = (range . start . bytes () as usize) .. (range . end . bytes () as usize) ; let bytes = alloc . inspect_with_uninit_and_ptr_outside_interpreter (range) ; cx . const_bytes (bytes) } InitChunk :: Uninit (range) => { let len = range . end . bytes () - range . start . bytes () ; cx . const_undef (cx . type_array (cx . type_i8 () , len)) } } ; let max = cx . sess () . opts . unstable_opts . uninit_const_chunk_threshold ; let allow_uninit_chunks = chunks . clone () . take (max . saturating_add (1)) . count () <= max ; if allow_uninit_chunks { llvals . extend (chunks . map (chunk_to_llval)) ; } else { let bytes = alloc . inspect_with_uninit_and_ptr_outside_interpreter (range) ; llvals . push (cx . const_bytes (bytes)) ; } } let mut next_offset = 0 ; for & (offset , prov) in alloc . provenance () . ptrs () . iter () { let offset = offset . bytes () ; assert_eq ! (offset as usize as u64 , offset) ; let offset = offset as usize ; if offset > next_offset { append_chunks_of_init_and_uninit_bytes (& mut llvals , cx , alloc , next_offset .. offset) ; } let ptr_offset = read_target_uint (dl . endian , alloc . inspect_with_uninit_and_ptr_outside_interpreter (offset .. (offset + pointer_size_bytes) ,) ,) . expect ("const_alloc_to_llvm: could not read relocation pointer") as u64 ; let address_space = cx . tcx . global_alloc (prov . alloc_id ()) . address_space (cx) ; llvals . push (cx . scalar_to_backend (InterpScalar :: from_pointer (Pointer :: new (prov , Size :: from_bytes (ptr_offset)) , & cx . tcx) , Scalar :: Initialized { value : Primitive :: Pointer (address_space) , valid_range : WrappingRange :: full (pointer_size) , } , cx . type_ptr_ext (address_space) ,)) ; next_offset = offset + pointer_size_bytes ; } if alloc . len () >= next_offset { let range = next_offset .. alloc . len () ; append_chunks_of_init_and_uninit_bytes (& mut llvals , cx , alloc , range) ; } if let & [data] = & * llvals { data } else { cx . const_struct (& llvals , true) } }
/* FP:consts.rs-0045 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_FN_0023
/* FP:consts.rs-0046 */ fn codegen_static_initializer < 'll , 'tcx > (cx : & CodegenCx < 'll , 'tcx > , def_id : DefId ,) -> Result < (& 'll Value , ConstAllocation < 'tcx >) , ErrorHandled > { let alloc = cx . tcx . eval_static_initializer (def_id) ? ; Ok ((const_alloc_to_llvm (cx , alloc . inner () , true) , alloc)) }
/* FP:consts.rs-0047 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_FN_0024
/* FP:consts.rs-0048 */ fn set_global_alignment < 'll > (cx : & CodegenCx < 'll , '_ > , gv : & 'll Value , mut align : Align) { if let Some (min_global) = cx . sess () . target . min_global_align { align = Ord :: max (align , min_global) ; } llvm :: set_alignment (gv , align) ; }
/* FP:consts.rs-0049 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_FN_0025
/* FP:consts.rs-0050 */ fn check_and_apply_linkage < 'll , 'tcx > (cx : & CodegenCx < 'll , 'tcx > , attrs : & CodegenFnAttrs , llty : & 'll Type , sym : & str , def_id : DefId ,) -> & 'll Value { if let Some (linkage) = attrs . import_linkage { debug ! ("get_static: sym={} linkage={:?}" , sym , linkage) ; let g1 = if matches ! (attrs . import_linkage , Some (Linkage :: ExternalWeak)) { let instance = Instance :: mono (cx . tcx , def_id) ; if let ty :: Adt (struct_def , args) = instance . ty (cx . tcx , cx . typing_env ()) . kind () && cx . tcx . is_lang_item (struct_def . did () , LangItem :: Option) && let ty :: FnPtr (sig , header) = args . type_at (0) . kind () { let fn_sig = sig . with (* header) ; let fn_abi = cx . fn_abi_of_fn_ptr (fn_sig , ty :: List :: empty ()) ; cx . declare_fn (sym , & fn_abi , None) } else { cx . declare_global (sym , cx . type_i8 ()) } } else { cx . declare_global (sym , cx . type_i8 ()) } ; llvm :: set_linkage (g1 , base :: linkage_to_llvm (linkage)) ; let real_name = format ! ("_rust_extern_with_linkage_{:016x}_{sym}" , cx . tcx . stable_crate_id (LOCAL_CRATE)) ; let g2 = cx . define_global (& real_name , llty) . unwrap_or_else (| | { cx . sess () . dcx () . emit_fatal (SymbolAlreadyDefined { span : cx . tcx . def_span (def_id) , symbol_name : sym , }) }) ; llvm :: set_linkage (g2 , llvm :: Linkage :: InternalLinkage) ; llvm :: set_initializer (g2 , g1) ; g2 } else if cx . tcx . sess . target . arch == "x86" && common :: is_mingw_gnu_toolchain (& cx . tcx . sess . target) && let Some (dllimport) = crate :: common :: get_dllimport (cx . tcx , def_id , sym) { cx . declare_global (& common :: i686_decorated_name (dllimport , true , true , false) , llty) } else { cx . declare_global (sym , llty) } }
/* FP:consts.rs-0051 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_IMPL_0026
/* FP:consts.rs-0052 */ impl < 'll > CodegenCx < 'll , '_ > { pub (crate) fn const_bitcast (& self , val : & 'll Value , ty : & 'll Type) -> & 'll Value { unsafe { llvm :: LLVMConstBitCast (val , ty) } } pub (crate) fn const_pointercast (& self , val : & 'll Value , ty : & 'll Type) -> & 'll Value { unsafe { llvm :: LLVMConstPointerCast (val , ty) } } # [doc = " Create a global variable."] # [doc = ""] # [doc = " The returned global variable is a pointer in the default address space for globals."] # [doc = " Fails if a symbol with the given name already exists."] pub (crate) fn static_addr_of_mut (& self , cv : & 'll Value , align : Align , kind : Option < & str > ,) -> & 'll Value { let gv = match kind { Some (kind) if ! self . tcx . sess . fewer_names () => { let name = self . generate_local_symbol_name (kind) ; let gv = self . define_global (& name , self . val_ty (cv)) . unwrap_or_else (| | { bug ! ("symbol `{}` is already defined" , name) ; }) ; llvm :: set_linkage (gv , llvm :: Linkage :: PrivateLinkage) ; gv } _ => self . define_private_global (self . val_ty (cv)) , } ; llvm :: set_initializer (gv , cv) ; set_global_alignment (self , gv , align) ; llvm :: set_unnamed_address (gv , llvm :: UnnamedAddr :: Global) ; gv } # [doc = " Create a global constant."] # [doc = ""] # [doc = " The returned global variable is a pointer in the default address space for globals."] pub (crate) fn static_addr_of_impl (& self , cv : & 'll Value , align : Align , kind : Option < & str > ,) -> & 'll Value { if let Some (& gv) = self . const_globals . borrow () . get (& cv) { unsafe { let llalign = align . bytes () as u32 ; if llalign > llvm :: LLVMGetAlignment (gv) { llvm :: LLVMSetAlignment (gv , llalign) ; } } return gv ; } let gv = self . static_addr_of_mut (cv , align , kind) ; llvm :: set_global_constant (gv , true) ; self . const_globals . borrow_mut () . insert (cv , gv) ; gv } # [instrument (level = "debug" , skip (self))] pub (crate) fn get_static (& self , def_id : DefId) -> & 'll Value { let instance = Instance :: mono (self . tcx , def_id) ; trace ! (? instance) ; let DefKind :: Static { nested , .. } = self . tcx . def_kind (def_id) else { bug ! () } ; let llty = if nested { self . type_i8 () } else { let ty = instance . ty (self . tcx , self . typing_env ()) ; trace ! (? ty) ; self . layout_of (ty) . llvm_type (self) } ; self . get_static_inner (def_id , llty) } # [instrument (level = "debug" , skip (self , llty))] fn get_static_inner (& self , def_id : DefId , llty : & 'll Type) -> & 'll Value { let instance = Instance :: mono (self . tcx , def_id) ; if let Some (& g) = self . instances . borrow () . get (& instance) { trace ! ("used cached value") ; return g ; } let defined_in_current_codegen_unit = self . codegen_unit . items () . contains_key (& MonoItem :: Static (def_id)) ; assert ! (! defined_in_current_codegen_unit , "consts::get_static() should always hit the cache for \
/* FP:consts.rs-0054 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_codegen_llvm_src_consts_IMPL_0027
/* FP:consts.rs-0055 */ impl < 'll > StaticCodegenMethods for CodegenCx < 'll , '_ > { # [doc = " Get a pointer to a global variable."] # [doc = ""] # [doc = " The pointer will always be in the default address space. If global variables default to"] # [doc = " a different address space, an addrspacecast is inserted."] fn static_addr_of (& self , cv : & 'll Value , align : Align , kind : Option < & str >) -> & 'll Value { let gv = self . static_addr_of_impl (cv , align , kind) ; self . const_pointercast (gv , self . type_ptr ()) } fn codegen_static (& mut self , def_id : DefId) { self . codegen_static_item (def_id) } }