/* FP:custom.rs-0001 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_trait_selection_src_traits_query_type_op_custom_USE_0001
/* FP:custom.rs-0002 */ use std :: fmt ;
/* FP:custom.rs-0003 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_trait_selection_src_traits_query_type_op_custom_USE_0002
/* FP:custom.rs-0004 */ use crate :: rustc_complete :: ErrorGuaranteed ;
/* FP:custom.rs-0005 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_trait_selection_src_traits_query_type_op_custom_USE_0003
/* FP:custom.rs-0006 */ use crate :: rustc_complete :: def_id :: LocalDefId ;
/* FP:custom.rs-0007 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_trait_selection_src_traits_query_type_op_custom_USE_0004
/* FP:custom.rs-0008 */ use crate :: rustc_infer :: infer :: region_constraints :: RegionConstraintData ;
/* FP:custom.rs-0009 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_trait_selection_src_traits_query_type_op_custom_USE_0005
/* FP:custom.rs-0010 */ use crate :: rustc_complete :: traits :: query :: NoSolution ;
/* FP:custom.rs-0011 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_trait_selection_src_traits_query_type_op_custom_USE_0006
/* FP:custom.rs-0012 */ use crate :: rustc_complete :: ty :: { TyCtxt , TypeFoldable } ;
/* FP:custom.rs-0013 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_trait_selection_src_traits_query_type_op_custom_USE_0007
/* FP:custom.rs-0014 */ use crate :: rustc_complete :: Span ;
/* FP:custom.rs-0015 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_trait_selection_src_traits_query_type_op_custom_USE_0008
/* FP:custom.rs-0016 */ use tracing :: info ;
/* FP:custom.rs-0017 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_trait_selection_src_traits_query_type_op_custom_USE_0009
/* FP:custom.rs-0018 */ use crate :: infer :: InferCtxt ;
/* FP:custom.rs-0019 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_trait_selection_src_traits_query_type_op_custom_USE_0010
/* FP:custom.rs-0020 */ use crate :: infer :: canonical :: query_response ;
/* FP:custom.rs-0021 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_trait_selection_src_traits_query_type_op_custom_USE_0011
/* FP:custom.rs-0022 */ use crate :: traits :: ObligationCtxt ;
/* FP:custom.rs-0023 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_trait_selection_src_traits_query_type_op_custom_USE_0012
/* FP:custom.rs-0024 */ use crate :: traits :: query :: type_op :: TypeOpOutput ;
/* FP:custom.rs-0025 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_trait_selection_src_traits_query_type_op_custom_STRUCT_0013
/* FP:custom.rs-0026 */ pub struct CustomTypeOp < F > { closure : F , description : & 'static str , }
/* FP:custom.rs-0027 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_trait_selection_src_traits_query_type_op_custom_IMPL_0014
/* FP:custom.rs-0028 */ impl < F > CustomTypeOp < F > { pub fn new < 'tcx , R > (closure : F , description : & 'static str) -> Self where F : FnOnce (& ObligationCtxt < '_ , 'tcx >) -> Result < R , NoSolution > , { CustomTypeOp { closure , description } } }
/* FP:custom.rs-0029 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_trait_selection_src_traits_query_type_op_custom_IMPL_0015
/* FP:custom.rs-0030 */ impl < 'tcx , F , R > super :: TypeOp < 'tcx > for CustomTypeOp < F > where F : FnOnce (& ObligationCtxt < '_ , 'tcx >) -> Result < R , NoSolution > , R : fmt :: Debug + TypeFoldable < TyCtxt < 'tcx > > , { type Output = R ; # [doc = " We can't do any custom error reporting for `CustomTypeOp`, so"] # [doc = " we can use `!` to enforce that the implementation never provides it."] type ErrorInfo = ! ; # [doc = " Processes the operation and all resulting obligations,"] # [doc = " returning the final result along with any region constraints"] # [doc = " (they will be given over to the NLL region solver)."] fn fully_perform (self , infcx : & InferCtxt < 'tcx > , root_def_id : LocalDefId , span : Span ,) -> Result < TypeOpOutput < 'tcx , Self > , ErrorGuaranteed > { if cfg ! (debug_assertions) { info ! ("fully_perform({:?})" , self) ; } Ok (scrape_region_constraints (infcx , root_def_id , self . description , span , self . closure) ? . 0) } }
/* FP:custom.rs-0031 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_trait_selection_src_traits_query_type_op_custom_IMPL_0016
/* FP:custom.rs-0032 */ impl < F > fmt :: Debug for CustomTypeOp < F > { fn fmt (& self , f : & mut fmt :: Formatter < '_ >) -> fmt :: Result { self . description . fmt (f) } }
/* FP:custom.rs-0033 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_trait_selection_src_traits_query_type_op_custom_FN_0017
/* FP:custom.rs-0034 */ # [doc = " Executes `op` and then scrapes out all the \"old style\" region"] # [doc = " constraints that result, creating query-region-constraints."] pub fn scrape_region_constraints < 'tcx , Op , R > (infcx : & InferCtxt < 'tcx > , root_def_id : LocalDefId , name : & 'static str , span : Span , op : impl FnOnce (& ObligationCtxt < '_ , 'tcx >) -> Result < R , NoSolution > ,) -> Result < (TypeOpOutput < 'tcx , Op > , RegionConstraintData < 'tcx >) , ErrorGuaranteed > where R : TypeFoldable < TyCtxt < 'tcx > > , Op : super :: TypeOp < 'tcx , Output = R > , { let pre_obligations = infcx . take_registered_region_obligations () ; assert ! (pre_obligations . is_empty () , "scrape_region_constraints: incoming region obligations = {pre_obligations:#?}" ,) ; let pre_assumptions = infcx . take_registered_region_assumptions () ; assert ! (pre_assumptions . is_empty () , "scrape_region_constraints: incoming region assumptions = {pre_assumptions:#?}" ,) ; let value = infcx . commit_if_ok (| _ | { let ocx = ObligationCtxt :: new (infcx) ; let value = op (& ocx) . map_err (| _ | { infcx . dcx () . span_delayed_bug (span , format ! ("error performing operation: {name}")) }) ? ; let errors = ocx . select_all_or_error () ; if errors . is_empty () { Ok (value) } else if let Err (guar) = infcx . tcx . check_potentially_region_dependent_goals (root_def_id) { Err (guar) } else { Err (infcx . dcx () . delayed_bug (format ! ("errors selecting obligation during MIR typeck: {errors:?}"))) } }) ? ; let value = infcx . resolve_vars_if_possible (value) ; let region_obligations = infcx . take_registered_region_obligations () ; let region_assumptions = infcx . take_registered_region_assumptions () ; let region_constraint_data = infcx . take_and_reset_region_constraints () ; let region_constraints = query_response :: make_query_region_constraints (region_obligations , & region_constraint_data , region_assumptions ,) ; if region_constraints . is_empty () { Ok ((TypeOpOutput { output : value , constraints : None , error_info : None } , region_constraint_data ,)) } else { Ok ((TypeOpOutput { output : value , constraints : Some (infcx . tcx . arena . alloc (region_constraints)) , error_info : None , } , region_constraint_data ,)) } }