/* FP:check_export.rs-0001 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_USE_0001
/* FP:check_export.rs-0002 */ use std :: iter ;
/* FP:check_export.rs-0003 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_USE_0002
/* FP:check_export.rs-0004 */ use std :: ops :: ControlFlow ;
/* FP:check_export.rs-0005 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_USE_0003
/* FP:check_export.rs-0006 */ use crate :: rustc_abi :: ExternAbi ;
/* FP:check_export.rs-0007 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_USE_0004
/* FP:check_export.rs-0008 */ use crate :: rustc_data_structures :: fx :: { FxIndexMap , FxIndexSet } ;
/* FP:check_export.rs-0009 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_USE_0005
/* FP:check_export.rs-0010 */ use rustc_hir as hir ;
/* FP:check_export.rs-0011 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_USE_0006
/* FP:check_export.rs-0012 */ use crate :: rustc_complete :: attrs :: AttributeKind ;
/* FP:check_export.rs-0013 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_USE_0007
/* FP:check_export.rs-0014 */ use crate :: rustc_complete :: def :: DefKind ;
/* FP:check_export.rs-0015 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_USE_0008
/* FP:check_export.rs-0016 */ use crate :: rustc_complete :: def_id :: { DefId , LocalDefId } ;
/* FP:check_export.rs-0017 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_USE_0009
/* FP:check_export.rs-0018 */ use crate :: rustc_complete :: find_attr ;
/* FP:check_export.rs-0019 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_USE_0010
/* FP:check_export.rs-0020 */ use crate :: rustc_complete :: intravisit :: { self , Visitor } ;
/* FP:check_export.rs-0021 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_USE_0011
/* FP:check_export.rs-0022 */ use crate :: rustc_complete :: hir :: nested_filter ;
/* FP:check_export.rs-0023 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_USE_0012
/* FP:check_export.rs-0024 */ use crate :: rustc_complete :: middle :: privacy :: { EffectiveVisibility , Level } ;
/* FP:check_export.rs-0025 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_USE_0013
/* FP:check_export.rs-0026 */ use crate :: rustc_complete :: query :: { LocalCrate , Providers } ;
/* FP:check_export.rs-0027 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_USE_0014
/* FP:check_export.rs-0028 */ use crate :: rustc_complete :: ty :: { self , Ty , TyCtxt , TypeSuperVisitable , TypeVisitable , TypeVisitor , Visibility , } ;
/* FP:check_export.rs-0029 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_USE_0015
/* FP:check_export.rs-0030 */ use crate :: rustc_complete :: config :: CrateType ;
/* FP:check_export.rs-0031 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_USE_0016
/* FP:check_export.rs-0032 */ use crate :: rustc_complete :: Span ;
/* FP:check_export.rs-0033 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_USE_0017
/* FP:check_export.rs-0034 */ use crate :: errors :: UnexportableItem ;
/* FP:check_export.rs-0035 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_STRUCT_0018
/* FP:check_export.rs-0036 */ struct ExportableItemCollector < 'tcx > { tcx : TyCtxt < 'tcx > , exportable_items : FxIndexSet < DefId > , in_exportable_mod : bool , seen_exportable_in_mod : bool , }
/* FP:check_export.rs-0037 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_IMPL_0019
/* FP:check_export.rs-0039 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_IMPL_0020
/* FP:check_export.rs-0041 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_STRUCT_0021
/* FP:check_export.rs-0042 */ struct ExportableItemsChecker < 'tcx , 'a > { tcx : TyCtxt < 'tcx > , exportable_items : & 'a FxIndexSet < DefId > , item_id : DefId , }
/* FP:check_export.rs-0043 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_IMPL_0022
/* FP:check_export.rs-0044 */ impl < 'tcx , 'a > ExportableItemsChecker < 'tcx , 'a > { fn check (& mut self) { match self . tcx . def_kind (self . item_id) { DefKind :: Fn | DefKind :: AssocFn => self . check_fn () , DefKind :: Enum | DefKind :: Struct | DefKind :: Union => self . check_ty () , _ => { } } } fn check_fn (& mut self) { let def_id = self . item_id . expect_local () ; let span = self . tcx . def_span (def_id) ; if self . tcx . generics_of (def_id) . requires_monomorphization (self . tcx) { self . tcx . dcx () . emit_err (UnexportableItem :: GenericFn (span)) ; return ; } let sig = self . tcx . fn_sig (def_id) . instantiate_identity () . skip_binder () ; if ! matches ! (sig . abi , ExternAbi :: C { .. }) { self . tcx . dcx () . emit_err (UnexportableItem :: FnAbi (span)) ; return ; } let sig = self . tcx . try_normalize_erasing_regions (ty :: TypingEnv :: non_body_analysis (self . tcx , def_id) , sig) . unwrap_or (sig) ; let hir_id = self . tcx . local_def_id_to_hir_id (def_id) ; let decl = self . tcx . hir_fn_decl_by_hir_id (hir_id) . unwrap () ; for (input_ty , input_hir) in iter :: zip (sig . inputs () , decl . inputs) { self . check_nested_types_are_exportable (* input_ty , input_hir . span) ; } if let hir :: FnRetTy :: Return (ret_hir) = decl . output { self . check_nested_types_are_exportable (sig . output () , ret_hir . span) ; } } fn check_ty (& mut self) { let ty = self . tcx . type_of (self . item_id) . skip_binder () ; if let ty :: Adt (adt_def , _) = ty . kind () { if ! adt_def . repr () . inhibit_struct_field_reordering () { self . tcx . dcx () . emit_err (UnexportableItem :: TypeRepr (self . tcx . def_span (self . item_id))) ; } for variant in adt_def . variants () { for field in & variant . fields { if ! field . vis . is_public () { self . tcx . dcx () . emit_err (UnexportableItem :: AdtWithPrivFields { span : self . tcx . def_span (self . item_id) , vis_note : self . tcx . def_span (field . did) , field_name : field . name . as_str () , }) ; } } } } } fn check_nested_types_are_exportable (& mut self , ty : Ty < 'tcx > , ty_span : Span) { let res = ty . visit_with (self) ; if let Some (err_cause) = res . break_value () { self . tcx . dcx () . emit_err (UnexportableItem :: TypeInInterface { span : self . tcx . def_span (self . item_id) , desc : self . tcx . def_descr (self . item_id) , ty : & format ! ("{}" , err_cause) , ty_span , }) ; } } }
/* FP:check_export.rs-0045 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_IMPL_0023
/* FP:check_export.rs-0046 */ impl < 'tcx , 'a > TypeVisitor < TyCtxt < 'tcx > > for ExportableItemsChecker < 'tcx , 'a > { type Result = ControlFlow < Ty < 'tcx > > ; fn visit_ty (& mut self , ty : Ty < 'tcx >) -> Self :: Result { match ty . kind () { ty :: Adt (adt_def , _) => { let did = adt_def . did () ; let exportable = if did . is_local () { self . exportable_items . contains (& did) } else { self . tcx . is_exportable (did) } ; if ! exportable { return ControlFlow :: Break (ty) ; } for variant in adt_def . variants () { for field in & variant . fields { let field_ty = self . tcx . type_of (field . did) . instantiate_identity () ; field_ty . visit_with (self) ? ; } } return ty . super_visit_with (self) ; } ty :: Int (_) | ty :: Uint (_) | ty :: Float (_) | ty :: Bool | ty :: Char | ty :: Error (_) => { } ty :: Array (_ , _) | ty :: Ref (_ , _ , _) | ty :: Param (_) | ty :: Closure (_ , _) | ty :: Dynamic (_ , _ , _) | ty :: Coroutine (_ , _) | ty :: Foreign (_) | ty :: Str | ty :: Tuple (_) | ty :: Pat (..) | ty :: Slice (_) | ty :: RawPtr (_ , _) | ty :: FnDef (_ , _) | ty :: FnPtr (_ , _) | ty :: CoroutineClosure (_ , _) | ty :: CoroutineWitness (_ , _) | ty :: Never | ty :: UnsafeBinder (_) | ty :: Alias (ty :: AliasTyKind :: Opaque , _) => { return ControlFlow :: Break (ty) ; } ty :: Alias (..) | ty :: Infer (_) | ty :: Placeholder (_) | ty :: Bound (..) => unreachable ! () , } ControlFlow :: Continue (()) } }
/* FP:check_export.rs-0047 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_FN_0024
/* FP:check_export.rs-0048 */ # [doc = " Exportable items:"] # [doc = ""] # [doc = " 1. Structs/enums/unions with a stable representation (e.g. repr(i32) or repr(C))."] # [doc = " 2. Primitive types."] # [doc = " 3. Non-generic functions with a stable ABI (e.g. extern \"C\") for which every user"] # [doc = "    defined type used in the signature is also marked as `#[export]`."] fn exportable_items_provider_local < 'tcx > (tcx : TyCtxt < 'tcx > , _ : LocalCrate) -> & 'tcx [DefId] { if ! tcx . crate_types () . contains (& CrateType :: Sdylib) && ! tcx . is_sdylib_interface_build () { return & [] ; } let mut visitor = ExportableItemCollector :: new (tcx) ; tcx . hir_walk_toplevel_module (& mut visitor) ; let exportable_items = visitor . exportable_items ; for item_id in exportable_items . iter () { let mut validator = ExportableItemsChecker { tcx , exportable_items : & exportable_items , item_id : * item_id } ; validator . check () ; } tcx . arena . alloc_from_iter (exportable_items . into_iter ()) }
/* FP:check_export.rs-0049 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_STRUCT_0025
/* FP:check_export.rs-0050 */ struct ImplsOrderVisitor < 'tcx > { tcx : TyCtxt < 'tcx > , order : FxIndexMap < DefId , usize > , }
/* FP:check_export.rs-0051 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_IMPL_0026
/* FP:check_export.rs-0052 */ impl < 'tcx > ImplsOrderVisitor < 'tcx > { fn new (tcx : TyCtxt < 'tcx >) -> ImplsOrderVisitor < 'tcx > { ImplsOrderVisitor { tcx , order : Default :: default () } } }
/* FP:check_export.rs-0053 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_IMPL_0027
/* FP:check_export.rs-0054 */ impl < 'tcx > Visitor < 'tcx > for ImplsOrderVisitor < 'tcx > { type NestedFilter = nested_filter :: All ; fn maybe_tcx (& mut self) -> Self :: MaybeTyCtxt { self . tcx } fn visit_item (& mut self , item : & 'tcx hir :: Item < 'tcx >) { if let hir :: ItemKind :: Impl (impl_) = item . kind && impl_ . of_trait . is_none () && self . tcx . is_exportable (item . owner_id . def_id . to_def_id ()) { self . order . insert (item . owner_id . def_id . to_def_id () , self . order . len ()) ; } intravisit :: walk_item (self , item) ; } }
/* FP:check_export.rs-0055 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_FN_0028
/* FP:check_export.rs-0056 */ # [doc = " During symbol mangling rustc uses a special index to distinguish between two impls of"] # [doc = " the same type in the same module(See `DisambiguatedDefPathData`). For exportable items"] # [doc = " we cannot use the current approach because it is dependent on the compiler's"] # [doc = " implementation."] # [doc = ""] # [doc = " In order to make disambiguation independent of the compiler version we can assign an"] # [doc = " id to each impl according to the relative order of elements in the source code."] fn stable_order_of_exportable_impls < 'tcx > (tcx : TyCtxt < 'tcx > , _ : LocalCrate ,) -> & 'tcx FxIndexMap < DefId , usize > { if ! tcx . crate_types () . contains (& CrateType :: Sdylib) && ! tcx . is_sdylib_interface_build () { return tcx . arena . alloc (FxIndexMap :: < DefId , usize > :: default ()) ; } let mut vis = ImplsOrderVisitor :: new (tcx) ; tcx . hir_walk_toplevel_module (& mut vis) ; tcx . arena . alloc (vis . order) }
/* FP:check_export.rs-0057 */ #[warn(unused_variables)] // AST_.._rust_compiler_rustc_passes_src_check_export_FN_0029
/* FP:check_export.rs-0058 */ pub (crate) fn provide (providers : & mut Providers) { * providers = Providers { exportable_items : exportable_items_provider_local , stable_order_of_exportable_impls , .. * providers } ; }