// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
impl<'tcx> QueryContext<'tcx, TyCtxt<'tcx>, Item<'tcx>> for TyCtxt<'tcx> {
    fn walk_hir_tops(&self, mut f: impl FnMut(&'tcx Item<'tcx>)) {
        self.hir().walk_tops(|item| f(item));
    }
}
