[package]
name = "cargo-toml-parts"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo-toml-generator-macros = { workspace = true }
cargo-toml-generator-types = { workspace = true }
toml = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
syn = { workspace = true, features = ["full", "visit"] }
serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }
