// Generated macro for pretty_print_region_elements (function)
macro_rules! Depcrate_region_infer_valuespretty_print_region_elements {
() => {
// Module: crate::region_infer::values
// Provides: {"pretty_print_region_elements"}
// Dependencies: {}
# [doc = " For debugging purposes, returns a pretty-printed string of the given region elements."] fn pretty_print_region_elements (elements : impl IntoIterator < Item = RegionElement >) -> String { let mut result = String :: new () ; result . push ('{') ; let mut open_location : Option < (Location , Location) > = None ; let mut sep = "" ; let mut push_sep = | s : & mut String | { s . push_str (sep) ; sep = ", " ; } ; for element in elements { match element { RegionElement :: Location (l) => { if let Some ((location1 , location2)) = open_location { if location2 . block == l . block && location2 . statement_index == l . statement_index - 1 { open_location = Some ((location1 , l)) ; continue ; } push_sep (& mut result) ; push_location_range (& mut result , location1 , location2) ; } open_location = Some ((l , l)) ; } RegionElement :: RootUniversalRegion (fr) => { if let Some ((location1 , location2)) = open_location { push_sep (& mut result) ; push_location_range (& mut result , location1 , location2) ; open_location = None ; } push_sep (& mut result) ; result . push_str (& format ! ("{fr:?}")) ; } RegionElement :: PlaceholderRegion (placeholder) => { if let Some ((location1 , location2)) = open_location { push_sep (& mut result) ; push_location_range (& mut result , location1 , location2) ; open_location = None ; } push_sep (& mut result) ; result . push_str (& format ! ("{placeholder:?}")) ; } } } if let Some ((location1 , location2)) = open_location { push_sep (& mut result) ; push_location_range (& mut result , location1 , location2) ; } result . push ('}') ; return result ; fn push_location_range (s : & mut String , location1 : Location , location2 : Location) { if location1 == location2 { s . push_str (& format ! ("{location1:?}")) ; } else { assert_eq ! (location1 . block , location2 . block) ; s . push_str (& format ! ("{:?}[{}..={}]" , location1 . block , location1 . statement_index , location2 . statement_index)) ; } } }
};
}
