// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[cfg(windows)]
fn handle_is_console(handle: BorrowedHandle<'_>) -> bool {
    use windows_sys::Win32::System::Console::GetConsoleMode;
    let handle = handle.as_raw_handle();
    if handle.is_null() {
        return false;
    }
    unsafe {
        let mut out = 0;
        if GetConsoleMode(handle as HANDLE, &mut out) != 0 {
            return true;
        }
        msys_tty_on(handle as HANDLE)
    }
}
