// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter.rs:211 from submodules/split-decls-rs/src/eager_splitter.rs
// Do not edit this file by hand. Your changes will be overwritten.

#[llm_error_message(message = "Module file not found for: compile_fail_tests")]
#[llm_context(crate_name = "wrapped_arc_swap", module_name = "compile_fail_tests")]
pub struct wrapped_arc_swap_decls_module_not_found_compile_fail_tests;
