// Generated macro for other_38 (other)
macro_rules! Depcrateother_38 {
() => {
// Module: crate
// Provides: {"other_38"}
// Dependencies: {}
# [wasm_bindgen] extern "C" { # [wasm_bindgen (extends = Object , typescript_type = "ArrayBuffer")] # [derive (Clone , Debug , PartialEq , Eq)] pub type ArrayBuffer ; # [doc = " The `ArrayBuffer` object is used to represent a generic,"] # [doc = " fixed-length raw binary data buffer. You cannot directly"] # [doc = " manipulate the contents of an `ArrayBuffer`; instead, you"] # [doc = " create one of the typed array objects or a `DataView` object"] # [doc = " which represents the buffer in a specific format, and use that"] # [doc = " to read and write the contents of the buffer."] # [doc = ""] # [doc = " [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer)"] # [wasm_bindgen (constructor)] pub fn new (length : u32) -> ArrayBuffer ; # [doc = " The byteLength property of an object which is an instance of type ArrayBuffer"] # [doc = " it's an accessor property whose set accessor function is undefined,"] # [doc = " meaning that you can only read this property."] # [doc = " The value is established when the array is constructed and cannot be changed."] # [doc = " This property returns 0 if this ArrayBuffer has been detached."] # [doc = ""] # [doc = " [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/byteLength)"] # [wasm_bindgen (method , getter , js_name = byteLength)] pub fn byte_length (this : & ArrayBuffer) -> u32 ; # [doc = " The `isView()` method returns true if arg is one of the `ArrayBuffer`"] # [doc = " views, such as typed array objects or a DataView; false otherwise."] # [doc = ""] # [doc = " [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/isView)"] # [wasm_bindgen (static_method_of = ArrayBuffer , js_name = isView)] pub fn is_view (value : & JsValue) -> bool ; # [doc = " The `slice()` method returns a new `ArrayBuffer` whose contents"] # [doc = " are a copy of this `ArrayBuffer`'s bytes from begin, inclusive,"] # [doc = " up to end, exclusive."] # [doc = ""] # [doc = " [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/slice)"] # [wasm_bindgen (method)] pub fn slice (this : & ArrayBuffer , begin : u32) -> ArrayBuffer ; # [doc = " Like `slice()` but with the `end` argument."] # [doc = ""] # [doc = " [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/slice)"] # [wasm_bindgen (method , js_name = slice)] pub fn slice_with_end (this : & ArrayBuffer , begin : u32 , end : u32) -> ArrayBuffer ; }
};
}
