macro_rules! deps {
    () => {
        CodePointSetData!();
        CodePointSetDataBorrowed!();
    };
}

macro_rules! impl_5 {
    () => {
        deps!();
        impl < 'a > CodePointSetDataBorrowed < 'a > { # [doc = " Check if the set contains a character"] # [doc = ""] # [doc = " ```rust"] # [doc = " use icu::properties::CodePointSetData;"] # [doc = " use icu::properties::props::Alphabetic;"] # [doc = ""] # [doc = " let alphabetic = CodePointSetData::new::<Alphabetic>();"] # [doc = ""] # [doc = " assert!(!alphabetic.contains('3'));"] # [doc = " assert!(!alphabetic.contains('੩'));  // U+0A69 GURMUKHI DIGIT THREE"] # [doc = " assert!(alphabetic.contains('A'));"] # [doc = " assert!(alphabetic.contains('Ä'));  // U+00C4 LATIN CAPITAL LETTER A WITH DIAERESIS"] # [doc = " ```"] # [inline] pub fn contains (self , ch : char) -> bool { self . set . contains (ch) } # [doc = " See [`Self::contains`]."] # [inline] pub fn contains32 (self , ch : u32) -> bool { self . set . contains32 (ch) } # [doc = " included in the [`CodePointSetData`]"] # [doc = ""] # [doc = " Ranges are returned as [`RangeInclusive`], which is inclusive of its"] # [doc = " `end` bound value. An end-inclusive behavior matches the ICU4C/J"] # [doc = " behavior of ranges, ex: `UnicodeSet::contains(UChar32 start, UChar32 end)`."] # [doc = ""] # [doc = " # Example"] # [doc = ""] # [doc = " ```"] # [doc = " use icu::properties::props::Alphabetic;"] # [doc = " use icu::properties::CodePointSetData;"] # [doc = ""] # [doc = " let alphabetic = CodePointSetData::new::<Alphabetic>();"] # [doc = " let mut ranges = alphabetic.iter_ranges();"] # [doc = ""] # [doc = " assert_eq!(Some(0x0041..=0x005A), ranges.next()); // 'A'..'Z'"] # [doc = " assert_eq!(Some(0x0061..=0x007A), ranges.next()); // 'a'..'z'"] # [doc = " ```"] # [inline] pub fn iter_ranges (self) -> impl Iterator < Item = RangeInclusive < u32 > > + 'a { self . set . iter_ranges () } # [doc = " *not* included in the [`CodePointSetData`]"] # [doc = ""] # [doc = " Ranges are returned as [`RangeInclusive`], which is inclusive of its"] # [doc = " `end` bound value. An end-inclusive behavior matches the ICU4C/J"] # [doc = " behavior of ranges, ex: `UnicodeSet::contains(UChar32 start, UChar32 end)`."] # [doc = ""] # [doc = " # Example"] # [doc = ""] # [doc = " ```"] # [doc = " use icu::properties::props::Alphabetic;"] # [doc = " use icu::properties::CodePointSetData;"] # [doc = ""] # [doc = " let alphabetic = CodePointSetData::new::<Alphabetic>();"] # [doc = " let mut ranges = alphabetic.iter_ranges();"] # [doc = ""] # [doc = " assert_eq!(Some(0x0041..=0x005A), ranges.next()); // 'A'..'Z'"] # [doc = " assert_eq!(Some(0x0061..=0x007A), ranges.next()); // 'a'..'z'"] # [doc = " ```"] # [inline] pub fn iter_ranges_complemented (self) -> impl Iterator < Item = RangeInclusive < u32 > > + 'a { self . set . iter_ranges_complemented () } }
    };
}

impl_5!()