// Generated macro for impl_175 (impl)
macro_rules! Depcrate_idl_typeimpl_175 {
() => {
// Module: crate::idl_type
// Provides: {"impl_175"}
// Dependencies: {}
impl IdentifierType < '_ > { # [doc = " Converts to syn type if possible."] pub (crate) fn to_syn_type (& self , pos : TypePosition , legacy : bool ,) -> Result < Option < syn :: Type > , TypeError > { let externref = | ty | { Some (match pos { TypePosition :: Argument => shared_ref (ty , false) , TypePosition :: Return => ty , }) } ; let js_sys = | name : & str | { let path = vec ! [rust_ident ("js_sys") , rust_ident (name)] ; let ty = leading_colon_path_ty (path) ; externref (ty) } ; match self { IdentifierType :: Callback => Ok (js_sys ("Function")) , IdentifierType :: Iterator => Ok (js_sys ("Iterator")) , IdentifierType :: AsyncIterator => Ok (js_sys ("AsyncIterator")) , IdentifierType :: Interface (name) | IdentifierType :: Dictionary (name) | IdentifierType :: CallbackInterface { name , .. } => { let ty = ident_ty (rust_ident (camel_case_ident (name) . as_str ())) ; Ok (externref (ty)) } IdentifierType :: Enum (name) => { Ok (Some (ident_ty (rust_ident (camel_case_ident (name) . as_str ())))) } IdentifierType :: UnsignedLongLong => IdlType :: UnsignedLongLong . to_syn_type (pos , legacy) , IdentifierType :: AllowSharedBufferSource { immutable } => IdlType :: BufferSource { allow_shared : true , immutable : * immutable , } . to_syn_type (pos , legacy) , IdentifierType :: Int8Slice { immutable , .. } => Ok (Some (array ("i8" , pos , * immutable))) , IdentifierType :: Uint8Slice { immutable , .. } => Ok (Some (array ("u8" , pos , * immutable))) , IdentifierType :: Uint8ClampedSlice { immutable , .. } => { Ok (Some (clamped (array ("u8" , pos , * immutable)))) } IdentifierType :: Int16Slice { immutable , .. } => Ok (Some (array ("i16" , pos , * immutable))) , IdentifierType :: Uint16Slice { immutable , .. } => { Ok (Some (array ("u16" , pos , * immutable))) } IdentifierType :: Int32Slice { immutable , .. } => Ok (Some (array ("i32" , pos , * immutable))) , IdentifierType :: Uint32Slice { immutable , .. } => { Ok (Some (array ("u32" , pos , * immutable))) } IdentifierType :: Float32Slice { immutable , .. } => { Ok (Some (array ("f32" , pos , * immutable))) } IdentifierType :: Float64Slice { immutable , .. } => { Ok (Some (array ("f64" , pos , * immutable))) } } } }
};
}
