// Generated macro for Registry (struct)
macro_rules! Depcrate_registryRegistry {
() => {
// Module: crate::registry
// Provides: {"Registry"}
// Dependencies: {}
# [doc = " Actors registry"] # [doc = ""] # [doc = " An Actor can register itself as a service. A Service can be defined as an"] # [doc = " `ArbiterService`, which is unique per arbiter, or a `SystemService`, which"] # [doc = " is unique per system."] # [doc = ""] # [doc = " If an arbiter service is used outside of a running arbiter, it panics."] # [doc = ""] # [doc = " # Examples"] # [doc = ""] # [doc = " ```"] # [doc = " use actix::prelude::*;"] # [doc = ""] # [doc = " #[derive(Message)]"] # [doc = " #[rtype(result = \"()\")]"] # [doc = " struct Ping;"] # [doc = ""] # [doc = " #[derive(Default)]"] # [doc = " struct MyActor1;"] # [doc = ""] # [doc = " impl Actor for MyActor1 {"] # [doc = "     type Context = Context<Self>;"] # [doc = " }"] # [doc = " impl actix::Supervised for MyActor1 {}"] # [doc = ""] # [doc = " impl ArbiterService for MyActor1 {"] # [doc = "    fn service_started(&mut self, ctx: &mut Context<Self>) {"] # [doc = "       println!(\"Service started\");"] # [doc = "    }"] # [doc = " }"] # [doc = ""] # [doc = " impl Handler<Ping> for MyActor1 {"] # [doc = "    type Result = ();"] # [doc = ""] # [doc = "    fn handle(&mut self, _: Ping, ctx: &mut Context<Self>) {"] # [doc = "       println!(\"ping\");"] # [doc = " #     System::current().stop();"] # [doc = "    }"] # [doc = " }"] # [doc = ""] # [doc = " struct MyActor2;"] # [doc = ""] # [doc = " impl Actor for MyActor2 {"] # [doc = "    type Context = Context<Self>;"] # [doc = ""] # [doc = "    fn started(&mut self, _: &mut Context<Self>) {"] # [doc = "       // get MyActor1 address from the registry"] # [doc = "       let act = MyActor1::from_registry();"] # [doc = "       act.do_send(Ping);"] # [doc = "    }"] # [doc = " }"] # [doc = ""] # [doc = " #[actix::main]"] # [doc = " async fn main() {"] # [doc = "     // Start MyActor2 in new Arbiter"] # [doc = "     Arbiter::new().spawn_fn(|| {"] # [doc = "         MyActor2.start();"] # [doc = "     });"] # [doc = "     # System::current().stop();"] # [doc = " }"] # [doc = " ```"] # [derive (Clone)] pub struct Registry { registry : Rc < RefCell < AnyMap > > , }
};
}
