// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[cfg(all(feature = "std", any(doc, doctest, feature = "docsrs")))]
# [cfg_attr (any (doc , doctest , feature = "docsrs") , doc = include_str ! ("../doc/nom_recipes.md"))]
pub mod recipes {}
