// Generated macro for main (function)
macro_rules! Depcratemain {
() => {
// Module: crate
// Provides: {"main"}
// Dependencies: {}
fn main () { let mut lookup = BTreeMap :: new () ; load_file (SYN_CRATE_ROOT , quote ! () , & mut lookup) . unwrap () ; let mut state = Default :: default () ; for s in lookup . values () { codegen :: generate (& mut state , & lookup , s) ; } let full_macro = "
#[cfg(feature = \"full\")]
macro_rules! full {
    ($e:expr) => { $e }
}

#[cfg(not(feature = \"full\"))]
macro_rules! full {
    ($e:expr) => { unreachable!() }
}
" ; let mut fold_file = File :: create (FOLD_SRC) . unwrap () ; write ! (fold_file , "
// THIS FILE IS AUTOMATICALLY GENERATED; DO NOT EDIT

//! A Folder represents an AST->AST fold; it accepts an AST piece,
//! and returns a piece of the same type.

// Unreachable code is generated sometimes without the full feature.
#![allow(unreachable_code)]

use *;
use synom::delimited::Delimited;

trait FoldHelper {{
    type Item;
    fn lift<F>(self, f: F) -> Self where F: FnMut(Self::Item) -> Self::Item;
}}

impl<T> FoldHelper for Vec<T> {{
    type Item = T;
    fn lift<F>(self, f: F) -> Self where F: FnMut(Self::Item) -> Self::Item {{
        self.into_iter().map(f).collect()
    }}
}}

impl<T, U> FoldHelper for Delimited<T, U> {{
    type Item = T;
    fn lift<F>(self, mut f: F) -> Self where F: FnMut(Self::Item) -> Self::Item {{
        self.into_iter().map(|elem| {{
            let (t, u) = elem.into_tuple();
            (f(t), u)
        }}).collect::<Vec<(T, Option<U>)>>().into()
    }}
}}

{full_macro}

/// AST->AST fold.
///
/// Each method of the Folder trait is a hook to be potentially overridden. Each
/// method's default implementation recursively visits the substructure of the
/// input via the `walk` functions, which perform an \"identity fold\", that
/// is, they return the same structure that they are given (for example the
/// `fold_file` method by default calls `fold::walk_file`).
///
/// If you want to ensure that your code handles every variant
/// explicitly, you need to override each method.  (And you also need
/// to monitor future changes to `Folder` in case a new method with a
/// new default implementation gets introduced.)
pub trait Folder {{
{fold_trait}
}}

{fold_impl}
" , full_macro = full_macro , fold_trait = state . fold_trait , fold_impl = state . fold_impl) . unwrap () ; let mut visit_file = File :: create (VISIT_SRC) . unwrap () ; write ! (visit_file , "
// THIS FILE IS AUTOMATICALLY GENERATED; DO NOT EDIT

//! AST walker. Each overridden visit method has full control over what
//! happens with its node, it can do its own traversal of the node's children,
//! call `visit::walk_*` to apply the default traversal algorithm, or prevent
//! deeper traversal by doing nothing.

use *;

{full_macro}

/// Each method of the Visitor trait is a hook to be potentially
/// overridden.  Each method's default implementation recursively visits
/// the substructure of the input via the corresponding `walk` method;
/// e.g. the `visit_mod` method by default calls `visit::walk_mod`.
///
/// If you want to ensure that your code handles every variant
/// explicitly, you need to override each method.  (And you also need
/// to monitor future changes to `Visitor` in case a new method with a
/// new default implementation gets introduced.)
pub trait Visitor {{
{visit_trait}
}}

{visit_impl}
" , full_macro = full_macro , visit_trait = state . visit_trait , visit_impl = state . visit_impl) . unwrap () ; let mut visit_mut_file = File :: create (VISIT_MUT_SRC) . unwrap () ; write ! (visit_mut_file , "
// THIS FILE IS AUTOMATICALLY GENERATED; DO NOT EDIT

//! AST walker. Each overridden visit method has full control over what
//! happens with its node, it can do its own traversal of the node's children,
//! call `visit::walk_*` to apply the default traversal algorithm, or prevent
//! deeper traversal by doing nothing.

use *;

{full_macro}

/// Each method of the VisitorMut trait is a hook to be potentially
/// overridden.  Each method's default implementation recursively visits
/// the substructure of the input via the corresponding `walk` method;
/// e.g. the `visit_mod` method by default calls `visit::walk_mod`.
///
/// If you want to ensure that your code handles every variant
/// explicitly, you need to override each method.  (And you also need
/// to monitor future changes to `VisitorMut` in case a new method with a
/// new default implementation gets introduced.)
pub trait VisitorMut {{
{visit_mut_trait}
}}

{visit_mut_impl}
" , full_macro = full_macro , visit_mut_trait = state . visit_mut_trait , visit_mut_impl = state . visit_mut_impl) . unwrap () ; }
};
}
