// Generated by submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs at 31:submodules/split-decls-rs/src/eager_splitter/invocation_generator.rs from 35
// Do not edit this file by hand. Your changes will be overwritten.

use introspector_decl2_macros::decl_module;
decl_module!(
    wrapped_gix_validate_decls_module_not_found_reference,
    wrapped_gix_validate_decls_module_not_found_tag,
    wrapped_gix_validate_decls_module_not_found_submodule,
    wrapped_gix_validate_decls_module_not_found_path
);
