// Generated by unified_build.rs
#![feature(rustc_attrs)]
#![feature(type_alias_impl_trait)]
#![feature(dropck_eyepatch)]
#![feature(ascii_char_variants)]
#![feature(ascii_char)]
#![feature(auto_traits)]
#![feature(specialization)]
#![feature(never_type)]
#![feature(cfg_select)]
#![feature(ptr_alignment_type)]
#![feature(negative_impls)]

//! The `rustc_ast_passes` crate contains passes which validate the AST in `syntax`
//! parsed by `rustc_parse` and then lowered, after the passes in this crate,
//! by `rustc_ast_lowering`.

// tidy-alphabetical-start
// tidy-alphabetical-end

pub mod ast_validation;
mod errors;
pub mod feature_gate;

rustc_fluent_macro::fluent_messages! { "messages.ftl" }