// Generated macro for impl_24 (impl)
macro_rules! Depcrate_arrayimpl_24 {
() => {
// Module: crate::array
// Provides: {"impl_24"}
// Dependencies: {}
# [doc = " Direct, unsafe object accessors."] # [doc = ""] # [doc = " CFArray stores its values directly, and you can get references to said"] # [doc = " values data without having to retain it first - but only if the array"] # [doc = " isn't mutated while doing so - otherwise, we might end up accessing a"] # [doc = " deallocated object."] impl < T : ? Sized > CFArray < T > { # [doc = " Get a direct reference to one of the array's objects."] # [doc = ""] # [doc = " Consider using the [`get`](Self::get) method instead, unless you're"] # [doc = " seeing performance issues from the retaining."] # [doc = ""] # [doc = " # Safety"] # [doc = ""] # [doc = " - The index must not be negative, and must be in bounds of the array."] # [doc = " - The array must not be mutated while the returned reference is live."] # [inline] # [doc (alias = "CFArrayGetValueAtIndex")] pub unsafe fn get_unchecked (& self , index : CFIndex) -> & T where T : Type + Sized , { let ptr = unsafe { self . as_opaque () . value_at_index (index) } ; unsafe { & * ptr . cast :: < T > () } } # [doc = " A vector containing direct references to the array's objects."] # [doc = ""] # [doc = " Consider using the [`to_vec`](Self::to_vec) method instead, unless"] # [doc = " you're seeing performance issues from the retaining."] # [doc = ""] # [doc = " # Safety"] # [doc = ""] # [doc = " The array must not be mutated while the returned references are alive."] # [cfg (feature = "alloc")] # [doc (alias = "CFArrayGetValues")] pub unsafe fn to_vec_unchecked (& self) -> Vec < & T > where T : Type , { let len = self . len () ; let range = crate :: CFRange { location : 0 , length : len as CFIndex , } ; let mut vec = Vec :: < & T > :: with_capacity (len) ; let ptr = vec . as_mut_ptr () . cast :: < * const c_void > () ; unsafe { self . as_opaque () . values (range , ptr) } ; unsafe { vec . set_len (len) } ; vec } # [doc = " Iterate over the array without touching the elements."] # [doc = ""] # [doc = " Consider using the [`iter`](Self::iter) method instead, unless you're"] # [doc = " seeing performance issues from the retaining."] # [doc = ""] # [doc = " # Safety"] # [doc = ""] # [doc = " The array must not be mutated for the lifetime of the iterator or for"] # [doc = " the lifetime of the elements the iterator returns."] # [inline] pub unsafe fn iter_unchecked (& self) -> CFArrayIterUnchecked < '_ , T > where T : Type , { CFArrayIterUnchecked { array : self , index : 0 , len : self . len () as CFIndex , } } }
};
}
