// Generated macro for ImageReader (struct)
macro_rules! Depcrate_image_reader_image_reader_typeImageReader {
() => {
// Module: crate::image_reader::image_reader_type
// Provides: {"ImageReader"}
// Dependencies: {}
# [doc = " A multi-format image reader."] # [doc = ""] # [doc = " Wraps an input reader to facilitate automatic detection of an image's format, appropriate"] # [doc = " decoding method, and dispatches into the set of supported [`ImageDecoder`] implementations."] # [doc = ""] # [doc = " ## Usage"] # [doc = ""] # [doc = " Opening a file, deducing the format based on the file path automatically, and trying to decode"] # [doc = " the image contained can be performed by constructing the reader and immediately consuming it."] # [doc = ""] # [doc = " ```no_run"] # [doc = " # use image::ImageError;"] # [doc = " # use image::ImageReader;"] # [doc = " # fn main() -> Result<(), ImageError> {"] # [doc = " let image = ImageReader::open(\"path/to/image.png\")?"] # [doc = "     .decode()?;"] # [doc = " # Ok(()) }"] # [doc = " ```"] # [doc = ""] # [doc = " It is also possible to make a guess based on the content. This is especially handy if the"] # [doc = " source is some blob in memory and you have constructed the reader in another way. Here is an"] # [doc = " example with a `pnm` black-and-white subformat that encodes its pixel matrix with ascii values."] # [doc = ""] # [doc = " ```"] # [doc = " # use image::ImageError;"] # [doc = " # use image::ImageReader;"] # [doc = " # fn main() -> Result<(), ImageError> {"] # [doc = " use std::io::Cursor;"] # [doc = " use image::ImageFormat;"] # [doc = ""] # [doc = " let raw_data = b\"P1 2 2\\n\\"] # [doc = "     0 1\\n\\"] # [doc = "     1 0\\n\";"] # [doc = ""] # [doc = " let mut reader = ImageReader::new(Cursor::new(raw_data))"] # [doc = "     .with_guessed_format()"] # [doc = "     .expect(\"Cursor io never fails\");"] # [doc = " assert_eq!(reader.format(), Some(ImageFormat::Pnm));"] # [doc = ""] # [doc = " # #[cfg(feature = \"pnm\")]"] # [doc = " let image = reader.decode()?;"] # [doc = " # Ok(()) }"] # [doc = " ```"] # [doc = ""] # [doc = " As a final fallback or if only a specific format must be used, the reader always allows manual"] # [doc = " specification of the supposed image format with [`set_format`]."] # [doc = ""] # [doc = " [`set_format`]: #method.set_format"] # [doc = " [`ImageDecoder`]: ../trait.ImageDecoder.html"] pub struct ImageReader < R : Read + Seek > { # [doc = " The reader. Should be buffered."] inner : R , # [doc = " The format, if one has been set or deduced."] format : Option < ImageFormat > , # [doc = " Decoding limits"] limits : super :: Limits , }
};
}
