// Generated macro for test_support (module)
macro_rules! Depcratetest_support {
() => {
// Module: crate
// Provides: {"test_support"}
// Dependencies: {}
# [cfg (test)] mod test_support { use core :: ffi :: c_char ; # [doc = " Just verify that we are able to call the function."] pub trait CallTest { fn check (f : Self) ; } macro_rules ! impl_calltest { ($ (($ ($ arg : ty) ,*) -> $ ret : ty ;) *) => { $ (impl CallTest for fn ($ ($ arg) ,*) -> $ ret { fn check (f : Self) { f ($ (1 as $ arg) ,*) ; } }) * } ; } impl_calltest ! { (f32) -> f32 ; (f64) -> f64 ; (f32 , f32) -> f32 ; (f64 , f64) -> f64 ; (i32 , f32) -> f32 ; (i32 , f64) -> f64 ; (f32 , f32 , f32) -> f32 ; (f64 , f64 , f64) -> f64 ; (f32 , i32) -> f32 ; (f32 , i64) -> f32 ; (f32) -> i32 ; (f64) -> i32 ; (f64 , i32) -> f64 ; (f64 , i64) -> f64 ; } impl CallTest for fn (f32 , & mut f32) -> f32 { fn check (f : Self) { let mut tmp = 0.0 ; f (0.0 , & mut tmp) ; } } impl CallTest for fn (f64 , & mut f64) -> f64 { fn check (f : Self) { let mut tmp = 0.0 ; f (0.0 , & mut tmp) ; } } impl CallTest for fn (f32 , & mut i32) -> f32 { fn check (f : Self) { let mut tmp = 1 ; f (0.0 , & mut tmp) ; } } impl CallTest for fn (f64 , & mut i32) -> f64 { fn check (f : Self) { let mut tmp = 1 ; f (0.0 , & mut tmp) ; } } impl CallTest for fn (f32 , f32 , & mut i32) -> f32 { fn check (f : Self) { let mut tmp = 1 ; f (0.0 , 0.0 , & mut tmp) ; } } impl CallTest for fn (f64 , f64 , & mut i32) -> f64 { fn check (f : Self) { let mut tmp = 1 ; f (0.0 , 0.0 , & mut tmp) ; } } impl CallTest for fn (f32 , & mut f32 , & mut f32) { fn check (f : Self) { let mut tmp1 = 1.0 ; let mut tmp2 = 1.0 ; f (0.0 , & mut tmp1 , & mut tmp2) ; } } impl CallTest for fn (f64 , & mut f64 , & mut f64) { fn check (f : Self) { let mut tmp1 = 1.0 ; let mut tmp2 = 1.0 ; f (0.0 , & mut tmp1 , & mut tmp2) ; } } impl CallTest for fn (* const c_char) -> f32 { fn check (f : Self) { f (c"1" . as_ptr ()) ; } } impl CallTest for fn (* const c_char) -> f64 { fn check (f : Self) { f (c"1" . as_ptr ()) ; } } }
};
}
