// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter.rs:211 from submodules/split-decls-rs/src/eager_splitter.rs
// Do not edit this file by hand. Your changes will be overwritten.

#[llm_error_message(message = "Module file not found for: base")]
#[llm_context(crate_name = "wrapped_rustc_codegen_llvm", module_name = "base")]
pub struct wrapped_rustc_codegen_llvm_decls_module_not_found_base;
