// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " `(line, column)` information in wide encodings."]
#[doc = ""]
#[doc = " See [`WideEncoding`] for the kinds of wide encodings available."]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct WideLineCol {
    #[doc = " Zero-based."]
    pub line: u32,
    #[doc = " Zero-based."]
    pub col: u32,
}
