// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Checks 16 byte chunks of text at a time. If the chunk contains"]
#[doc = " something other than printable ASCII characters and newlines, the"]
#[doc = " function falls back to the generic implementation. Otherwise it uses"]
#[doc = " SSE2 intrinsics to quickly find all newlines."]
#[target_feature(enable = "sse2")]
#[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
#[allow(unsafe_op_in_unsafe_fn)]
unsafe fn analyze_source_file_sse2(
    src: &str,
    lines: &mut Vec<TextSize>,
    multi_byte_chars: &mut IntMap<u32, Vec<WideChar>>,
) {
    #[cfg(target_arch = "x86")]
    use std::arch::x86::*;
    #[cfg(target_arch = "x86_64")]
    use std::arch::x86_64::*;
    const CHUNK_SIZE: usize = 16;
    let src_bytes = src.as_bytes();
    let chunk_count = src.len() / CHUNK_SIZE;
    let mut intra_chunk_offset = 0;
    for chunk_index in 0..chunk_count {
        let ptr = src_bytes.as_ptr() as *const __m128i;
        let chunk = unsafe { _mm_loadu_si128(ptr.add(chunk_index)) };
        let multibyte_test = _mm_cmplt_epi8(chunk, _mm_set1_epi8(0));
        let multibyte_mask = _mm_movemask_epi8(multibyte_test);
        if multibyte_mask == 0 {
            assert!(intra_chunk_offset == 0);
            let newlines_test = _mm_cmpeq_epi8(chunk, _mm_set1_epi8(b'\n' as i8));
            let newlines_mask = _mm_movemask_epi8(newlines_test);
            if newlines_mask != 0 {
                let mut newlines_mask = 0xFFFF0000 | newlines_mask as u32;
                let output_offset = TextSize::from((chunk_index * CHUNK_SIZE + 1) as u32);
                loop {
                    let index = newlines_mask.trailing_zeros();
                    if index >= CHUNK_SIZE as u32 {
                        break;
                    }
                    lines.push(TextSize::from(index) + output_offset);
                    newlines_mask &= (!1) << index;
                }
            }
            continue;
        }
        let scan_start = chunk_index * CHUNK_SIZE + intra_chunk_offset;
        intra_chunk_offset = analyze_source_file_generic(
            &src[scan_start..],
            CHUNK_SIZE - intra_chunk_offset,
            TextSize::from(scan_start as u32),
            lines,
            multi_byte_chars,
        );
    }
    let tail_start = chunk_count * CHUNK_SIZE + intra_chunk_offset;
    if tail_start < src.len() {
        analyze_source_file_generic(
            &src[tail_start..],
            src.len() - tail_start,
            TextSize::from(tail_start as u32),
            lines,
            multi_byte_chars,
        );
    }
}
