// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct WideChar {
    #[doc = " Start offset of a character inside a line, zero-based."]
    start: TextSize,
    #[doc = " End offset of a character inside a line, zero-based."]
    end: TextSize,
}
