// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " Simplified version of `FluentArg` that can implement `Encodable` and `Decodable`. Collection of"]
#[doc = " `DiagArg` are converted to `FluentArgs` (consuming the collection) at the start of diagnostic"]
#[doc = " emission."]
pub type DiagArg<'iter> = (&'iter DiagArgName, &'iter DiagArgValue);
