// SRC: compiler/rustc_public/src/mir.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_public/src/mir.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_public/src/mir.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_public/src/mir.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_public/src/mir.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_public/src/mir.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_public/src/mir.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: compiler/rustc_public/src/mir.rs
// GENERATED BY: build.rs (split-decls-genesis)
// SRC: ../rust/compiler/rustc_public/src/mir.rs

pub use body::*;
pub use visit::{MirVisitor, MutMirVisitor};