// Generated macro for tests (module)
macro_rules! Depcrate_worktreetests {
() => {
// Module: crate::worktree
// Provides: {"tests"}
// Dependencies: {}
# [cfg (test)] mod tests { use crate :: WorktreeAddOptions ; use crate :: WorktreeLockStatus ; use tempfile :: TempDir ; # [test] fn smoke_add_no_ref () { let (_td , repo) = crate :: test :: repo_init () ; let wtdir = TempDir :: new () . unwrap () ; let wt_path = wtdir . path () . join ("tree-no-ref-dir") ; let opts = WorktreeAddOptions :: new () ; let wt = repo . worktree ("tree-no-ref" , & wt_path , Some (& opts)) . unwrap () ; assert_eq ! (wt . name () , Some ("tree-no-ref")) ; assert_eq ! (wt . path () . canonicalize () . unwrap () , wt_path . canonicalize () . unwrap ()) ; let status = wt . is_locked () . unwrap () ; assert_eq ! (status , WorktreeLockStatus :: Unlocked) ; } # [test] fn smoke_add_locked () { let (_td , repo) = crate :: test :: repo_init () ; let wtdir = TempDir :: new () . unwrap () ; let wt_path = wtdir . path () . join ("locked-tree") ; let mut opts = WorktreeAddOptions :: new () ; opts . lock (true) ; let wt = repo . worktree ("locked-tree" , & wt_path , Some (& opts)) . unwrap () ; assert ! (wt . lock (Some ("my reason")) . is_err ()) ; assert_eq ! (wt . name () , Some ("locked-tree")) ; assert_eq ! (wt . path () . canonicalize () . unwrap () , wt_path . canonicalize () . unwrap ()) ; assert_eq ! (wt . is_locked () . unwrap () , WorktreeLockStatus :: Locked (None)) ; assert ! (wt . unlock () . is_ok ()) ; assert ! (wt . lock (Some ("my reason")) . is_ok ()) ; assert_eq ! (wt . is_locked () . unwrap () , WorktreeLockStatus :: Locked (Some ("my reason" . to_string ()))) ; } # [test] fn smoke_add_from_branch () { let (_td , repo) = crate :: test :: repo_init () ; let (wt_top , branch) = crate :: test :: worktrees_env_init (& repo) ; let wt_path = wt_top . path () . join ("test") ; let mut opts = WorktreeAddOptions :: new () ; let reference = branch . into_reference () ; opts . reference (Some (& reference)) ; let wt = repo . worktree ("test-worktree" , & wt_path , Some (& opts)) . unwrap () ; assert_eq ! (wt . name () , Some ("test-worktree")) ; assert_eq ! (wt . path () . canonicalize () . unwrap () , wt_path . canonicalize () . unwrap ()) ; let status = wt . is_locked () . unwrap () ; assert_eq ! (status , WorktreeLockStatus :: Unlocked) ; } }
};
}
