// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
#[doc = " A `Punct` is a single punctuation character like `+`, `-` or `#`."]
#[doc = ""]
#[doc = " Multicharacter operators like `+=` are represented as two instances of"]
#[doc = " `Punct` with different forms of `Spacing` returned."]
#[derive(Clone)]
pub struct Punct {
    ch: char,
    spacing: Spacing,
    span: Span,
}
