// Generated macro for allocating (module)
macro_rules! Depcrate_stringallocating {
() => {
// Module: crate::string
// Provides: {"allocating"}
// Dependencies: {}
# [cfg (feature = "alloc")] pub (crate) mod allocating { use super :: StringRef ; use crate :: { BytesRef , DecodeValue , EncodeValue , Error , Header , Length , Reader , Result , Writer , } ; use alloc :: { borrow :: ToOwned , string :: String } ; use core :: { borrow :: Borrow , ops :: Deref , str } ; # [doc = " String newtype which respects the [`Length::max`] limit."] # [derive (Clone , Debug , Eq , PartialEq , PartialOrd , Ord , Hash)] pub struct StringOwned { # [doc = " Inner value"] pub (crate) inner : String , # [doc = " Precomputed `Length` (avoids possible panicking conversions)"] pub (crate) length : Length , } impl StringOwned { # [doc = " Create a new [`StringOwned`], ensuring that the byte representation of"] # [doc = " the provided `str` value is shorter than `Length::max()`."] pub fn new (s : String) -> Result < Self > { let length = Length :: try_from (s . len ()) ? ; Ok (Self { inner : s , length }) } # [doc = " Parse a [`String`] from UTF-8 encoded bytes."] pub fn from_bytes (bytes : & [u8]) -> Result < Self > { Ok (Self { inner : String :: from_utf8 (bytes . to_vec ()) ? , length : Length :: try_from (bytes . len ()) ? , }) } # [doc = " Borrow the inner `str`"] pub fn as_str (& self) -> & str { & self . inner } # [doc = " Borrow the inner byte slice"] pub fn as_bytes (& self) -> & [u8] { self . inner . as_bytes () } # [doc = " Get the [`Length`] of this [`StringOwned`]"] pub fn len (& self) -> Length { self . length } # [doc = " Is this [`StringOwned`] empty?"] pub fn is_empty (& self) -> bool { self . len () == Length :: ZERO } } impl AsRef < str > for StringOwned { fn as_ref (& self) -> & str { self . as_str () } } impl AsRef < [u8] > for StringOwned { fn as_ref (& self) -> & [u8] { self . as_bytes () } } impl AsRef < BytesRef > for StringOwned { fn as_ref (& self) -> & BytesRef { BytesRef :: new_unchecked (self . as_bytes ()) } } impl AsRef < StringRef > for StringOwned { fn as_ref (& self) -> & StringRef { StringRef :: new_unchecked (& self . inner) } } impl Borrow < StringRef > for StringOwned { fn borrow (& self) -> & StringRef { StringRef :: new_unchecked (& self . inner) } } impl Deref for StringOwned { type Target = StringRef ; fn deref (& self) -> & StringRef { self . borrow () } } impl < 'a > DecodeValue < 'a > for StringOwned { type Error = Error ; fn decode_value < R : Reader < 'a > > (reader : & mut R , header : Header) -> Result < Self > { Self :: from_bytes (< & 'a BytesRef > :: decode_value (reader , header) ? . as_slice ()) } } impl EncodeValue for StringOwned { fn value_len (& self) -> Result < Length > { Ok (self . length) } fn encode_value (& self , writer : & mut impl Writer) -> Result < () > { writer . write (self . as_ref ()) } } impl ToOwned for StringRef { type Owned = StringOwned ; fn to_owned (& self) -> StringOwned { StringOwned { inner : self . as_str () . into () , length : self . len () , } } } }
};
}
