// Generated by add_generated_rust_header! macro at submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs:72 from submodules/split-decls-rs/src/eager_splitter/declaration_writer.rs
// Do not edit this file by hand. Your changes will be overwritten.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
impl BuildMetadata {
    pub const EMPTY: Self = BuildMetadata {
        identifier: Identifier::empty(),
    };
    pub fn new(text: &str) -> Result<Self, Error> {
        BuildMetadata::from_str(text)
    }
    pub fn as_str(&self) -> &str {
        self.identifier.as_str()
    }
    pub fn is_empty(&self) -> bool {
        self.identifier.is_empty()
    }
}
